import { CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, GitBranch, MapPin, Trophy, Users } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import type { TournamentDetail, TournamentFixtureDto } from '../domain';
import { tournamentKickoffLabel, tournamentReadiness } from '../tournament-readiness';
import { TournamentConnections } from './TournamentConnections';

export type TournamentWorkspaceSection = 'overview' | 'participants' | 'bracket' | 'schedule' | 'people';
export function TournamentOverview({ tournament, canManage, onSection, onMatch }: { tournament: TournamentDetail; canManage: boolean; onSection: (section: TournamentWorkspaceSection) => void; onMatch: (match: TournamentFixtureDto) => void }) {
    const { i18n } = useTranslation();
    const copy = (en: string, ka: string) => i18n.language.startsWith('ka') ? ka : en;
    const state = tournamentReadiness(tournament);
    const tasks = [
        { key: 'participants' as const, icon: Users, count: state.pending.length, title: copy('Entries to review', 'განსახილველი მონაწილეობა'), hint: copy('Requests, waiting list and final confirmations.', 'მოთხოვნები, მოლოდინის სია და საბოლოო დადასტურება.') },
        { key: 'bracket' as const, icon: GitBranch, count: tournament.stages.length ? null : 1, title: copy('Competition structure', 'შეჯიბრების სტრუქტურა'), hint: copy('Stages, draw, standings and progression.', 'ეტაპები, წილისყრა, ცხრილი და შემდეგ ეტაპზე გასვლა.') },
        { key: 'schedule' as const, icon: CalendarDays, count: state.unscheduled, title: copy('Kickoffs to arrange', 'დასანიშნი დრო'), hint: copy('Set match times and review clashes.', 'დანიშნეთ დრო და შეამოწმეთ გადაფარვა.') },
        { key: 'schedule' as const, icon: MapPin, count: state.withoutVenue, title: copy('Location checks', 'ადგილის შემოწმება'), hint: copy('Review recorded locations. Pitch bookings are arranged separately.', 'შეამოწმეთ მითითებული ადგილი. მოედანი ცალკე იჯავშნება.') },
    ];
    return <div className="tc-overview">
        <div className="tc-metrics">
            {[{icon:Users,label:copy('Confirmed entries','დადასტურებული მონაწილეობა'),value:state.confirmed.length,section:'participants' as const},{icon:GitBranch,label:copy('Stages','ეტაპები'),value:tournament.stages.length,section:'bracket' as const},{icon:CalendarDays,label:copy('Matches','მატჩები'),value:tournament.fixtures.length,section:'schedule' as const},{icon:Trophy,label:copy('Final results','საბოლოო შედეგები'),value:state.completed,section:'schedule' as const}].map(item => <button key={item.label} onClick={() => onSection(item.section)}><item.icon size={20}/><span>{item.label}</span><strong>{item.value}</strong><ChevronRight size={15}/></button>)}
        </div>
        <div className="tc-overview-grid"><div className="tc-stack">
            <section className="tc-panel"><div className="tc-panel-heading"><CalendarDays size={18}/><div><h2>{copy('Coming up','მომავალი მატჩები')}</h2><p>{copy('The next fixtures, in kickoff order.','შემდეგი მატჩები დროის მიხედვით.')}</p></div><button className="tc-text-button" onClick={() => onSection('schedule')}>{copy('Full schedule','სრული განრიგი')} <ChevronRight size={14}/></button></div>
                {state.upcoming.length ? state.upcoming.slice(0,4).map(f => <button className="tc-fixture" key={f.id} onClick={() => onMatch(f)}><span className="tc-fixture-date"><CalendarDays size={18}/>{tournamentKickoffLabel(f.scheduledAt,i18n.language) || copy('Time to arrange','დრო დასანიშნია')}</span><span><small>{f.stageName}</small><strong>{f.homeLabel || copy('To be decided','გასარკვევია')} <span className="tc-vs">vs</span> {f.awayLabel || copy('To be decided','გასარკვევია')}</strong><small>{f.venueReservation?.venueName || (f.locationId != null ? copy('Location recorded','ადგილი მითითებულია') : copy('Venue to arrange','ადგილი დასანიშნია'))}</small></span><ChevronRight size={17}/></button>) : <div className="tc-empty"><CalendarDays size={26}/><h3>{copy('No upcoming fixtures','მომავალი მატჩები არ არის')}</h3><p>{tournament.status === 'PLANNING' ? copy('Build the competition, then arrange the matchday.','შექმენით შეჯიბრება და შემდეგ დაგეგმეთ მატჩები.') : copy('View Matchday for recorded results.','შედეგები ნახეთ მატჩების განრიგში.')}</p><button className="tw-button" onClick={() => onSection(tournament.status === 'PLANNING' ? 'bracket' : 'schedule')}>{copy('Open competition','შეჯიბრების გახსნა')}</button></div>}
                {state.awaitingResult > 0 && <button className="tc-text-button" onClick={() => onSection('schedule')}>{state.awaitingResult} {copy('past fixtures await a result · open Matchday','წარსულ მატჩს შედეგი აკლია · გახსენით განრიგი')} <ChevronRight size={14}/></button>}
            </section>
            <section className="tc-panel"><div className="tc-panel-heading"><ClipboardCheck size={18}/><h2>{canManage ? copy('Competition checklist','შეჯიბრების საკონტროლო სია') : copy('Competition at a glance','შეჯიბრების მოკლე მიმოხილვა')}</h2></div><div className="tc-task-grid">{tasks.map(item => <button key={item.title} className="tc-task" onClick={() => onSection(item.key)}><item.icon size={18}/><span><strong>{item.title}</strong><small>{item.hint}</small></span>{item.count != null ? <span className={item.count ? 'tc-count attention' : 'tc-count'}>{item.count ? item.count : <CheckCircle2 size={16}/>}</span> : <ChevronRight size={15}/>}</button>)}</div><p className="tc-note">{copy('This checklist describes recorded setup. Starting the tournament still uses its validation rules; a location assignment alone does not confirm a pitch booking.','ეს სია ასახავს არსებულ ჩანაწერებს. დაწყებისას მოქმედებს შემოწმების წესები; ადგილის მითითება მოედნის ჯავშანს არ ადასტურებს.')}</p></section>
        </div><aside className="tc-stack"><TournamentConnections tournament={tournament} privateView/><section className="tc-panel"><div className="tc-panel-heading"><Users size={18}/><h2>{copy('Tournament team','ტურნირის გუნდი')}</h2></div>{tournament.staffAssignments.filter(s=>s.status==='ACTIVE').slice(0,4).map(s=><div className="tc-person-summary" key={s.id}><span className="tw-avatar"><Users size={16}/></span><span><strong>{s.fullName || copy('Team member','გუნდის წევრი')}</strong><small>{s.role === 'ADMIN' ? copy('Tournament admin','ტურნირის ადმინისტრატორი') : s.role === 'STAFF' ? copy('Tournament staff','ტურნირის თანამშრომელი') : copy('Referee','მსაჯი')}</small></span></div>)}<button className="tc-text-button" onClick={()=>onSection('people')}>{copy('People & responsibilities','ადამიანები და პასუხისმგებლობები')} <ChevronRight size={14}/></button></section></aside></div>
    </div>;
}
