import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, ShieldCheck, UserPlus, Users, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { assignTournamentStaff, removeTournamentStaff, searchPlayersForInvite } from '../api';
import type { TournamentDetail, TournamentStaffAssignmentDto, UserSearchResult } from '../domain';
import { extractApiErrorMessage } from '../../../utils/apiError';
import { ConfirmDialog } from '../../../components/ui/ConfirmDialog';
import { useAuth } from '../../../context/AuthContext';

export function TournamentPeople({ tournament, canEdit, onUpdate }: { tournament: TournamentDetail; canEdit: boolean; onUpdate: (value: TournamentDetail) => void }) {
    const { i18n } = useTranslation(); const { user } = useAuth();
    const copy=(en:string,ka:string)=>i18n.language.startsWith('ka')?ka:en;
    const [query,setQuery]=useState(''),[results,setResults]=useState<UserSearchResult[]>([]),[selected,setSelected]=useState(''),[role,setRole]=useState<'ADMIN'|'STAFF'|'REFEREE'>('STAFF');
    const [busy,setBusy]=useState(false),[searched,setSearched]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[removing,setRemoving]=useState<TournamentStaffAssignmentDto|null>(null);
    const lookup=useRef(0); const editable=canEdit && tournament.status==='PLANNING';
    const roleName=(value:string)=>value==='ADMIN'?copy('Tournament admin','ტურნირის ადმინისტრატორი'):value==='STAFF'?copy('Tournament staff','ტურნირის თანამშრომელი'):copy('Referee','მსაჯი');
    const change=async(action:()=>Promise<TournamentDetail>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{onUpdate(await action());setSelected('');setRemoving(null);setNotice(copy('Tournament responsibilities updated.','ტურნირის პასუხისმგებლობები განახლდა.'));}catch(err){setError(extractApiErrorMessage(err,copy('Could not update responsibilities.','პასუხისმგებლობები ვერ განახლდა.')));setRemoving(null);}finally{setBusy(false);}};
    return <div className="tc-stack"><div className="tw-toolbar"><div><h2>{copy('People & responsibilities','ადამიანები და პასუხისმგებლობები')}</h2><p>{copy('Recorded tournament assignments, separate from club roles and football profiles.','ტურნირის დანიშნული პასუხისმგებლობები განსხვავდება კლუბის როლებისა და საფეხბურთო პროფილებისგან.')}</p></div><ShieldCheck size={24}/></div>
        {error&&<p className="tw-error" role="alert">{error}</p>}{notice&&<p className="tw-notice" role="status">{notice}</p>}
        <section className="tc-panel"><div className="tc-panel-heading"><Users size={18}/><h3>{copy('Active tournament team','ტურნირის მოქმედი გუნდი')}</h3></div>{tournament.staffAssignments.filter(s=>s.status==='ACTIVE').map(s=><div className="tc-person-row" key={s.id}><span className="tw-avatar"><ShieldCheck size={18}/></span><span><strong>{s.userId != null ? <Link to={`/profile/${s.userId}`}>{s.fullName || copy('Member profile','წევრის პროფილი')}</Link> : s.fullName || copy('Team member','გუნდის წევრი')}</strong><small>{roleName(s.role)}</small></span>{editable && s.userId!==user?.id && <button className="tw-icon" disabled={busy} aria-label={`${copy('Remove assignment for','პასუხისმგებლობის გაუქმება:')} ${s.fullName}`} onClick={()=>setRemoving(s)}><X size={15}/></button>}</div>)}</section>
        {editable && <section className="tc-panel"><div className="tc-panel-heading"><UserPlus size={18}/><h3>{copy('Assign an organizer member','ორგანიზატორის წევრის დანიშვნა')}</h3></div><p className="tc-note">{copy('Only members of this tournament’s organizer organization can be assigned. The server checks membership and keeps at least one active admin.','ინიშნება მხოლოდ ორგანიზატორი ორგანიზაციის წევრი. სერვერი ამოწმებს წევრობას და ინარჩუნებს სულ მცირე ერთ ადმინისტრატორს.')}</p>
            <form className="tc-search-row" onSubmit={async e=>{e.preventDefault();const revision=++lookup.current;setError('');setSelected('');try{const found=await searchPlayersForInvite(query);if(revision===lookup.current){setResults(found);setSearched(true);}}catch(err){if(revision===lookup.current)setError(extractApiErrorMessage(err,copy('Search failed. Try again.','ძებნა ვერ შესრულდა. სცადეთ ხელახლა.')));}}}><label>{copy('Find an existing member','არსებული წევრის ძებნა')}<input value={query} onChange={e=>{setQuery(e.target.value);lookup.current++;setResults([]);setSelected('');setSearched(false);}} maxLength={200}/></label><button className="tw-button" disabled={busy||!query.trim()}><Search size={16}/>{copy('Search','ძებნა')}</button></form>
            {searched && !results.length && <p className="tc-note">{copy('No matching people. Try their full name.','ვერავინ მოიძებნა. სცადეთ სრული სახელი.')}</p>}
            <form className="tc-assign-form" onSubmit={e=>{e.preventDefault();if(selected)void change(()=>assignTournamentStaff(tournament.id,Number(selected),role));}}><label>{copy('Person','პირი')}<select required value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}><option value="">{copy('Choose from search results','აირჩიეთ ძებნის შედეგებიდან')}</option>{results.map(r=><option key={r.id} value={r.id}>{r.fullName || r.username}</option>)}</select></label><label>{copy('Responsibility','პასუხისმგებლობა')}<select value={role} disabled={busy} onChange={e=>setRole(e.target.value as typeof role)}>{(['STAFF','ADMIN','REFEREE'] as const).map(r=><option key={r} value={r}>{roleName(r)}</option>)}</select></label><button className="tw-primary" disabled={busy||!selected}>{busy?copy('Saving…','ინახება…'):copy('Assign responsibility','პასუხისმგებლობის დანიშვნა')}</button></form>
        </section>}
        <section className="tc-panel"><h3>{copy('Match officials','მატჩის მსაჯები')}</h3><p className="tc-note">{copy('Tournament-specific referee invitations are not available in this release. Referee appointments in Match Exchange remain separate. A referee assignment here does not grant results-editing access.','ტურნირის მსაჯის მოწვევა ამ ვერსიაში მიუწვდომელია. მატჩების გაცვლის მსაჯის დანიშვნა ცალკეა. აქ მსაჯის როლი შედეგის რედაქტირების უფლებას არ იძლევა.')}</p></section>
        <ConfirmDialog open={!!removing} title={copy('Remove this responsibility?','გაუქმდეს პასუხისმგებლობა?')} message={copy('This removes tournament access through this assignment. Other club and organization responsibilities remain separate.','გაუქმდება ამ დანიშვნით მიღებული წვდომა. სხვა კლუბისა და ორგანიზაციის პასუხისმგებლობები ცალკე რჩება.')} confirmLabel={copy('Remove assignment','დანიშვნის გაუქმება')} variant="danger" onCancel={()=>{if(!busy)setRemoving(null);}} onConfirm={()=>{if(removing)void change(()=>removeTournamentStaff(tournament.id,removing.id));}}/>
    </div>;
}
