import { chromium,expect } from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});const failures=[];
page.on('pageerror',error=>failures.push(error.message));
await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:5300')?route.continue():route.abort());
await page.goto('http://127.0.0.1:5300/e2e/fixtures/schedule-preview.html');
await page.getByRole('button',{name:'Edit schedule',exact:true}).click();
await page.getByRole('button',{name:/^Edit training series: U16/}).first().click();
await expect(page.getByRole('dialog',{name:'Edit training series',exact:true})).toBeVisible();
await page.getByRole('button',{name:'Cancel',exact:true}).click();
await expect(page.getByRole('dialog')).toHaveCount(0);
await page.getByRole('button',{name:'Done editing',exact:true}).click();
await page.getByRole('button',{name:'Month',exact:true}).click();
await page.getByRole('button',{name:'Next period',exact:true}).click();await page.getByRole('button',{name:'Next period',exact:true}).click();await page.getByRole('button',{name:'Next period',exact:true}).click();
await expect(page.getByRole('button',{name:/^Create event on/})).toHaveCount(42);
await page.getByRole('button',{name:/^Create event on/}).first().click();await expect(page.getByRole('dialog',{name:'New event'})).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.screenshot({path:'review/schedule-redesign-20260913/14-empty-calendar.png'});
await page.goto('http://127.0.0.1:5300/e2e/fixtures/schedule-preview.html');await page.setViewportSize({width:390,height:480});
await page.getByRole('button',{name:'Filters',exact:true}).click();await page.getByRole('button',{name:'Create weekly training',exact:true}).click();await expect(page.getByRole('dialog',{name:'New weekly training',exact:true})).toBeVisible();
await page.getByLabel('Training name',{exact:true}).fill('Small screen training');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeInViewport();
await page.screenshot({path:'review/schedule-redesign-20260913/15-short-phone.png'});
await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Discard',exact:true}).click();
await expect(page.getByRole('button',{name:'Preview light theme',exact:true})).toBeVisible();
console.log(JSON.stringify({checks:['edit-mode-recurring-opens-series','empty-month-retains-grid','empty-date-opens-create','phone-weekly-shortcut','short-phone-keeps-footer-visible','discard-restores-background'],errors:failures}));await browser.close();
