import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';import path from 'node:path';
import {createServer} from 'vite';import {chromium,expect} from '@playwright/test';
const fixture=JSON.parse(await readFile(process.argv[2],'utf8'));
const root=path.resolve(process.env.GK_STORE_FRONTEND),output=path.resolve(path.dirname(process.argv[2]),'campaigns-browser');await mkdir(output,{recursive:true});
const server=await createServer({root,configFile:path.join(root,'vite.config.ts'),define:{'import.meta.env.VITE_API_BASE_URL':JSON.stringify(fixture.backend+'/api'),'import.meta.env.VITE_ENABLE_MOCKS':'"false"'},server:{host:'127.0.0.1',port:5179,strictPort:true,hmr:false}});
await server.listen();const browser=await chromium.launch({channel:'chrome',headless:true}),results={};
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}});context.setDefaultTimeout(12000);
 await context.addInitScript(owner=>{localStorage.setItem('accessToken',owner.token);localStorage.setItem('userId',String(owner.id));},fixture.owner);
 const headers={Authorization:'Bearer '+fixture.owner.token},base=`${fixture.backend}/api/clubs/${fixture.club}/campaigns`;

 const upload=async()=>{const r=await context.request.post(fixture.backend+'/api/media/upload?context=general',{headers,multipart:{file:{name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jB9kAAAAASUVORK5CYII=','base64')}}});expect(r.status(),await r.text()).toBe(200);return (await r.json()).url;};
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:5179/e2e/fixtures/campaigns.html?club='+fixture.club;
 await page.goto(url);await page.evaluate(()=>document.documentElement.classList.add('dark'));
 await page.getByRole('button',{name:'Create campaign',exact:true}).click();
 for(const [label,value] of [['Campaign title','A pitch for everyone'],['Short summary','Help our youth teams train on a safe, welcoming pitch.'],['Campaign purpose','We are restoring our community training ground so young players can train throughout the year.'],['Who benefits','Our youth teams and local families'],['Funding goal (optional)','10000'],['How funds will be used','New goals, safe lighting and essential pitch repairs.']]) await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByText('Report funds received outside GrassKickZ (optional)',{exact:true}).click();await page.getByLabel('Club-reported amount',{exact:true}).fill('1250');await page.getByLabel('Explanation of reported funds',{exact:true}).fill('Club fundraising day: amount counted by the club committee.');
 await page.getByRole('button',{name:'Save campaign',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Campaign saved.'})).toContainText('Campaign saved.');
 let response=await context.request.get(`${fixture.backend}/api/campaigns?clubId=${fixture.club}&state=ALL`);expect((await response.json()).totalElements).toBe(0);
 await page.getByRole('button',{name:'Publish A pitch for everyone',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Campaign published.'})).toContainText('Campaign published.');
 response=await context.request.get(base,{headers});let campaign=(await response.json())[0];expect(campaign.reportedAmount).toBe(1250);expect(campaign.goalAmount).toBe(10000);
 response=await context.request.put(base+'/'+campaign.id,{headers,data:{...campaign,images:[await upload(),await upload()]}});expect(response.status()).toBe(200);campaign=await response.json();
 await page.getByRole('link',{name:'View club campaigns',exact:true}).click();await expect(page.getByRole('heading',{name:'Campaign Demo FC campaigns'})).toBeVisible();
 await page.getByRole('link',{name:'A pitch for everyone',exact:true}).click();await expect(page.getByRole('heading',{name:'A pitch for everyone',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Online contributions unavailable'})).toBeDisabled();await expect(page.getByText('Club-reported funds are not verified by GrassKickZ.',{exact:false})).toBeVisible();await expect(page.getByRole('link',{name:'Contact the club'})).toHaveAttribute('href',`/clubs/${fixture.club}?tab=contact`);
 await page.getByRole('button',{name:'View photo 2'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('img',{name:/A pitch for everyone.*photo 2/})).toBeVisible();await expect.poll(()=>page.getByRole('img',{name:/A pitch for everyone.*photo 2/}).evaluate(el=>el.complete && el.naturalWidth>0)).toBe(true);
 await page.screenshot({path:path.join(output,'detail-dark.png'),fullPage:true,animations:'disabled'});results.publishing={draftPrivate:true,clubScoped:true,reportedAmount:1250,goal:10000,paymentsDisabled:true,keyboardGallery:true};
 await page.getByRole('link',{name:'Manage Campaigns',exact:true}).click();await page.getByRole('button',{name:'Updates for A pitch for everyone',exact:true}).click();
 await page.getByLabel('Update title',{exact:true}).fill('Our first milestone');await page.getByLabel('Update message',{exact:true}).fill('The new goals have arrived. Thank you to everyone helping our club.');await page.getByRole('button',{name:'Publish update',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Campaign update published.'})).toContainText('Campaign update published.');await page.screenshot({path:path.join(output,'workspace.png'),fullPage:true});
 await page.getByRole('link',{name:'View campaign',exact:true}).click();await expect(page.getByRole('heading',{name:'Our first milestone'})).toBeVisible();
 await page.getByRole('link',{name:'Manage Campaigns',exact:true}).click();await page.getByRole('button',{name:'Edit A pitch for everyone',exact:true}).click();await page.getByLabel('Campaign title',{exact:true}).fill('Our unsaved title');
 response=await context.request.get(base+'/'+campaign.id,{headers});campaign=await response.json();response=await context.request.put(base+'/'+campaign.id,{headers,data:{...campaign,summary:'A safe pitch for our youth teams and community.'}});expect(response.status()).toBe(200);
 await page.getByRole('button',{name:'Save campaign',exact:true}).click();await expect(page.getByRole('alert')).toContainText('This campaign changed');await expect(page.getByLabel('Campaign title',{exact:true})).toHaveValue('Our unsaved title');await page.getByRole('button',{name:'Close editor',exact:true}).click();await page.getByRole('button',{name:'Discard edits',exact:true}).click();results.updates={publishedHistory:true,conflictingEditsRetained:true};
 // Returning through discovery reloads the current manager versions.
 await page.getByRole('link',{name:'View club campaigns',exact:true}).click();await page.getByRole('link',{name:'Browse all campaigns',exact:true}).click();await expect(page.getByRole('heading',{name:'A pitch for everyone',exact:true})).toBeVisible();
 await page.screenshot({path:path.join(output,'catalog-dark.png'),fullPage:true,animations:'disabled'});
 expect(await page.locator('.store-heading .store-eyebrow').evaluate(el=>getComputedStyle(el).color)).toBe('rgb(251, 191, 36)');
 await page.evaluate(()=>document.documentElement.classList.remove('dark'));await page.screenshot({path:path.join(output,'catalog-light.png'),fullPage:true,animations:'disabled'});await page.evaluate(()=>document.documentElement.classList.add('dark'));
 await page.setViewportSize({width:390,height:844});await expect(page.locator('#campaign-filters')).toBeHidden();await page.getByRole('button',{name:'Filters',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#campaign-filters')).toBeVisible();await page.getByRole('button',{name:'Show campaigns',exact:true}).click();await expect(page.getByRole('button',{name:'Filters',exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:path.join(output,'catalog-narrow.png'),fullPage:true});
 await page.getByRole('link',{name:'A pitch for everyone',exact:true}).click();await expect(page.getByRole('heading',{name:'Our first milestone'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:path.join(output,'detail-narrow.png'),fullPage:true});results.layout={amberAccent:true,darkAndLight:true,narrowFits:true,filtersKeyboardAndFocus:true};
 const guest=await browser.newContext();response=await guest.request.get(`${fixture.backend}/api/campaigns/${campaign.id}`);expect(response.status()).toBe(200);response=await guest.request.get(`${fixture.backend}/api/campaigns?clubId=${fixture.otherClub}`);expect((await response.json()).totalElements).toBe(0);response=await guest.request.get(base);expect([401,403]).toContain(response.status());
 await page.getByRole('link',{name:'Manage Campaigns',exact:true}).click();await page.getByRole('button',{name:'Pause A pitch for everyone',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Campaign paused.'})).toContainText('Campaign paused.');response=await guest.request.get(`${fixture.backend}/api/campaigns?clubId=${fixture.club}`);expect((await response.json()).totalElements).toBe(0);response=await guest.request.get(`${fixture.backend}/api/campaigns/${campaign.id}`);expect((await response.json()).phase).toBe('PAUSED');
 await page.getByRole('button',{name:'Close A pitch for everyone',exact:true}).click();await page.getByRole('button',{name:'Confirm close',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Campaign closed.'})).toContainText('Campaign closed.');response=await guest.request.get(`${fixture.backend}/api/campaigns/${campaign.id}`);expect((await response.json()).phase).toBe('CLOSED');
 await page.getByRole('button',{name:'Archive A pitch for everyone',exact:true}).click();await page.getByRole('button',{name:'Confirm archive',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Campaign archived.'})).toContainText('Campaign archived.');response=await guest.request.get(`${fixture.backend}/api/campaigns/${campaign.id}`);expect(response.status()).toBe(404);results.visibility={guestAccess:true,otherClubExcluded:true,managementProtected:true,pausedHiddenFromActive:true,closedDetailsRemain:true,archiveHidesDetails:true};
 expect(errors).toEqual([]);console.log('PASS',JSON.stringify(results));
} finally {await writeFile(path.join(output,'results.json'),JSON.stringify(results,null,2));await browser.close();await server.close();}

