import { ClubRefereeChoices } from './ClubRefereeChoices';
import { lazy, Suspense, useRef, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { ages, formats, levels, label, post, type Squad, type Referee } from './api';
import type { Venue } from '../venues/api';
import { useLoad, useAction } from './hooks';
import './arrangement.css';
import '../../components/schedule/schedule-event-editor.css';
import '../../components/schedule/schedule-editor-identity.css';
import './arrangement-composer.css';
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock, Handshake, Lock, MapPin, ShieldCheck, Swords, Users, X } from 'lucide-react';
import { localStamp, reservationIssue, reservationTiming } from './reservationEligibility';
const GroundPicker = lazy(() => import('./GroundPicker'));
export type ArrangementBooking = { allocations?: { startsAt: string; endsAt: string }[]; id: number; venueId: number; venueName: string; pitchId: number; pitchName: string; format: string; startsAt: string; endsAt: string; timezone: string; totalPrice: number; currency: string; status: string; allocatedClubId?: number; canAllocate: boolean; city: string; addressText: string; latitude: number | null; longitude: number | null };

export function ArrangementEditor({ targetClubId, targetClubName, sourceClubId, onClose }: { targetClubId?: number; targetClubName?: string; sourceClubId?: number; onClose: () => void }) {
  const { user, sessionId } = useAuth();
  const navigate = useNavigate();
  const storageKey = `gk:match-draft:${user?.id}:${sessionId}:${targetClubId ?? 'open'}`;
  const blank = { squadId: 0, targetSquadId: 0, title: targetClubName ? `Friendly vs ${targetClubName}` : '', matchType: 'FRIENDLY', description: '', startsAt: '', endsAt: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, city: '', locationName: '', latitude: '', longitude: '', ageGroup: 'U12', level: 'DEVELOPMENT', format: '7_A_SIDE', hostingChoice: 'FLEXIBLE', groundMode: 'LATER', venueId: 0, bookingId: 0, officialMode: 'LATER', officialResponsibility: 'HOST', refereeId: 0, refereeName: '', externalRefereeName: '', volunteer: true, fee: '0', currency: 'GEL', requestId: crypto.randomUUID() };
  const [draft, setDraft] = useState(() => { try { const stored = JSON.parse(sessionStorage.getItem(storageKey) ?? 'null'); return stored ? { ...blank, ...stored } as typeof blank : blank; } catch { return blank; } });
  const [discard, setDiscard] = useState(false);
  const [step, setStep] = useState(0);
  const [validation, setValidation] = useState('');
  const content = useRef<HTMLDivElement>(null);
  const stepHeading = useRef<HTMLHeadingElement>(null);
  const [venueQuery, setVenueQuery] = useState('');
  const [refQuery, setRefQuery] = useState('');
  const [venuePage, setVenuePage] = useState(0);
  const [share, setShare] = useState(false);
  const saving = useRef(false);
  const { data: squads, error: squadError } = useLoad<Squad[]>('/match-exchange/squads');
  const { data: targets, error: targetError } = useLoad<{ id: number; name: string; category: string }[]>(targetClubId ? `/clubs/${targetClubId}/squads` : '');
  const { data: venues, error: venueError, reload: refreshVenues } = useLoad<{ content: Venue[]; totalElements: number }>(draft.groundMode === 'VENUE' ? `/venues?q=${encodeURIComponent(venueQuery)}&page=${venuePage}&size=20` : '');
  const { data: bookings, error: bookingError, reload: refreshBookings } = useLoad<ArrangementBooking[]>(draft.squadId ? `/match-arrangements/bookings?squadId=${draft.squadId}` : '');
  const { data: referees, error: refereeError } = useLoad<{ items: Referee[] }>(draft.officialMode === 'INVITE' ? `/referees?q=${encodeURIComponent(refQuery)}` : '');
  const { run, busy, feedback } = useAction(() => {});
  function patch(value: Partial<typeof draft>) { setValidation(''); setDraft(old => { const next = { ...old, ...value, ...((value.squadId!==undefined&&value.squadId!==old.squadId)||(value.officialMode!==undefined&&value.officialMode!==old.officialMode)||(value.volunteer!==undefined&&value.volunteer!==old.volunteer)?{refereeId:0,refereeName:''}:{}) }; try { sessionStorage.setItem(storageKey, JSON.stringify(next)); } catch { /* Draft remains in memory. */ } return next; }); }
  const chosen = squads?.find(s => s.id === draft.squadId);
  const booking = bookings?.find(b => b.id === draft.bookingId);
  function chooseBooking(id: number) {
    const b = bookings?.find(x => x.id === id); setShare(false);
    if (!b) return patch({ bookingId: 0 });
    patch({ bookingId: id, venueId: b.venueId, city: b.city || '', locationName: `${b.venueName} · ${b.pitchName}`, latitude: b.latitude?.toString() ?? '', longitude: b.longitude?.toString() ?? '', ...reservationTiming(b, draft), currency: b.currency });
  }
  async function submit(e: FormEvent) {
    e.preventDefault(); if (step < 2) { go(step + 1); return; } const problem = issue(2); if (problem) { showProblem(problem); return; } if (saving.current) return;
    saving.current = true;
    await run(async () => {
      if (draft.endsAt <= draft.startsAt) throw new Error('The end time must follow kickoff.');
      if (draft.groundMode === 'BOOKING' && (!booking || reservationIssue(booking, draft))) throw new Error(booking ? `Reservation unavailable: ${reservationIssue(booking, draft)}.` : 'Choose a confirmed reservation, or arrange the ground later.');
      if (share && booking && chosen) await post(`/match-arrangements/bookings/${booking.id}/allocate`, { clubId: chosen.club_id });
      const match = { ...draft, venuePreference: draft.hostingChoice === 'HOME' || draft.hostingChoice === 'AWAY' ? draft.hostingChoice : 'EITHER', refereeRequired: draft.officialMode !== 'NONE', venueId: draft.venueId || null, latitude: draft.latitude ? Number(draft.latitude) : null, longitude: draft.longitude ? Number(draft.longitude) : null, locationName: draft.locationName.trim() || 'Ground to be arranged', revision: 0 };
      const result = await post('/match-arrangements', { match, targetClubId: targetClubId ?? null, targetSquadId: draft.targetSquadId || null, bookingId: draft.bookingId || null, matchType: draft.matchType, hostingChoice: draft.hostingChoice, officialMode: draft.officialMode, officialResponsibility: draft.officialResponsibility, refereeId: draft.refereeId || null, externalRefereeName: draft.externalRefereeName || null, volunteer: draft.volunteer, fee: draft.volunteer ? 0 : Number(draft.fee), currency: draft.currency });
      try { sessionStorage.removeItem(storageKey); } catch { /* Optional local persistence. */ } onClose(); navigate(`/match-exchange/${result.event_id}`);
    }, 'Match arrangement created'); saving.current = false;
  }

  function issue(until: number): { step: number; message: string } | undefined {
    if (!draft.squadId) return { step:0, message:'Choose the squad you represent.' };
    if (!draft.title.trim()) return { step:0, message:'Give this match a name.' };
    if (until < 1) return;
    if (!draft.startsAt || !draft.endsAt) return { step:1, message:'Choose kickoff and the match end time.' };
    if (draft.endsAt <= draft.startsAt) return { step:1, message:'The end time must follow kickoff.' };
    try { new Intl.DateTimeFormat('en', { timeZone:draft.timezone }).format(); } catch { return { step:1, message:'Choose a valid timezone, such as Asia/Tbilisi.' }; }
    if (!draft.city.trim()) return { step:1, message:'Add the city where you plan to play.' };
    if (draft.groundMode === 'BOOKING' && (!booking || reservationIssue(booking,draft))) return { step:1, message:booking ? `Reservation unavailable: ${reservationIssue(booking,draft)}.` : 'Choose a confirmed reservation or arrange the ground later.' };
    if (draft.groundMode === 'VENUE' && !draft.venueId) return { step:1, message:'Select a stadium or choose another ground option.' };
    if (draft.groundMode !== 'LATER' && !draft.locationName.trim()) return { step:1, message:'Add the ground name or meeting address.' };
    if (until < 2) return;
    if (draft.officialMode === 'INVITE' && !draft.refereeId) return { step:2, message:'Choose the referee to invite.' };
    if (draft.officialMode === 'EXTERNAL' && !draft.externalRefereeName.trim()) return { step:2, message:'Name the referee you have arranged.' };
    if (['INVITE','OPEN'].includes(draft.officialMode) && !draft.volunteer && (!draft.fee.trim() || !Number.isFinite(Number(draft.fee)) || Number(draft.fee)<0 || Number(draft.fee)>1000000 || !/^[A-Z]{3}$/.test(draft.currency))) return { step:2, message:'Check the referee fee and three-letter currency.' };
  }
  function move(next: number) { setStep(next); requestAnimationFrame(() => { content.current?.scrollTo({ top:0 }); stepHeading.current?.focus(); }); }
  function showProblem(problem: { step:number;message:string }) { setValidation(problem.message); move(problem.step); }
  function go(next: number) { const problem = next > step ? issue(next-1) : undefined; if (problem) showProblem(problem); else { setValidation(''); move(next); } }
  const officialLabel = draft.officialMode === 'INVITE' ? draft.refereeName || referees?.items.find(r => r.user_id === draft.refereeId)?.full_name || 'Choose a referee' : draft.officialMode === 'EXTERNAL' ? draft.externalRefereeName || 'External referee' : ({ OPEN:'Open referee request',LATER:'Referee still needed',NONE:'No referee required' } as Record<string,string>)[draft.officialMode];
  const steps = ['Plan','When & where','Review & send'];
  return <section className="schedule-compose match-compose">
    <header className="schedule-compose-header"><div><div className="schedule-compose-context"><CalendarDays size={14}/><span>{chosen?.club_name || 'Your club'}</span><ChevronRight size={12}/><span>Arrange a match</span></div><h2>{targetClubId ? 'Challenge a club' : 'New match'}</h2><p>{targetClubName ? `Invite ${targetClubName} to play, in a few simple steps.` : 'Find an opponent, choose a ground and agree the details.'}</p></div><button type="button" className="schedule-compose-close" aria-label="Close challenge" disabled={busy} onClick={onClose}><X size={20}/></button></header>
    <nav className="schedule-compose-steps" aria-label="Challenge steps">{steps.map((name,index) => <button type="button" key={name} disabled={busy} aria-current={step === index ? 'step' : undefined} className={step === index ? 'active' : step > index ? 'visited' : ''} onClick={() => go(index)}><span>{step > index ? <Check size={15}/> : index+1}</span><strong>{name}</strong>{index < 2 && <ChevronRight size={15}/>}</button>)}</nav>
    <form noValidate className="match-compose-form" onSubmit={e => void submit(e)}>
      <div className="schedule-compose-body" ref={content}>
        {validation && <p className="match-form-error" role="alert">{validation}</p>}{squadError && <p className="match-form-error" role="alert">{squadError}</p>}{targetError && <p className="match-form-error" role="alert">{targetError}</p>}{feedback}
        <div className="schedule-compose-columns"><fieldset disabled={busy} className="schedule-compose-fields"><section className="schedule-compose-card"><header><span className="schedule-compose-number">0{step+1}</span><div><h3 tabIndex={-1} ref={stepHeading}>{['Who is playing?','When and where?','Ready to send the invitation?'][step]}</h3><p>{['Choose the teams and the kind of match.','Set the time, then choose a ground or arrange it later.','Check the details and decide how to arrange the referee.'][step]}</p></div></header>
        <div className="schedule-compose-card-body">
{step === 0 && <><div className="match-type-choice"><span>Match type</span><div className="schedule-compose-types">{([['FRIENDLY','Friendly',Handshake],['COMPETITIVE','Competitive match',Swords]] as const).map(([value,name,Icon]) => <button type="button" key={value} aria-pressed={draft.matchType === value} className={draft.matchType === value ? 'selected' : ''} onClick={() => patch({ matchType:value })}><Icon size={16}/>{name}</button>)}</div></div><div className="match-fields">      <label>Your squad<select aria-label="Your squad" required value={draft.squadId || ''} onChange={e => { const s = squads?.find(x => x.id === Number(e.target.value)); patch({ squadId: Number(e.target.value), bookingId: 0, ageGroup: s?.category && ages.includes(s.category) ? s.category : draft.ageGroup }); }}><option value="">Choose the squad you represent</option>{squads?.filter(s => !sourceClubId || s.club_id === sourceClubId).map(s => <option key={s.id} value={s.id}>{s.club_name} · {s.name}</option>)}</select></label>
      {targetClubId && <label>Opponent squad<select aria-label="Opponent squad" value={draft.targetSquadId} onChange={e => patch({ targetSquadId: Number(e.target.value) })}><option value={0}>Let the opponent choose a suitable squad</option>{targets?.map(s => <option key={s.id} value={s.id}>{s.name} · {s.category}</option>)}</select></label>}
      <label className="mx-wide">Match title<input aria-label="Match title" required maxLength={140} value={draft.title} onChange={e => patch({ title: e.target.value })} /></label>
      <label>Playing format<select aria-label="Playing format" value={draft.format} onChange={e => patch({ format: e.target.value })}>{Object.entries(formats).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label>
</div><details className="match-extra"><summary>Age group & playing level</summary><div className="match-fields">      <label>Age group<select aria-label="Age group" value={draft.ageGroup} onChange={e => patch({ ageGroup: e.target.value })}>{ages.map(a => <option key={a}>{a}</option>)}</select></label><label>Playing level<select aria-label="Playing level" value={draft.level} onChange={e => patch({ level: e.target.value })}>{levels.map(l => <option key={l} value={l}>{label(l)}</option>)}</select></label>
</div></details><details className="match-extra"><summary>Notes for the match <small>Optional</small></summary><div className="match-fields">      <label className="mx-wide">Match notes<textarea aria-label="Match notes" maxLength={2000} value={draft.description} onChange={e => patch({ description: e.target.value })} placeholder="Playing rules, kit colours, arrival time and travel arrangements" /></label>
</div></details></>}{step === 1 && <div className="match-fields">      <label>Kickoff<input aria-label="Kickoff" required type="datetime-local" value={draft.startsAt} onChange={e => patch({ startsAt: e.target.value })} /></label><label>Match ends<input aria-label="Match ends" required type="datetime-local" value={draft.endsAt} onChange={e => patch({ endsAt: e.target.value })} /></label>
<label>City<input aria-label="City" required maxLength={120} value={draft.city} onChange={e => patch({ city: e.target.value })} /></label>
<details className="mx-wide match-extra"><summary>Timezone · {draft.timezone}</summary>      <label>Timezone<input aria-label="Timezone" required value={draft.timezone} onChange={e => patch({ timezone: e.target.value })} placeholder="Asia/Tbilisi" /></label></details>      <label>Hosting<select aria-label="Hosting" value={draft.hostingChoice} onChange={e => patch({ hostingChoice: e.target.value })}><option value="HOME">We host</option><option value="AWAY">They host</option><option value="NEUTRAL">Neutral ground</option><option value="FLEXIBLE">To be agreed</option></select></label>
      <label>Choose the ground<select aria-label="Choose the ground" value={draft.groundMode} onChange={e => patch({ groundMode: e.target.value, venueId: 0, bookingId: 0, latitude: '', longitude: '', locationName: '' })}><option value="LATER">To be arranged</option><option value="BOOKING">Use an existing reservation</option><option value="VENUE">Find and book a stadium</option><option value="EXTERNAL">Choose an external ground on the map</option></select></label>
      {draft.groundMode === 'BOOKING' && <div className="mx-wide">{bookingError && <p role="alert">{bookingError}</p>}{draft.squadId > 0 && !bookings && !bookingError && <p role="status">Loading reservations…</p>}{bookings?.length === 0 && <p>No upcoming reservations yet. Book a stadium, then return here after confirmation.</p>}<label>Available reservations<select aria-label="Available reservations" required value={draft.bookingId || ''} onChange={e => chooseBooking(Number(e.target.value))}><option value="">Choose a confirmed reservation</option>{bookings?.map(b => <option key={b.id} value={b.id} disabled={!!reservationIssue(b, draft)}>{b.venueName} · {b.pitchName} · {localStamp(b.startsAt,b.timezone).replace('T',' ')} – {localStamp(b.endsAt,b.timezone).slice(11)} ({b.timezone}) · {b.totalPrice} {b.currency} · {reservationIssue(b, draft) || 'Available'}</option>)}</select></label><button type="button" onClick={refreshBookings}>Refresh reservations</button>{!draft.squadId && <p>Choose your squad first.</p>}{booking?.canAllocate && !booking.allocatedClubId && <label className="mx-check"><input type="checkbox" checked={share} onChange={e => { setShare(e.target.checked); setValidation(''); }} />Allow {chosen?.club_name} staff to use this reservation for club matches</label>}<p className="mx-muted">The reservation must cover the whole match and support its playing format. Sharing a reservation exposes its pitch, time and price to club staff, not your phone or private notes.</p></div>}
      {draft.groundMode === 'VENUE' && <div className="mx-wide">{venueError && <p role="alert">{venueError}</p>}{!venues && !venueError && <p role="status">Loading stadiums…</p>}{venues?.content.length === 0 && <p>No stadiums match this search.</p>}<label>Find a stadium<input aria-label="Find a stadium" value={venueQuery} onChange={e => { setVenueQuery(e.target.value); setVenuePage(0); }} placeholder="Search by stadium or city" /></label><button type="button" onClick={refreshVenues}>Refresh stadiums</button><div className="mx-venue-results">{venues?.content.map(v => <article key={v.id}><strong>{v.displayName}</strong><span>{v.city} · {v.addressText}</span><button type="button" onClick={() => patch({ venueId: v.id, bookingId: 0, city: v.city, locationName: v.displayName, latitude: v.latitude?.toString() ?? '', longitude: v.longitude?.toString() ?? '' })}>{draft.venueId === v.id ? 'Selected' : 'Select stadium'}</button><a className="mx-button" href={`/stadiums/${v.id}?book=1`} target="_blank" rel="noopener noreferrer">Book a pitch ↗</a></article>)}</div><div className="mx-actions"><button type="button" disabled={!venuePage} onClick={() => setVenuePage(p => p-1)}>Previous</button><button type="button" disabled={!venues || (venuePage+1)*20 >= venues.totalElements} onClick={() => setVenuePage(p => p+1)}>Next</button></div><p>Your draft stays here while you book in another tab. Once the owner confirms, choose “Use an existing reservation” and refresh. Selecting a stadium alone does not reserve it.</p></div>}
      {draft.groundMode === 'EXTERNAL' && <Suspense fallback={<p>Loading ground map…</p>}><GroundPicker latitude={draft.latitude} longitude={draft.longitude} onChange={(latitude,longitude) => patch({ latitude,longitude })} /></Suspense>}
      {draft.groundMode !== 'LATER' && <label className="mx-wide">Ground name / meeting address<input aria-label="Ground name / meeting address" required maxLength={255} value={draft.locationName} onChange={e => patch({ locationName: e.target.value })} /></label>}
</div>}{step === 2 && <><section className="schedule-compose-review" aria-label="Review match"><div><span>Teams</span><strong>{chosen?.name} vs {targetClubName ?? 'Open opponent listing'}<small>{draft.targetSquadId ? targets?.find(s => s.id === draft.targetSquadId)?.name : 'Opponent chooses their squad'}</small></strong></div><div><span>Match</span><strong>{formats[draft.format]} · {draft.ageGroup} · {label(draft.level)}</strong></div><div><span>When</span><strong>{draft.startsAt.replace("T", " · ")} – {draft.endsAt.slice(0,10) === draft.startsAt.slice(0,10) ? draft.endsAt.slice(11) : draft.endsAt.replace("T", " · ")}<small>{draft.timezone}</small></strong></div><div><span>Ground</span><strong>{draft.locationName || 'To be arranged'}<small>{booking ? `${booking.pitchName} · ${booking.totalPrice} ${booking.currency}` : 'No reservation attached'} · {({HOME:'We host',AWAY:'They host',NEUTRAL:'Neutral ground',FLEXIBLE:'Hosting to be agreed'} as Record<string,string>)[draft.hostingChoice]}</small></strong></div></section><div className="match-fields">      <label>Who arranges the referee?<select aria-label="Who arranges the referee?" value={draft.officialResponsibility} onChange={e => patch({ officialResponsibility: e.target.value, officialMode: 'LATER', refereeId: 0 })}><option value="HOST">Our coaching team</option><option value="OPPONENT">The opponent after accepting</option></select></label>
      <label>Referee arrangement<select aria-label="Referee arrangement" value={draft.officialMode} onChange={e => patch({ officialMode: e.target.value, refereeId: 0 })}><option value="LATER">Still needed</option>{draft.officialResponsibility === 'HOST' && <><option value="INVITE">Invite a GrassKickZ referee</option><option value="OPEN">Publish an open referee request</option><option value="EXTERNAL">Already arranged outside GrassKickZ</option></>}<option value="NONE">No referee required</option></select></label>
      {draft.officialMode === 'INVITE' && <><ClubRefereeChoices squadId={draft.squadId} volunteer={draft.volunteer} selectedId={draft.refereeId} onSelect={r=>patch({refereeId:r.user_id,refereeName:r.full_name,fee:String(r.fee),currency:r.currency})}/>{draft.refereeId>0&&<p className="mx-wide" role="status">Selected: <strong>{officialLabel}</strong> · invitation sent with this match</p>}{refereeError && <p className="mx-wide" role="alert">{refereeError}</p>}{referees && !referees.items.some(r => draft.volunteer ? r.accepts_volunteer : r.accepts_paid) && <p className="mx-wide">No referees match this search and these terms. Try another search or publish an open request.</p>}<label>Search referees<input aria-label="Search referees" value={refQuery} onChange={e => setRefQuery(e.target.value)} /></label><label>Referee<select aria-label="Referee" required value={draft.refereeId || ''} onChange={e => {const r=referees?.items.find(r=>r.user_id===Number(e.target.value));patch({refereeId:r?.user_id??0,refereeName:r?.full_name??'',fee:String(r?.fee??0),currency:r?.currency??draft.currency});}}><option value="">Choose from the directory</option>{draft.refereeId>0&&!referees?.items.some(r=>r.user_id===draft.refereeId)&&<option value={draft.refereeId}>{draft.refereeName || 'Selected club referee'}</option>}{referees?.items.filter(r => draft.volunteer ? r.accepts_volunteer : r.accepts_paid).map(r => <option key={r.user_id} value={r.user_id}>{r.full_name} · {r.service_area}</option>)}</select></label></>}
      {['INVITE','OPEN'].includes(draft.officialMode) && <><label>Terms<select aria-label="Terms" value={draft.volunteer ? 'VOLUNTEER':'PAID'} onChange={e => patch({ volunteer: e.target.value === 'VOLUNTEER', fee: '0', refereeId: 0 })}><option value="VOLUNTEER">Volunteer</option><option value="PAID">Paid appointment</option></select></label>{!draft.volunteer && <><label>Agreed fee<input aria-label="Agreed fee" type="number" min="0" max="1000000" required value={draft.fee} onChange={e => patch({ fee: e.target.value })} /></label><label>Currency<input aria-label="Currency" required maxLength={3} value={draft.currency} onChange={e => patch({ currency: e.target.value.toUpperCase() })} /></label></>}<p className="mx-wide mx-muted">{draft.officialMode === 'OPEN' ? 'Eligible referees can offer to officiate. Selecting an offer confirms their appointment at these terms.' : 'The referee receives an invitation and must accept it.'} Payment is agreed directly. Open requests reveal the fixture time and location to referees.</p></>}
      {draft.officialMode === 'EXTERNAL' && <label className="mx-wide">External referee name<input aria-label="External referee name" required maxLength={160} value={draft.externalRefereeName} onChange={e => patch({ externalRefereeName: e.target.value })} /><span className="mx-muted">Recorded as your arrangement; this does not create a verified GrassKickZ appointment.</span></label>}
</div></>}
        </div></section></fieldset>
        <aside className="schedule-compose-preview" aria-label="Match summary"><div className="schedule-compose-preview-heading"><span>YOUR MATCH</span><span><i/>Live summary</span></div><div className="schedule-compose-event-card"><div className="schedule-compose-event-meta">{draft.matchType === 'FRIENDLY' ? 'Friendly' : 'Competitive match'}</div><h3>{draft.title || 'Your next match'}</h3><div className="match-summary-lines"><p><Users size={17}/><span>{chosen ? `${chosen.club_name} · ${chosen.name}` : 'Choose your squad'}<small>vs {targetClubName || 'An opponent from Match Exchange'}{draft.targetSquadId ? ` · ${targets?.find(s => s.id === draft.targetSquadId)?.name || ''}` : ''}</small></span></p><p><CalendarDays size={17}/><span>{draft.startsAt ? draft.startsAt.slice(0,10) : 'Date to be added'}</span></p><p><Clock size={17}/><span>{draft.startsAt ? `${draft.startsAt.slice(11)} – ${draft.endsAt.slice(11) || 'Choose end time'}` : 'Time to be added'}<small>{draft.timezone}</small></span></p><p><MapPin size={17}/><span>{draft.locationName || 'Ground to be arranged'}{booking && <small>Confirmed rental · {booking.totalPrice} {booking.currency}</small>}</span></p><p><ShieldCheck size={17}/><span>{officialLabel}</span></p></div><div className="match-summary-privacy"><Lock size={14}/>{targetClubId ? 'Direct invitation to this club' : 'Open opponent listing'}</div></div><p className="schedule-compose-muted">{targetClubId ? 'The other team must accept before the match is agreed.' : 'Other squads can propose to play. You choose the opponent.'}</p></aside></div>
      </div>
      <footer className="schedule-compose-footer"><div><span>{targetClubId ? 'Sending a direct club invitation' : 'Publishing in Match Exchange'}</span><button type="button" className="match-draft-reset" disabled={busy} onClick={() => setDiscard(v => !v)}>Start a new draft</button></div><div className="match-footer-actions"><button type="button" className="schedule-compose-secondary" disabled={busy} onClick={() => step ? go(step-1) : onClose()}>{step ? <><ChevronLeft size={15}/>Back</> : 'Cancel'}</button><button className="schedule-compose-primary" disabled={busy}>{busy ? 'Sending…' : step < 2 ? <>Continue<ChevronRight size={15}/></> : targetClubId ? 'Send challenge' : 'Publish match'}</button></div></footer>
      {discard && <div className="match-discard" role="alert"><p>Discard this saved draft?</p><button type="button" onClick={() => { patch({ ...blank, requestId:crypto.randomUUID() }); setShare(false); setDiscard(false); move(0); }}>Discard draft</button><button type="button" onClick={() => setDiscard(false)}>Keep this draft</button></div>}
    </form>
  </section>;
}
