import { useTranslation } from "react-i18next";

// Scoped copy avoids changing the shared locale registry while journeys run concurrently.
export const journeyCopy = {
  copyMatchLink: ["Copy match link", "მატჩის ბმულის კოპირება"],
  matchLinkCopied: ["Match link copied. Paste it into your message.", "მატჩის ბმული დაკოპირებულია. ჩასვით შეტყობინებაში."],
  copyMatchLinkManually: ["Select and copy this match link", "მონიშნეთ და დააკოპირეთ მატჩის ბმული"],
  privateMatchLink: ["This is a private arrangement. Invite the referee first so they can open the link and respond.", "ეს კერძო შეთანხმებაა. ჯერ მოიწვიეთ მსაჯი, რომ ბმულის გახსნა და პასუხი შეძლოს."],
  matchLinkInvitation: ["Sharing a link does not appoint a referee. Send an invitation and wait for their acceptance.", "ბმულის გაზიარება მსაჯის დანიშვნას არ ნიშნავს. გაგზავნეთ მოწვევა და დაელოდეთ თანხმობას."],
  exchange: ["Match Exchange", "მატჩების სივრცე"],
  exchangeIntro: ["Find the right opponent. Keep the arrangements in one place.", "იპოვეთ შესაფერისი მეტოქე. მართეთ შეთანხმებები ერთ სივრცეში."],
  findMatch: ["Find a match", "მატჩის ძიება"],
  arrangements: ["My arrangements", "ჩემი შეთანხმებები"],
  findReferee: ["Find a referee", "მსაჯის ძიება"],
  refereeWorkspace: ["Referee workspace", "მსაჯის სამუშაო სივრცე"],
  createListing: ["Create listing", "განაცხადის შექმნა"],
  viewMatch: ["View match details", "მატჩის ნახვა"],
  reviewArrangement: ["Review arrangement", "შეთანხმების ნახვა"],
  theyHost: ["They host", "მასპინძლობენ"],
  theyTravel: ["They travel", "სტუმრად თამაშობენ"],
  eitherVenue: ["Home or away", "შინ ან სტუმრად"],
  pitch: ["Pitch", "მოედანი"],
  official: ["Referee", "მსაჯი"],
  readiness: ["Match readiness", "მატჩის მზადყოფნა"],
  readinessRegion: ["Match readiness and next action", "მატჩის მზადყოფნა და შემდეგი მოქმედება"],
  opponent: ["Opponent", "მეტოქე"],
  pitchVenue: ["Pitch / venue", "მოედანი / ადგილი"],
  officials: ["Officials", "მსაჯები"],
  communication: ["Communication", "კომუნიკაცია"],
  coordinationDetails: ["Coordination & booking details", "კომუნიკაცია და ჯავშნის დეტალები"],
  readinessNote: ["Opponent agreement holds the fixture in both squad schedules. Pitch and officials are confirmed separately.", "მეტოქის შეთანხმებით მატჩი ორივე გუნდის განრიგში აისახება. მოედანი და მსაჯები ცალ-ცალკე დასტურდება."],
  matchDetails: ["Match details", "მატჩის დეტალები"],
  matchOfficials: ["Match officials", "მატჩის მსაჯები"],
  squadSchedule: ["Squad schedule", "გუნდის განრიგი"],
  editDetails: ["Edit details", "დეტალების შეცვლა"],
  arrangementHelp: ["About match updates", "მატჩის განახლებების შესახებ"],
  arrangementHelpBody: ["Both squads receive updates when the opponent or arrangements change. Referees answer their own invitations.", "მეტოქის ან შეთანხმებების ცვლილებისას ორივე გუნდი იღებს განახლებას. მსაჯები მოწვევებს თავად პასუხობენ."],
  appointmentsTitle: ["Your appointments", "თქვენი დანიშვნები"],
  refereeIntro: ["Answer invitations and prepare for your next match.", "უპასუხეთ მოწვევებს და მოემზადეთ შემდეგი მატჩისთვის."],
  availabilityTab: ["Availability", "ხელმისაწვდომობა"],
  appointmentsTab: ["Appointments", "დანიშვნები"],
  mySchedule: ["My schedule", "ჩემი განრიგი"],
  viewProfile: ["View profile", "პროფილის ნახვა"],
  profileAvailability: ["Profile & availability", "პროფილი და ხელმისაწვდომობა"],
  invitationHelp: ["How appointments work", "როგორ მუშაობს დანიშვნები"],
  invitationHelpBody: ["An invitation holds no commitment until you accept. Check the time, venue and fee first. Removing availability never withdraws an accepted appointment.", "მოწვევა ვალდებულებას მხოლოდ მიღების შემდეგ ქმნის. ჯერ შეამოწმეთ დრო, მოედანი და ანაზღაურება. ხელმისაწვდომობის წაშლა მიღებულ დანიშვნას არ აუქმებს."],
  noAppointmentsTitle: ["No appointments yet", "დანიშვნები ჯერ არ არის"],
  noAppointmentsHelp: ["Publish your referee profile and add availability so squads can invite you.", "გამოაქვეყნეთ მსაჯის პროფილი და მიუთითეთ ხელმისაწვდომობა, რათა გუნდებმა მოგიწვიონ."],
  availabilityTitle: ["When you can officiate", "როდის შეგიძლიათ მსაჯობა"],
  availabilityHelp: ["Add a window covering the whole match before accepting an invitation.", "მოწვევის მიღებამდე დაამატეთ ხელმისაწვდომობის პერიოდი მთელი მატჩისთვის."],
  appointmentTerms: ["Appointment terms", "დანიშვნის პირობები"],
  feeLabel: ["Fee", "ანაზღაურება"],
  noPayment: ["Agreed directly", "უშუალო შეთანხმებით"],
  invitations: ["Invitations", "მოწვევები"],
  upcoming: ["Upcoming", "მომავალი"],
  currentAssignments: ["Current assignments", "მიმდინარე დანიშვნები"],
  history: ["History", "ისტორია"],
  offers: ["Offers", "შეთავაზებები"],
  noAppointments: ["No appointments in this section.", "ამ განყოფილებაში დანიშვნები არ არის."],
  yourAppointment: ["Your appointment", "თქვენი დანიშვნა"],
  invitedBy: ["Invited by", "მომწვევი"],
  opponentPending: ["Opponent to be agreed", "მეტოქე შესათანხმებელია"],
  venue: ["Venue", "მოედანი"],
  volunteer: ["Volunteer appointment", "მოხალისეობრივი დანიშვნა"],
  paid: ["agreed directly", "შეთანხმებულია უშუალოდ"],
  accept: ["Accept invitation", "მოწვევის მიღება"],
  decline: ["Decline invitation", "მოწვევის უარყოფა"],
  withdraw: ["Withdraw from appointment", "დანიშვნიდან გასვლა"],
  confirmWithdraw: ["Confirm withdrawal", "გასვლის დადასტურება"],
  withdrawalHelp: ["The host will be told a replacement is needed. The fixture stays scheduled.", "მასპინძელი მიიღებს შეტყობინებას შემცვლელის საჭიროების შესახებ. მატჩი დაგეგმილი რჩება."],
  back: ["Keep appointment", "დანიშვნის შენარჩუნება"],
  accepted: ["Appointment accepted. Both squads will receive an update.", "დანიშვნა მიღებულია. ორივე გუნდი მიიღებს განახლებას."],
  declined: ["Invitation declined.", "მოწვევა უარყოფილია."],
  withdrawn: ["Appointment withdrawn. The host needs a replacement.", "დანიშვნიდან გასვლა დადასტურებულია. მასპინძელს შემცვლელი სჭირდება."],
  availability: ["Set availability for the whole match", "მიუთითეთ ხელმისაწვდომობა მთელი მატჩისთვის"],
  profile: ["Set up referee profile", "მსაჯის პროფილის შექმნა"],
  roles: ["Review football roles", "საფეხბურთო როლების ნახვა"],
  schedule: ["Review My schedule", "ჩემი განრიგის ნახვა"],
  workspace: ["Open referee workspace", "მსაჯის სამუშაო სივრცის გახსნა"],
  refresh: ["Refresh appointment", "დანიშვნის განახლება"],
  conflict: ["The appointment changed or a commitment conflicts. Current details are being refreshed. Review them before trying again.", "დანიშვნა შეიცვალა ან სხვა ვალდებულებას ემთხვევა. მონაცემები ახლდება. ხელახლა ცდამდე გადახედეთ მათ."],
  failed: ["Could not save the appointment. Your input is preserved.", "დანიშვნის შენახვა ვერ მოხერხდა. შეყვანილი ტექსტი შენარჩუნებულია."],
  lateHelp: ["Kickoff has passed. Report inability to attend so the host can follow up. The accepted appointment and fee terms stay in history; this does not cancel the match or confirm a replacement.", "მატჩი უკვე დაწყებულია. აცნობეთ მასპინძელს, რომ მისვლას ვერ ახერხებთ. მიღებული დანიშვნა და ანაზღაურების პირობები ისტორიაში რჩება; ეს მატჩს არ აუქმებს და შემცვლელს არ ადასტურებს."],
  reportInability: ["Report inability to attend", "შეტყობინება მისვლის შეუძლებლობის შესახებ"],
  reason: ["Reason for the coaching teams", "მიზეზი მწვრთნელებისთვის"],
  reasonPrivacy: ["Visible to you and the two squads’ coaching teams. Avoid medical or other sensitive details.", "ხელმისაწვდომია თქვენთვის და ორივე გუნდის მწვრთნელებისთვის. ნუ მიუთითებთ სამედიცინო ან სხვა მგრძნობიარე ინფორმაციას."],
  issueSaved: ["Attendance issue recorded. Coaching teams have been notified; contact the host directly for urgent follow-up.", "შეტყობინება დაფიქსირდა და მწვრთნელებს გაეგზავნა. გადაუდებელი საკითხისთვის დაუკავშირდით მასპინძელს უშუალოდ."],
  issueRecorded: ["Unable to attend — host follow-up needed", "ვერ ესწრება — საჭიროა მასპინძლის მოქმედება"],
  report: ["Match report", "მატჩის ანგარიში"],
  saveReport: ["Save report", "ანგარიშის შენახვა"],
  reportSaved: ["Report saved.", "ანგარიში შენახულია."],
  roleRequired: ["An active verified referee role is required.", "საჭიროა მსაჯის აქტიური და დადასტურებული როლი."],
  profileRequired: ["Save your referee profile first.", "ჯერ შეინახეთ მსაჯის პროფილი."],
  availabilityRequired: ["Add availability covering the entire match before accepting. The time zone is shown with the match time.", "მიღებამდე მიუთითეთ ხელმისაწვდომობა მთელი მატჩისთვის. დროის სარტყელი მატჩის დროსთან ერთად არის მითითებული."],
  appointmentConflict: ["Another accepted appointment overlaps this match. Review your schedule before accepting.", "სხვა მიღებული დანიშვნა ამ მატჩს ემთხვევა. მიღებამდე გადახედეთ განრიგს."],
  personalConflict: ["A personal event overlaps this match. Review your schedule before accepting.", "პირადი ღონისძიება ამ მატჩს ემთხვევა. მიღებამდე გადახედეთ განრიგს."],
  kickoffPassed: ["Kickoff has passed. Acceptance and withdrawal are closed.", "მატჩი უკვე დაწყებულია. მიღება და დანიშვნიდან გასვლა დახურულია."],
  fixtureClosed: ["The fixture is cancelled or completed. This appointment remains in history.", "მატჩი გაუქმებულია ან დასრულებულია. დანიშვნა ისტორიაში რჩება."],
  prerequisitesUnknown: ["Refresh to check the available actions and acceptance requirements.", "განაახლეთ ხელმისაწვდომი მოქმედებებისა და მიღების მოთხოვნების სანახავად."],
  replacement: ["Replacement needed", "საჭიროა შემცვლელი"],
  nextHostReferee: ["Host: arrange a replacement referee. A reported absence does not confirm a new official.", "მასპინძელი: მოიძიეთ შემცვლელი მსაჯი. არყოფნის შეტყობინება ახალ მსაჯს არ ადასტურებს."],
  nextHostLate: ["Host: contact both coaching teams and the referee about the absence. New invitations cannot be accepted after kickoff. Cancel the fixture if it could not be played, preserving its history.", "მასპინძელი: არყოფნის შესახებ დაუკავშირდით ორივე გუნდის მწვრთნელებსა და მსაჯს. მატჩის დაწყების შემდეგ ახალი მოწვევის მიღება შეუძლებელია. თუ მატჩი ვერ ჩატარდა, გააუქმეთ ის ისტორიის შენარჩუნებით."],
  nextResult: ["Academy leadership: record the outcome. If the match could not be played or completed, hosting staff can review cancellation.", "აკადემიის ხელმძღვანელობა: დააფიქსირეთ შედეგი. თუ მატჩი ვერ ჩატარდა ან დასრულდა, მასპინძლის თანამშრომლებს შეუძლიათ გაუქმების განხილვა."],
  communicationClosed: ["Closed — history retained", "დახურულია — ისტორია შენარჩუნებულია"],
  nextReferee: ["Awaiting the invited referee’s response.", "ველოდებით მოწვეული მსაჯის პასუხს."],
  nextHostVenue: ["Host: confirm the pitch or follow up on its reservation.", "მასპინძელი: დაადასტურეთ მოედანი ან მოაგვარეთ ჯავშანი."],
  nextOpponent: ["Host and proposing squad: agree an opponent and the match terms.", "მასპინძელი და შეთავაზების ავტორი გუნდი: შეათანხმეთ მეტოქე და მატჩის პირობები."],
  nextHostInvite: ["Host: invite the required referee.", "მასპინძელი: მოიწვიეთ საჭირო მსაჯი."],
  ready: ["Opponent, venue and required referee are confirmed. Coaching teams can coordinate matchday details.", "მეტოქე, მოედანი და საჭირო მსაჯი დადასტურებულია. მწვრთნელებს შეუძლიათ მატჩის დეტალების შეთანხმება."],
  finished: ["This fixture is complete. Review its recorded result and history.", "მატჩი დასრულებულია. იხილეთ შედეგი და ისტორია."],
  cancelled: ["This fixture is cancelled. Review any remaining venue follow-up.", "მატჩი გაუქმებულია. გადაამოწმეთ მოედნის დარჩენილი საკითხები."],
  cancelFixture: ["Cancel fixture", "მატჩის გაუქმება"],
  cancelReason: ["Why could this fixture not be played or completed?", "რატომ ვერ ჩატარდა ან დასრულდა მატჩი?"],
  cancelHelp: ["Review who will be notified. Cancellation keeps the opponent, appointment and venue history. Reservations and financial terms remain unchanged.", "გადახედეთ, ვის გაეგზავნება შეტყობინება. გაუქმება ინარჩუნებს მეტოქის, დანიშვნისა და მოედნის ისტორიას. ჯავშანი და ფინანსური პირობები უცვლელი რჩება."],
  reviewCancel: ["Review cancellation", "გაუქმების გადახედვა"],
  confirmCancel: ["Confirm cancellation and notify participants", "გაუქმების დადასტურება და მონაწილეების შეტყობინება"],
  venueFollowup: ["Venue follow-up", "მოედნის საკითხის მოგვარება"],
  bookingFollowup: ["The linked reservation and its charges remain unchanged. Use the stadium booking workflow or contact the facility for ongoing or past bookings. Fixture cancellation does not cancel or refund it.", "დაკავშირებული ჯავშანი და საფასური უცვლელია. გამოიყენეთ სტადიონის ჯავშნის მართვა ან მიმდინარე/წარსულ ჯავშანზე დაუკავშირდით ობიექტს. მატჩის გაუქმება ჯავშანს არ აუქმებს და თანხას არ აბრუნებს."],
  externalFollowup: ["Contact the ground owner. Record the outcome once agreed; the original confirmation remains in history.", "დაუკავშირდით მოედნის მფლობელს. შეთანხმების შემდეგ დააფიქსირეთ შედეგი; თავდაპირველი დადასტურება ისტორიაში დარჩება."],
  resolution: ["Outcome agreed with the ground owner", "მოედნის მფლობელთან შეთანხმებული შედეგი"],
  saveResolution: ["Record external venue follow-up", "მოედნის საკითხის მოგვარების დაფიქსირება"],
  resolutionSaved: ["External venue follow-up recorded.", "მოედნის საკითხის მოგვარება დაფიქსირდა."],
  arrangementHistory: ["Arrangement history", "შეთანხმებების ისტორია"],
  resolveFirst: ["Resolve these arrangements first", "ჯერ მოაგვარეთ ეს საკითხები"],
  reviewImpact: ["Review the affected arrangements", "გადახედეთ დაკავშირებულ შეთანხმებებს"],
  unchanged: ["The match has not changed.", "მატჩი არ შეცვლილა."],
  resolveReload: ["Resolve the items above, then reload and review again.", "მოაგვარეთ ზემოთ ჩამოთვლილი საკითხები, შემდეგ განაახლეთ და გადაამოწმეთ."],
  confirmImpact: ["Confirm below to apply these changes and notify affected participants. Venue follow-up stays separate.", "ცვლილებებისა და მონაწილეთა შეტყობინებისთვის დაადასტურეთ ქვემოთ. მოედნის საკითხი ცალკე მოსაგვარებელია."],
  bookingBeforeEdit: ["Resolve the linked reservation through the stadium workflow before changing the match. The reservation remains linked.", "მატჩის შეცვლამდე მოაგვარეთ დაკავშირებული ჯავშანი სტადიონის მართვის სივრცეში. ჯავშანი მატჩთან დაკავშირებული რჩება."],
  externalBeforeEdit: ["Resolve the external ground arrangement and remove its confirmation before changing the match.", "მატჩის შეცვლამდე მოაგვარეთ მოედნის მფლობელთან შეთანხმება და მოხსენით მისი დადასტურება."],
} as const;
export type JourneyKey = keyof typeof journeyCopy;
export function useJourneyCopy() {
  const { i18n } = useTranslation();
  const language = (i18n.resolvedLanguage || i18n.language || "en").startsWith("ka") ? "ka" : "en";
  return { language, copy: (key: JourneyKey): string => journeyCopy[key][language === "ka" ? 1 : 0] };
}
export function matchTime(instant: string, timeZone: string, language: string) {
  return new Intl.DateTimeFormat(language === "ka" ? "ka-GE" : "en-GB", {
    dateStyle: "medium", timeStyle: "short", timeZone,
  }).format(new Date(instant));
}
export function matchSchedule(start: string, end: string, timeZone: string, language: string) {
  const locale = language === "ka" ? "ka-GE" : "en-GB";
  const day = new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", year: "numeric", timeZone });
  const time = new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit", hour12: false, timeZone });
  const first = new Date(start), last = new Date(end);
  return { date: day.format(first), time: `${time.format(first)} – ${day.format(first) === day.format(last) ? "" : `${day.format(last)}, `}${time.format(last)}` };
}
const georgianStates: Record<string,string> = {
  INVITED: "მოწვეული", ACCEPTED: "მიღებული", DECLINED: "უარყოფილი", WITHDRAWN: "გასული", CANCELLED: "გაუქმებული",
  COMPLETED: "დასრულებული", BOOKED: "დაჯავშნილი", HOST_CONFIRMED: "მასპინძლის მიერ დადასტურებული", PENDING: "მოლოდინში", NEEDED: "საჭიროა",
  NEEDS_ATTENTION: "საჭიროა მოქმედება", NOT_REQUIRED: "არ არის საჭირო", REFEREE: "მსაჯი", ASSISTANT_1: "პირველი ასისტენტი", ASSISTANT_2: "მეორე ასისტენტი",
  REPLACEMENT_NEEDED: "საჭიროა შემცვლელი", RESOLVED: "მოგვარებული", ARRANGED: "შეთანხმებული", OPEN: "ღია", CLOSED: "დახურული", EXPIRED: "ვადაგასული",
  PROPOSAL: "შეთავაზება", OPPONENT: "მეტოქე", CHAT: "საუბარი", VENUE_BOOKING: "მოედნის ჯავშანი", EXTERNAL_VENUE: "გარე მოედანი", REVISE: "ცვლილება", CANCEL: "გაუქმება", VENUE: "მოედანი",
};
export function journeyLabel(value: string, language: string) {
  return language === "ka" && georgianStates[value] ? georgianStates[value] : value.toLowerCase().replaceAll("_", " ").replace(/^./, v => v.toUpperCase());
}
