import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Archive, ArrowLeft, ArrowRight, Bell, BriefcaseBusiness, CalendarDays, Check, CheckCheck, ChevronRight, CircleHelp, Eye, FileText, Flag, HeartHandshake, House, ImagePlus, Inbox, LayoutGrid, MapPin, Menu, MessageSquare, MoreHorizontal, Pencil, Plus, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, Trash2, Users, X } from 'lucide-react';
import { campaignCategories, emptyDraft, example, initialRecords, jobCategories, meta, money, productCategories, stock, type Draft, type Editor, type RecordItem, type Section } from './data';
import './opportunities-preview.css';

const icons = {store: ShoppingBag, campaigns: HeartHandshake, jobs: BriefcaseBusiness};
const sectionLabel = {store: 'Store', campaigns: 'Campaigns', jobs: 'Jobs'};
const dateLabel = (date: string) => date ? new Intl.DateTimeFormat('en-GB', {day: 'numeric', month: 'short', year: 'numeric'}).format(new Date(`${date}T12:00:00`)) : 'Not set';

function Badge({status}: {status: string}) {
    return <span className="op-badge" data-status={status}><i/>{status}</span>;
}

function ProductArt({item, large = false}: {item: Draft; large?: boolean}) {
    if (item.images[0]) return <img className={`op-product-art ${large ? 'large' : ''}`} src={item.images[0]} alt={item.title || 'Selected product image'}/>;
    return <div className={`op-product-art op-art-${item.artwork || 'empty'} ${large ? 'large' : ''}`} aria-hidden="true">
        {['shirt', 'top'].includes(item.artwork) ? <svg viewBox="0 0 140 140" fill="none"><path d="M47 24 62 19Q70 26 78 19L93 24 121 44 106 66 94 60 94 121 46 121 46 60 34 66 19 44Z" fill={item.artwork === 'shirt' ? '#2f66c6' : '#273140'} stroke={item.artwork === 'shirt' ? '#628ee2' : '#56677d'} strokeWidth="2"/><path d="M60 20Q70 36 80 20M47 25 32 49M93 25 108 49" stroke="#dfe8ff" strokeWidth="5"/><path d="M58 69H82M63 76H77" stroke="#dfe8ff" strokeWidth="3"/><path d="m79 44 5-3 5 3v8l-5 3-5-3Z" fill="#e9efff"/><path d="M48 115H92" stroke="#c9dcff" strokeWidth="2"/></svg>
        : item.artwork === 'scarf' ? <svg viewBox="0 0 140 140" fill="none"><path d="m31 22 32-5 14 97-33 5Z" fill="#215bbb"/><path d="m75 19 33 5-15 97-33-6Z" fill="#e5eaf0"/><path d="m36 50 32-5m-25 49 32-5" stroke="#eef3ff" strokeWidth="14"/><path d="m71 47 32 5m-39 44 32 5" stroke="#3471d6" strokeWidth="14"/><path d="m45 119 1 10m9-12 1 10m9-11 1 10m-4-10-1 10m12-8-1 10m11-9-1 10" stroke="#94b4ef" strokeWidth="3"/></svg>
        : item.artwork === 'ball' ? <svg viewBox="0 0 140 140"><circle cx="70" cy="70" r="43" fill="#e5e8ed" stroke="#b7c1d1" strokeWidth="2"/><path d="m70 49 21 15-8 24H57l-8-24Zm-4-22h14l-8 12Zm-39 48 15 8-8 12Zm19 30 22-2 4 10Zm57-9-7-23 17 1Zm-3-57-9 13 15 7Z" fill="#344359"/><path d="m70 49 2-10m19 25 15-5M83 88l13-15m-39 15-15-5m7-19-10-18m18 42 11 15m15-15-11 25" stroke="#344359" strokeWidth="2"/></svg>
        : item.artwork === 'boots' ? <svg viewBox="0 0 140 140"><path d="m27 76 10-31 22 9 9 17 43 13q18 7 11 19H24q-9-17 3-27" fill="#eeebe5" stroke="#a4adb8" strokeWidth="2"/><path d="m27 103 2 10m23-10 2 10m25-10 2 10m25-10 2 10" stroke="#8396b5" strokeWidth="5"/><path d="m63 65-10 12m20-7L62 82m21-7L73 86" stroke="#2563b5" strokeWidth="3"/></svg>
        : item.artwork === 'membership' ? <ShieldCheck/> : item.artwork === 'camp' ? <Flag/> : <ImagePlus/>}
        {!item.artwork && large && <span>Your cover photo</span>}
    </div>;
}

function Modal({title, children, close}: {title: string; children: ReactNode; close: () => void}) {
    const dialog = useRef<HTMLDialogElement>(null);
    useEffect(() => {const el = dialog.current; el?.showModal(); return () => el?.close();}, []);
    return <dialog className="op-modal" ref={dialog} aria-labelledby="op-modal-title" onCancel={close}>
        <header><h2 id="op-modal-title">{title}</h2><button className="op-icon-button" aria-label="Close dialog" onClick={close}><X size={20}/></button></header>{children}
    </dialog>;
}

function Field({label, hint, required, children, wide = false}: {label: string; hint?: string; required?: boolean; children: ReactNode; wide?: boolean}) {
    return <label className={`op-field ${wide ? 'op-wide' : ''}`}><span>{label}{required && <b aria-hidden="true">*</b>}</span>{children}{hint && <small>{hint}</small>}</label>;
}

function SelectField({label, value, options, change}: {label: string; value: string; options: readonly string[]; change: (value: string) => void}) {
    return <Field label={label}><select aria-label={label} value={value} onChange={e => change(e.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select></Field>;
}

function MenuActions({name, children}: {name: string; children: ReactNode}) {
    const details = useRef<HTMLDetailsElement>(null);
    return <details ref={details} className="op-more" onKeyDown={e => {if (e.key === 'Escape' && details.current) {details.current.open = false; details.current.querySelector('summary')?.focus();}}}>
        <summary aria-label={`More actions for ${name}`}><MoreHorizontal size={19}/></summary>
        <div className="op-more-menu" onClick={e => {if ((e.target as HTMLElement).closest('button') && details.current) details.current.open = false;}}>{children}</div>
    </details>;
}

function LivePreview({section, draft}: {section: Section; draft: Draft}) {
    const isStore = section === 'store', isCampaign = section === 'campaigns';
    const ready = isStore ? [!!draft.title.trim(), Number(draft.price) > 0, draft.images.length > 0 || !!draft.artwork]
        : isCampaign ? [!!draft.title.trim() && !!draft.summary.trim(), !!draft.description.trim() && !!draft.beneficiary.trim(), !draft.goal || !!draft.useOfFunds.trim()]
        : [!!draft.title.trim(), !!draft.description.trim(), draft.engagement !== 'Not specified'];
    const labels = isStore ? ['Name your product', 'Set a price', 'Add a photo · recommended'] : isCampaign ? ['Title and short summary', 'Purpose and beneficiaries', 'Explain the funding goal'] : ['A clear job title', 'Responsibilities · recommended', 'Commitment · recommended'];
    return <aside className="op-preview-column" aria-label={`${sectionLabel[section]} live preview`}>
        <div className="op-preview-kicker"><Eye size={14}/><span>{isStore ? 'SUPPORTER PREVIEW' : isCampaign ? 'CAMPAIGN PREVIEW' : 'CANDIDATE PREVIEW'}</span><span className="op-live-dot">Live</span></div>
        <article className="op-live-card">
            {isStore ? <ProductArt item={draft} large/> : isCampaign ? <div className="op-campaign-cover">{draft.images[0] ? <img src={draft.images[0]} alt="Campaign cover"/> : <><HeartHandshake size={38}/><span>Your campaign cover</span></>}</div> : <div className="op-job-cover"><BriefcaseBusiness size={26}/><span>{draft.engagement}</span></div>}
            <div className="op-live-content"><span className="op-category">{draft.category}</span><h3>{draft.title || (isStore ? 'Your product name' : isCampaign ? 'Your next club project' : 'Your next club opening')}</h3>
                {isStore && <strong className="op-live-price">{draft.price ? money(draft.price, draft.currency) : `${draft.currency} —`}</strong>}
                <p>{(isCampaign ? draft.summary : draft.description) || (isStore ? 'A few details to help supporters choose the right item.' : isCampaign ? 'A short story about the difference your project will make.' : 'Describe the role, the commitment and what your club offers.')}</p>
                {isStore ? <div className="op-size-pills">{draft.variants.map((v, i) => <span key={i}>{v.label || 'Size'}</span>)}</div> : isCampaign ? <><div className="op-progress"><i style={{width: '0%'}}/></div><div className="op-progress-caption"><strong>{draft.goal ? `${money(draft.goal, draft.currency)} goal` : 'No target set'}</strong><span>New campaign</span></div></> : <><div className="op-tags"><span><MapPin size={12}/>Tbilisi</span><span>{draft.age}</span></div><div className="op-application-label"><ArrowRight size={15}/>{draft.application === 'Contact the club' ? 'Contact the club' : 'Apply in GrassKickZ'}</div></>}
            </div>
            <footer><ShieldCheck size={14}/>{isStore ? draft.visibility === 'Published' ? 'Visible in the store after saving' : 'Draft · only your club can see it' : isCampaign ? 'Saved as a draft before publication' : 'Review before opening this role'}</footer>
        </article>
        <div className="op-readiness"><h4>{isStore ? 'The essentials' : isCampaign ? 'Before you publish' : 'Before you post'}</h4>{labels.map((label, i) => <div key={label} className={ready[i] ? 'done' : ''}><span>{ready[i] ? <Check size={12}/> : <i/>}</span>{label}</div>)}</div>
        <p className="op-preview-note"><CircleHelp size={14}/>{isStore ? 'A clear photo and accurate stock help supporters choose.' : isCampaign ? 'A draft only needs a title. Build the rest at your own pace.' : 'Player and coach applications stay in GrassKickZ. Other roles use club contacts.'}</p>
    </aside>;
}

export default function OpportunitiesPreview() {
    const initialTab = new URLSearchParams(location.search).get('tab');
    const [section, setSection] = useState<Section>(initialTab === 'campaigns' || initialTab === 'jobs' ? initialTab : 'store');
    const [records, setRecords] = useState(initialRecords);
    const [editors, setEditors] = useState<Partial<Record<Section, Editor>>>({});
    const [editorVisible, setEditorVisible] = useState<Partial<Record<Section, boolean>>>({});
    const [query, setQuery] = useState(''), [filter, setFilter] = useState('All'), [category, setCategory] = useState('All categories');
    const [message, setMessage] = useState(''), [error, setError] = useState('');
    const [modal, setModal] = useState<{kind: 'discard' | 'archive' | 'reset' | 'applicants' | 'updates'; item?: RecordItem} | null>(null);
    const [mobileNav, setMobileNav] = useState(false);
    const [campaignUpdates, setCampaignUpdates] = useState<Record<number, {title: string; body: string}[]>>({});
    const [updateTitle, setUpdateTitle] = useState(''), [updateBody, setUpdateBody] = useState('');
    const fileUrls = useRef<string[]>([]);
    const main = useRef<HTMLElement>(null);
    const editor = editorVisible[section] ? editors[section] : undefined;
    const spec = meta[section], Icon = icons[section];
    const items = records[section].filter(item => item.status !== 'Archived');
    useEffect(() => () => fileUrls.current.forEach(url => URL.revokeObjectURL(url)), []);
    useEffect(() => {
        if (!Object.values(editors).some(item => item?.dirty)) return;
        const guard = (event: BeforeUnloadEvent) => {event.preventDefault(); event.returnValue = '';};
        window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard);
    }, [editors]);
    const scrollTop = () => window.scrollTo({top: 0, behavior: 'instant'});
    const switchSection = (next: Section) => {
        setSection(next); setQuery(''); setFilter('All'); setCategory('All categories'); setError(''); setMessage(''); setMobileNav(false);
        history.replaceState(null, '', `${location.pathname}?tab=${next}`); scrollTop();
    };
    const openEditor = (item?: RecordItem) => {
        setError(''); setMessage('');
        setEditors(prev => ({...prev, [section]: {step: 0, dirty: false, draft: item ? {...structuredClone(item), visibility: item.status === 'Published' ? 'Published' : 'Draft'} : emptyDraft(section)}}));
        setEditorVisible(prev => ({...prev, [section]: true})); scrollTop();
    };
    const patch = (change: Partial<Draft>) => setEditors(prev => ({...prev, [section]: {...prev[section]!, draft: {...prev[section]!.draft, ...change}, dirty: true}}));
    const goStep = (step: number) => {setEditors(prev => ({...prev, [section]: {...prev[section]!, step}})); setError(''); scrollTop();};
    const closeEditor = (discard = false) => {
        if (editor?.dirty && !discard) {setModal({kind: 'discard'}); return;}
        setEditorVisible(prev => ({...prev, [section]: false})); setEditors(prev => ({...prev, [section]: undefined})); setModal(null); setError(''); scrollTop();
    };
    const validate = (draft: Draft, save: boolean) => {
        if (!draft.title.trim()) {goStep(0); setError(`Add a ${spec.singular === 'product' ? 'product name' : spec.singular === 'campaign' ? 'campaign title' : 'job title'} to continue.`); return false;}
        if (section === 'store' && (save || editor?.step === 1)) {
            if (!Number.isFinite(Number(draft.price)) || Number(draft.price) <= 0 || Number(draft.price) > 99999999.99) {goStep(1); setError('Enter a price greater than zero.'); return false;}
            if (draft.variants.some(v => !v.label.trim() || v.stock === '' || !Number.isInteger(Number(v.stock)) || Number(v.stock) < 0 || Number(v.stock) > 1000000) || new Set(draft.variants.map(v => v.label.trim().toLowerCase())).size !== draft.variants.length) {goStep(1); setError('Give every variant a unique name and a whole stock quantity of zero or more.'); return false;}
        }
        if (section === 'campaigns' && (save || editor?.step === 1)) {
            if ((draft.goal && (Number(draft.goal) <= 0 || !Number.isFinite(Number(draft.goal)))) || (draft.reported && (Number(draft.reported) < 0 || !Number.isFinite(Number(draft.reported))))) {goStep(1); setError('Use a positive funding goal and a reported amount of zero or more.'); return false;}
            if (draft.end && draft.start && draft.end < draft.start) {goStep(1); setError('The end date must be on or after the start date.'); return false;}
            if (draft.reported && !draft.reportedNote.trim()) {goStep(1); setError('Explain where the club-reported funds came from.'); return false;}
        }
        return true;
    };
    const save = (asDraft = false) => {
        if (!editor || !validate(editor.draft, true)) return;
        const draft = editor.draft, original = records[section].find(item => item.id === draft.id);
        const status = section === 'store' ? asDraft ? 'Draft' : draft.visibility : section === 'campaigns' ? original?.status ?? 'Draft' : original?.status ?? 'Open';
        const saved: RecordItem = {...draft, title: draft.title.trim(), id: draft.id ?? Date.now(), status, applicants: original?.applicants ?? 0, updated: 'Just now'};
        setRecords(prev => ({...prev, [section]: original ? prev[section].map(item => item.id === saved.id ? saved : item) : [saved, ...prev[section]]}));
        closeEditor(true); setFilter('All'); setQuery(''); setCategory('All categories'); setMessage(`${saved.title} ${original ? 'updated' : 'saved'} in this preview. No server changes.`);
    };
    const transition = (item: RecordItem, status: string) => {
        if (section === 'campaigns' && status === 'Active' && (!item.summary.trim() || !item.description.trim() || !item.beneficiary.trim() || (item.goal && !item.useOfFunds.trim()))) {openEditor(item); setError('Before publishing, complete the summary, purpose, beneficiaries and how the funding goal will be used.'); return;}
        setRecords(prev => ({...prev, [section]: prev[section].map(current => current.id === item.id ? {...current, status} : current)}));
        setModal(null); setMessage(`${item.title}: ${status.toLowerCase()} in this preview.`);
    };
    const upload = (files: FileList | null) => {
        if (!files || !editor) return;
        const selected = Array.from(files);
        if (editor.draft.images.length + selected.length > 8 || selected.some(file => !file.type.startsWith('image/') || file.size > 10 * 1024 * 1024)) {setError('Choose up to 8 image files, each smaller than 10 MB.'); return;}
        const urls = selected.map(file => URL.createObjectURL(file)); fileUrls.current.push(...urls);
        patch({images: [...editor.draft.images, ...urls]}); setError('');
    };
    const options = section === 'store' ? ['All', 'Published', 'Draft', 'Out of stock'] : section === 'campaigns' ? ['All', 'Active', 'Draft', 'Paused', 'Closed'] : ['All', 'Open', 'Closed'];
    const matchesStatus = (item: RecordItem, status: string) => status === 'All' || (status === 'Out of stock' ? stock(item) === 0 : item.status === status);
    const visible = items.filter(item => matchesStatus(item, filter) && (category === 'All categories' || item.category === category) && `${item.title} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
    const uploadPanel = (draft: Draft) => <div className="op-upload-section"><div className="op-label-row"><span>{section === 'store' ? 'Product photos' : 'Campaign photos'} <small>Optional</small></span><small>{draft.images.length}/8 photos</small></div><label className="op-upload"><ImagePlus size={24}/><span><strong>Choose photos</strong><small>or drop them here · first photo becomes the cover</small></span><input aria-label={`Choose ${spec.singular} photos`} type="file" accept="image/*" multiple onChange={e => {upload(e.currentTarget.files); e.currentTarget.value = '';}}/></label>{draft.images.length > 0 && <div className="op-uploaded">{draft.images.map((url, index) => <div key={url}><img src={url} alt={`Selected photo ${index + 1}`}/>{index === 0 && <span>Cover</span>}<button type="button" aria-label={`Remove photo ${index + 1}`} onClick={() => patch({images: draft.images.filter((_, i) => i !== index)})}><X size={13}/></button></div>)}</div>}<p className="op-field-note">JPG, PNG or another image format. Up to 10 MB each. Files stay in this browser preview.</p></div>;
    const textField = (draft: Draft, key: keyof Draft, label: string, placeholder: string, required = false, lines = 0, max = 2000) => <Field label={label} required={required}><>{lines ? <textarea aria-label={label} rows={lines} maxLength={max} placeholder={placeholder} value={String(draft[key])} onChange={e => patch({[key]: e.target.value})}/> : <input aria-label={label} maxLength={max} placeholder={placeholder} value={String(draft[key])} onChange={e => patch({[key]: e.target.value})}/>}</></Field>;

    return <div className="opportunities-preview" data-section={section}>
        <header className="op-global"><div className="op-global-top"><img className="op-logo" src="/brand/grasskickz-main.png" alt="GrassKickZ"/><div className="op-shell-search"><Search size={16}/><span>Search people, clubs, events…</span></div><div className="op-shell-tools"><span><LayoutGrid size={15}/> Shortcuts</span><img src="/brand/grasskickz-world-wordmark.png" alt="GrassKickZ World"/><MessageSquare size={19}/><Bell size={19}/><b>CO</b></div></div><div className="op-global-nav"><span><House size={15}/>Home</span><span><MapPin size={15}/>Map</span><span><ShieldCheck size={15}/>Clubs</span><span className="selected"><Users size={15}/>My Club</span><span><CalendarDays size={15}/>Schedule</span></div></header>
        <aside className={`op-sidebar ${mobileNav ? 'is-open' : ''}`}><div className="op-club"><span><ArrowLeft size={13}/> Club workspace</span><div><b className="op-club-crest">D</b><div><strong>FC Dinamo Tbilisi</strong><small>Owner · Club management</small></div></div></div><div className="op-sidebar-static"><small>CLUB</small><span><LayoutGrid/>Overview</span><span><Settings/>Settings</span><small>PEOPLE</small><span><Users/>Personnel</span><span><Users/>Players</span><span><Inbox/>Applications <b>1</b></span><small>FOOTBALL</small><span><ShieldCheck/>Squads</span><span><FileText/>Player cards</span><span><Flag/>Tryouts</span></div><small className="op-nav-heading">OPPORTUNITIES</small><nav aria-label="Opportunity workspaces">{(['jobs', 'store', 'campaigns'] as const).map(key => {const ItemIcon = icons[key]; return <button key={key} data-color={key} aria-label={sectionLabel[key]} aria-description={editors[key] ? "Unfinished editor; return to continue" : undefined} className={key === section ? 'active' : ''} aria-current={key === section ? 'page' : undefined} onClick={() => switchSection(key)}><ItemIcon size={17}/>{sectionLabel[key]}{editors[key] && <i aria-hidden="true"/>}</button>;})}</nav><div className="op-sidebar-bottom"><ShieldCheck size={16}/><div>Club workspace<small>Manage what your club shares</small></div></div></aside>
        <main ref={main} className="op-main">
            <div className="op-preview-banner"><span><Pencil size={13}/><strong>Design preview</strong><i/>Sample data · changes stay here</span><button onClick={() => setModal({kind: 'reset'})}>Reset preview</button></div>
            <div className="op-mobile-navigation"><button onClick={() => setMobileNav(!mobileNav)} aria-expanded={mobileNav}><Menu size={18}/> Workspace</button><div>{(['store', 'campaigns', 'jobs'] as const).map(key => <button key={key} aria-pressed={section === key} onClick={() => switchSection(key)}>{sectionLabel[key]}</button>)}</div></div>
            {editor ? <>
                <header className="op-page-heading op-editor-heading"><div><button className="op-back" onClick={() => closeEditor()}><ArrowLeft size={15}/> Back to {section === 'store' ? 'products' : section === 'campaigns' ? 'campaigns' : 'openings'}</button><h1>{editor.draft.id ? `Edit ${spec.singular}` : section === 'store' ? 'Add a product' : section === 'campaigns' ? 'Create a campaign' : 'Post a job'}</h1><p>{section === 'store' ? 'From a few details to a product your supporters can find.' : section === 'campaigns' ? 'One step at a time. Tell the story, set the goal, then review.' : 'Make the opportunity clear so the right people can find it.'}</p></div><button className="op-button op-example" onClick={() => {patch({...example(section), id: editor.draft.id}); setError('');}}><Sparkles size={14}/> Use sample details</button></header>
                <nav className="op-steps" aria-label="Editor steps">{spec.steps.map((label, index) => <button key={label} type="button" onClick={() => goStep(index)} aria-current={editor.step === index ? 'step' : undefined} className={`${editor.step === index ? 'active' : ''} ${editor.step > index ? 'visited' : ''}`}><span>{editor.step > index ? <Check size={15}/> : `0${index + 1}`}</span><strong>{label}</strong>{index < 2 && <ChevronRight size={16}/>}</button>)}</nav>
                {error && <div className="op-error" role="alert">{error}</div>}
                <div className="op-editor-layout"><div className="op-editor-fields"><section className="op-form-card"><header><div className="op-step-number">0{editor.step + 1}</div><div><h2>{spec.steps[editor.step]}</h2><p>{section === 'store' ? ['Show supporters what makes this product worth picking up.', 'A clear price and accurate stock keep the shop useful.', 'Take one last look and choose who can see this product.'][editor.step] : section === 'campaigns' ? ['A clear purpose is the start of a campaign people care about.', 'Targets and dates are optional. A plan makes them meaningful.', 'Add a cover, check the story and save when you’re ready.'][editor.step] : ['What will this person do, and what does your club offer?', 'Help suitable candidates find the opening and know how to apply.', 'Check the details that candidates will see.'][editor.step]}</p></div><small>{editor.step === 2 ? 'Review' : '* Required'}</small></header>
                    <div className="op-form-body">
                    {section === 'store' && editor.step === 0 && <>{textField(editor.draft, 'title', 'Product name', 'e.g. Home Kit 2026/27', true, 0, 120)}<SelectField label="Category" value={editor.draft.category} options={productCategories} change={category => patch({category})}/>{textField(editor.draft, 'description', 'Description', 'Tell supporters about the fit, material and what’s included.', false, 3)}{uploadPanel(editor.draft)}</>}
                    {section === 'store' && editor.step === 1 && <><div className="op-price-row"><Field label="Price per item" required><input aria-label="Price per item" type="number" min="0.01" step="0.01" placeholder="0.00" value={editor.draft.price} onChange={e => patch({price: e.target.value})}/></Field><SelectField label="Currency" value={editor.draft.currency} options={['GEL', 'EUR', 'GBP', 'USD']} change={currency => patch({currency})}/></div><div className="op-section-divider"/><div className="op-label-row"><h3>Sizes & available stock</h3><span>{stock(editor.draft)} items total</span></div><p className="op-field-note">Use “One size” for items without options. Zero stock means sold out.</p><div className="op-suggested-sizes"><span>Quick add</span>{['XS', 'S', 'M', 'L', 'XL', 'XXL'].map(size => <button key={size} disabled={editor.draft.variants.some(v => v.label === size)} onClick={() => patch({variants: [...editor.draft.variants.filter(v => !(v.label === 'One size' && v.stock === '0')), {label: size, stock: '0'}]})}>{size}</button>)}</div><div className="op-variant-table"><div className="op-variant-head"><span>Size / variant</span><span>In stock</span><span/></div>{editor.draft.variants.map((variant, i) => <div className="op-variant-row" key={i}><input aria-label={`Variant ${i + 1}`} maxLength={40} placeholder="e.g. Medium" value={variant.label} onChange={e => patch({variants: editor.draft.variants.map((v, index) => index === i ? {...v, label: e.target.value} : v)})}/><input aria-label={`Stock ${i + 1}`} type="number" min="0" step="1" value={variant.stock} onChange={e => patch({variants: editor.draft.variants.map((v, index) => index === i ? {...v, stock: e.target.value} : v)})}/><button aria-label={`Remove variant ${i + 1}`} disabled={editor.draft.variants.length === 1} className="op-icon-button" onClick={() => patch({variants: editor.draft.variants.filter((_, index) => index !== i)})}><Trash2 size={15}/></button></div>)}</div><button className="op-button op-add-variant" disabled={editor.draft.variants.length >= 20} onClick={() => patch({variants: [...editor.draft.variants, {label: '', stock: '0'}]})}><Plus size={15}/>Add another variant</button></>}
                    {section === 'store' && editor.step === 2 && <><div className="op-review-product"><ProductArt item={editor.draft}/><div><h3>{editor.draft.title || 'Untitled product'}</h3><p>{editor.draft.category}</p><strong>{money(editor.draft.price, editor.draft.currency)}</strong></div><button className="op-text-button" onClick={() => goStep(0)}><Pencil size={14}/>Edit</button></div><div className="op-review-stats"><div><span>Available stock</span><strong>{stock(editor.draft)} items</strong></div><div><span>Variants</span><strong>{editor.draft.variants.map(v => v.label).join(', ')}</strong></div></div><div className="op-section-divider"/><h3>Product visibility</h3><p className="op-field-note">Choose what happens when you save this product.</p>{['Draft', 'Published'].map(value => <label key={value} className={`op-choice ${editor.draft.visibility === value ? 'selected' : ''}`}><input type="radio" name="visibility" checked={editor.draft.visibility === value} onChange={() => patch({visibility: value})}/><span><strong>{value === 'Draft' ? 'Keep as a draft' : 'Publish in the club store'}</strong><small>{value === 'Draft' ? 'Only your club can see it. Publish whenever you’re ready.' : 'Supporters will be able to find this product in your store.'}</small></span>{value === 'Draft' ? <FileText size={19}/> : <Eye size={19}/>}</label>)}<p className="op-inline-note"><ShieldCheck size={16}/>Publishing lists the product. Online checkout remains unavailable.</p></>}
                    {section === 'campaigns' && editor.step === 0 && <>{textField(editor.draft, 'title', 'Campaign title', 'e.g. Community Boot Library', true, 0, 120)}{textField(editor.draft, 'summary', 'Short summary', 'What will this campaign make possible? One or two sentences.', false, 2, 240)}<div className="op-field-row"><SelectField label="Category" value={editor.draft.category} options={campaignCategories} change={category => patch({category})}/>{textField(editor.draft, 'beneficiary', 'Who benefits?', 'e.g. Our academy’s U14 players', false, 0, 240)}</div>{textField(editor.draft, 'description', 'The story behind it', 'Explain the need, your plan and the difference it will make.', false, 4, 5000)}<p className="op-inline-note"><FileText size={16}/>Only a title is needed to save a draft. Add the rest before publishing.</p></>}
                    {section === 'campaigns' && editor.step === 1 && <><div className="op-price-row"><Field label="Funding goal" hint="Optional — leave blank if there is no target."><input aria-label="Funding goal" type="number" min="0.01" step="0.01" placeholder="e.g. 4,000" value={editor.draft.goal} onChange={e => patch({goal: e.target.value})}/></Field><SelectField label="Currency" value={editor.draft.currency} options={['GEL', 'EUR', 'GBP', 'USD']} change={currency => patch({currency})}/></div>{textField(editor.draft, 'useOfFunds', 'How will the funds be used?', 'e.g. 40 pairs of boots, cleaning supplies and storage.', false, 3)}<div className="op-field-row"><Field label="Start date" hint="Optional"><input aria-label="Start date" type="date" value={editor.draft.start} onChange={e => patch({start: e.target.value})}/></Field><Field label="End date" hint="Optional"><input aria-label="End date" type="date" value={editor.draft.end} min={editor.draft.start} onChange={e => patch({end: e.target.value})}/></Field></div><details className="op-disclosure" open={editor.draft.reported ? true : undefined}><summary><span><strong>Already received funds elsewhere?</strong><small>Add a club-reported amount · optional</small></span><Plus size={16}/></summary><div><p className="op-field-note">This figure is labelled club-reported. It is not a verified online contribution.</p><Field label="Club-reported amount"><input type="number" aria-label="Club-reported amount" min="0" step="0.01" value={editor.draft.reported} onChange={e => patch({reported: e.target.value})}/></Field>{textField(editor.draft, 'reportedNote', 'Where did these funds come from?', 'Explain the source and when the funds were received.', !!editor.draft.reported, 2, 1000)}</div></details></>}
                    {section === 'campaigns' && editor.step === 2 && <>{uploadPanel(editor.draft)}<div className="op-section-divider"/><div className="op-label-row"><h3>Your campaign at a glance</h3><button className="op-text-button" onClick={() => goStep(0)}><Pencil size={14}/>Edit story</button></div><dl className="op-review-list"><div><dt>Campaign</dt><dd>{editor.draft.title || 'Not named yet'}</dd></div><div><dt>For</dt><dd>{editor.draft.beneficiary || 'Not added yet'}</dd></div><div><dt>Goal</dt><dd>{editor.draft.goal ? money(editor.draft.goal, editor.draft.currency) : 'No target'}</dd></div><div><dt>Dates</dt><dd>{dateLabel(editor.draft.start)} — {dateLabel(editor.draft.end)}</dd></div></dl><p className="op-inline-note"><ShieldCheck size={16}/>New campaigns save as drafts. Publish from the campaign list once the story is ready.</p></>}
                    {section === 'jobs' && editor.step === 0 && <>{textField(editor.draft, 'title', 'Job title', 'e.g. U14 goalkeeper coach', true, 0, 120)}<div className="op-field-row"><SelectField label="Role category" value={editor.draft.category} options={jobCategories} change={category => patch({category})}/><SelectField label="Commitment" value={editor.draft.engagement} options={['Not specified', 'Paid role', 'Volunteer role', 'Paid or volunteer']} change={engagement => patch({engagement})}/></div>{textField(editor.draft, 'description', 'About the role', 'Describe the responsibilities, location, expected hours and what your club offers.', false, 6)}<p className="op-field-note">Useful details: responsibilities · training days · location · experience · what you offer</p></>}
                    {section === 'jobs' && editor.step === 1 && <><h3>Who are you looking for?</h3><p className="op-field-note">Keep these broad unless the opening is for a specific team or level.</p><div className="op-field-row"><SelectField label="Age group" value={editor.draft.age} options={['Any age group', 'U8', 'U10', 'U12', 'U14', 'U16', 'U18', 'Senior']} change={age => patch({age})}/><SelectField label="Experience" value={editor.draft.experience} options={['Any experience', 'Experienced', 'Licensed']} change={experience => patch({experience})}/></div><div className="op-section-divider"/><h3>How should candidates apply?</h3>{['Coach application', 'Player application', 'Contact the club'].map(value => <label key={value} className={`op-choice ${editor.draft.application === value ? 'selected' : ''}`}><input type="radio" name="application" checked={editor.draft.application === value} onChange={() => patch({application: value})}/><span><strong>{value}</strong><small>{value === 'Contact the club' ? 'For other roles. Candidates use your public club contact details.' : 'Receive and review applications here in GrassKickZ.'}</small></span>{value === 'Contact the club' ? <MessageSquare size={18}/> : <Inbox size={18}/>}</label>)}</>}
                    {section === 'jobs' && editor.step === 2 && <><div className="op-review-job"><div className="op-feature-icon"><BriefcaseBusiness size={24}/></div><div><h3>{editor.draft.title || 'Untitled opening'}</h3><p>{editor.draft.category} · {editor.draft.engagement}</p></div></div><p className="op-review-description">{editor.draft.description || 'Add a description to help candidates understand the role.'}</p><dl className="op-review-list"><div><dt>Age group</dt><dd>{editor.draft.age}</dd></div><div><dt>Experience</dt><dd>{editor.draft.experience}</dd></div><div><dt>Application route</dt><dd>{editor.draft.application}</dd></div></dl><button className="op-text-button" onClick={() => goStep(0)}><Pencil size={14}/>Edit role details</button><p className="op-inline-note"><Eye size={16}/>{editor.draft.id ? 'Saving keeps the posting’s current open or closed status.' : 'Posting opens this opportunity to candidates. Review the details before continuing.'}</p></>}
                    </div></section></div><LivePreview section={section} draft={editor.draft}/></div>
                <footer className="op-editor-footer"><div><span><CheckCheck size={15}/>Your work stays while you switch tabs</span><small>{section === 'jobs' ? 'New postings open after you post.' : 'You can save a draft and come back to it.'}</small></div><div className="op-footer-actions">{section !== 'jobs' && editor.step !== 2 && <button className="op-button" onClick={() => save(true)}>Save draft</button>}{editor.step > 0 && <button className="op-button" onClick={() => goStep(editor.step - 1)}><ArrowLeft size={15}/>Back</button>}{editor.step < 2 ? <button className="op-button primary" onClick={() => {if (validate(editor.draft, false)) goStep(editor.step + 1);}}>Continue<ArrowRight size={16}/></button> : <button className="op-button primary" onClick={() => save()}><Check size={16}/>{section === 'store' ? 'Save product' : section === 'campaigns' ? 'Save campaign' : editor.draft.id ? 'Save changes' : 'Post job'}</button>}</div></footer>
            </> : <>
                <header className="op-page-heading"><div><div className="op-breadcrumb">Workspace <ChevronRight size={12}/> Opportunities</div><h1><span className="op-feature-icon"><Icon size={23}/></span>{spec.title}</h1><p>{spec.intro}</p></div><button className="op-button primary op-create" onClick={() => openEditor()}><Plus size={17}/>{spec.action}</button></header>
                {message && <div className="op-success" role="status"><Check size={17}/>{message}<button className="op-icon-button" aria-label="Dismiss message" onClick={() => setMessage('')}><X size={15}/></button></div>}
                <div className="op-list-note"><span><ShieldCheck size={15}/>{section === 'store' ? 'Supporters can browse products and prepare their carts. Online checkout is not available yet.' : section === 'campaigns' ? 'Fundraising figures are club-reported. Online contributions are not available yet.' : 'Player and coach applications arrive here. Other roles direct candidates to the club.'}</span></div>
                <div className="op-list-toolbar"><div className="op-filter-tabs" aria-label={`${sectionLabel[section]} status filters`}>{options.map(value => <button key={value} className={filter === value ? 'active' : ''} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value === 'All' ? section === 'store' ? 'All products' : section === 'campaigns' ? 'All campaigns' : 'All openings' : value === 'Draft' ? 'Drafts' : value}<span>{items.filter(item => matchesStatus(item, value)).length}</span></button>)}</div><div className="op-search-row"><label className="op-search"><Search size={17}/><input aria-label={`Search ${sectionLabel[section].toLowerCase()}`} placeholder={section === 'store' ? 'Search products…' : section === 'campaigns' ? 'Find a campaign…' : 'Search job postings…'} value={query} onChange={e => setQuery(e.target.value)}/>{query && <button onClick={() => setQuery('')} aria-label="Clear search"><X size={14}/></button>}</label><label className="op-category-filter"><span className="op-sr-only">Filter by category</span><select aria-label="Filter by category" value={category} onChange={e => setCategory(e.target.value)}>{['All categories', ...Array.from(new Set(items.map(item => item.category)))].map(c => <option key={c}>{c}</option>)}</select></label><span className="op-result-count">{visible.length} {visible.length === 1 ? spec.singular : section === 'jobs' ? 'openings' : `${spec.singular}s`}</span></div></div>
                {visible.length === 0 && <div className="op-empty"><Search size={30}/><h2>No matches here</h2><p>Try another search or show all {sectionLabel[section].toLowerCase()}.</p><button className="op-button" onClick={() => {setQuery(''); setFilter('All'); setCategory('All categories');}}>Clear filters</button></div>}
                {section === 'store' && visible.length > 0 && <section className="op-product-table" aria-label="Managed products"><div className="op-product-table-head"><span>Product</span><span>Price</span><span>Stock</span><span>Visibility</span><span/></div>{visible.map(item => <article className="op-product-row" key={item.id}><div className="op-product-name"><ProductArt item={item}/><div><h2>{item.title}</h2><p>{item.category} <span>· {item.variants.length} {item.variants.length === 1 ? 'variant' : 'variants'}</span></p></div></div><strong className="op-product-price">{money(item.price, item.currency)}</strong><div className="op-stock" data-low={stock(item) <= 5}><strong>{stock(item) === 0 ? 'Out of stock' : `${stock(item)} available`}</strong><small>{stock(item) === 0 ? 'Add stock to sell' : stock(item) <= 5 ? 'Running low' : 'Stock ready'}</small></div><Badge status={item.status}/><div className="op-row-actions"><button className="op-button op-edit" aria-label={`Edit ${item.title}`} onClick={() => openEditor(item)}><Pencil size={14}/>Edit</button><MenuActions name={item.title}><button onClick={() => transition(item, item.status === 'Published' ? 'Draft' : 'Published')}><Eye size={15}/>{item.status === 'Published' ? 'Hide from store' : 'Publish product'}</button><button className="danger" onClick={() => setModal({kind: 'archive', item})}><Archive size={15}/>Archive product</button></MenuActions></div></article>)}</section>}
                {section === 'campaigns' && visible.length > 0 && <section className="op-campaign-list" aria-label="Managed campaigns">{visible.map(item => <article className="op-campaign-row" key={item.id}><div className="op-campaign-thumbnail">{item.images[0] ? <img src={item.images[0]} alt="Campaign cover"/> : <HeartHandshake size={34}/>}</div><div className="op-campaign-main"><div className="op-campaign-eyebrow"><span className="op-category">{item.category}</span><Badge status={item.status}/></div><h2>{item.title}</h2><p>{item.summary}</p><div className="op-campaign-meta"><span><CalendarDays size={13}/>{item.end ? `Until ${dateLabel(item.end)}` : 'No end date'}</span><span>Edited {item.updated}</span></div></div><div className="op-campaign-funding"><div><strong>{money(item.reported, item.currency)}</strong><span>{item.goal ? `of ${money(item.goal, item.currency)}` : 'No target'}</span></div><div className="op-progress"><i style={{width: `${item.goal ? Math.min(100, Number(item.reported || 0) / Number(item.goal) * 100) : 0}%`}}/></div><small>Club-reported funds</small><div className="op-row-actions"><button className="op-button" onClick={() => openEditor(item)} aria-label={`Edit ${item.title}`}><Pencil size={14}/>Edit campaign</button><MenuActions name={item.title}>{item.status !== 'Closed' && <button onClick={() => transition(item, item.status === 'Active' ? 'Paused' : 'Active')}><Eye size={15}/>{item.status === 'Active' ? 'Pause campaign' : item.status === 'Draft' ? 'Publish campaign' : 'Resume campaign'}</button>}{item.status !== 'Draft' && <button onClick={() => {setUpdateTitle(''); setUpdateBody(''); setModal({kind: 'updates', item});}}><MessageSquare size={15}/>Post an update</button>}{['Active', 'Paused'].includes(item.status) && <button onClick={() => transition(item, 'Closed')}><CheckCheck size={15}/>Close campaign</button>}<button className="danger" onClick={() => setModal({kind: 'archive', item})}><Archive size={15}/>Archive campaign</button></MenuActions></div></div></article>)}</section>}
                {section === 'jobs' && visible.length > 0 && <section className="op-jobs-list" aria-label="Managed jobs">{visible.map(item => <article className="op-job-row" key={item.id}><div className="op-job-mark"><BriefcaseBusiness size={24}/></div><div className="op-job-main"><div><h2>{item.title}</h2><Badge status={item.status}/></div><p>{item.category} · {item.engagement}</p><div className="op-tags"><span>{item.age}</span><span>{item.application === 'Contact the club' ? 'Club contact' : 'In-app applications'}</span></div></div><div className="op-row-actions">{item.application !== 'Contact the club' && <button className="op-button op-applicants" aria-label={`View applicants for ${item.title}`} onClick={() => setModal({kind: 'applicants', item})}><Users size={15}/><strong>{item.applicants}</strong> applicants<ChevronRight size={14}/></button>}<button className="op-button op-edit" aria-label={`Edit ${item.title}`} onClick={() => openEditor(item)}><Pencil size={14}/>Edit</button><MenuActions name={item.title}><button onClick={() => transition(item, item.status === 'Open' ? 'Closed' : 'Open')}><CheckCheck size={15}/>{item.status === 'Open' ? 'Close posting' : 'Reopen posting'}</button><button className="danger" onClick={() => setModal({kind: 'archive', item})}><Trash2 size={15}/>Remove posting</button></MenuActions></div></article>)}</section>}
                <footer className="op-list-footer"><span><Icon size={14}/>{section === 'store' ? 'A clear collection starts with good details and accurate stock.' : section === 'campaigns' ? 'Keep the community involved with clear goals and regular updates.' : 'Clear role descriptions help the right people take the next step.'}</span><span>FC Dinamo Tbilisi</span></footer>
            </>}
        </main>
        {modal && <Modal title={modal.kind === 'discard' ? 'Leave this editor?' : modal.kind === 'archive' ? section === 'jobs' ? 'Remove this posting?' : `Archive this ${spec.singular}?` : modal.kind === 'reset' ? 'Reset the design preview?' : modal.kind === 'applicants' ? 'Applications' : 'Post a campaign update'} close={() => setModal(null)}>
            {modal.kind === 'discard' && <><p>Your unsaved changes will be discarded. You can also keep editing or switch workspace tabs to return later.</p><div className="op-modal-actions"><button className="op-button" onClick={() => setModal(null)}>Keep editing</button><button className="op-button danger" onClick={() => closeEditor(true)}>Discard changes</button></div></>}
            {modal.kind === 'archive' && modal.item && <><p><strong>{modal.item.title}</strong> will be removed from this preview’s active list. The server is unaffected.</p><div className="op-modal-actions"><button className="op-button" onClick={() => setModal(null)}>Cancel</button><button className="op-button danger" onClick={() => transition(modal.item!, 'Archived')}>Confirm {section === 'jobs' ? 'removal' : 'archive'}</button></div></>}
            {modal.kind === 'reset' && <><p>This restores the sample products, campaigns and jobs, and clears unfinished preview editors. It does not change the app.</p><div className="op-modal-actions"><button className="op-button" onClick={() => setModal(null)}>Keep preview</button><button className="op-button danger" onClick={() => {setRecords(initialRecords()); setCampaignUpdates({}); setEditors({}); setEditorVisible({}); setMessage(''); setError(''); setModal(null); setFilter('All'); setQuery(''); setCategory('All categories'); fileUrls.current.forEach(url => URL.revokeObjectURL(url)); fileUrls.current = []; scrollTop();}}>Reset sample data</button></div></>}
            {modal.kind === 'applicants' && <><p>{modal.item?.title}</p><div className="op-inline-note">Sample applicants for the design preview. The existing application review flow stays in the app.</div>{modal.item?.applicants ? ['Candidate A', 'Candidate B', 'Candidate C'].slice(0, modal.item.applicants).map((name, i) => <div className="op-sample-applicant" key={name}><span>{i + 1}</span><div><strong>{name}</strong><small>Coach application · awaiting review</small></div><Badge status="Pending"/></div>) : <div className="op-empty"><Inbox/><p>No pending applicants for this sample opening.</p></div>}</>}
            {modal.kind === 'updates' && <form onSubmit={e => {e.preventDefault(); if (!updateTitle.trim() || !updateBody.trim() || !modal.item) return; const campaignId = modal.item.id; setCampaignUpdates(previous => ({...previous, [campaignId]: [...(previous[campaignId] ?? []), {title: updateTitle.trim(), body: updateBody.trim()}]})); setMessage(`“${updateTitle}” added to this preview. No update was sent or published on the server.`); setModal(null);}}><p>Keep supporters in the loop about <strong>{modal.item?.title}</strong>.</p><Field label="Update title" required><input required maxLength={120} value={updateTitle} onChange={e => setUpdateTitle(e.target.value)}/></Field><Field label="What’s new?" required><textarea rows={4} required maxLength={2000} value={updateBody} onChange={e => setUpdateBody(e.target.value)}/></Field><div className="op-modal-actions"><button type="button" className="op-button" onClick={() => setModal(null)}>Cancel</button><button className="op-button primary">Save preview update</button></div>{(campaignUpdates[modal.item?.id ?? 0] ?? []).length > 0 && <section className="op-saved-updates"><h3>Updates in this preview</h3>{campaignUpdates[modal.item!.id].map((update, index) => <article key={index}><h4>{update.title}</h4><p>{update.body}</p></article>)}</section>}</form>}
        </Modal>}
    </div>;
}
