import { journeyPlaces } from './publishedJourney';
import { useEffect,useState } from 'react';
import { Check,Clock,ShieldCheck,RefreshCw } from 'lucide-react';
import { extractApiErrorMessage } from '../../utils/apiError';
import { planGet,planPost,permissionDecision,dateTime,type FamilyPlan,type PlanPlace } from './api';

export function FamilyPlans({childId,onPlaces,onFocus}:{childId?:number;onPlaces?:(places:PlanPlace[])=>void;onFocus?:(place:PlanPlace)=>void}={}){
  const [items,setItems]=useState<FamilyPlan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');void planGet<FamilyPlan[]>('/family',c.signal).then(setItems).catch(e=>{if(!c.signal.aborted)setError(extractApiErrorMessage(e,'Could not load family itineraries.'));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[refresh]);
  const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();setRefresh(v=>v+1);}catch(e){setError(extractApiErrorMessage(e,'Could not record your decision.'));}finally{setBusy(false);}};
  return <section className="mp-family" aria-label="Family itineraries"><div className="mp-section-heading"><div><span className="atlas-eyebrow">SHARED BY YOUR CLUB</span><h2>Your next journey.</h2></div><button className="mp-icon" aria-label="Refresh family itineraries" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={17}/></button></div>
    {loading&&<p role="status">Loading published itineraries…</p>}{error&&<p role="alert" className="mp-alert">{error}</p>}
    {!loading&&!items.length&&<div className="mp-empty"><ShieldCheck size={32}/><h3>No journeys shared with you yet.</h3><p>Published journeys appear here when you are a participating player or a verified parent or guardian. Your staff plans stay in the planning workspace, including private drafts.</p><p>Only the published itinerary is shared. Staff notes and draft changes stay private.</p></div>}
    {items.filter(p=>!childId||p.child_id===childId).map(p=><PublishedJourney key={p.id} p={p} busy={busy} action={action} onPlaces={onPlaces} onFocus={onFocus}/>)}
  </section>;
}

export function PublishedJourney({p,busy,action,onPlaces,onFocus}:{p:FamilyPlan;busy:boolean;action:(fn:()=>Promise<unknown>)=>Promise<void>;onPlaces?:(places:PlanPlace[])=>void;onFocus?:(place:PlanPlace)=>void}){
 const [now,setNow]=useState(Date.now);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 return <article className="mp-family-card" ><span className="mp-pill">Version {p.version} · {p.child_name}</span><h3>{p.title}</h3><p>{p.club_name} · {p.itinerary.destination}</p><p className="mp-muted">{dateTime(p.itinerary.startsAt,p.itinerary.timezone)} — {dateTime(p.itinerary.endsAt,p.itinerary.timezone)} · {p.itinerary.timezone}</p>
      {onPlaces&&<button className="mp-secondary" onClick={()=>onPlaces(journeyPlaces(p))}>Show journey on map</button>}
      {onFocus&&<div className="mp-actions">{journeyPlaces(p).map(place=><button className="mp-link" key={place.key} onClick={()=>onFocus(place)}>{place.name}</button>)}</div>}
      <dl className="mp-facts"><dt>Meet</dt><dd>{p.itinerary.meetingPoint}</dd><dt>Collect</dt><dd>{p.itinerary.collectionPoint}</dd><dt>Contact</dt><dd>{p.itinerary.supervisionContact}</dd></dl>
      {p.itinerary.message&&<p className="mp-note">{p.itinerary.message}</p>}
      <ol className="mp-timeline">{p.itinerary.activities.map((a,i)=><li key={i}><span className="mp-time">{dateTime(a.startsAt,p.itinerary.timezone)}</span><div><strong>{a.title}</strong><p>{a.place?.name||a.kind.toLowerCase()}</p>{a.place?.address&&<small>{a.place.address}</small>}</div></li>)}</ol>
      {!!p.itinerary.arrangements?.length&&<section className="mp-inset"><h4>Shared arrangements</h4>{p.itinerary.arrangements.map((a,i)=><p key={i}>{a.title}{a.place ? ` · ${a.place}` : ''}</p>)}</section>}<div className="mp-travel-status"><Clock size={18}/><div><strong>{p.travel.passenger?.status||p.travel.status}</strong><p>{p.travel.source||'Journey preparation'}{p.travel.updated_at?` · Updated ${dateTime(p.travel.passenger?.updated_at||p.travel.updated_at,p.itinerary.timezone)}`:''}</p>{p.travel.updated_at&&now-Date.parse(p.travel.passenger?.updated_at||p.travel.updated_at)>3600000&&p.travel.status==='DEPARTED'&&<p>There is no recent staff update. Contact the supervision lead if you need help.</p>}</div></div>
      {p.viewer==='GUARDIAN'&&<div className="mp-decision"><h4>{p.child_name} · journey attendance</h4><p>RSVP for the whole journey. Travel permission and boarding remain separate.</p><p role="status">{p.response?.status==='GOING'?'Going':p.response?.status==='NOT_GOING'?'Not going':p.response?.status==='RECONFIRMATION_REQUIRED'?'Confirm the updated journey':'Awaiting your reply'}</p>{p.canRespond&&<div className="mp-actions"><button className="mp-primary" disabled={busy} onClick={()=>void action(()=>planPost(`/${p.plan_id}/journey-response`,{version:p.version,subjectId:p.child_id,response:'GOING'}))}>I am going</button><button className="mp-secondary" disabled={busy} onClick={()=>void action(()=>planPost(`/${p.plan_id}/journey-response`,{version:p.version,subjectId:p.child_id,response:'NOT_GOING'}))}>I cannot go</button></div>}</div>}
      {p.viewer==='PLAYER'?<div className="mp-decision"><h4>Your journey response</h4><p>Your reply is shared with the planning team for version {p.version}. Staff record boarding and arrival separately.</p><p role="status"><strong>{p.response?.status==='GOING'?"You're going":p.response?.status==='NOT_GOING'?"You're not going":'Attendance awaiting reply'}</strong>{p.response?.acknowledged?' · Update read':''}</p><div className="mp-actions">{!p.response?.acknowledged&&<button className="mp-secondary" disabled={busy} onClick={()=>void action(()=>planPost(`/${p.plan_id}/my-response`,{version:p.version,response:'READ'}))}>I have read this itinerary</button>}{p.canRespond&&<><button className="mp-primary" disabled={busy||p.response?.status==='GOING'} onClick={()=>void action(()=>planPost(`/${p.plan_id}/my-response`,{version:p.version,response:'GOING'}))}>I'm going</button><button className="mp-secondary" disabled={busy||p.response?.status==='NOT_GOING'} onClick={()=>void action(()=>planPost(`/${p.plan_id}/my-response`,{version:p.version,response:'NOT_GOING'}))}>I'm not going</button></>}</div>{!p.canRespond&&<p>Attendance decisions may require guardian review or the journey may already be underway. Contact the supervision lead for help.</p>}</div>:<><div className="mp-decision"><h4>Read the update</h4><p>Acknowledgement tells the club you have seen version {p.version}.</p>{p.acknowledged_at?<span className="mp-success"><Check size={16}/>Acknowledged</span>:<button className="mp-primary" disabled={busy} onClick={()=>void action(()=>planPost(`/${p.plan_id}/acknowledge`,{version:p.version,childId:p.child_id}))}>I have read this itinerary</button>}</div>
      <div className="mp-decision"><h4>Travel permission · {p.permission.status.toLowerCase()}</h4><p>{p.permission.data.wording}</p><div className="mp-actions">{p.permission.transitions.filter(s=>['GRANTED','DECLINED','REVOKED'].includes(s)).map(s=><button key={s} className={s==='GRANTED'?'mp-primary':'mp-secondary'} disabled={busy} onClick={()=>void action(()=>permissionDecision(p.club_id,p.permission_id,p.permission.revision,s))}>{s==='GRANTED'?'Give travel permission':s==='REVOKED'?'Withdraw permission':'Decline permission'}</button>)}</div></div></>}
    </article>;
}
