import { JourneyExplorer } from './JourneyExplorer';
import { draftItinerary,type JourneyMapState } from './journeyModel';
import { MyJourneys } from './MyJourneys';
import { ResponsibilitiesWindow } from './ResponsibilitiesWindow';
import { SmoothSelect } from './SmoothSelect';
import { useCallback,useEffect,useMemo,useRef,useState,type CSSProperties } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { ArrowLeft,ArrowUpRight,Check,CheckCircle2,ChevronRight,ClipboardList,Clock,Compass,Flag,Loader2,MapPin,Menu,PanelLeft,PanelRight,Plus,RefreshCw,Save,ShieldCheck,Users,Wallet,X } from 'lucide-react';
import { extractApiErrorMessage } from '../../utils/apiError';
import { useDialogFocus } from '../../components/workspace/useDialogFocus';
import { CostsEditor,Field,PlacesEditor,PlanDetails,ScheduleEditor } from './PlanEditors';
import { FamilyPlanWindow } from './FamilyPlanWindow';
import { ChangeReview } from './ChangeReview';
import { dateTime,emptyDraft,money,planGet,planPost,savePlan,type Plan,type PlanContext,type PlanDraft,type PlanPlace,type PlanSummary } from './api';
import './planning.css';
import './recovery-ui.css';
import { useMapWorkspaceChrome, setPlanningNavigation } from '../../context/mapWorkspaceChrome';
import { PlanningMapTools } from './PlanningMapTools';
import { usePlanningPanels, type PanelWidths } from './PlanningPanels';
import { locationRoles, putPlanningPlace, planningStops, type LocationRole, type PickTarget } from './mapPlanning';

import { getAuthSessionId } from '../../utils/authStorage';
import { draftFingerprint,forgetPlan,recoverPlan,recoverSelection,rememberSelection,recoveryKey,rememberPlan,validatePlanDraft } from './draftRecovery';

type Tab='plan'|'places'|'schedule'|'costs'|'people'|'travel'|'family';
const tabs=[{id:'plan',label:'Plan',icon:ClipboardList},{id:'places',label:'Places',icon:MapPin},{id:'schedule',label:'Schedule',icon:Clock},{id:'costs',label:'Costs',icon:Wallet},{id:'people',label:'People',icon:Users},{id:'travel',label:'Travel',icon:Flag}] as const;
export default function MapPlanWorkspace({initialClubId,candidate,onCandidateUsed,onPlaces,onFocus,onClose,onMapClick,onPickMode,onPreview,onLayout,onRoute,onJourney}:{initialClubId?:number|null;candidate:PlanPlace|null;onCandidateUsed:()=>void;onPlaces:(places:PlanPlace[])=>void;onFocus:(place:PlanPlace)=>void;onExplore:()=>void;onClose:()=>void;onMapClick:(handler:((place:PlanPlace)=>void)|null)=>void;onPickMode:(target:PickTarget|null)=>void;onPreview:(place:PlanPlace|null)=>void;onLayout:(widths:PanelWidths)=>void;onRoute?:(places:PlanPlace[])=>void;onJourney?:(state:JourneyMapState|null)=>void}){
  const [params,setParams]=useSearchParams();
  const [recovered]=useState(()=>recoverPlan(params.has('plan')?`plan:${params.get('plan')}`:params.has('draft')?`draft:${params.get('draft')}`:undefined));
  const [lastSelection]=useState(()=>!params.has('plan')&&!params.has('draft')?recoverSelection():null);
  const [responsibilities,setResponsibilities]=useState(false);
  const [authSession]=useState(getAuthSessionId);
  const selected=Number(params.get('plan'))||(!params.has('draft')?recovered?.planId||(!recovered?lastSelection?.planId:0)||0:0);
  const family=params.get('familyWindow')==='1'||params.get('plans')==='family'&&!params.has('journey');
  const viewKind=params.get('view');
  const viewMode=viewKind==='journey'||viewKind==='draft';
  const [journeyActive,setJourneyActive]=useState(false);
  const updateJourney=useCallback((state:JourneyMapState|null)=>{setJourneyActive(Boolean(state));onJourney?.(state);},[onJourney]);
  const [contexts,setContexts]=useState<PlanContext[]>([]),[club,setClub]=useState(Number(params.get('club'))||recovered?.clubId||lastSelection?.clubId||initialClubId||0),[squad,setSquad]=useState(Number(params.get('squad'))||recovered?.squadId||lastSelection?.squadId||0),[plans,setPlans]=useState<PlanSummary[]>([]);
  const [plan,setPlan]=useState<Plan|null>(null),[draft,setDraft]=useState<PlanDraft|null>(null);
  const viewItinerary=useMemo(()=>viewKind==='journey'&&plan?.published?plan.published:draft?draftItinerary(draft):null,[viewKind,plan?.published,draft]);
  const [recoveryRevision,setRecoveryRevision]=useState<number|null>(null),[recoveryWarning,setRecoveryWarning]=useState(''),[createdNotice,setCreatedNotice]=useState(false),[validation,setValidation]=useState<{field:string;message:string}|null>(null),[saving,setSaving]=useState<'creating'|'saving'|null>(null);
  const inFlight=useRef(false),pendingRoute=useRef<{planId?:number;draftId?:string}|null>(null);
  const routePending=Boolean(pendingRoute.current&&(pendingRoute.current.planId?Number(params.get('plan'))!==pendingRoute.current.planId:params.get('draft')!==pendingRoute.current.draftId));
  const [tab,setTab]=useState<Tab>('plan'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[mobileMap,setMobileMap]=useState(false),[preview,setPreview]=useState(false),[review,setReview]=useState(false);
  const [pending,setPending]=useState<null|(()=>void)>(null),[requestId,setRequestId]=useState(()=>params.get('draft')||recovered?.requestId||crypto.randomUUID());
  const [pickTarget,setPickTarget]=useState<PickTarget|null>(null),[pointCandidate,setPointCandidate]=useState<PlanPlace|null>(null),[activitySeed,setActivitySeed]=useState<PlanPlace|null>(null);
  const [connections,setConnections]=useState(true);
  const stops=useMemo(()=>planningStops({places:draft?.places||[],activities:draft?.activities||[]}),[draft?.places,draft?.activities]);
  useEffect(()=>{if(!viewMode)onRoute?.(connections?stops:[]);},[connections,stops,onRoute,viewMode]);
  const pickReceiver=useRef<((place:PlanPlace)=>void)|null>(null);
  const panels=usePlanningPanels(useCallback((widths:PanelWidths)=>onLayout({...widths,right:!loading&&!contexts.length&&!journeyActive?0:widths.right}),[onLayout,loading,contexts.length,journeyActive])),chrome=useMapWorkspaceChrome();
  const pristine=useRef<PlanDraft|null>(null),workspace=useRef<HTMLDivElement>(null);
  const context=contexts.find(c=>c.id===club),dirty=Boolean(draft&&draftFingerprint(draft)!==draftFingerprint(plan?.draft||pristine.current||draft));
  const availableParticipantIds=useMemo(()=>new Set(context?.participants.filter(p=>p.squad_id===squad).map(p=>p.id)||[]),[context,squad]);
  const unavailableParticipants=draft?.participants.filter(id=>!availableParticipantIds.has(id))||[];
  const mounted=useRef(true),skipLoad=useRef<number|null>(null);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const publishDialog=useRef<HTMLElement>(null),unsavedDialog=useRef<HTMLElement>(null);
  useDialogFocus(preview,publishDialog,()=>setPreview(false));useDialogFocus(Boolean(pending),unsavedDialog,()=>setPending(null));
  const retain=(next:PlanDraft,base=plan?.draft||pristine.current||next,planId=plan?.id||0,revision=recoveryRevision??plan?.revision??null)=>{
    const ok=rememberPlan({key:recoveryKey(planId,requestId),planId,clubId:club,squadId:squad,requestId,baseRevision:revision,baseDraft:base,draft:next,savedAt:Date.now()},authSession);
    setRecoveryWarning(ok?'':'Local recovery is unavailable in this browser. Save your plan before leaving.');
  };
  const change=(patch:Partial<PlanDraft>)=>{if(!draft)return;const next={...draft,...patch};setDraft(next);setNotice('');setValidation(null);retain(next);};
  useEffect(()=>{const c=new AbortController();void planGet<PlanContext[]>('/context',c.signal).then(data=>{setContexts(data);setClub(v=>data.some(c=>c.id===v)?v:data.find(c=>c.name.includes('Dinamo'))?.id||data[0]?.id||0);}).catch(e=>{if(!c.signal.aborted)setError(extractApiErrorMessage(e,'Could not load your planning access.'));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[]);
  useEffect(()=>{if(routePending)return;pendingRoute.current=null;const id=params.get('draft');if(selected||!id||(id===requestId&&!plan))return;setPlan(null);setDraft(null);setRequestId(id);setRecoveryRevision(null);setValidation(null);setCreatedNotice(false);setNotice('');setClub(Number(params.get('club'))||club);setSquad(Number(params.get('squad'))||squad);},[params,requestId,selected,club,squad,plan,routePending]);
  useEffect(()=>{if(routePending||!context||(params.has('draft')&&params.get('draft')!==requestId))return;setSquad(v=>context.squads.some(s=>s.id===v)?v:context.squads[0]?.id||0);if(!selected){setLoading(false);setDraft(d=>{if(d)return d;const backup=recoverPlan(`draft:${requestId}`)||(!params.has('draft')?recovered:null);const allowed=backup&&!backup.planId&&backup.clubId===club&&context.squads.some(s=>s.id===backup.squadId&&s.canEdit);const initial=allowed?backup.draft:emptyDraft(context);pristine.current=allowed?backup.baseDraft:initial;return initial;});}if(!selected&&!params.has('draft'))setParams(p=>{p.set('draft',requestId);p.set('club',String(club));return p;},{replace:true});const c=new AbortController();void planGet<PlanSummary[]>(`?clubId=${club}`,c.signal).then(setPlans).catch(e=>{if(!c.signal.aborted)setError(extractApiErrorMessage(e,'Could not load saved plans.'));});return()=>c.abort();},[club,context,selected,refresh,requestId,recovered,params,setParams,routePending]);
  useEffect(()=>{if(routePending||!selected)return;if(skipLoad.current===selected){skipLoad.current=null;return;}const c=new AbortController();setLoading(true);setPlan(null);setDraft(null);setError('');void planGet<Plan>(`/${selected}`,c.signal).then(p=>{if(c.signal.aborted)return;const backup=recoverPlan(`plan:${p.id}`);const canRecover=backup&&p.rights.edit&&backup.clubId===p.club_id&&backup.squadId===p.squad_id;setPlan(p);setDraft(canRecover?backup.draft:p.draft);setRecoveryRevision(canRecover?backup.baseRevision:null);setNotice(canRecover?'Your unsaved changes were recovered.':'');if(canRecover&&backup.baseRevision!==p.revision)setError('This saved plan changed elsewhere. Your recovered work is kept. Reload the saved plan to review before replacing it.');setClub(p.club_id);setSquad(p.squad_id);rememberSelection(p.id,p.club_id,p.squad_id,authSession);}).catch(e=>{if(!c.signal.aborted){setPlan(null);setDraft(null);setError(extractApiErrorMessage(e,'Could not load this plan.'));}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[selected,refresh,routePending,authSession]);
  useEffect(()=>{if(viewMode||!candidate||!draft||!context?.squads.some(s=>s.id===squad&&s.canEdit)||(selected&&!plan?.rights.edit))return;if(!draft.places.some(p=>p.key===candidate.key)&&draft.places.length<60){const next={...draft,places:[...draft.places,candidate]};setDraft(next);const ok=rememberPlan({key:recoveryKey(selected,requestId),planId:selected,clubId:club,squadId:squad,requestId,baseRevision:recoveryRevision??plan?.revision??null,baseDraft:plan?.draft||pristine.current||draft,draft:next,savedAt:Date.now()},authSession);if(!ok)setRecoveryWarning('Local recovery is unavailable in this browser. Save your plan before leaving.');}setTab('places');onCandidateUsed();},[candidate,draft,selected,plan,onCandidateUsed,context,squad,club,requestId,recoveryRevision,authSession,viewMode]);
  useEffect(()=>{if(!viewMode&&contexts.length)onPlaces(draft?.places||[]);},[draft?.places,onPlaces,viewMode,contexts.length]);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const clean=useCallback((fn:()=>void)=>{if(dirty)setPending(()=>fn);else fn();},[dirty]);
  const show=(id:number)=>clean(()=>{pendingRoute.current={planId:id};skipLoad.current=null;setPlan(null);setDraft(null);setRecoveryRevision(null);setCreatedNotice(false);setParams(p=>{p.set('plan',String(id));p.delete('draft');p.set('plans','staff');return p;});});
  const startDraft=(clubId=club,squadId=squad)=>{const nextId=crypto.randomUUID();pendingRoute.current={draftId:nextId};skipLoad.current=null;setLoading(true);setPlan(null);setDraft(null);setRecoveryRevision(null);setCreatedNotice(false);setValidation(null);setError('');setNotice('');setTab('plan');setParams(p=>{p.delete('plan');p.set('draft',nextId);p.set('club',String(clubId));p.set('squad',String(squadId));p.set('plans','staff');return p;});};
  const fresh=()=>clean(()=>startDraft());
  const received=(p:Plan,keptDraft?:PlanDraft)=>{if(!mounted.current)return;pendingRoute.current={planId:p.id};if(selected!==p.id)skipLoad.current=p.id;forgetPlan(recoveryKey(plan?.id||0,requestId),authSession);setPlan(p);rememberSelection(p.id,p.club_id,p.squad_id,authSession);setDraft(keptDraft||p.draft);setRecoveryRevision(null);setNotice(keptDraft?'Plan created. Your newer changes are kept; save them to update it.':'All changes saved');setPlans(list=>[{...p,starts_at:p.draft.startsAt},...list.filter(x=>x.id!==p.id)]);setParams(q=>{q.set('plan',String(p.id));q.delete('draft');if(!q.has('plans'))q.set('plans','staff');return q;},{replace:true});if(keptDraft)retain(keptDraft,p.draft,p.id,p.revision);};
  const persist=async():Promise<Plan|null>=>{
    if(!draft||busy||loading||inFlight.current)return null;
    const invalid=validatePlanDraft(draft);if(invalid){setValidation(invalid);setError('');setTab(invalid.field==='Schedule'?'schedule':'plan');setMobileMap(false);requestAnimationFrame(()=>workspace.current?.querySelector<HTMLInputElement>(`[aria-label="${invalid.field}"]`)?.focus());return null;}
    const invalidTime=workspace.current?.querySelector<HTMLInputElement>('input[type=datetime-local][aria-invalid=true]');if(invalidTime){setValidation({field:invalidTime.getAttribute('aria-label')||'Leaving',message:'Choose a complete, valid date and time before saving.'});invalidTime.focus();return null;}
    inFlight.current=true;setBusy(true);setSaving(plan?'saving':'creating');setError('');setValidation(null);retain(draft);
    try{const result=plan?await savePlan(plan.id,recoveryRevision??plan.revision,draft):await planPost('',{requestId,clubId:club,squadId:squad,draft});const kept=!plan&&draftFingerprint(result.draft)!==draftFingerprint(draft)?draft:undefined;received(result,kept);if(!plan)setCreatedNotice(true);return result;}
    catch(e){setError(extractApiErrorMessage(e,'Could not save. Your changes are protected here; you can retry.'));return null;}finally{inFlight.current=false;setBusy(false);setSaving(null);}
  };
  const switchFamily=()=>setParams(q=>{if(q.has('journey')){if(family)q.delete('familyWindow');else q.set('familyWindow','1');}else q.set('plans',family?'staff':'family');if(plan)q.set('plan',String(plan.id));else if(contexts.length)q.set('draft',requestId);return q;});
  const discard=()=>{forgetPlan(recoveryKey(plan?.id||0,requestId),authSession);setValidation(null);setRecoveryRevision(null);};
  const command=async(path:string,extra:Record<string,unknown>={})=>{
    if(!plan||busy)return;if(dirty){setError('Save your draft before recording a decision or publishing.');return;}setBusy(true);setError('');
    try{received(await planPost(`/${plan.id}/${path}`,{revision:plan.revision,...extra}));setPreview(false);}catch(e){setError(extractApiErrorMessage(e,'The action was not completed.'));}finally{setBusy(false);}
  };
  const budget=draft?.arrangements.reduce((v,a)=>v+a.amountMinor,0)||0,canEdit=plan?.rights.edit??Boolean(context?.squads.find(s=>s.id===squad)?.canEdit);
  const days=draft?Math.max(1,Math.ceil((Date.parse(draft.endsAt)-Date.parse(draft.startsAt))/86400000)):1;
  const finish=()=>clean(()=>{setParams(p=>{p.delete('plans');return p;},{replace:true});onClose();});
  const cancelPick=()=>{setPickTarget(null);setPointCandidate(null);pickReceiver.current=null;onPreview(null);};
  const beginPick=(target:PickTarget,receive?:(place:PlanPlace)=>void)=>{if(!canEdit||busy)return;setPickTarget(target);setPointCandidate(null);pickReceiver.current=receive||null;onPreview(null);setMobileMap(true);};
  const selectedPoint=useCallback((place:PlanPlace)=>{if(!canEdit||busy)return;setPointCandidate(place);},[canEdit,busy]);
  useEffect(()=>{onMapClick(viewMode?null:selectedPoint);return()=>onMapClick(null);},[onMapClick,selectedPoint,viewMode]);
  useEffect(()=>{onPickMode(pickTarget);return()=>onPickMode(null);},[pickTarget,onPickMode]);
  useEffect(()=>{onPreview(pointCandidate);return()=>onPreview(null);},[pointCandidate,onPreview]);
  const usePoint=(place:PlanPlace,target:PickTarget)=>{
    if(!draft||!canEdit||busy)return;const patch=putPlanningPlace(draft,place,target);
    if(patch.places!.length>60){setError('This plan has 60 saved places. Remove one before adding another.');return;}
    const saved=patch.places!.find(p=>p.key===(target in locationRoles?locationRoles[target as LocationRole].key:place.key))!;
    change(patch);if(target==='activity'){if(pickReceiver.current)pickReceiver.current(saved);else{setActivitySeed(saved);setTab('schedule');}}else setTab(target==='place'?'places':'plan');
    cancelPick();setMobileMap(false);
  };
  const showRole=(role:LocationRole)=>{const place=draft?.places.find(p=>p.key===locationRoles[role].key);if(place){onFocus(place);setMobileMap(true);}else beginPick(role);};
  return <div ref={workspace} style={{'--mp-left':`${panels.widths.left}px`,'--mp-right':`${!loading&&!contexts.length&&!journeyActive?0:panels.widths.right}px`} as CSSProperties} className={`mp-workspace ${panels.widths.animated?'mp-panels-animate':''} ${panels.widths.left===0?'mp-workspace--plan-collapsed':''} ${panels.widths.right===0?'mp-workspace--review-collapsed':''} ${mobileMap?'mp-workspace--map':''} ${family?'mp-workspace--family':''} ${tab==='travel'&&plan?.published_version?'mp-travel-focus':''}`}>
    <header className="mp-topbar"><button className="mp-back" aria-label="Explore" onClick={finish}><ArrowLeft size={17}/><span>Explore</span></button><span className="mp-wordmark"><span className="atlas-brand-mark">G</span> WORLD <i>/</i> <strong>{viewMode?'Journey preview':'Planning'}</strong></span><button className="mp-chrome-toggle" aria-label={chrome.navigationExpanded?"Hide navigation":"Show navigation"} title={chrome.navigationExpanded?"Hide navigation":"Show navigation"} aria-expanded={chrome.navigationExpanded} onClick={()=>setPlanningNavigation(!chrome.navigationExpanded)}><Menu size={17}/></button><div className="mp-top-actions"><button className="mp-panel-toggle" aria-label={panels.widths.left?"Collapse plan panel":"Expand plan panel"} title="Plan panel" aria-expanded={Boolean(panels.widths.left)} onClick={()=>panels.toggle("left")}><PanelLeft size={17}/></button><button hidden={!contexts.length&&!journeyActive} className="mp-panel-toggle" aria-label={panels.widths.right?"Collapse review panel":"Expand review panel"} title="Plan review panel" aria-expanded={Boolean(panels.widths.right)} onClick={()=>panels.toggle("right")}><PanelRight size={17}/></button><button hidden={!contexts.length} className="mp-view-journey" disabled={!draft||loading} onClick={()=>{cancelPick();setParams(p=>{if(viewMode)p.delete('view');else p.set('view','journey');return p;});}}><Compass size={16}/><span>{viewMode?'Back to planning':'View journey'}</span></button><button aria-label="Family plans" className={family?'is-active':''} aria-pressed={family} disabled={busy||loading} onClick={switchFamily}><ShieldCheck size={16}/><span>Family plans</span></button><button aria-label="New plan" hidden={!contexts.length} disabled={busy||loading} onClick={fresh}><Plus size={16}/><span>New plan</span></button><button className="mp-phone-map" onClick={()=>setMobileMap(v=>!v)}><Compass size={17}/>{mobileMap?'Open plan':'Map'}</button></div></header>
    <FamilyPlanWindow open={family} onClose={switchFamily}/>
    <ResponsibilitiesWindow open={responsibilities} onClose={()=>setResponsibilities(false)}/>
    {!loading&&!contexts.length&&<MyJourneys workspace onJourney={updateJourney} onPlaces={onPlaces} onFocus={onFocus}/>}
    {viewMode&&viewItinerary&&<JourneyExplorer itinerary={viewItinerary} journeyKey={`preview:${plan?.id||requestId}:${viewKind}:${plan?.published_version||0}`} clubName={context?.name||'Your club'} version={plan?.published_version||0} preview onPreviewSource={plan?.published?source=>setParams(p=>{p.set("view",source);return p;}):undefined} publication={viewKind==='journey'&&Boolean(plan?.published)} onMap={updateJourney} onFocus={onFocus} onExit={()=>setParams(p=>{p.delete('view');return p;})}/>}
    <div className="mp-staff-surface" hidden={viewMode||(!loading&&!contexts.length)} inert={viewMode}>
      <aside className="mp-rail" aria-label="Plan workspace" inert={panels.widths.left===0&&innerWidth>=1100}>
        <div className="mp-identity-fold" inert={tab==='travel'&&Boolean(plan?.published_version)}><div><div className="mp-identity">{createdNotice&&<div className="mp-created-notice" role="status"><CheckCircle2 size={19}/><div><strong>Plan created</strong><p>Saved to your club. It stays private until you review and publish it for families.</p></div><button className="mp-icon" aria-label="Dismiss creation confirmation" onClick={()=>setCreatedNotice(false)}><X size={15}/></button></div>}{validation&&<div className="mp-validation-notice" role="alert">{validation.message}</div>}<div className="mp-two"><Field label="Club"><SmoothSelect disabled={Boolean(plan)||busy||loading} value={club} onChange={e=>{const id=Number(e.target.value);clean(()=>startDraft(id,contexts.find(c=>c.id===id)?.squads[0]?.id||0));}}>{contexts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</SmoothSelect></Field><Field label="Squad"><SmoothSelect disabled={Boolean(plan)||busy||loading} value={squad} onChange={e=>changeSquad(Number(e.target.value))}>{context?.squads.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</SmoothSelect></Field></div>
          {!!plans.length&&<Field label="Saved journeys"><SmoothSelect value={selected} onChange={e=>e.target.value==='0'?fresh():show(Number(e.target.value))}><option value={0}>New draft</option>{plans.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</SmoothSelect></Field>}
          <div className="mp-plan-heading"><div><span className="atlas-eyebrow">{plan?.published_version?`VERSION ${plan.published_version} SHARED`:'YOUR NEXT FOOTBALL JOURNEY'}</span><h1>{draft?.title||'A little further together.'}</h1></div>{plan&&<button className="mp-icon" aria-label="Reload saved plan" disabled={busy} onClick={()=>clean(()=>{discard();setRefresh(v=>v+1);})}><RefreshCw size={17}/></button>}</div>
          <div className="mp-overview"><span><Clock size={13}/>{days} {days===1?'day':'days'}</span><span><Users size={13}/>{draft?.participants.length||0} players</span><span><MapPin size={13}/>{draft?.places.length||0} places</span></div>
        </div></div></div>
        {tab==='travel'&&Boolean(plan?.published_version)&&<div className="mp-travel-context"><Flag size={15}/><strong>{plan?.title}</strong><span>Version {plan?.published_version}</span></div>}
        <nav className="mp-tabs" aria-label="Planning sections">{tabs.map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>setTab(t.id)}><t.icon size={17}/><span>{t.label}</span></button>)}</nav>
        <div className="mp-scroll" tabIndex={0} role="region" aria-label="Planning details">
          {loading&&<p role="status" className="mp-loading">Opening your workspace…</p>}{error&&<div role="alert" className="mp-alert">{error}<button className="mp-link" onClick={()=>clean(()=>{discard();setRefresh(v=>v+1);})}>Reload server state</button></div>}
          {!loading&&!contexts.length&&<div className="mp-empty"><ClipboardList size={32}/><h2>Your club's next chapter.</h2><p>A current match-planning or travel responsibility gives you access to squad plans. Your published family itineraries are available above.</p><button onClick={()=>setResponsibilities(true)} className="mp-link">Review my club responsibilities <ArrowUpRight size={15}/></button></div>}
          {draft&&<fieldset disabled={!canEdit||busy||loading} className="mp-editable">
            {tab==='plan'&&<PlanDetails draft={draft} change={change} context={context} onPick={beginPick} onShow={showRole} validation={validation}/>}
            {tab==='places'&&<PlacesEditor draft={draft} change={change} onFocus={p=>{onFocus(p);setMobileMap(true);}} onPick={()=>beginPick("place")}/>}
            {tab==='schedule'&&<ScheduleEditor draft={draft} change={change} context={context} squad={squad} plan={plan} onFocus={onFocus} seedPlace={activitySeed} onSeedUsed={()=>setActivitySeed(null)} onPickPlace={receive=>beginPick("activity",receive)} busy={busy||dirty} onCalendar={activityKey=>void command('calendar-event',{activityKey})}/>}
            {tab==='costs'&&<CostsEditor draft={draft} change={change} context={context} squad={squad} plan={plan} busy={busy} onSupplier={(arrangementKey,status,source,evidence)=>void command('supplier',{arrangementKey,status,source,evidence})}/>}
            {tab==='people'&&<div className="mp-editor"><span className="atlas-eyebrow">05 / THE TEAM</span><h2>Everyone accounted for.</h2><p className="mp-muted">Choose current squad players. Their verified family links determine who receives the itinerary and permission request.</p>{unavailableParticipants.length>0&&<div role="status"><p className="mp-muted">{unavailableParticipants.length} selected {unavailableParticipants.length===1?'player is':'players are'} no longer available on this squad's eligible roster. Remove them before saving or publishing; your other planning details will be kept.</p><button className="mp-secondary" onClick={()=>change({participants:draft.participants.filter(id=>availableParticipantIds.has(id))})}>Remove unavailable players</button></div>}<div className="mp-person-list">{context?.participants.filter(p=>p.squad_id===squad).map(p=><label key={p.id}><input type="checkbox" checked={draft.participants.includes(p.id)} onChange={e=>change({participants:e.target.checked?[...draft.participants,p.id]:draft.participants.filter(id=>id!==p.id)})}/><span className="mp-avatar">{p.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span>{p.name}</span><Check size={15}/></label>)}</div><Field label="Family update"><textarea rows={5} maxLength={2000} value={draft.familyMessage} onChange={e=>change({familyMessage:e.target.value})} placeholder="What should players bring? What has changed?"/></Field><button className="mp-secondary" onClick={()=>change({familyMessage:`Our ${draft.title||'upcoming journey'} is planned for ${dateTime(draft.startsAt,draft.timezone)}. We will meet at ${draft.meetingPoint||'[meeting point]'} and return to ${draft.collectionPoint||'[collection point]'}. Please read this itinerary and respond to the separate travel permission request. Contact: ${draft.supervisionContact||'[supervision contact]'}.`})}>Prepare an editable update</button><p className="mp-muted">Prepared from your saved facts. Review the wording before publication.</p></div>}
          </fieldset>}
          {tab==='travel'&&draft&&<TravelPanel plan={plan} busy={busy||dirty} command={command}/>}
          {plan&&<details className="mp-history"><summary>Plan history <ChevronRight size={14}/></summary>{plan.history.map(h=><div key={h.id}><strong>{h.action.toLowerCase().replaceAll('_',' ')}</strong><p>{h.note}</p><small>{h.actor} · {dateTime(h.created_at,draft?.timezone||'UTC')}</small></div>)}</details>}
        </div>
        {draft&&<footer className="mp-savebar"><div role="status">{saving==='creating'?'Creating your plan…':saving==='saving'?'Saving your changes…':busy?'Updating…':error?'Save was not completed. Your draft is kept.':validation?validation.message:notice|| (dirty?'Draft protected on this device':plan?'Saved to your club':'Give your plan a name to get started')}{recoveryWarning&&<small>{recoveryWarning}</small>}{plan&&!dirty&&<small>Revision {plan.revision} · {plan.published_version?`Family version ${plan.published_version}`:'Private draft'}</small>}</div><button className="mp-primary" disabled={busy||loading||(Boolean(plan)&&!dirty)||!canEdit||!club||!squad} aria-busy={Boolean(saving)} onClick={()=>void persist()}>{saving?<Loader2 className="mp-save-spinner" size={16}/>:<Save size={16}/>}<span>{saving==='creating'?'Creating…':saving==='saving'?'Saving…':plan?'Save changes':'Create plan'}</span></button></footer>}
      </aside>
      {draft&&<><PlanningMapTools stopCount={stops.length} connections={connections} onConnections={setConnections} draft={draft} target={pickTarget} candidate={pointCandidate} onPick={beginPick} onSelect={selectedPoint} onFocus={p=>{onFocus(p);setMobileMap(true);}} onUse={usePoint} onCancel={cancelPick}/></>}
      <div className="mp-map-caption"><Compass size={16}/><span>{draft?.destination||'Make room for the next adventure.'}<small>{draft?.places.length?'Your saved planning places':'Save a ground, a base and the stops between them.'}</small></span></div>
      {draft&&<aside className={`mp-review ${review?'mp-review--open':''}`} aria-label="Plan readiness" inert={panels.widths.right===0&&innerWidth>=1100}><button className="mp-review-toggle" onClick={()=>setReview(v=>!v)}><CheckCircle2 size={16}/>Plan review <ChevronRight size={16}/></button><div className="mp-review-body"><span className="atlas-eyebrow">THE WHOLE PICTURE</span><h2>Ready when you are.</h2><div className="mp-budget"><span>Estimated journey cost</span><strong>{money(budget,draft.currency)}</strong><div className="mp-budget-track"><i style={{width:`${Math.min(100,draft.budgetMinor?budget/draft.budgetMinor*100:budget?100:0)}%`}} className={budget>draft.budgetMinor?'is-over':''}/></div><p>{money(draft.budgetMinor,draft.currency)} budget · {budget>draft.budgetMinor?'review needed':money(draft.budgetMinor-budget,draft.currency)+' available'}</p><small>{budget===0?'No spending recorded':plan?.budgetApproved&&!dirty?'Independently approved':'Awaiting independent finance review'}</small>{plan?.rights.finance&&!plan.budgetApproved&&<button className="mp-secondary" disabled={busy||dirty} onClick={()=>void command('approve-budget',{note:'Reviewed from the connected map plan.'})}>Approve these costs</button>}</div>
        <div className="mp-readiness-list">{plan?.issues.length?plan.issues.map((i,index)=><div key={`${i.code}-${index}`} className={i.severity==='BLOCKING'?'is-blocking':''}><span className="mp-status-dot"/><p>{i.message}</p></div>):<div><CheckCircle2 size={17}/><p>{plan?'No outstanding schedule, supplier or cost checks.':'Save your plan to check the connected records.'}</p></div>}</div>
        {plan?.rights.edit&&plan.issues.some(i=>i.code==='SCHEDULE_CHANGED')&&<ChangeReview plan={plan} busy={busy||dirty} onApplied={received} portalTarget={workspace.current}/>}<div className="mp-publication"><ShieldCheck size={22}/><h3>One clear family itinerary.</h3><p>{plan?.published_version?`Families can read version ${plan.published_version}. Draft edits stay with the planning team until you publish.`:'Share the schedule, meeting details and supervision contact with the right families.'}</p><button className="mp-primary" disabled={!plan||busy||dirty||!plan.rights.publish} onClick={()=>setPreview(true)}>Review & publish <ArrowUpRight size={16}/></button>{plan&&!plan.rights.publish&&<small>A colleague with guardian coordination access can publish this plan.</small>}</div>
        {plan&&<>{plan.rights.edit&&<button className="mp-secondary" disabled={busy||dirty} onClick={()=>void command('request-review',{note:'Please review this journey, its costs and family publication.'})}>Request colleague review</button>}<div className="mp-response-summary"><strong>{plan.familyResponses.filter(r=>r.acknowledged_at).length}/{plan.familyResponses.length}</strong><span>family updates read</span><strong>{plan.familyResponses.filter(r=>r.permission_status==='GRANTED').length}/{plan.familyResponses.length}</strong><span>travel permissions granted</span></div><Link className="mp-link" to={`/clubs/${plan.club_id}/workspace`}>Open club workspace <ArrowUpRight size={14}/></Link></>}
      </div></aside>}
    </div>
    {(draft||journeyActive)&&<>{panels.separator("left")}{panels.separator("right")}</>}
    {preview&&draft&&plan&&<div className="mp-modal-backdrop"><section ref={publishDialog} className="mp-dialog" role="dialog" aria-modal="true" aria-labelledby="mp-publish-title"><button className="mp-dialog-close" aria-label="Close publication preview" onClick={()=>setPreview(false)}><X size={19}/></button><span className="atlas-eyebrow">REVIEW FAMILY INFORMATION</span><h2 id="mp-publish-title">Read it as a parent.</h2><h3>{draft.title}</h3><p>{draft.destination} · {dateTime(draft.startsAt,draft.timezone)} — {dateTime(draft.endsAt,draft.timezone)} · {draft.timezone}</p><dl className="mp-facts"><dt>Meet</dt><dd>{draft.meetingPoint||'Missing'}</dd><dt>Collect</dt><dd>{draft.collectionPoint||'Missing'}</dd><dt>Contact</dt><dd>{draft.supervisionContact||'Missing'}</dd></dl><p>{draft.familyMessage}</p><ol className="mp-timeline">{draft.activities.map(a=><li key={a.key}><span className="mp-time">{dateTime(a.startsAt,draft.timezone)}</span><div><strong>{a.title}</strong><p>{draft.places.find(p=>p.key===a.placeKey)?.name}</p><small>{draft.places.find(p=>p.key===a.placeKey)?.address}</small><small>Until {dateTime(a.endsAt,draft.timezone)}</small></div></li>)}</ol>{!!draft.arrangements.length&&<section className="mp-inset"><h4>Shared arrangements</h4>{draft.arrangements.map(a=><p key={a.key}>{a.title}{a.placeKey?` · ${draft.places.find(p=>p.key===a.placeKey)?.name||""}`:""}</p>)}</section>}<p className="mp-note">Changed family information creates a new itinerary version and travel permission request. Private staff edits preserve the existing family version. Supplier decisions and spending approval keep their own status.</p><div className="mp-actions"><button className="mp-secondary" onClick={()=>setPreview(false)}>Keep editing</button><button className="mp-primary" disabled={busy} onClick={()=>void command('publish')}>{busy?'Publishing…':'Publish family itinerary'}</button></div></section></div>}
    {pending&&<div className="mp-modal-backdrop"><section ref={unsavedDialog} className="mp-dialog mp-dialog--small" role="alertdialog" aria-modal="true" aria-labelledby="mp-unsaved"><h2 id="mp-unsaved">Keep your changes?</h2><p>Your draft has changes that have not reached the club yet.</p><div className="mp-actions"><button className="mp-primary" disabled={busy} onClick={()=>void persist().then(p=>{if(p){const fn=pending;setPending(null);fn();}})}>Save & continue</button><button className="mp-secondary" onClick={()=>{const fn=pending;discard();setPending(null);fn();}}>Discard changes</button><button className="mp-link" onClick={()=>setPending(null)}>Keep editing</button></div></section></div>}
  </div>;
  function changeSquad(id:number){clean(()=>startDraft(club,id));}
}

function TravelPanel({plan,busy,command}:{plan:Plan|null;busy:boolean;command:(path:string,extra?:Record<string,unknown>)=>Promise<void>}){
  const [absent,setAbsent]=useState<number|null>(null),[reason,setReason]=useState('');
  return <div className="mp-editor"><span className="atlas-eyebrow">06 / ON THE MOVE</span><h2>A team, safely together.</h2><p className="mp-muted">These checks use the same trip and passenger records as Club operations. Updates are reported by staff.</p>{!plan?<p>Save and publish a plan to prepare its journey.</p>:<>
    {!!plan.journeyResponses?.length&&<section className="mp-inset"><h3>Journey attendance · separate from permission</h3>{plan.journeyResponses.map(r=><p key={r.subject_id}><strong>{r.name}</strong> · {r.response==='GOING'?'Going':r.response==='NOT_GOING'?'Not going':'Reply again after the journey update'} · {dateTime(r.updated_at,plan.draft.timezone)}</p>)}</section>}
    {!plan.journeyResponses?.length&&!!plan.playerResponses?.length&&<section className="mp-inset"><h3>Player replies · version {plan.published_version}</h3>{plan.playerResponses.map(r=><p key={r.actor_id}><strong>{r.name}</strong> · {r.status==='GOING'?'Going':r.status==='NOT_GOING'?'Not going':'Update read'} · {dateTime(r.created_at,plan.draft.timezone)}</p>)}</section>}
    <div className="mp-trip-banner"><Flag size={25}/><div><strong>{plan.trip?.status.toLowerCase()||'Travel not connected yet'}</strong><p>{plan.trip?`Trip #${plan.trip.id}`:'Connect the published itinerary and its passengers.'}</p></div></div>
    {plan.rights.travel&&<button className="mp-primary" disabled={busy} onClick={()=>void command('connect-trip')}>{plan.trip?'Update travel connection':'Connect travel records'}</button>}
    {plan.trip&&<><div className="mp-actions">{plan.trip.transitions.filter(s=>['READY','DEPARTED','RETURNED'].includes(s)).map(s=><button className="mp-secondary" key={s} disabled={busy||!plan.rights.travel} onClick={()=>void command('milestones',{status:s,note:'Staff milestone recorded from the map workspace.'})}>{s==='READY'?'Mark travel ready':s==='DEPARTED'?'Record departure':'Record team return'}</button>)}</div><div className="mp-passengers">{plan.passengers.map(p=><article key={p.id}><div><strong>{p.name}</strong><span className="mp-pill">{p.status==='CANCELLED'?'Not travelling':p.status.toLowerCase()}</span></div>{plan.rights.travel&&<div className="mp-actions">{(p.status==='PLANNED'?['BOARDED']:p.status==='BOARDED'?['ARRIVED']:p.status==='ARRIVED'?['RETURNED']:[]).map(s=><button className="mp-secondary" disabled={busy} key={s} onClick={()=>void command('passengers',{passengerId:p.id,status:s})}>{s==='BOARDED'?'Boarded':s==='ARRIVED'?'Arrived':'Returned'}</button>)}{p.status==='PLANNED'&&<button className="mp-link" disabled={busy} onClick={()=>setAbsent(p.id)}>Not travelling</button>}</div>}{absent===p.id&&<form onSubmit={e=>{e.preventDefault();void command('passengers',{passengerId:p.id,status:'CANCELLED',note:reason});setAbsent(null);setReason('');}}><Field label="Reason for absence"><input required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><button className="mp-secondary">Record absence</button></form>}</article>)}</div><Link className="mp-link" to={`/clubs/${plan.club_id}/workspace?tab=travel&record=${plan.trip.id}`}>Open shared travel record <ArrowUpRight size={14}/></Link></>}
  </>}</div>;
}
