import { SmoothSelect } from './SmoothSelect';
import { PlacePhotoEditor } from './PlacePhoto';
import './trip-view.css';
import { useEffect,useState,type ReactNode } from 'react';
import { ArrowDown,ArrowUp,ArrowUpRight,MapPin,Plus,Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { dateTime,localInput,money,zonedIso,type Plan,type PlanActivity,type PlanArrangement,type PlanContext,type PlanDraft,type PlanPlace } from './api';

import { locationRoles, roleForPlace, type LocationRole } from './mapPlanning';

export const Field=({label,children,hint}:{label:string;children:ReactNode;hint?:string})=><label className="mp-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
export function TimeField({label,value,zone,onChange}:{label:string;value:string;zone:string;onChange:(v:string)=>void}){
  const [error,setError]=useState('');
  return <Field label={label} hint={error||zone}><input aria-label={label} aria-invalid={Boolean(error)} type="datetime-local" value={localInput(value,zone)} onChange={e=>{try{onChange(zonedIso(e.target.value,zone));setError('');}catch(err){setError((err as Error).message);}}}/></Field>;
}
export function PlanDetails({draft:d,change,context,onPick,onShow,validation}:{draft:PlanDraft;change:(p:Partial<PlanDraft>)=>void;context?:PlanContext;onPick:(role:LocationRole)=>void;onShow:(role:LocationRole)=>void;validation?:{field:string;message:string}|null}){
  return <div className="mp-editor"><span className="atlas-eyebrow">01 / THE BIG PICTURE</span><h2>Good days start with a plan.</h2><p className="mp-muted">An away match, a training camp, or the journey between them.</p>
    <Field label="Plan name"><input aria-label="Plan name" aria-invalid={validation?.field==='Plan name'} aria-describedby={validation?.field==='Plan name'?'mp-name-error':undefined} required maxLength={160} value={d.title} onChange={e=>change({title:e.target.value})} placeholder="U16 · Weekend in Batumi"/>{validation?.field==='Plan name'&&<small id="mp-name-error" className="mp-field-error">{validation.message}</small>}</Field>
    <div className="mp-location-field"><Field label="Destination"><input value={d.destination} maxLength={400} onChange={e=>change({destination:e.target.value})} placeholder="Choose a place on the map, or add details"/></Field><div className="mp-actions"><button className="mp-link" type="button" onClick={()=>onPick('destination')}><MapPin size={14}/>{d.places.some(p=>p.key===locationRoles.destination.key)?'Change on map':'Pick on map'}</button><button className="mp-link" type="button" onClick={()=>onShow('destination')}>{locationRoles.destination.label} <ArrowUpRight size={14}/></button></div></div>
    <div className="mp-two"><TimeField label="Leaving" value={d.startsAt} zone={d.timezone} onChange={startsAt=>change({startsAt})}/><TimeField label="Expected return" value={d.endsAt} zone={d.timezone} onChange={endsAt=>change({endsAt})}/></div>
    <Field label="Time zone"><SmoothSelect value={d.timezone} onChange={e=>change({timezone:e.target.value})}>{[...new Set([d.timezone,context?.settings.timezone||'Asia/Tbilisi','Asia/Tbilisi','Europe/Tallinn','Europe/London','Europe/Paris','Europe/Berlin','Europe/Istanbul','UTC'])].map(z=><option key={z}>{z}</option>)}</SmoothSelect></Field>
    <div className="mp-location-field"><Field label="Meeting point"><input value={d.meetingPoint} maxLength={400} onChange={e=>change({meetingPoint:e.target.value})} placeholder="Choose a place on the map, or add details"/></Field><div className="mp-actions"><button className="mp-link" type="button" onClick={()=>onPick('meeting')}><MapPin size={14}/>{d.places.some(p=>p.key===locationRoles.meeting.key)?'Change on map':'Pick on map'}</button><button className="mp-link" type="button" onClick={()=>onShow('meeting')}>{locationRoles.meeting.label} <ArrowUpRight size={14}/></button></div></div>
    <div className="mp-location-field"><Field label="Collection point"><input value={d.collectionPoint} maxLength={400} onChange={e=>change({collectionPoint:e.target.value})} placeholder="Choose a place on the map, or add details"/></Field><div className="mp-actions"><button className="mp-link" type="button" onClick={()=>onPick('collection')}><MapPin size={14}/>{d.places.some(p=>p.key===locationRoles.collection.key)?'Change on map':'Pick on map'}</button><button className="mp-link" type="button" onClick={()=>onShow('collection')}>{locationRoles.collection.label} <ArrowUpRight size={14}/></button></div></div>
    <Field label="Supervision contact" hint="This will be shared with the families on this plan."><input maxLength={400} value={d.supervisionContact} onChange={e=>change({supervisionContact:e.target.value})} placeholder="Lead coach and contact number"/></Field>
    <Field label="Private planning notes" hint="Visible to authorised planning staff. Excluded from the family itinerary."><textarea maxLength={4000} rows={3} value={d.privateNotes} onChange={e=>change({privateNotes:e.target.value})}/></Field>
  </div>;
}
export function PlacesEditor({draft:d,change,onFocus,onPick}:{draft:PlanDraft;change:(p:Partial<PlanDraft>)=>void;onFocus:(p:PlanPlace)=>void;onPick:()=>void}){
  const [comparison,setComparison]=useState<string[]>([]);
  const remove=(key:string)=>{const role=roleForPlace(key);change({places:d.places.filter(p=>p.key!==key),activities:d.activities.map(a=>a.placeKey===key?{...a,placeKey:null}:a),arrangements:d.arrangements.map(a=>a.placeKey===key?{...a,placeKey:null}:a),...(role?{[locationRoles[role].field]:''}:{})});};
  return <div className="mp-editor"><span className="atlas-eyebrow">02 / PLACES TO GO</span><h2>Find your base.</h2><p className="mp-muted">Click a location on the map, give it a useful name and keep it with your journey. Supplier availability still needs confirmation.</p><div className="mp-actions"><button className="mp-primary" onClick={onPick}><MapPin size={16}/>Find on map</button><button className="mp-secondary" onClick={onPick}><Plus size={16}/>Add a place</button></div>
    {!d.places.length&&<div className="mp-empty"><MapPin size={32}/><h3>A whole world of possibilities.</h3><p>Your shortlist will appear here. Grounds, stays, meeting points—keep them with the trip they belong to.</p></div>}
    <div className="mp-place-list">{d.places.map((p,i)=><article key={p.key}><div className="mp-place-heading"><span className="mp-number">{String(i+1).padStart(2,'0')}</span><div><span className="mp-muted">{p.type==='MANUAL'?'Recorded by your team':p.type.toLowerCase()}</span><h3>{p.name}</h3></div><button className="mp-icon" aria-label={`Remove ${p.name}`} onClick={()=>remove(p.key)}><Trash2 size={15}/></button></div><p>{p.address||'Chosen on the map'}</p><PlacePhotoEditor url={p.photoUrl} name={p.name} onChange={url=>change({places:d.places.map(place=>place.key===p.key?{...place,photoUrl:url}:place)})}/>{p.notes&&<p className="mp-note">{p.notes}</p>}<div className="mp-actions"><button className="mp-secondary" onClick={()=>onFocus(p)}>Show on map <ArrowUpRight size={15}/></button><label className="mp-check"><input type="checkbox" checked={comparison.includes(p.key)} disabled={!comparison.includes(p.key)&&comparison.length>=3} onChange={e=>setComparison(v=>e.target.checked?[...v,p.key]:v.filter(k=>k!==p.key))}/>Compare</label></div>{p.type==='STADIUM'&&p.entityId&&<Link className="mp-link" to={`/stadiums/${p.entityId}`}>Check actual availability <ArrowUpRight size={14}/></Link>}</article>)}</div>
    {comparison.length>=2&&<section className="mp-comparison"><h3>Side by side</h3><div className="mp-comparison-grid">{d.places.filter(p=>comparison.includes(p.key)).map(p=><article key={p.key}><strong>{p.name}</strong><p>{p.address}</p><p>{p.notes||'No comparison notes yet.'}</p><span className="mp-muted">{d.arrangements.filter(a=>a.placeKey===p.key).map(a=>money(a.amountMinor,d.currency)).join(' · ')||'Cost not recorded'}</span></article>)}</div></section>}
  </div>;
}
export function ScheduleEditor({draft:d,change,context,squad,plan,onFocus,busy,onCalendar,seedPlace,onSeedUsed,onPickPlace}:{draft:PlanDraft;change:(p:Partial<PlanDraft>)=>void;context?:PlanContext;squad:number;plan:Plan|null;onFocus:(p:PlanPlace)=>void;busy:boolean;onCalendar:(key:string)=>void;seedPlace:PlanPlace|null;onSeedUsed:()=>void;onPickPlace:(receive:(place:PlanPlace)=>void)=>void}){
  const [editing,setEditing]=useState<PlanActivity|null>(null),[error,setError]=useState(''),[source,setSource]=useState<'new'|'event'|'session'>('new');
  const events=context?.events.filter(e=>e.challenger_squad_id===squad||e.target_squad_id===squad)||[],sessions=context?.sessions.filter(s=>s.squad_id===squad)||[];
  const blank=(place?:PlanPlace):PlanActivity=>{const last=d.activities.at(-1);const starts=last&&Date.parse(last.endsAt)<Date.parse(d.endsAt)?last.endsAt:d.startsAt;return {key:crypto.randomUUID(),title:place?.name||'',kind:'ACTIVITY',startsAt:starts,endsAt:new Date(Math.min(Date.parse(d.endsAt),Date.parse(starts)+3600000)).toISOString(),placeKey:place?.key||null,eventId:null,sessionId:null,notes:''};};
  const [consumedSeed,setConsumedSeed]=useState<PlanPlace|null>(null);
  if(seedPlace&&seedPlace!==consumedSeed){setConsumedSeed(seedPlace);setEditing(blank(seedPlace));setSource('new');setError('');}
  useEffect(()=>{if(seedPlace)onSeedUsed();},[seedPlace,onSeedUsed]);
  const add=()=>{setEditing(blank());setSource('new');setError('');};
  const link=(value:string)=>{if(!editing)return;const item=source==='event'?events.find(e=>e.id===Number(value)):sessions.find(e=>e.id===Number(value));if(!item)return;const convert=(v:string)=>/[Zz]|[+-]\d\d:\d\d$/.test(v)?new Date(v).toISOString():zonedIso(v.slice(0,16),context?.settings.timezone||'Asia/Tbilisi');let placeKey=editing.placeKey;
    if('location_lat' in item&&typeof item.location_lat==='number'&&typeof item.location_lng==='number'){const place:PlanPlace={key:`calendar:${item.id}`,name:item.location_name||item.title,address:item.location_name||'',latitude:item.location_lat,longitude:item.location_lng,type:'MANUAL',notes:''};change({places:d.places.some(p=>p.key===place.key)?d.places.map(p=>p.key===place.key?place:p):[...d.places,place]});placeKey=place.key;}
    setEditing({...editing,title:item.title,kind:source==='event'?'MATCH':'TRAINING',eventId:source==='event'?item.id:null,sessionId:source==='session'?item.id:null,startsAt:convert(item.starts_at),endsAt:convert(item.ends_at),placeKey});};
  const shift=(index:number,offset:number)=>{const next=[...d.activities];[next[index],next[index+offset]]=[next[index+offset],next[index]];change({activities:next});};
  const typeLabels={MATCH:'Match',TRAINING:'Training',TRAVEL:'Travel',STAY:'Stay',MEAL:'Meal',ACTIVITY:'Other activity'};
  return <div className="mp-editor"><span className="atlas-eyebrow">03 / THE SCHEDULE</span><h2>Plan the day.</h2><p className="mp-muted">Add what happens, when it starts and where to go. Choose a place directly on the map or use a match or training session already in your squad's calendar.</p><button className="mp-primary" onClick={add}><Plus size={16}/>Add an activity</button>
    {editing&&<form className="mp-inset" onSubmit={e=>{e.preventDefault();setError('');if(Date.parse(editing.endsAt)<=Date.parse(editing.startsAt)){setError('End time must be after start time.');return;}if(Date.parse(editing.startsAt)<Date.parse(d.startsAt)||Date.parse(editing.endsAt)>Date.parse(d.endsAt)){setError('This activity is outside the journey dates. Update the dates in Plan or choose another time.');return;}change({activities:d.activities.some(a=>a.key===editing.key)?d.activities.map(a=>a.key===editing.key?editing:a):[...d.activities,editing]});setEditing(null);}}>
      <div className="mp-field"><span>Start from</span><div className="mp-source-options" role="radiogroup" aria-label="Activity source">{(['new','event','session'] as const).map(value=><label key={value}><input type="radio" name="activity-source" checked={source===value} onChange={()=>{setSource(value);setEditing({...editing,eventId:null,sessionId:null});}}/>{value==='new'?'New activity':value==='event'?'Existing match':'Existing training'}</label>)}</div></div>
      {source!=='new'&&<Field label={source==='event'?'Choose a match':'Choose a training session'}>{(source==='event'?events:sessions).length?<SmoothSelect value={editing.eventId||editing.sessionId||''} onChange={e=>link(e.target.value)}><option value="">Choose an entry</option>{(source==='event'?events:sessions).map(item=><option key={item.id} value={item.id}>{item.title} · {dateTime(/[Zz]|[+-]\d\d:\d\d$/.test(item.starts_at)?item.starts_at:zonedIso(item.starts_at.slice(0,16),context?.settings.timezone||d.timezone),d.timezone)}</option>)}</SmoothSelect>:<small>No {source==='event'?'matches':'training sessions'} are available for this squad. Choose New activity to plan one.</small>}</Field>}
      <Field label="Activity name"><input required maxLength={160} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder="Meet the team, travel, lunch…"/></Field><Field label="Type"><SmoothSelect value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as PlanActivity['kind']})}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</SmoothSelect></Field>
      <div className="mp-two"><TimeField label="Starts" value={editing.startsAt} zone={d.timezone} onChange={startsAt=>setEditing({...editing,startsAt})}/><TimeField label="Ends" value={editing.endsAt} zone={d.timezone} onChange={endsAt=>setEditing({...editing,endsAt})}/></div><Field label="Place"><SmoothSelect value={editing.placeKey||''} onChange={e=>setEditing({...editing,placeKey:e.target.value||null})}><option value="">Choose later</option>{d.places.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</SmoothSelect></Field><button className="mp-link" type="button" onClick={()=>onPickPlace(place=>setEditing(current=>current?{...current,placeKey:place.key}:current))}><MapPin size={14}/>Pick activity place on map</button><Field label="Staff notes"><textarea maxLength={2000} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></Field>{error&&<p role="alert" className="mp-alert">{error}</p>}<div className="mp-actions"><button className="mp-primary" type="submit" disabled={source!=='new'&&!editing.eventId&&!editing.sessionId}>Add to schedule</button><button className="mp-secondary" type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
    {!d.activities.length&&!editing&&<div className="mp-empty"><h3>What happens on this journey?</h3><p>Add the departure, match or training, meals and return. You can also click a place on the map and choose Add to schedule.</p></div>}
    <ol className="mp-timeline">{d.activities.map((a,i)=>{const p=d.places.find(p=>p.key===a.placeKey);return <li key={a.key}><span className="mp-time">{dateTime(a.startsAt,d.timezone)}</span><div><span className="mp-pill">{typeLabels[a.kind]}{a.eventId||a.sessionId?' · calendar linked':''}</span><button className="mp-title-button" onClick={()=>{setEditing(a);setSource(a.eventId?'event':a.sessionId?'session':'new');setError('');}}>{a.title}</button>{p&&<button className="mp-link" onClick={()=>onFocus(p)}><MapPin size={12}/>{p.name}</button>}<small>Until {dateTime(a.endsAt,d.timezone)}</small>{plan&&!a.eventId&&!a.sessionId&&['MATCH','TRAINING'].includes(a.kind)&&<button className="mp-link" disabled={busy} onClick={()=>onCalendar(a.key)}>Add to club calendar <ArrowUpRight size={12}/></button>}<div className="mp-row-actions"><button disabled={!i} aria-label={`Move ${a.title} up`} onClick={()=>shift(i,-1)}><ArrowUp size={14}/></button><button disabled={i===d.activities.length-1} aria-label={`Move ${a.title} down`} onClick={()=>shift(i,1)}><ArrowDown size={14}/></button><button aria-label={`Remove ${a.title}`} onClick={()=>change({activities:d.activities.filter(x=>x.key!==a.key)})}><Trash2 size={14}/></button></div></div></li>;})}</ol>
  </div>;
}
export function CostsEditor({draft:d,change,plan,onSupplier,busy,context,squad}:{context?:PlanContext;squad:number;draft:PlanDraft;change:(p:Partial<PlanDraft>)=>void;plan:Plan|null;onSupplier:(key:string,status:string,source:string,evidence:string)=>void;busy:boolean}){
  const [editing,setEditing]=useState<PlanArrangement|null>(null),[evidence,setEvidence]=useState<string|null>(null);
  const total=d.arrangements.reduce((v,a)=>v+a.amountMinor,0);
  return <div className="mp-editor"><span className="atlas-eyebrow">04 / ARRANGEMENTS & COSTS</span><h2>Know what is agreed.</h2><p className="mp-muted">Estimates, supplier confirmations and finance decisions stay separate. Opening or editing this workspace makes no paid AI or booking calls.</p><div className="mp-two"><Field label="Budget"><input type="number" min={0} step="0.01" value={d.budgetMinor/100} onChange={e=>change({budgetMinor:Math.round(Number(e.target.value)*100)})}/></Field><Field label="Currency"><SmoothSelect value={d.currency} onChange={e=>change({currency:e.target.value})}>{[...new Set([d.currency,'GEL','EUR','USD','GBP'])].map(c=><option key={c}>{c}</option>)}</SmoothSelect></Field></div><div className="mp-cost-total"><span>Estimated total</span><strong>{money(total,d.currency)}</strong><small>{money(Math.abs(d.budgetMinor-total),d.currency)} {total>d.budgetMinor?'over budget':'remaining'}</small></div>
    <button className="mp-primary" onClick={()=>setEditing({key:crypto.randomUUID(),title:'',kind:'TRANSPORT',amountMinor:0,placeKey:null,notes:'',financeRecordId:null})}><Plus size={16}/>Add arrangement</button>
    {editing&&<form className="mp-inset" onSubmit={e=>{e.preventDefault();change({arrangements:d.arrangements.some(a=>a.key===editing.key)?d.arrangements.map(a=>a.key===editing.key?editing:a):[...d.arrangements,editing]});setEditing(null);}}><Field label="Arrangement"><input required value={editing.title} maxLength={160} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder="Coach transfer · 22 seats"/></Field><div className="mp-two"><Field label="Category"><SmoothSelect value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as PlanArrangement['kind']})}>{['TRANSPORT','ACCOMMODATION','MEALS','VENUE','OTHER'].map(k=><option key={k}>{k}</option>)}</SmoothSelect></Field><Field label={`Estimated amount · ${d.currency}`}><input type="number" min={0} step="0.01" required value={editing.amountMinor/100} onChange={e=>setEditing({...editing,amountMinor:Math.round(Number(e.target.value)*100)})}/></Field></div><Field label="Saved place"><SmoothSelect value={editing.placeKey||''} onChange={e=>setEditing({...editing,placeKey:e.target.value||null})}><option value="">No place linked</option>{d.places.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</SmoothSelect></Field><Field label="Terms & planning notes"><textarea maxLength={2000} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></Field><Field label="Linked finance record" hint="Choose an existing record you can access. Its approval and payment rules remain in Finance."><SmoothSelect value={editing.financeRecordId||""} onChange={e=>setEditing({...editing,financeRecordId:e.target.value?Number(e.target.value):null})}><option value="">No finance record linked</option>{editing.financeRecordId&&!context?.financeRecords?.some(r=>r.id===editing.financeRecordId)&&<option value={editing.financeRecordId}>Existing link · finance access required</option>}{context?.financeRecords?.filter(r=>r.squad_id===squad).map(r=><option key={r.id} value={r.id}>{r.title} · {r.status.toLowerCase().replaceAll("_"," ")}</option>)}</SmoothSelect></Field><div className="mp-actions"><button className="mp-primary" type="submit">Keep arrangement</button><button className="mp-secondary" type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
    <div className="mp-arrangements">{d.arrangements.map(a=><article key={a.key}><div className="mp-between"><span className="mp-pill">{a.kind.toLowerCase()}</span><strong>{money(a.amountMinor,d.currency)}</strong></div><button className="mp-title-button" onClick={()=>setEditing(a)}>{a.title}</button><p>{a.notes||'Terms have not been recorded.'}</p><span className="mp-muted">Supplier: {plan?.suppliers[a.key]?.status.toLowerCase()||'awaiting evidence'}</span>{plan?.suppliers[a.key]&&<details className="mp-source"><summary>Recorded evidence</summary><p>{plan.suppliers[a.key].source}</p><p>{plan.suppliers[a.key].evidence}</p><small>{dateTime(plan.suppliers[a.key].at,d.timezone)}</small></details>}<div className="mp-actions">{plan?.rights.travel&&<button className="mp-secondary" onClick={()=>setEvidence(a.key)}>Record supplier response</button>}<button className="mp-icon" aria-label={`Remove ${a.title}`} onClick={()=>change({arrangements:d.arrangements.filter(x=>x.key!==a.key)})}><Trash2 size={15}/></button></div>{a.financeRecordId&&plan&&<Link className="mp-link" to={`/clubs/${plan.club_id}/workspace?tab=finance&record=${a.financeRecordId}`}>Open finance record <ArrowUpRight size={14}/></Link>}
      {evidence===a.key&&<form className="mp-inset" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSupplier(a.key,String(f.get('status')),String(f.get('source')),String(f.get('evidence')));setEvidence(null);}}><Field label="Supplier response"><SmoothSelect name="status"><option value="CONFIRMED">Confirmed externally</option><option value="PENDING">Awaiting response</option><option value="DECLINED">Declined</option></SmoothSelect></Field><Field label="Who confirmed, and when?"><input required maxLength={160} name="source" placeholder="Supplier contact · date"/></Field><Field label="Confirmation evidence / reference"><textarea required maxLength={2000} name="evidence"/></Field><button className="mp-primary" disabled={busy}>Record evidence</button></form>}
    </article>)}</div>
  </div>;
}
