import {useCompetitionCopy} from './competitionCopy';
import { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { extractApiErrorMessage } from '../../utils/apiError';
import type { TournamentDetail } from '../tournaments/domain';
import { getOperations, operation, familyLabels, structureLabels, type OperationsState } from './api';
import './competition-operations.css';
import { useCompetitionCommand } from './useCompetitionCommand';
import { CompetitionDrawPanel } from './CompetitionDrawPanel';
import { CompetitionDivisionsPanel } from './CompetitionDivisionsPanel';
import { CompetitionLifecyclePanel } from './CompetitionLifecyclePanel';
import { CompetitionResourcesPanel } from './CompetitionResourcesPanel';
import { CompetitionRecoveryPanel } from './CompetitionRecoveryPanel';

export function CompetitionOperationsPanel({ tournament, changed, interactive = false }: { tournament: TournamentDetail; changed?: () => Promise<void>; interactive?: boolean }) {
  const {sessionId}=useAuth();
  return <OperationsContent key={`${tournament.id}:${sessionId}`} tournament={tournament} changed={changed} interactive={interactive}/>;
}
function OperationsContent({ tournament, changed, interactive = false }: { tournament: TournamentDetail; changed?: () => Promise<void>; interactive?: boolean }) {
  const activityCopy=useCompetitionCopy();
  const { sessionId } = useAuth();
  const [state,setState] = useState<{sessionId: typeof sessionId; value: OperationsState}>();
  const [error,setError] = useState(''),[attempt,setAttempt] = useState(0);
  const [startsAt,setStartsAt] = useState(''),[entryId,setEntryId] = useState(''),[targetId,setTargetId] = useState(''),[venue,setVenue] = useState(''),[reason,setReason] = useState('');
  const [rankOrders,setRankOrders]=useState<Record<number,string>>({});
  const commands=useCompetitionCommand(),{busy,notice}=commands;
  const data=state?.sessionId===sessionId?state.value:undefined;
  useEffect(()=>{const controller=new AbortController();void getOperations(tournament.id,controller.signal).then(value=>{if(!controller.signal.aborted){setState({sessionId,value});setError('');}}).catch(cause=>{if(!controller.signal.aborted){setState(undefined);setError(extractApiErrorMessage(cause,'Could not load competition operations.'));}});return()=>controller.abort();},[tournament.id,tournament.status,tournament.fixtures,sessionId,attempt]);
  const rules=data?.profile.rules;
  if(data?.profile.legacy)return null;
  async function command(path:string,body:Record<string,unknown>){
    if(!data)return;
    await commands.run(path,body,data.profile.revision,payload=>operation(tournament.id,path,payload),async value=>{setState({sessionId,value});if(changed)await changed();},()=>setAttempt(a=>a+1));
  }
  const dateValue=():string|null=>{const date=new Date(startsAt);return Number.isFinite(date.getTime())?date.toISOString():null;};
  const editable=interactive&&data?.canOperate&&['PLANNING','ACTIVE'].includes(tournament.status);
  const hasDraw=rules&&['ROUND_ROBIN','HOME_AWAY','KNOCKOUT','GROUPS_KNOCKOUT','SPLIT_LEAGUE'].includes(rules.structure);
  return <section className="co-panel" aria-labelledby={`competition-operations-${tournament.id}`}>
    {interactive&&<CompetitionRecoveryPanel id={tournament.id} changed={async()=>{setAttempt(a=>a+1);if(changed)await changed();}}/>}
    {error&&<div role="alert"><p>{error}</p><button type="button" onClick={()=>setAttempt(a=>a+1)}>{activityCopy("Reload competition")}</button></div>}
    {!data&&!error&&<p role="status">{activityCopy("Loading competition rules…")}</p>}
    {notice&&<p role="status">{notice}</p>}
    {commands.error&&<p role="alert">{commands.error}</p>}
    {rules&&<>
      {<CompetitionResourcesPanel id={tournament.id} rules={rules} editable={interactive} changed={async()=>{setAttempt(a=>a+1);if(changed)await changed();}}/>}
      {interactive&&data.canOperate&&<CompetitionDivisionsPanel tournament={tournament} operations={data} changed={async()=>{setAttempt(a=>a+1);if(changed)await changed();}}/>}
      {interactive&&data.canOperate&&<CompetitionLifecyclePanel tournament={tournament} busy={busy} canReopen={data.canComplete} canWithdraw={rules.family!=='CUP'} run={command}/>}
      <header><div><p>{activityCopy(familyLabels[rules.family])}</p><h2 id={`competition-operations-${tournament.id}`}>{activityCopy(structureLabels[rules.structure])}</h2></div><span>{rules.city} · {rules.ageGroup} · {rules.sideSize}v{rules.sideSize}</span></header>
      <p>{rules.ruleset}</p><dl className="co-facts"><div><dt>{activityCopy("Playing discipline")}</dt><dd>{rules.discipline.toLowerCase()}</dd></div><div><dt>{activityCopy("Match / rest")}</dt><dd>{rules.matchMinutes} / {rules.restMinutes} {activityCopy("minutes")}</dd></div><div><dt>{activityCopy("Eligibility")}</dt><dd>{rules.eligibilityCategory}{rules.ageCutoff?` · cutoff ${rules.ageCutoff}`:''}</dd></div><div><dt>{activityCopy("Entry fee")}</dt><dd>{rules.entryFee} {rules.currency} / {rules.feeBasis.toLowerCase()}</dd></div></dl>
      <details><summary>{activityCopy("Competition rules & season policy")}</summary><p>{rules.seasonPolicy}</p><p>{rules.tiebreaks.map(t=>t.toLowerCase().replaceAll('_',' ')).join(' → ')}</p>{rules.jurisdiction&&<p>{rules.jurisdiction} {activityCopy("· organiser-reported")}</p>}</details>
      {data.policy&&<details><summary>{activityCopy("Eligibility review & rule authority")}</summary><p>{data.policy.ruleAuthority} {activityCopy("· organiser-reported")}</p><p>{activityCopy("Minimum roster:")}{' '}{data.policy.minimumRoster} {activityCopy("· maximum match length:")}{' '}{data.policy.maximumMatchMinutes} {activityCopy("minutes · minimum age at cutoff:")}{' '}{data.policy.minimumAge}.</p>{data.policy.sanctioningEvidence&&<p>{data.policy.sanctioningEvidence} {activityCopy("· evidence supplied by organiser, unverified")}</p>}{editable&&<form onSubmit={event=>{event.preventDefault();void command(`entries/${entryId}/eligibility`,{action:'REVIEW',reason});}}><label>{activityCopy("Entry for eligibility / reactivation review")}<select required value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">{activityCopy("Choose an entry")}</option>{tournament.entries.filter(e=>!['REJECTED','WITHDRAWN'].includes(e.status)).map(e=><option key={e.id} value={e.id}>{e.squadName||e.clubName||e.displayName||`Entry ${e.id}`} · {e.status}</option>)}</select></label><label>{activityCopy("Private review evidence")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>{activityCopy("Record roster, cutoff, category and institution checks without unnecessary personal data. Then activate an eligible pending entry in Participants. Review notes remain private.")}</p><button type="submit" disabled={busy}>{activityCopy("Record eligibility review")}</button></form>}</details>}
      {rules.family==='LADDER'&&<p>{activityCopy("Elo ranking starts at 1500, K=32, for this competition only. Challenge within")}{' '}{rules.challengeRange} {activityCopy("positions; offers expire after")}{' '}{rules.challengeExpiryDays} {activityCopy("days or before kick-off.")}{' '}{data.policy?.inactivityDays?`Entries inactive for ${data.policy.inactivityDays} days need an organiser's recorded reactivation review.`:'No inactivity suspension is configured.'}</p>}
      {rules.family==='FESTIVAL'&&!rules.standings&&<p>{activityCopy("Development festival: no standings or champion. Teams rotate through the agreed timetable.")}</p>}
      {!hasDraw&&data.standings.length>0&&<div className="co-table-scroll" tabIndex={0} role="region" aria-label={activityCopy("Competition standings")}><table><caption>{rules.family==='LADDER'?'Ladder ranking':'Competition standings'}</caption><thead><tr><th scope="col">{activityCopy("Rank")}</th><th scope="col">{activityCopy("Entry")}</th><th scope="col">{activityCopy("Played")}</th><th scope="col">W</th><th scope="col">D</th><th scope="col">L</th><th scope="col">GD</th><th scope="col">{rules.family==='LADDER'?'Rating':'Points'}</th></tr></thead><tbody>{data.standings.map(row=><tr key={row.entryId}><td>{row.rank}</td><th scope="row">{row.label}</th><td>{row.played}</td><td>{row.wins}</td><td>{row.draws}</td><td>{row.losses}</td><td>{row.goalsFor-row.goalsAgainst}</td><td>{rules.family==='LADDER'?row.rating:row.points}</td></tr>)}</tbody></table></div>}
      {editable&&data.rankingStageId&&data.rankContests?.map(contest=><details key={contest.fromRank}><summary>{activityCopy("Resolve tied season order · rank")}{' '}{contest.fromRank}</summary><ul>{contest.entries.map(entry=><li key={entry.entryId}>#{entry.entryId} · {entry.label}</li>)}</ul><form onSubmit={event=>{event.preventDefault();const orderedEntryIds=(rankOrders[contest.fromRank]||'').split(',').map(value=>Number(value.trim()));if(orderedEntryIds.every(Number.isSafeInteger))void command('resolve-rank',{stageId:data.rankingStageId,orderedEntryIds,reason});}}><div>{contest.entries.map((_,index)=><label key={index}>{activityCopy("Rank")} {contest.fromRank+index}<select required value={(rankOrders[contest.fromRank]||'').split(',')[index]||''} onChange={e=>{const next=(rankOrders[contest.fromRank]||'').split(',');next[index]=e.target.value;setRankOrders({...rankOrders,[contest.fromRank]:next.join(',')});}}><option value="">{activityCopy("Choose an entry")}</option>{contest.entries.map(entry=><option key={entry.entryId} value={entry.entryId}>{entry.label}</option>)}</select></label>)}</div><label>{activityCopy("Published rule and decision evidence")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={busy}>{activityCopy("Record season order")}</button></form></details>)}
      {['SWISS','ROTATION','KING_OF_PITCH'].includes(rules.structure)&&<>
        <p>{data.rounds.length} of {rules.rounds} {activityCopy("rounds generated.")}{' '}{rules.structure==='SWISS'?'Confirm the current results before drawing the next round.':'Check pitch allocation, playing time and rest before the next rotation.'}</p>
        {editable&&data.rounds.length<rules.rounds&&<form onSubmit={event=>{event.preventDefault();const date=dateValue();if(date)void command('rounds',{startsAt:date});}}><label>{activityCopy("Next round start (")}{' '}{Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" required value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><button type="submit" className="co-primary" disabled={busy}>{activityCopy("Generate next round")}</button></form>}
        {editable&&data.rounds.length>0&&<details><summary>{activityCopy("Correct a previous round")}</summary><p>{activityCopy("Retract the last unplayed, unlinked round before correcting a result that determined later pairings.")}</p><label>{activityCopy("Reason")}<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy||!reason.trim()} onClick={()=>void command('rounds/retract',{action:'RETRACT',reason})}>{activityCopy("Retract last unplayed round")}</button></details>}
      </>}
      {rules.family==='LADDER'&&interactive&&data.controllableEntries.length>0&&['PLANNING','ACTIVE'].includes(tournament.status)&&<form onSubmit={event=>{event.preventDefault();const date=dateValue();if(date)void command('challenges',{entryId:Number(entryId),targetEntryId:Number(targetId),startsAt:date,venue});}}>
        <h3>{activityCopy("Propose a ladder challenge")}</h3><label>{activityCopy("Your entry")}<select required value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">{activityCopy("Choose your entry")}</option>{data.standings.filter(row=>data.controllableEntries.includes(row.entryId)).map(row=><option key={row.entryId} value={row.entryId}>{row.label}</option>)}</select></label>
        <label>{activityCopy("Opponent")}<select required value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">{activityCopy("Choose an opponent")}</option>{data.standings.filter(row=>row.entryId!==Number(entryId)).map(row=><option key={row.entryId} value={row.entryId}>#{row.rank} · {row.label}</option>)}</select></label><label>{activityCopy("Proposed kick-off (")}{' '}{Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" required value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label>{activityCopy("Venue & agreed conditions")}<input required maxLength={255} value={venue} onChange={e=>setVenue(e.target.value)}/></label><button type="submit" className="co-primary" disabled={busy}>{activityCopy("Send challenge")}</button>
      </form>}
      {data.challenges.length>0&&<div className="co-challenges"><h3>{activityCopy("Your challenges")}</h3>{data.challenges.map(challenge=><article key={challenge.id}><p>#{challenge.id} · {challenge.status} · {new Date(challenge.proposed_at).toLocaleString()}</p><p>{challenge.venue}</p>{challenge.fixture_id&&<p>{activityCopy("Fixture #")}{' '}{challenge.fixture_id} {activityCopy("· see Matchday for its preparation and result.")}</p>}
        {interactive&&challenge.status==='PENDING'&&<div>{data.controllableEntries.includes(challenge.target_entry_id)&&['ACCEPT','DECLINE'].map(action=><button type="button" key={action} disabled={busy} onClick={()=>void command(`challenges/${challenge.id}/decision`,{action,reason:''})}>{action==='ACCEPT'?'Accept challenge':'Decline'}</button>)}{data.controllableEntries.includes(challenge.challenger_entry_id)&&<button type="button" disabled={busy} onClick={()=>void command(`challenges/${challenge.id}/decision`,{action:'WITHDRAW',reason:''})}>{activityCopy("Withdraw")}</button>}</div>}
        {interactive&&['ACCEPTED','COMPLETED','DISPUTED'].includes(challenge.status)&&<details><summary>{activityCopy("Dispute or resolve")}</summary><label>{activityCopy("Reason")}<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{challenge.status!=='DISPUTED'&&<button type="button" disabled={busy||!reason.trim()} onClick={()=>void command(`challenges/${challenge.id}/decision`,{action:'DISPUTE',reason})}>{activityCopy("Raise a dispute")}</button>}{data.canOperate&&challenge.status==='DISPUTED'&&<button type="button" disabled={busy||!reason.trim()} onClick={()=>void command(`challenges/${challenge.id}/decision`,{action:'RESOLVE',reason})}>{activityCopy("Resolve dispute")}</button>}</details>}
      </article>)}</div>}
      {['ROUND_ROBIN','HOME_AWAY','KNOCKOUT','GROUPS_KNOCKOUT','SPLIT_LEAGUE'].includes(rules.structure)&&<CompetitionDrawPanel tournament={tournament} operations={data} interactive={interactive} changed={async()=>{setAttempt(a=>a+1);if(changed)await changed();}}/>}
      {editable&&data.canComplete&&tournament.status==='ACTIVE'&&<details><summary>{activityCopy("Complete the competition season")}</summary><p>{activityCopy("Resolve unfinished fixtures, challenges and disputes first. Festival completion can preserve participation without selecting a champion.")}</p><label>{activityCopy("Completion reason")}<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy||!reason.trim()} onClick={()=>void command('finish',{action:'FINISH',reason})}>{activityCopy("Complete season")}</button></details>}
    </>}
  </section>;
}
