import {useCompetitionCopy} from './competitionCopy';
import { useEffect, useState } from 'react';
import type { TournamentDetail } from '../tournaments/domain';
import { extractApiErrorMessage } from '../../utils/apiError';
import { drawOperation, getDraw, type DrawPlan, type DrawState, type OperationsState } from './api';
import { useCompetitionCommand } from './useCompetitionCommand';
import { CompetitionReplayPanel } from './CompetitionReplayPanel';
import { CompetitionPlayoffForm } from './CompetitionPlayoffForm';

export function CompetitionDrawPanel({tournament,operations,interactive,changed}:{tournament:TournamentDetail;operations:OperationsState;interactive:boolean;changed:()=>Promise<void>}) {
  const activityCopy=useCompetitionCopy();
  const [draw,setDraw]=useState<DrawState>(),[loadError,setLoadError]=useState(''),[attempt,setAttempt]=useState(0);
  const [start,setStart]=useState(''),[reason,setReason]=useState(''),[selected,setSelected]=useState<Record<number,string>>({});
  const [rankOrders,setRankOrders]=useState<Record<string,string>>({});
  const [plan,setPlan]=useState<Omit<DrawPlan,'startsAt'>>({daysBetweenRounds:0,groupCount:2,qualifiers:1,routes:1,thirdPlace:false,twoLegged:false,aggregateResolution:'PENALTIES',carryResults:false,splitCut:2,divisionLinks:''});
  const commands=useCompetitionCommand(),rules=operations.profile.rules;
  useEffect(()=>{const controller=new AbortController();void getDraw(tournament.id,controller.signal).then(value=>{if(!controller.signal.aborted){setDraw(value);setLoadError('');}}).catch(cause=>{if(!controller.signal.aborted)setLoadError(extractApiErrorMessage(cause,'Could not load the competition draw.'));});return()=>controller.abort();},[tournament.id,operations.profile.revision,attempt]);
  if(!rules)return null;
  const isCup=['KNOCKOUT','GROUPS_KNOCKOUT'].includes(rules.structure),isSplit=rules.structure==='SPLIT_LEAGUE';
  const editable=interactive&&operations.canOperate&&['PLANNING','ACTIVE'].includes(tournament.status);
  async function run(path:string,body:Record<string,unknown>){await commands.run(`draw/${path}`,body,operations.profile.revision,payload=>drawOperation(tournament.id,path,payload),async value=>{setDraw(value);await changed();},()=>setAttempt(a=>a+1));}
  const time=()=>{const value=new Date(start);return Number.isFinite(value.getTime())?value.toISOString():null;};
  const label=(id:number|undefined)=>tournament.entries.find(e=>e.id===id)?.displayName||operations.standings.find(e=>e.entryId===id)?.label||`Entry #${id}`;
  return <section className="co-draw" aria-label={activityCopy("Draw and qualification")}>
    <h3>{activityCopy("Draw & qualification")}</h3>
    {loadError&&<div role="alert"><p>{loadError}</p><button type="button" onClick={()=>setAttempt(a=>a+1)}>{activityCopy("Retry draw")}</button></div>}
    {commands.error&&<p role="alert">{commands.error}</p>}{commands.notice&&<p role="status">{commands.notice}</p>}
    {!draw&&!loadError&&<p role="status">{activityCopy("Loading draw…")}</p>}
    {draw&&!draw.plan&&<>
      {tournament.fixtures.length>0?<p>{activityCopy("The existing draw is retained. Continue with its stages and matchday tools.")}</p>:<p>{activityCopy("Activate the eligible entries, then review a complete schedule. Every fixture uses the competition timezone, playing time, pitches and rest rules.")}</p>}
      {editable&&tournament.status==='PLANNING'&&tournament.fixtures.length===0&&<form onSubmit={event=>{event.preventDefault();const startsAt=time();if(startsAt)void run('',{...plan,startsAt});}}>
        <div className="co-draw-fields"><label>{activityCopy("Opening kick-off (")}{' '}{Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label>
        <label>{activityCopy("Days between rounds")}<input type="number" min={0} max={365} required value={plan.daysBetweenRounds} onChange={e=>setPlan({...plan,daysBetweenRounds:Number(e.target.value)})}/><small>{activityCopy("0 schedules sequential rounds with the configured rest.")}</small></label></div>
        {rules.structure==='GROUPS_KNOCKOUT'&&<div className="co-draw-fields"><label>{activityCopy("Groups")}<input type="number" required min={2} max={8} value={plan.groupCount} onChange={e=>setPlan({...plan,groupCount:Number(e.target.value)})}/></label><label>{activityCopy("Entries per group in each route")}<input type="number" required min={1} max={8} value={plan.qualifiers} onChange={e=>setPlan({...plan,qualifiers:Number(e.target.value)})}/></label><label>{activityCopy("Qualification routes")}<select value={plan.routes} onChange={e=>setPlan({...plan,routes:Number(e.target.value)})}><option value={1}>{activityCopy("Cup")}</option><option value={2}>{activityCopy("Cup & Plate")}</option><option value={3}>{activityCopy("Cup, Plate & Bowl")}</option><option value={4}>{activityCopy("Cup, Plate, Bowl & Shield")}</option></select></label></div>}
        {isCup&&<><label><input type="checkbox" checked={plan.twoLegged} onChange={e=>setPlan({...plan,twoLegged:e.target.checked})}/> {activityCopy("Two-legged knockout ties")}</label>{plan.twoLegged&&<label>{activityCopy("Level aggregate resolution")}<select value={plan.aggregateResolution} onChange={e=>setPlan({...plan,aggregateResolution:e.target.value as DrawPlan['aggregateResolution']})}><option value="PENALTIES">{activityCopy("Penalty decision, recorded with evidence")}</option><option value="REPLAY">{activityCopy("Replay decision, recorded with evidence")}</option><option value="DRAW_LOTS">{activityCopy("Drawing lots under the published rules")}</option></select><small>{activityCopy("No away-goals rule. Each leg keeps its own score.")}</small></label>}<label><input type="checkbox" checked={plan.thirdPlace} onChange={e=>setPlan({...plan,thirdPlace:e.target.checked})}/> {activityCopy("Third-place match for semifinal losers")}</label></>}
        {isSplit&&<><label>{activityCopy("Entries in the championship split")}<input type="number" required min={2} max={30} value={plan.splitCut} onChange={e=>setPlan({...plan,splitCut:Number(e.target.value)})}/></label><label><input type="checkbox" checked={plan.carryResults} onChange={e=>setPlan({...plan,carryResults:e.target.checked})}/> {activityCopy("Carry first-phase results between teams in the same split")}</label></>}
        {(isSplit||rules.family==='LEAGUE')&&<label>{activityCopy("Divisions & promotion / playoff destinations")}<textarea maxLength={1000} value={plan.divisionLinks} onChange={e=>setPlan({...plan,divisionLinks:e.target.value})}/><small>{activityCopy("State the linked competition and decision authority. This declaration does not grant federation approval or change another competition.")}</small></label>}
        <button type="submit" className="co-primary" disabled={commands.busy}>{activityCopy("Create reviewed draw")}</button>
      </form>}
    </>}
    {draw?.plan&&<>
      {editable&&['ROUND_ROBIN','HOME_AWAY'].includes(rules.structure)&&!draw.transitioned&&<CompetitionPlayoffForm draw={draw} busy={commands.busy} run={run}/>}
      <CompetitionReplayPanel id={tournament.id} draw={draw} editable={Boolean(editable)} busy={commands.busy} run={run}/>
      <p>{draw.plan.twoLegged?'Two-legged ties; no away goals. ':''}{draw.plan.thirdPlace?'Semifinal losers enter third-place fixtures. ':''}{draw.plan.carryResults?'First-phase results within each split are carried forward. ':''}{draw.plan.divisionLinks}</p>
      {draw.stages.filter(stage=>stage.standings?.length).map(stage=><div key={stage.id} className="co-table-scroll" tabIndex={0} role="region" aria-label={`${stage.name} table`}><table><caption>{stage.name}{stage.carry_results?' · results carried forward':''}</caption><thead><tr><th scope="col">{activityCopy("Rank")}</th><th scope="col">{activityCopy("Entry")}</th><th scope="col">{activityCopy("Played")}</th><th scope="col">GD</th><th scope="col">{activityCopy("Points")}</th></tr></thead><tbody>{stage.standings?.map(row=><tr key={row.entryId}><td>{row.rank}</td><th scope="row">{row.label}</th><td>{row.played}</td><td>{row.goalsFor-row.goalsAgainst}</td><td>{row.points}</td></tr>)}</tbody></table></div>)}
      {editable&&draw.stages.flatMap(stage=>(stage.rankContests||[]).map(contest=>{const key=`${stage.id}:${contest.fromRank}`;return <details key={key}><summary>{activityCopy("Resolve tied sporting order ·")}{' '}{stage.name}{activityCopy(", rank")}{' '}{contest.fromRank}</summary><ul>{contest.entries.map(entry=><li key={entry.entryId}>#{entry.entryId} · {entry.label}</li>)}</ul><form onSubmit={event=>{event.preventDefault();const orderedEntryIds=(rankOrders[key]||'').split(',').map(value=>Number(value.trim()));if(orderedEntryIds.every(value=>Number.isSafeInteger(value)&&value>0))void run('resolve-rank',{stageId:stage.id,orderedEntryIds,reason});}}><div>{contest.entries.map((_,index)=><label key={index}>{activityCopy("Rank")} {contest.fromRank+index}<select required value={(rankOrders[key]||'').split(',')[index]||''} onChange={e=>{const next=(rankOrders[key]||'').split(',');next[index]=e.target.value;setRankOrders({...rankOrders,[key]:next.join(',')});}}><option value="">{activityCopy("Choose an entry")}</option>{contest.entries.map(entry=><option key={entry.entryId} value={entry.entryId}>{entry.label}</option>)}</select></label>)}</div><label>{activityCopy("Published rule and decision evidence")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={commands.busy}>{activityCopy("Record sporting order")}</button></form></details>;}))}
      {editable&&['GROUPS_KNOCKOUT','SPLIT_LEAGUE'].includes(rules.structure)&&!draw.transitioned&&<form onSubmit={event=>{event.preventDefault();const startsAt=time();if(startsAt)void run('transition',{startsAt});}}><p>{activityCopy("Confirm all first-phase results and resolve qualification ties before drawing the next phase.")}</p><label>{activityCopy("Next-phase opening (")}{' '}{Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><button type="submit" className="co-primary" disabled={commands.busy}>{activityCopy("Draw qualified next phase")}</button></form>}
      {draw.aggregates.length>0&&<div><h4>{activityCopy("Aggregate ties")}</h4>{draw.aggregates.map(tie=><article key={tie.deciding_fixture_id}><p>{activityCopy("Legs #")}{' '}{tie.first_fixture_id} & #{tie.deciding_fixture_id} · {tie.ready?`${label(tie.homeEntryId)} ${tie.homeAggregate}–${tie.awayAggregate} ${label(tie.awayEntryId)}`:'Awaiting both confirmed leg scores'}</p><p>{tie.winner?`Advances: ${label(tie.winner)}`:tie.tied?`Level aggregate · ${tie.resolution.toLowerCase().replaceAll('_',' ')}`:''}</p>{editable&&tie.resolution!=='REPLAY'&&tie.ready&&tie.tied&&!tie.winner&&<form onSubmit={event=>{event.preventDefault();void run('resolve-aggregate',{fixtureId:tie.deciding_fixture_id,selectedEntryId:Number(selected[tie.deciding_fixture_id]),reason});}}><label>{activityCopy("Winner under the agreed resolution")}<select required value={selected[tie.deciding_fixture_id]||''} onChange={e=>setSelected({...selected,[tie.deciding_fixture_id]:e.target.value})}><option value="">{activityCopy("Choose the resolved winner")}</option>{[tie.homeEntryId,tie.awayEntryId].map(id=><option key={id} value={id}>{label(id)}</option>)}</select></label><label>{activityCopy("Decision and evidence")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={commands.busy}>{activityCopy("Record aggregate decision")}</button></form>}</article>)}</div>}
      {draw.routes.length>0&&<details><summary>{activityCopy("Advancement & placement destinations")}</summary><ul>{draw.routes.map(route=><li key={`${route.target_fixture_id}:${route.slot}`}>{route.outcome==='LOSER'?'Loser':'Winner'} {activityCopy("of fixture #")}{' '}{route.source_fixture_id} → #{route.target_fixture_id}, {route.slot.toLowerCase()} {activityCopy("side")}</li>)}</ul></details>}
      {draw.slots.length>0&&<details><summary>{activityCopy("Pitch allocation & timetable (")}{' '}{rules.timezone})</summary><ol>{draw.slots.map(slot=><li key={slot.fixture_id}>{activityCopy("Fixture #")}{' '}{slot.fixture_id} {activityCopy("· Pitch")}{' '}{slot.pitch_number} · {new Date(slot.starts_at).toLocaleString(undefined,{timeZone:rules.timezone})} · {rules.matchMinutes} {activityCopy("minutes")}</li>)}</ol></details>}
      {editable&&draw.transitioned&&<details><summary>{activityCopy("Retract an unplayed second phase")}</summary><p>{activityCopy("Use this before correcting first-phase qualification or carried results. Played or linked matches require reopening and unlinking first.")}</p><label>{activityCopy("Reason")}<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={commands.busy||!reason.trim()} onClick={()=>void run('retract-transition',{action:'RETRACT',reason})}>{activityCopy("Retract second phase")}</button></details>}
    </>}
  </section>;
}
