import {useCompetitionCopy} from './competitionCopy';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiClient } from '../../api/axiosConfig';
import { extractApiErrorMessage } from '../../utils/apiError';
import type { TournamentDetail } from '../tournaments/domain';
import type { OperationsState } from './api';
import { useCompetitionCommand } from './useCompetitionCommand';

interface Route {id:number;source_competition_id:number;source_stage_id:number;target_competition_id:number;from_rank:number;places:number;route_kind:string;status:string;target_entry_ids:number[]|null;target_invitation_ids:number[]|null;reason:string}
export function CompetitionDivisionsPanel({tournament,operations,changed}:{tournament:TournamentDetail;operations:OperationsState;changed:()=>Promise<void>}){
  const activityCopy=useCompetitionCopy();
  const [routes,setRoutes]=useState<Route[]>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  const [destination,setDestination]=useState(''),[stage,setStage]=useState(''),[from,setFrom]=useState(1),[places,setPlaces]=useState(1),[kind,setKind]=useState('PROMOTION'),[reason,setReason]=useState('');
  const commands=useCompetitionCommand();
  useEffect(()=>{const controller=new AbortController();void apiClient.get<Route[]>(`/competitions/${tournament.id}/divisions`,{signal:controller.signal}).then(response=>{if(!controller.signal.aborted){setRoutes(response.data);setError('');}}).catch(cause=>{if(!controller.signal.aborted){setRoutes(undefined);setError(extractApiErrorMessage(cause,'Could not load division offers.'));}});return()=>controller.abort();},[tournament.id,operations.profile.revision,attempt]);
  const run=async(path:string,body:Record<string,unknown>)=>commands.run(`divisions/${path}`,body,operations.profile.revision,async payload=>(await apiClient.post<Route[]>(`/competitions/${tournament.id}/divisions${path?`/${path}`:''}`,payload)).data,async value=>{setRoutes(value);await changed();},()=>setAttempt(a=>a+1));
  return <details className="co-divisions"><summary>{activityCopy("Divisions, promotion & qualification offers")}</summary>
    <p>{activityCopy("A completed table or playoff can qualify entries for a compatible next competition. Its organiser reviews the offer; clubs and players still accept their invitations. These recorded decisions do not certify federation promotion.")}</p>
    {error&&<div role="alert"><p>{error}</p><button type="button" onClick={()=>setAttempt(a=>a+1)}>{activityCopy("Retry division offers")}</button></div>}{commands.error&&<p role="alert">{commands.error}</p>}{commands.notice&&<p role="status">{commands.notice}</p>}
    {tournament.status==='COMPLETED'&&<form onSubmit={event=>{event.preventDefault();const match=destination.match(/(?:^|\/)tournaments\/(\d+)(?:[?#]|$)/);if(match)void run('',{sourceStageId:Number(stage),targetCompetitionId:Number(match[1]),fromRank:from,places,kind,reason});else setError('Paste a GrassKickZ competition link, for example /tournaments/123.');}}><label>{activityCopy("Source table or playoff")}<select required value={stage} onChange={e=>setStage(e.target.value)}><option value="">{activityCopy("Choose the sporting source")}</option>{tournament.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>{activityCopy("Destination competition link")}<input required value={destination} onChange={e=>setDestination(e.target.value)} maxLength={500}/></label><div className="co-draw-fields"><label>{activityCopy("First qualifying rank")}<input required type="number" min={1} max={64} value={from} onChange={e=>setFrom(Number(e.target.value))}/></label><label>{activityCopy("Places")}<input required type="number" min={1} max={32} value={places} onChange={e=>setPlaces(Number(e.target.value))}/></label></div><label>{activityCopy("Purpose")}<select value={kind} onChange={e=>setKind(e.target.value)}><option value="PROMOTION">{activityCopy("Promotion offer")}</option><option value="RELEGATION">{activityCopy("Relegation / lower-division offer")}</option><option value="QUALIFICATION">{activityCopy("Qualification offer")}</option></select></label><label>{activityCopy("Published rules, authority and reason")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={commands.busy}>{activityCopy("Propose qualified entries")}</button></form>}
    {routes?.length===0&&<p>{activityCopy("No division offers recorded.")}</p>}
    {routes?.filter(route=>route.status==='PROPOSED'||route.status==='ACCEPTED'&&route.target_competition_id===tournament.id&&tournament.status==='PLANNING').map(route=><form key={`retract-${route.id}`} onSubmit={event=>{event.preventDefault();void run(`${route.id}/retract`,{action:'RETRACT',reason});}}><label>{activityCopy("Correction evidence for offer #")}{' '}{route.id}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>{activityCopy("Pending invitations and entry reviews can be withdrawn. Accepted entries and fixtures must be resolved in the destination first.")}</p><button type="submit" disabled={commands.busy}>{activityCopy("Retract division offer #")}{' '}{route.id}</button></form>)}
    {routes?.map(route=><article key={route.id}><p><Link to={`/tournaments/${route.source_competition_id}`}>{activityCopy("Source competition")}</Link> → <Link to={`/tournaments/${route.target_competition_id}`}>{activityCopy("Destination competition")}</Link> · {route.route_kind.toLowerCase()} {activityCopy("· ranks")}{' '}{route.from_rank}–{route.from_rank+route.places-1} · {route.status.toLowerCase()}</p><p>{route.reason}</p>{route.status==='ACCEPTED'&&<p>{route.target_invitation_ids?.length||0} {activityCopy("invitation(s) awaiting participant consent;")}{' '}{route.target_entry_ids?.length||0} {activityCopy("off-platform entry review(s). Review them in the destination's Participants.")}</p>}{route.status==='PROPOSED'&&route.target_competition_id===tournament.id&&tournament.status==='PLANNING'&&<form onSubmit={event=>{event.preventDefault();void run(`${route.id}/decision`,{action:'ACCEPT',reason});}}><label>{activityCopy("Destination decision evidence")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={commands.busy}>{activityCopy("Accept qualification offers")}</button><button type="button" disabled={commands.busy||!reason.trim()} onClick={()=>void run(`${route.id}/decision`,{action:'DECLINE',reason})}>{activityCopy("Decline")}</button></form>}</article>)}
  </details>;
}
