import {useCompetitionCopy} from './competitionCopy';
import { useState } from 'react';
import type { TournamentDetail } from '../tournaments/domain';

export function CompetitionLifecyclePanel({tournament,busy,canReopen,canWithdraw,run}:{tournament:TournamentDetail;busy:boolean;canReopen:boolean;canWithdraw:boolean;run:(path:string,body:Record<string,unknown>)=>Promise<void>}){
  const activityCopy=useCompetitionCopy();
  const [fixtureId,setFixtureId]=useState(''),[entryId,setEntryId]=useState(''),[start,setStart]=useState(''),[pitch,setPitch]=useState(1),[awarded,setAwarded]=useState(1),[conceded,setConceded]=useState(0),[reason,setReason]=useState('');
  const fixture=tournament.fixtures.find(f=>f.id===Number(fixtureId));
  const label=(id:number|null)=>{const e=tournament.entries.find(e=>e.id===id);return e?.squadName||e?.clubName||e?.displayName||'Awaiting qualification';};
  return <details><summary>{activityCopy("Postponement, forfeits & season corrections")}</summary>
    {tournament.status==='COMPLETED'&&canReopen?<form onSubmit={e=>{e.preventDefault();void run('reopen-season',{action:'REOPEN',reason});}}><p>{activityCopy("Reopening clears the current champion and preserves the previous outcome in the audit. Resolve downstream division offers first, then correct dependent matches in reverse order.")}</p><label>{activityCopy("Correction evidence")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={busy}>{activityCopy("Reopen season for correction")}</button></form>:['PLANNING','ACTIVE'].includes(tournament.status)&&<>
      <label>{activityCopy("Unplayed fixture")}<select value={fixtureId} onChange={e=>{setFixtureId(e.target.value);setEntryId('');}}><option value="">{activityCopy("Choose a fixture")}</option>{tournament.fixtures.filter(f=>f.status==='SCHEDULED').map(f=><option key={f.id} value={f.id}>{f.stageName} · {label(f.homeEntryId)} vs {label(f.awayEntryId)}</option>)}</select></label>
      <label>{activityCopy("Published rule, request and reason")}<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>
      {fixture&&<form onSubmit={e=>{e.preventDefault();const date=new Date(start);if(Number.isFinite(date.getTime()))void run('fixtures/postpone',{fixtureId:fixture.id,startsAt:date.toISOString(),locationId:fixture.locationId,pitch,reason});}}><h4>{activityCopy("Postpone this fixture")}</h4><label>{activityCopy("New kick-off (")}{' '}{Intl.DateTimeFormat().resolvedOptions().timeZone})<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>{activityCopy("Allocated pitch")}<input required type="number" min={1} max={20} value={pitch} onChange={e=>setPitch(Number(e.target.value))}/></label><button type="submit" disabled={busy||!reason.trim()}>{activityCopy("Record postponement")}</button></form>}
      {tournament.status==='ACTIVE'&&<>
        <p>{activityCopy("Forfeit scores are explicit organiser choices under the published rules; no universal score is assumed.")}</p><div className="co-draw-fields"><label>{activityCopy("Awarded goals")}<input type="number" required min={1} max={100} value={awarded} onChange={e=>setAwarded(Number(e.target.value))}/></label><label>{activityCopy("Forfeiting side's goals")}<input type="number" required min={0} max={99} value={conceded} onChange={e=>setConceded(Number(e.target.value))}/></label></div>
        {fixture&&<form onSubmit={e=>{e.preventDefault();void run('fixtures/forfeit',{fixtureId:fixture.id,forfeitingEntryId:Number(entryId),awardedGoals:awarded,forfeitingGoals:conceded,reason});}}><label>{activityCopy("Forfeiting participant")}<select required value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">{activityCopy("Choose the participant")}</option>{[fixture.homeEntryId,fixture.awayEntryId].filter(id=>id!=null).map(id=><option key={id} value={id!}>{label(id)}</option>)}</select></label><button type="submit" disabled={busy||!reason.trim()||awarded<=conceded}>{activityCopy("Record forfeit result")}</button></form>}
        {canWithdraw&&<details><summary>{activityCopy("Approve an entry's season withdrawal")}</summary><p>{activityCopy("Record the entry's request or organiser authority. Remaining assigned fixtures receive the explicit forfeit score. Prior results remain. Retract dependent split/playoff phases first.")}</p><label>{activityCopy("Withdrawing entry")}<select required value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">{activityCopy("Choose an active entry")}</option>{tournament.entries.filter(e=>e.status==='ACTIVE').map(e=><option key={e.id} value={e.id}>{label(e.id)}</option>)}</select></label><button type="button" disabled={busy||!reason.trim()||!entryId||awarded<=conceded} onClick={()=>void run('entries/withdraw-season',{entryId:Number(entryId),awardedGoals:awarded,forfeitingGoals:conceded,reason})}>{activityCopy("Record season withdrawal")}</button></details>}
      </>}
    </>}
  </details>;
}
