import {useTranslation} from 'react-i18next';
export const competitionGeorgian:Record<string,string>={
  "Tournaments & leagues": "ტურნირები და ლიგები",
  "Tournament format": "ტურნირის ფორმატი",
  "Tournament type": "ტურნირის ტიპი",
  "Format": "ფორმატი",
  "All formats": "ყველა ფორმატი",
  "Competitions": "შეჯიბრებები",
  "Competition": "შეჯიბრება",
  "Discover hosts": "მასპინძლების ნახვა",
  "Competition family": "შეჯიბრების ოჯახი",
  "All competitions": "ყველა შეჯიბრება",
  "Leagues": "ლიგები",
  "Cups & Tournaments": "თასები და ტურნირები",
  "Ladders": "გამოწვევის ლიგები",
  "Festivals": "ფესტივალები",
  "Family": "ოჯახი",
  "Structure": "ფორმატი",
  "Age group": "ასაკობრივი ჯგუფი",
  "Discipline": "დისციპლინა",
  "Side size": "მხარის მოთამაშეთა რაოდენობა",
  "Entry type": "მონაწილეობის ტიპი",
  "Status": "სტატუსი",
  "Country": "ქვეყანა",
  "City": "ქალაქი",
  "Level": "დონე",
  "Eligibility": "მონაწილეობის პირობები",
  "Host type": "მასპინძლის ტიპი",
  "Host": "მასპინძელი",
  "Open places": "თავისუფალი ადგილები",
  "Registration": "რეგისტრაცია",
  "From": "დან",
  "Until": "მდე",
  "Currency": "ვალუტა",
  "Minimum fee": "მინიმალური საფასური",
  "Maximum fee": "მაქსიმალური საფასური",
  "Fee basis": "საფასურის საფუძველი",
  "Latitude": "განედი",
  "Longitude": "გრძედი",
  "Radius (km)": "რადიუსი (კმ)",
  "All": "ყველა",
  "Sort": "დალაგება",
  "Event date": "შეჯიბრების თარიღი",
  "Newest": "უახლესი",
  "Name": "სახელი",
  "Search competitions": "შეჯიბრებების ძებნა",
  "Competition name or description": "შეჯიბრების სახელი ან აღწერა",
  "Filters": "ფილტრები",
  "Active filters": "აქტიური ფილტრები",
  "Clear all": "ყველას წაშლა",
  "Find the right competition": "შეარჩიეთ შეჯიბრება",
  "Reset filters": "ფილტრების განულება",
  "Close filters": "ფილტრების დახურვა",
  "Playing discipline": "სათამაშო დისციპლინა",
  "Association football": "ფეხბურთი",
  "Futsal": "ფუტსალი",
  "Beach soccer": "სანაპიროს ფეხბურთი",
  "Walking football": "ფეხით სიარულის ფეხბურთი",
  "Other ruleset": "სხვა წესები",
  "Players per side": "მოთამაშეთა რაოდენობა მხარეს",
  "Club teams": "კლუბის გუნდები",
  "Squads": "გუნდები",
  "Individual players": "ინდივიდუალური მოთამაშეები",
  "Registration & planning": "რეგისტრაცია და დაგეგმვა",
  "In progress": "მიმდინარეობს",
  "Completed": "დასრულებულია",
  "Cancelled": "გაუქმებულია",
  "Playing level": "სათამაშო დონე",
  "Development": "განვითარება",
  "Recreational": "სამოყვარულო",
  "Competitive": "შეჯიბრებითი",
  "Elite": "ელიტური",
  "Eligibility category": "მონაწილეობის კატეგორია",
  "Exact published category": "გამოქვეყნებული კატეგორია",
  "Open now": "ახლა ღიაა",
  "Not yet open": "ჯერ არ გახსნილა",
  "Closed": "დახურულია",
  "Capacity": "ტევადობა",
  "Open places only": "მხოლოდ თავისუფალი ადგილები",
  "Organiser & host": "ორგანიზატორი და მასპინძელი",
  "Club": "კლუბი",
  "Organisation": "ორგანიზაცია",
  "Find a host and its competitions": "იპოვეთ მასპინძელი და მისი შეჯიბრებები",
  "Distance from a location": "მანძილი ადგილიდან",
  "Use my location": "ჩემი მდებარეობის გამოყენება",
  "Manual coordinates are also supported. A distance search needs all three values.": "კოორდინატების შეყვანაც შეგიძლიათ. მანძილით ძებნას სამივე მნიშვნელობა სჭირდება.",
  "Apply distance": "მანძილის გამოყენება",
  "Entry fee": "მონაწილეობის საფასური",
  "Compare fees in the same currency. Each record states its fee basis.": "შეადარეთ საფასური ერთ ვალუტაში. თითოეულ ჩანაწერში მითითებულია მისი საფუძველი.",
  "Per team": "გუნდზე",
  "Per player": "მოთამაშეზე",
  "Per event": "შეჯიბრებაზე",
  "Search could not be completed": "ძებნა ვერ დასრულდა",
  "Loading competitions…": "შეჯიბრებები იტვირთება…",
  "Try again": "ხელახლა ცდა",
  "No competitions match this search": "ამ ძებნით შეჯიბრებები ვერ მოიძებნა",
  "Try a different family, location or date.": "შეცვალეთ ოჯახი, ადგილი ან თარიღი.",
  "Clear filters": "ფილტრების წაშლა",
  "Dates": "თარიღები",
  "Location": "ადგილი",
  "Entries": "მონაწილეები",
  "individual entry": "ინდივიდუალური მონაწილეობა",
  "team entry": "გუნდური მონაწილეობა",
  "No entry fee": "მონაწილეობა უფასოა",
  "View competition": "შეჯიბრების ნახვა",
  "Round-robin": "წრიული სისტემა",
  "Home & away": "საშინაო და გასვლითი",
  "Knockout": "გამოთიშვით",
  "Groups then knockout": "ჯგუფები და გამოთიშვით",
  "Swiss rounds": "შვეიცარიული რაუნდები",
  "Split league": "გაყოფილი ლიგა",
  "Challenge ladder": "გამოწვევების რეიტინგი",
  "Development festival": "განვითარების ფესტივალი",
  "King of the Pitch": "მოედნის მეფე",
  "Minimum roster": "გუნდის მინიმალური შემადგენლობა",
  "Maximum match length for this age/ruleset (minutes)": "მატჩის მაქსიმალური ხანგრძლივობა ამ ასაკისა და წესებისთვის (წუთები)",
  "Minimum player age at cutoff": "მოთამაშის მინიმალური ასაკი ათვლის თარიღზე",
  "Ladder inactivity limit (days; 0 disables)": "უმოქმედობის ზღვარი (დღე; 0 გამორთავს)",
  "Reload competition": "შეჯიბრების ხელახლა ჩატვირთვა",
  "Match / rest": "მატჩი / დასვენება",
  "Competition rules & season policy": "შეჯიბრების წესები და სეზონის პოლიტიკა",
  "Eligibility review & rule authority": "მონაწილეობის შემოწმება და წესების წყარო",
  "Private review evidence": "შემოწმების პირადი მტკიცებულება",
  "Record eligibility review": "მონაწილეობის შემოწმების შენახვა",
  "Competition standings": "შეჯიბრების ცხრილი",
  "Ladder ranking": "გამოწვევების რეიტინგი",
  "Rank": "ადგილი",
  "Entry": "მონაწილე",
  "Played": "ნათამაშები",
  "Rating": "რეიტინგი",
  "Points": "ქულები",
  "Choose an entry": "აირჩიეთ მონაწილე",
  "Reason": "მიზეზი",
  "Generate next round": "შემდეგი რაუნდის შექმნა",
  "Correct a previous round": "წინა რაუნდის შესწორება",
  "Retract last unplayed round": "ბოლო უთამაშებელი რაუნდის გაუქმება",
  "Propose a ladder challenge": "გამოწვევის შეთავაზება",
  "Your entry": "თქვენი მონაწილე",
  "Choose your entry": "აირჩიეთ თქვენი მონაწილე",
  "Opponent": "მეტოქე",
  "Choose an opponent": "აირჩიეთ მეტოქე",
  "Venue & agreed conditions": "ადგილი და შეთანხმებული პირობები",
  "Send challenge": "გამოწვევის გაგზავნა",
  "Your challenges": "თქვენი გამოწვევები",
  "Accept challenge": "გამოწვევის მიღება",
  "Decline": "უარი",
  "Withdraw": "გასვლა",
  "Dispute or resolve": "დავის გახსნა ან მოგვარება",
  "Raise a dispute": "დავის გახსნა",
  "Resolve dispute": "დავის მოგვარება",
  "Complete the competition season": "შეჯიბრების სეზონის დასრულება",
  "Completion reason": "დასრულების მიზეზი",
  "Complete season": "სეზონის დასრულება",
  "Draw and qualification": "კენჭისყრა და კვალიფიკაცია",
  "Draw & qualification": "კენჭისყრა და კვალიფიკაცია",
  "Retry draw": "კენჭისყრის ხელახლა ჩატვირთვა",
  "Loading draw…": "კენჭისყრა იტვირთება…",
  "Third-place fixture": "მატჩი მესამე ადგილისთვის",
  "Two-legged ties": "ორმატჩიანი დაპირისპირებები",
  "Choose a fixture": "აირჩიეთ მატჩი",
  "Matchday changes": "მატჩების ცვლილებები",
  "Postpone fixture": "მატჩის გადადება",
  "Record forfeit": "ტექნიკური შედეგის შენახვა",
  "Withdraw entry from season": "მონაწილის სეზონიდან გასვლა",
  "Reopen season": "სეზონის ხელახლა გახსნა",
  "Division offers": "დივიზიონში გადასვლის შეთავაზებები",
  "Destination competition link": "მიმღები შეჯიბრების ბმული",
  "Choose the sporting source": "აირჩიეთ სპორტული წყარო",
  "Purpose": "მიზანი",
  "First qualifying rank": "პირველი საკვალიფიკაციო ადგილი",
  "Places": "ადგილები",
  "Source competition": "წყარო შეჯიბრება",
  "Destination competition": "მიმღები შეჯიბრება",
  "Accept qualification offers": "კვალიფიკაციის შეთავაზებების მიღება",
  "Propose qualified entries": "კვალიფიციური მონაწილეების შეთავაზება",
  "Pairings follow current points and the ordered tie-breaks. Repeat opponents and repeated byes are prevented. Confirm each round before generating the next.": "წყვილები განისაზღვრება ქულებითა და მითითებული თანაბრობის წესებით. მეტოქეები და თავისუფალი ტურები არ მეორდება. ახალი რაუნდის შექმნამდე დაადასტურეთ მიმდინარე შედეგები.",
  "Rankings use this competition’s confirmed results: Elo starts at 1500, K=32. Challenge only inside the agreed range. The organiser resolves disputes; corrections recalculate the ranking.": "რეიტინგი ეყრდნობა ამ შეჯიბრების დადასტურებულ შედეგებს: Elo იწყება 1500-დან, K=32. გამოწვევა დაშვებულია შეთანხმებულ დიაპაზონში. დავებს ორგანიზატორი წყვეტს; შესწორებები რეიტინგს ხელახლა ითვლის.",
  "Winners stay up to the configured limit. On a draw both teams rotate. Waiting teams with the fewest appearances enter first.": "გამარჯვებული რჩება მითითებულ ზღვრამდე. ფრისას ორივე გუნდი იცვლება. რიგში უპირატესობა ნაკლები მატჩის მქონე გუნდებს აქვთ.",
  "Teams rotate through distinct opponents. Development festivals can finish without standings or a winner.": "გუნდები მონაცვლეობით თამაშობენ სხვადასხვა მეტოქესთან. განვითარების ფესტივალი შეიძლება დასრულდეს ცხრილისა და გამარჯვებულის გარეშე.",
  "Self-reported rules and authority. No sanctioning or verification is implied.": "წესები და უფლებამოსილება ორგანიზატორის მიერაა მითითებული. ეს სანქცირებას ან გადამოწმებას არ ნიშნავს.",
  "Ordered tie-breaks": "თანაბრობის წესების თანმიმდევრობა",
  "Add tie-break": "თანაბრობის წესის დამატება",
  "Earlier": "წინ",
  "Remove": "მოხსნა",
  "Loading competition rules…": "შეჯიბრების წესები იტვირთება…",
  "minutes": "წუთი",
  "· organiser-reported": "· ორგანიზატორის მიერ მითითებული",
  "Minimum roster:": "მინიმალური შემადგენლობა:",
  "· maximum match length:": "· მატჩის მაქსიმალური ხანგრძლივობა:",
  "minutes · minimum age at cutoff:": "წუთი · მინიმალური ასაკი ათვლის თარიღზე:",
  "· evidence supplied by organiser, unverified": "· ორგანიზატორის მტკიცებულება, გადაუმოწმებელი",
  "Entry for eligibility / reactivation review": "მონაწილე პირობების ან დაბრუნების შესამოწმებლად",
  "Record roster, cutoff, category and institution checks without unnecessary personal data. Then activate an eligible pending entry in Participants. Review notes remain private.": "ჩაწერეთ შემადგენლობის, ასაკის, კატეგორიისა და დაწესებულების შემოწმება ზედმეტი პირადი მონაცემების გარეშე. შემდეგ გაააქტიურეთ შესაბამისი მონაწილე მონაწილეების ჩანართში. ჩანაწერები პირადია.",
  "Elo ranking starts at 1500, K=32, for this competition only. Challenge within": "ამ შეჯიბრების Elo რეიტინგი იწყება 1500-დან, K=32. გამოწვევის დიაპაზონია",
  "positions; offers expire after": "ადგილი; შეთავაზება ვადაგასულია შემდეგ",
  "days or before kick-off.": "დღეში ან მატჩის დაწყებამდე.",
  "Development festival: no standings or champion. Teams rotate through the agreed timetable.": "განვითარების ფესტივალი: ცხრილისა და ჩემპიონის გარეშე. გუნდები შეთანხმებული განრიგით იცვლებიან.",
  "Resolve tied season order · rank": "თანაბარი ადგილების გადაწყვეტა · ადგილი",
  "Complete tied entry order, separated by commas": "თანაბარ მონაწილეთა სრული რიგი, მძიმით გაყოფილი",
  "Published rule and decision evidence": "გამოქვეყნებული წესი და გადაწყვეტილების მტკიცებულება",
  "Record season order": "სეზონის რიგის შენახვა",
  "rounds generated.": "რაუნდი შექმნილია.",
  "Next round start (": "შემდეგი რაუნდის დასაწყისი (",
  "Retract the last unplayed, unlinked round before correcting a result that determined later pairings.": "მოგვიანებით წყვილების განმსაზღვრელი შედეგის შესწორებამდე გააუქმეთ ბოლო უთამაშებელი და დაუკავშირებელი რაუნდი.",
  "Proposed kick-off (": "შეთავაზებული დასაწყისი (",
  "Fixture #": "მატჩი №",
  "· see Matchday for its preparation and result.": "· მზადება და შედეგი იხილეთ მატჩების ჩანართში.",
  "Resolve unfinished fixtures, challenges and disputes first. Festival completion can preserve participation without selecting a champion.": "ჯერ დაასრულეთ მატჩები, გამოწვევები და დავები. ფესტივალი შეიძლება დასრულდეს მონაწილეობის ისტორიით, ჩემპიონის არჩევის გარეშე.",
  "The existing draw is retained. Continue with its stages and matchday tools.": "არსებული კენჭისყრა შენარჩუნებულია. გააგრძელეთ ეტაპებისა და მატჩების ინსტრუმენტებით.",
  "Activate the eligible entries, then review a complete schedule. Every fixture uses the competition timezone, playing time, pitches and rest rules.": "გაააქტიურეთ შესაბამისი მონაწილეები და შეამოწმეთ სრული განრიგი. ყველა მატჩი იყენებს შეჯიბრების დროის სარტყელს, თამაშის დროს, მოედნებსა და დასვენების წესებს.",
  "Opening kick-off (": "პირველი მატჩის დასაწყისი (",
  "Days between rounds": "დღეები რაუნდებს შორის",
  "0 schedules sequential rounds with the configured rest.": "0 ნიშნავს მიმდევრულ რაუნდებს მითითებული დასვენებით.",
  "Groups": "ჯგუფები",
  "Entries per group in each route": "მონაწილეები ჯგუფიდან თითოეულ გზაზე",
  "Qualification routes": "საკვალიფიკაციო გზები",
  "Cup": "თასი",
  "Cup & Plate": "თასი და Plate",
  "Cup, Plate & Bowl": "თასი, Plate და Bowl",
  "Cup, Plate, Bowl & Shield": "თასი, Plate, Bowl და Shield",
  "Two-legged knockout ties": "ორმატჩიანი გამოთიშვით დაპირისპირებები",
  "Level aggregate resolution": "თანაბარი ჯამური ანგარიშის გადაწყვეტა",
  "Penalty decision, recorded with evidence": "პენალტების გადაწყვეტილება მტკიცებულებით",
  "Replay decision, recorded with evidence": "გადათამაშების გადაწყვეტილება მტკიცებულებით",
  "Drawing lots under the published rules": "წილისყრა გამოქვეყნებული წესებით",
  "No away-goals rule. Each leg keeps its own score.": "გასვლითი გოლების წესი არ გამოიყენება. თითოეული მატჩის ანგარიში ინახება.",
  "Third-place match for semifinal losers": "ნახევარფინალში დამარცხებულთა მატჩი მესამე ადგილისთვის",
  "Entries in the championship split": "მონაწილეები საჩემპიონო ჯგუფში",
  "Carry first-phase results between teams in the same split": "პირველი ეტაპის შედეგების გადატანა იმავე ჯგუფის გუნდებს შორის",
  "Divisions & promotion / playoff destinations": "დივიზიონები და დაწინაურების ან პლეიოფის მიზნები",
  "State the linked competition and decision authority. This declaration does not grant federation approval or change another competition.": "მიუთითეთ დაკავშირებული შეჯიბრება და გადაწყვეტილების უფლებამოსილება. ეს ჩანაწერი ფედერაციის თანხმობას არ ნიშნავს და სხვა შეჯიბრებას არ ცვლის.",
  "Create reviewed draw": "შემოწმებული კენჭისყრის შექმნა",
  "Resolve tied sporting order ·": "თანაბარი სპორტული რიგის გადაწყვეტა ·",
  ", rank": ", ადგილი",
  "Complete order of the tied entry IDs, separated by commas": "თანაბარ მონაწილეთა სრული რიგი",
  "Record sporting order": "სპორტული რიგის შენახვა",
  "Confirm all first-phase results and resolve qualification ties before drawing the next phase.": "შემდეგი ეტაპის კენჭისყრამდე დაადასტურეთ პირველი ეტაპის შედეგები და გადაწყვიტეთ თანაბარი საკვალიფიკაციო ადგილები.",
  "Next-phase opening (": "შემდეგი ეტაპის დასაწყისი (",
  "Draw qualified next phase": "კვალიფიციურ მონაწილეთა შემდეგი ეტაპის შექმნა",
  "Aggregate ties": "ჯამური დაპირისპირებები",
  "Legs #": "მატჩები №",
  "Winner under the agreed resolution": "გამარჯვებული შეთანხმებული წესით",
  "Choose the resolved winner": "აირჩიეთ გადაწყვეტილი გამარჯვებული",
  "Decision and evidence": "გადაწყვეტილება და მტკიცებულება",
  "Record aggregate decision": "ჯამური გადაწყვეტილების შენახვა",
  "Advancement & placement destinations": "წინსვლისა და ადგილების გზები",
  "of fixture #": "მატჩიდან №",
  "side": "მხარე",
  "Pitch allocation & timetable (": "მოედნების განაწილება და განრიგი (",
  "· Pitch": "· მოედანი",
  "Retract an unplayed second phase": "უთამაშებელი მეორე ეტაპის გაუქმება",
  "Use this before correcting first-phase qualification or carried results. Played or linked matches require reopening and unlinking first.": "გამოიყენეთ პირველი ეტაპის კვალიფიკაციის ან გადატანილი შედეგების შესწორებამდე. ნათამაშები ან დაკავშირებული მატჩები ჯერ უნდა გახსნათ და მოხსნათ კავშირი.",
  "Retract second phase": "მეორე ეტაპის გაუქმება",
  "Divisions, promotion & qualification offers": "დივიზიონში გადასვლისა და კვალიფიკაციის შეთავაზებები",
  "A completed table or playoff can qualify entries for a compatible next competition. Its organiser reviews the offer; clubs and players still accept their invitations. These recorded decisions do not certify federation promotion.": "დასრულებულმა ცხრილმა ან პლეიოფმა შეიძლება მონაწილეები შესაბამის შემდეგ შეჯიბრებაში გაიყვანოს. შეთავაზებას მისი ორგანიზატორი განიხილავს; კლუბები და მოთამაშეები საკუთარ მოწვევებს იღებენ. ეს ფედერაციის მიერ დაწინაურების დამოწმება არ არის.",
  "Retry division offers": "შეთავაზებების ხელახლა ჩატვირთვა",
  "Source table or playoff": "წყარო ცხრილი ან პლეიოფი",
  "Promotion offer": "დაწინაურების შეთავაზება",
  "Relegation / lower-division offer": "დაქვეითების ან ქვედა დივიზიონის შეთავაზება",
  "Qualification offer": "კვალიფიკაციის შეთავაზება",
  "Published rules, authority and reason": "გამოქვეყნებული წესები, უფლებამოსილება და მიზეზი",
  "No division offers recorded.": "დივიზიონის შეთავაზებები ჯერ არ არის.",
  "Correction evidence for offer #": "შეთავაზების შესწორების მტკიცებულება №",
  "Pending invitations and entry reviews can be withdrawn. Accepted entries and fixtures must be resolved in the destination first.": "მომლოდინე მოწვევებისა და შემოწმებების გაუქმება შესაძლებელია. მიღებული მონაწილეები და მატჩები ჯერ მიმღებ შეჯიბრებაში უნდა მოგვარდეს.",
  "Retract division offer #": "დივიზიონის შეთავაზების გაუქმება №",
  "· ranks": "· ადგილები",
  "invitation(s) awaiting participant consent;": "მოწვევა ელოდება მონაწილის თანხმობას;",
  "off-platform entry review(s). Review them in the destination's Participants.": "გარე მონაწილის შემოწმება. იხილეთ მიმღები შეჯიბრების მონაწილეებში.",
  "Destination decision evidence": "მიმღების გადაწყვეტილების მტკიცებულება",
  "Postponement, forfeits & season corrections": "გადადება, ტექნიკური შედეგები და სეზონის შესწორება",
  "Reopening clears the current champion and preserves the previous outcome in the audit. Resolve downstream division offers first, then correct dependent matches in reverse order.": "ხელახლა გახსნა შლის მიმდინარე ჩემპიონის სტატუსს და ძველ შედეგს აუდიტში ინახავს. ჯერ მოაგვარეთ შემდგომი დივიზიონის შეთავაზებები, შემდეგ შესწორებები შეიტანეთ უკუ რიგით.",
  "Correction evidence": "შესწორების მტკიცებულება",
  "Reopen season for correction": "სეზონის გახსნა შესასწორებლად",
  "Unplayed fixture": "უთამაშებელი მატჩი",
  "Published rule, request and reason": "გამოქვეყნებული წესი, მოთხოვნა და მიზეზი",
  "Postpone this fixture": "ამ მატჩის გადადება",
  "New kick-off (": "ახალი დასაწყისი (",
  "Allocated pitch": "გამოყოფილი მოედანი",
  "Record postponement": "გადადების შენახვა",
  "Forfeit scores are explicit organiser choices under the published rules; no universal score is assumed.": "ტექნიკურ ანგარიშს ორგანიზატორი გამოქვეყნებული წესებით განსაზღვრავს; უნივერსალური ანგარიში არ გამოიყენება.",
  "Awarded goals": "მინიჭებული გოლები",
  "Forfeiting side's goals": "ტექნიკურად დამარცხებული მხარის გოლები",
  "Forfeiting participant": "ტექნიკურად დამარცხებული მონაწილე",
  "Choose the participant": "აირჩიეთ მონაწილე",
  "Record forfeit result": "ტექნიკური შედეგის შენახვა",
  "Approve an entry's season withdrawal": "მონაწილის სეზონიდან გასვლის დამტკიცება",
  "Record the entry's request or organiser authority. Remaining assigned fixtures receive the explicit forfeit score. Prior results remain. Retract dependent split/playoff phases first.": "ჩაწერეთ მონაწილის მოთხოვნა ან ორგანიზატორის უფლებამოსილება. დარჩენილ მატჩებს ენიჭება მითითებული ტექნიკური ანგარიში. წინა შედეგები ინახება. ჯერ გააუქმეთ დამოკიდებული ეტაპები.",
  "Withdrawing entry": "გამსვლელი მონაწილე",
  "Choose an active entry": "აირჩიეთ აქტიური მონაწილე",
  "Record season withdrawal": "სეზონიდან გასვლის შენახვა",
  "Promotion, relegation or championship playoffs": "დაწინაურების, დაქვეითების ან საჩემპიონო პლეიოფი",
  "Finish the source table and resolve its qualification boundaries. The organiser must state the published authority and destination.": "დაასრულეთ წყარო ცხრილი და გადაწყვიტეთ საკვალიფიკაციო ადგილები. ორგანიზატორმა უნდა მიუთითოს გამოქვეყნებული უფლებამოსილება და მიზანი.",
  "Source table": "წყარო ცხრილი",
  "Choose the league table": "აირჩიეთ ლიგის ცხრილი",
  "Playoff entries": "პლეიოფის მონაწილეები",
  "Published rules award the season championship through this playoff": "გამოქვეყნებული წესებით სეზონის ჩემპიონი ამ პლეიოფში წყდება",
  "Published rule, promotion / relegation destination and authority": "გამოქვეყნებული წესი, გადასვლის მიზანი და უფლებამოსილება",
  "Draw qualified playoffs": "კვალიფიციურ მონაწილეთა პლეიოფის შექმნა",
  "Actual replay:": "გადათამაშება:",
  "Open replay preparation and result": "გადათამაშების მზადებისა და შედეგის ნახვა",
  "Retract an unplayed replay": "უთამაშებელი გადათამაშების გაუქმება",
  "Retract replay": "გადათამაშების გაუქმება",
  "Draw the agreed replay": "შეთანხმებული გადათამაშების შექმნა",
  "The two leg scores stay intact. Advancement waits for the replay's confirmed outcome.": "ორივე მატჩის ანგარიში ინახება. წინსვლა ელოდება გადათამაშების დადასტურებულ შედეგს.",
  "Replay kick-off (": "გადათამაშების დასაწყისი (",
  "Reason and agreed conditions": "მიზეზი და შეთანხმებული პირობები",
  "Create replay fixture": "გადათამაშების მატჩის შექმნა"
};
const competitionEnglish:Record<string,string>={"SENIOR": "Senior", "VETERANS": "Veterans", "ASSOCIATION": "Association football", "FUTSAL": "Futsal", "BEACH": "Beach soccer", "WALKING": "Walking football", "OTHER": "Other ruleset", "DEVELOPMENT": "Development", "RECREATIONAL": "Recreational", "COMPETITIVE": "Competitive", "ELITE": "Elite", "TEAM": "Per team", "PLAYER": "Per player", "EVENT": "Per event", "POINTS": "Points", "GOAL_DIFFERENCE": "Goal difference", "GOALS_FOR": "Goals scored", "WINS": "Wins", "BUCHHOLZ": "Buchholz", "SEED": "Seed"};
Object.assign(competitionGeorgian,{"SENIOR": "უფროსები", "VETERANS": "ვეტერანები", "ASSOCIATION": "ფეხბურთი", "FUTSAL": "ფუტსალი", "BEACH": "პლაჟის ფეხბურთი", "WALKING": "სიარულით ფეხბურთი", "OTHER": "სხვა წესები", "DEVELOPMENT": "განვითარება", "RECREATIONAL": "სამოყვარულო", "COMPETITIVE": "შეჯიბრებითი", "ELITE": "ელიტური", "TEAM": "გუნდზე", "PLAYER": "მოთამაშეზე", "EVENT": "ღონისძიებაზე", "POINTS": "ქულები", "GOAL_DIFFERENCE": "გოლების სხვაობა", "GOALS_FOR": "გატანილი გოლები", "WINS": "მოგებები", "BUCHHOLZ": "ბუხჰოლცი", "SEED": "განთესვა", "individual entry": "ინდივიდუალური მონაწილე", "team entry": "გუნდის მონაწილეობა", "No entry fee": "მონაწილეობა უფასოა", "competitions": "შეჯიბრება", "Challenge range, ranking positions": "გამოწვევის დიაპაზონი, ადგილები", "Challenge expiry, days": "გამოწვევის ვადა, დღეები", "Maximum consecutive stays": "ზედიზედ დარჩენის ლიმიტი", "Jurisdiction / governing authority": "იურისდიქცია და მმართველი ორგანო"});
export function useCompetitionCopy(){const {i18n}=useTranslation();return (english:string)=>i18n.language.startsWith('ka')?competitionGeorgian[english]||competitionEnglish[english]||english:competitionEnglish[english]||english;}

