import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {fetchTournamentHosts,fetchTournamentHost} from '../tournaments/api';
import type {TournamentHost} from '../tournaments/domain';
import {extractApiErrorMessage} from '../../utils/apiError';
export function CompetitionHostPicker({kind,value,onChange}:{kind:string;value:string;onChange:(value:string,kind:string)=>void}){
 const {i18n}=useTranslation();const copy=(en:string,ka:string)=>i18n.language.startsWith('ka')?ka:en;const [q,setQ]=useState(''),[page,setPage]=useState(0),[total,setTotal]=useState(0),[hosts,setHosts]=useState<TournamentHost[]>([]),[selected,setSelected]=useState<TournamentHost>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{void fetchTournamentHosts({page,size:24,search:q}).then(r=>{if(active){setHosts(r.content);setTotal(r.totalPages);setError('');}}).catch(e=>{if(active)setError(extractApiErrorMessage(e,'Could not load competition hosts.'));});},200);return()=>{active=false;clearTimeout(timer);};},[q,page,attempt]);
 useEffect(()=>{if(!value||!['CLUB','ORGANIZATION'].includes(kind))return;let active=true;void fetchTournamentHost(kind as TournamentHost['kind'],Number(value)).then(r=>{if(active)setSelected(r);}).catch(e=>{if(active)setError(extractApiErrorMessage(e,'The selected host is unavailable.'));});return()=>{active=false;};},[kind,value]);
 const listed=hosts.filter(h=>!kind||h.kind===kind);const options=selected&&selected.kind===kind&&String(selected.id)===value&&!listed.some(h=>h.kind===selected.kind&&h.id===selected.id)?[selected,...listed]:listed;
 return <div><label>{copy('Search hosts by name','მოძებნეთ მასპინძელი სახელით')}<input type="search" maxLength={200} value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/></label><label>{copy('Host','მასპინძელი')}<select value={value?`${kind}:${value}`:''} onChange={e=>{const [nextKind,id]=e.target.value.split(':');onChange(id||'',nextKind||kind);}}><option value="">{copy('All hosts','ყველა მასპინძელი')}</option>{options.map(h=><option key={`${h.kind}:${h.id}`} value={`${h.kind}:${h.id}`}>{h.name} · {h.kind==='CLUB'?copy('Club','კლუბი'):copy('Organisation','ორგანიზაცია')}</option>)}</select></label>{total>1&&<div><button type="button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{copy('Previous hosts','წინა მასპინძლები')}</button><button type="button" disabled={page+1>=total} onClick={()=>setPage(p=>p+1)}>{copy('More hosts','სხვა მასპინძლები')}</button></div>}{error&&<p role="alert">{error}<button type="button" onClick={()=>setAttempt(a=>a+1)}>{copy('Retry','ხელახლა')}</button></p>}</div>;
}
