import {useCompetitionCopy} from './competitionCopy';
import { useState } from 'react';
import type { DrawState } from './api';

export function CompetitionPlayoffForm({draw,busy,run}:{draw:DrawState;busy:boolean;run:(path:string,body:Record<string,unknown>)=>Promise<void>}){
  const activityCopy=useCompetitionCopy();
  const [stage,setStage]=useState(''),[start,setStart]=useState(''),[from,setFrom]=useState(1),[places,setPlaces]=useState(2),[title,setTitle]=useState(false),[reason,setReason]=useState('');
  return <details><summary>{activityCopy("Promotion, relegation or championship playoffs")}</summary><form onSubmit={event=>{event.preventDefault();const value=new Date(start);if(Number.isFinite(value.getTime()))void run('playoff',{sourceStageId:Number(stage),fromRank:from,places,startsAt:value.toISOString(),titleRoute:title,reason});}}><p>{activityCopy("Finish the source table and resolve its qualification boundaries. The organiser must state the published authority and destination.")}</p><label>{activityCopy("Source table")}<select required value={stage} onChange={e=>setStage(e.target.value)}><option value="">{activityCopy("Choose the league table")}</option>{draw.stages.filter(s=>s.phase===1&&s.stage_type!=='KNOCKOUT').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="co-draw-fields"><label>{activityCopy("First qualifying rank")}<input required type="number" min={1} max={32} value={from} onChange={e=>setFrom(Number(e.target.value))}/></label><label>{activityCopy("Playoff entries")}<input required type="number" min={2} max={16} value={places} onChange={e=>setPlaces(Number(e.target.value))}/></label></div><label>{activityCopy("Opening kick-off (")}{' '}{Intl.DateTimeFormat().resolvedOptions().timeZone})<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label><input type="checkbox" checked={title} onChange={e=>setTitle(e.target.checked)}/> {activityCopy("Published rules award the season championship through this playoff")}</label><label>{activityCopy("Published rule, promotion / relegation destination and authority")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" disabled={busy}>{activityCopy("Draw qualified playoffs")}</button></form></details>;
}
