import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {apiClient} from '../../api/axiosConfig';
import {extractApiErrorMessage} from '../../utils/apiError';
import {useCompetitionCommand} from './useCompetitionCommand';
import type {CompetitionRules} from './api';
type Appointment={id:number;status:string;referee_id?:number;report?:string};
type Fixture={id:number;status:string;outcome_basis?:string;home_label?:string;away_label?:string;starts_at?:string;ends_at?:string;booking_id?:number;booking_status?:string;venue?:string;pitch?:string;appointments:Appointment[]};
type State={revision:number;canOperate:boolean;fixtures:Fixture[]};
type Booking={id:number;venueName:string;pitchName:string;status:string;startsAt:string;endsAt:string};
type Referee={user_id:number;full_name:string};
export function CompetitionResourcesPanel({id,rules,changed,editable=false}:{id:number;rules:CompetitionRules;changed:()=>Promise<void>;editable?:boolean}){
 const {i18n}=useTranslation();const copy=(en:string,ka:string)=>i18n.language.startsWith('ka')?ka:en;
 const [state,setState]=useState<State>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[fixture,setFixture]=useState(''),[booking,setBooking]=useState(''),[bookings,setBookings]=useState<Booking[]>([]);
 const [refs,setRefs]=useState<Referee[]>([]),[q,setQ]=useState(''),[official,setOfficial]=useState(''),[volunteer,setVolunteer]=useState(true),[fee,setFee]=useState(0),[currency,setCurrency]=useState(rules.currency),[reason,setReason]=useState('');
 const commands=useCompetitionCommand();const selected=state?.fixtures.find(f=>f.id===Number(fixture));
 useEffect(()=>{const abort=new AbortController();void apiClient.get<State>(`/competitions/${id}/resources`,{signal:abort.signal}).then(r=>{if(!abort.signal.aborted){setState(r.data);setError('');}}).catch(e=>{if(!abort.signal.aborted)setError(extractApiErrorMessage(e,'Could not load fixture preparation.'));});return()=>abort.abort();},[id,attempt]);
 useEffect(()=>{if(!editable||!state?.canOperate)return;const abort=new AbortController();void apiClient.get<Booking[]>('/venues/bookings/mine',{signal:abort.signal}).then(r=>{if(!abort.signal.aborted)setBookings(r.data);}).catch(e=>{if(!abort.signal.aborted)setError(extractApiErrorMessage(e,'Could not load your reservations.'));});return()=>abort.abort();},[editable,state?.canOperate,attempt]);
 useEffect(()=>{if(!selected?.starts_at||!selected.ends_at)return;const abort=new AbortController();const timer=setTimeout(()=>{void apiClient.get<{items:Referee[]}>('/referees',{signal:abort.signal,params:{q,format:rules.discipline==='FUTSAL'?'FUTSAL':`${rules.sideSize}_A_SIDE`,volunteer,from:selected.starts_at,to:selected.ends_at}}).then(r=>{if(!abort.signal.aborted)setRefs(r.data.items);}).catch(e=>{if(!abort.signal.aborted)setError(extractApiErrorMessage(e,'Could not load available referees.'));});},200);return()=>{clearTimeout(timer);abort.abort();};},[q,selected?.starts_at,selected?.ends_at,rules.discipline,rules.sideSize,volunteer]);
 async function run(path:string,body:Record<string,unknown>){if(!state)return;await commands.run(`resources/${path}`,body,state.revision,async payload=>(await apiClient.post(`/competitions/${id}/resources/${path}`,payload)).data,async()=>{setAttempt(a=>a+1);await changed();},()=>setAttempt(a=>a+1));}
 return <details className="co-resources"><summary>{copy('Venue reservations & referee appointments','სტადიონის ჯავშნები და მსაჯების დანიშვნა')}</summary>
 <p>{copy('A pitch number is a planned allocation. Link a confirmed reservation and an independently accepted official to confirm preparation.','მოედნის ნომერი დაგეგმილი განაწილებაა. მზადების დასადასტურებლად დაურთეთ დადასტურებული ჯავშანი და მსაჯის მიერ მიღებული დანიშვნა.')}</p>
 {error&&<p role="alert">{error}<button type="button" onClick={()=>setAttempt(a=>a+1)}>{copy('Retry','ხელახლა')}</button></p>}{commands.error&&<p role="alert">{commands.error}</p>}{commands.notice&&<p role="status">{commands.notice}</p>}
 {!state&&!error&&<p role="status">{copy('Loading preparation…','მზადება იტვირთება…')}</p>}{state?.fixtures.length===0&&<p>{copy('Generate the timetable first.','ჯერ შეადგინეთ განრიგი.')}</p>}
 {state&&<ul className="co-resource-list">{state.fixtures.map(f=><li key={f.id}><strong>{f.home_label||copy('Home entry','მასპინძელი')} – {f.away_label||copy('Away entry','სტუმარი')}</strong> · {f.starts_at?new Date(f.starts_at).toLocaleString(i18n.language):copy('Time to be agreed','დრო შესათანხმებელია')}<p>{f.outcome_basis&&<span>{copy(f.outcome_basis==='FORFEIT'?'Administrative forfeit':f.outcome_basis==='BYE'?'Bye':'Played result',f.outcome_basis==='FORFEIT'?'ადმინისტრაციული ტექნიკური შედეგი':f.outcome_basis==='BYE'?'მატჩის გარეშე გასვლა':'ჩატარებული მატჩის შედეგი')} · </span>}{f.venue?`${f.venue} · ${f.pitch} · ${f.booking_status}`:copy('Venue reservation to be confirmed','სტადიონის ჯავშანი დასადასტურებელია')}</p>{f.appointments.map(a=><div key={a.id}>{a.referee_id?<Link to={`/referees/${a.referee_id}`}>{copy('Referee profile','მსაჯის პროფილი')}</Link>:copy('Referee appointment','მსაჯის დანიშვნა')} · {a.status}{a.report&&<details><summary>{copy('Private official report','მსაჯის პირადი ანგარიში')}</summary><p>{a.report}</p></details>}{editable&&state.canOperate&&['INVITED','ACCEPTED'].includes(a.status)&&f.status==='SCHEDULED'&&<button type="button" disabled={commands.busy||!reason.trim()} onClick={()=>void run(`referees/${a.id}/decision`,{action:'CANCEL',reason})}>{copy('Cancel appointment','დანიშვნის გაუქმება')}</button>}</div>)}</li>)}</ul>}
 {editable&&state?.canOperate&&state.fixtures.some(f=>f.status==='SCHEDULED')&&<>
 <label>{copy('Fixture to prepare','მატჩი მოსამზადებლად')}<select value={fixture} onChange={e=>{setFixture(e.target.value);setOfficial('');setRefs([]);setBooking('');}}><option value="">{copy('Choose a fixture','აირჩიეთ მატჩი')}</option>{state.fixtures.filter(f=>f.status==='SCHEDULED').map(f=><option key={f.id} value={f.id}>{f.home_label||'Home'} – {f.away_label||'Away'} · {f.starts_at?new Date(f.starts_at).toLocaleString(i18n.language):''}</option>)}</select></label>
 <label>{copy('Terms or change reason','პირობები ან ცვლილების მიზეზი')}<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {selected?.starts_at&&selected.ends_at&&<>
 <form onSubmit={e=>{e.preventDefault();void run('booking',{fixtureId:selected.id,bookingId:Number(booking),reason});}}><label>{copy('Your confirmed reservations covering this fixture','თქვენი დადასტურებული ჯავშნები ამ მატჩის დროს')}<select required value={booking} onChange={e=>setBooking(e.target.value)}><option value="">{copy('Choose a reservation','აირჩიეთ ჯავშანი')}</option>{bookings.filter(b=>b.status==='CONFIRMED'&&new Date(b.startsAt)<=new Date(selected.starts_at!)&&new Date(b.endsAt)>=new Date(selected.ends_at!)).map(b=><option key={b.id} value={b.id}>{b.venueName} · {b.pitchName} · {new Date(b.startsAt).toLocaleString(i18n.language)}</option>)}</select></label><Link to="/stadiums">{copy('Find a stadium and request a booking','იპოვეთ სტადიონი და მოითხოვეთ ჯავშანი')}</Link><button disabled={commands.busy||!reason.trim()}>{copy('Allocate reservation','ჯავშნის მიბმა')}</button>{selected.booking_id&&<button type="button" disabled={commands.busy||!reason.trim()} onClick={()=>void run('booking',{fixtureId:selected.id,bookingId:null,reason})}>{copy('Release fixture allocation','მატჩის ჯავშნიდან მოხსნა')}</button>}</form>
 <form onSubmit={e=>{e.preventDefault();void run('referees',{fixtureId:selected.id,refereeId:Number(official),volunteer,fee:volunteer?0:fee,currency,terms:reason});}}><label>{copy('Search published available referees','მოძებნეთ გამოქვეყნებული და თავისუფალი მსაჯები')}<input type="search" value={q} maxLength={200} onChange={e=>setQ(e.target.value)}/></label><label>{copy('Referee','მსაჯი')}<select required value={official} onChange={e=>setOfficial(e.target.value)}><option value="">{copy('Choose an available referee','აირჩიეთ თავისუფალი მსაჯი')}</option>{refs.map(r=><option key={r.user_id} value={r.user_id}>{r.full_name}</option>)}</select></label><label><input type="checkbox" checked={volunteer} onChange={e=>setVolunteer(e.target.checked)}/>{copy('Volunteer appointment','მოხალისე მსაჯი')}</label>{!volunteer&&<><label>{copy('Agreed fee','შეთანხმებული საფასური')}<input type="number" min={0} max={1000000} step="0.01" value={fee} onChange={e=>setFee(Number(e.target.value))}/></label><label>{copy('Currency','ვალუტა')}<input required minLength={3} maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label></>}<button disabled={commands.busy||!reason.trim()}>{copy('Invite referee','მსაჯის მოწვევა')}</button></form>
 </>}
 </>}
 </details>;
}
