import { CaseDates } from '../lifecycle/CaseDates';
import { AdmissionPrivacyRequests, GuardianReviewStatus } from '../governance/FamilyGovernance';
import { useCallback } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../../../context/AuthContext';
import { fetchAdmissionCase } from '../api';
import { useAdmissionData } from './useAdmissionData';
import { useAdmissionTab } from './useAdmissionTab';
import { AdmissionError, AdmissionFrame, AdmissionLoading, AdmissionSection } from './AdmissionFrame';
import { useAdmissionCopy } from './copy';
import { MessageAction, OfferResponse, PrimaryChangeResponse, ReasonAction, RequirementResponse, SessionResponse } from './CaseActions';

export function AdmissionCasePage() {
    const {caseId}=useParams();const {user,sessionId}=useAuth();
    return <AdmissionCaseContent key={`${caseId}:${user?.id}:${sessionId}`} id={Number(caseId)}/>;
}
function AdmissionCaseContent({id}:{id:number}) {
    const {sessionId}=useAuth();const {copy,stage,owner,requirement,next}=useAdmissionCopy();
    const detail=useAdmissionData(useCallback(signal=>fetchAdmissionCase(id,sessionId,signal),[id,sessionId]),sessionId);
    const c=detail.error?null:detail.data;
    const tab=useAdmissionTab(['overview','sessions','agreement','conversation','history']);
    const schedule=c?.enrollment?.squadId?`/squads/${c.enrollment.squadId}?tab=sessions`:c?.enrollment?.scheduleDestination!==`/admissions/cases/${id}`?c?.enrollment?.scheduleDestination:null;
    const props=c?{admissionCase:c,onChanged:detail.setData,refresh:detail.refresh}:null;
    const eventLabel=(action:string)=>({SUBMITTED:copy('Request received','მოთხოვნა მიღებულია'),REQUEST:copy('Request received','მოთხოვნა მიღებულია'),MESSAGE:copy('Message','შეტყობინება'),INVITE_SESSION:copy('Session invitation','სესიის მოწვევა'),CONFIRM_SESSION:copy('Session confirmed','სესია დადასტურდა'),CHANGE_SESSION:copy('Session changed','სესია შეიცვალა'),DECLINE_SESSION:copy('Attendance declined','დასწრება უარყოფილია'),CANCEL_SESSION:copy('Session cancelled','სესია გაუქმდა'),RECORD_ATTENDANCE:copy('Attendance recorded','დასწრება დაფიქსირდა'),OFFER:copy('Place offered','ადგილი შემოთავაზებულია'),ACCEPT_OFFER:copy('Offer accepted','შეთავაზება მიღებულია'),DECLINE_OFFER:copy('Offer declined','შეთავაზება უარყოფილია'),EXTEND_OFFER:copy('Deadline extended','ვადა გახანგრძლივდა'),WITHDRAW_OFFER:copy('Offer withdrawn','შეთავაზება გაუქმდა'),COMPLETE_REQUIREMENT:copy('Requirement updated','მოთხოვნა განახლდა'),ENROLLED:copy('Enrollment confirmed','ჩარიცხვა დადასტურდა'),DIRECT_ENROLL:copy('Direct enrollment confirmed','პირდაპირი ჩარიცხვა დადასტურდა'),WAITLIST:copy('Waiting-list update','მოლოდინის სიის განახლება'),DECLINE:copy('Club decision','კლუბის გადაწყვეტილება'),WITHDRAW:copy('Request withdrawn','მოთხოვნა გაუქმდა'),CANCEL_ENROLLMENT:copy('Enrollment ended','ჩარიცხვა დასრულდა'),CONFIRM_PRIMARY_CHANGE:copy('Competitive affiliation decision','სათამაშო წევრობის გადაწყვეტილება'),ASSIGN:copy('Responsible staff updated','პასუხისმგებელი თანამშრომელი შეიცვალა')} as Record<string,string>)[action]||copy('Case update','საქმის განახლება');
    return <AdmissionFrame title={c ? c.groupName : copy('Your joining arrangement','თქვენი მონაწილეობის შეთანხმება')} description={c ? c.playerName + ' · ' + c.organizationName : undefined} back="/admissions"
        tabs={[{id:'overview',label:copy('Overview','მიმოხილვა')},{id:'sessions',label:copy('Sessions','სესიები'),count:c?.sessions.length},{id:'agreement',label:copy('Agreement','შეთანხმება')},{id:'conversation',label:copy('Conversation','საუბარი')},{id:'history',label:copy('History','ისტორია')}]} activeTab={tab}>
        {detail.error ? <AdmissionError message={detail.error} retry={detail.refresh}/> : !c ? <AdmissionLoading/> : props && <div className="admission-stack">
            <AdmissionSection active={tab==='overview'}><div className="admission-columns"><div className="admission-stack"><section className="admission-panel"><span className="admission-badge">{stage(c.stage)}</span><h2>{copy('Next step','შემდეგი ნაბიჯი')}</h2><p>{next(c.nextAction)}</p><dl className="admission-details"><div><dt>{copy('Who acts next','ვინ მოქმედებს შემდეგ')}</dt><dd>{owner(c.nextAction.owner)}</dd></div><div><dt>{copy('Responsible staff','პასუხისმგებელი თანამშრომელი')}</dt><dd>{c.responsible?.name||copy('Admissions queue','მიღების რიგი')}</dd></div>{c.nextAction.dueAt&&<div><dt>{copy('Due','ვადა')}</dt><dd>{new Date(c.nextAction.dueAt).toLocaleString()}</dd></div>}<div><dt>{copy('Requested','მოთხოვნის დრო')}</dt><dd>{new Date(c.submittedAt).toLocaleString()}</dd></div></dl><button className="admission-button" disabled={detail.loading} onClick={detail.refresh}>{copy('Refresh current arrangement','მიმდინარე შეთანხმების განახლება')}</button></section>
                {c.enrollment?.status==='ACTIVE'&&c.stage==='ENROLLED'&&<section className="admission-panel" role="status"><p className="admission-eyebrow">{copy('Enrollment confirmed','ჩარიცხვა დადასტურებულია')}</p><h2>{c.enrollment.groupName}</h2><p>{c.playerName} · {copy('Starts','იწყება')} {c.enrollment.startDate}{c.enrollment.endDate?` — ${c.enrollment.endDate}`:''}</p>{schedule?<Link className="admission-button admission-primary" to={schedule}>{copy('Open group schedule','ჯგუფის განრიგის გახსნა')}</Link>:<p>{copy('The recurring arrangement is recorded in the offer. Ask responsible staff for calendar details.','განმეორებითი განრიგი შეთავაზებაშია დაფიქსირებული. კალენდრის დეტალები პასუხისმგებელ თანამშრომელთან დააზუსტეთ.')}</p>}<p>{copy('This confirms regular participation. Official competition eligibility has not been granted by enrollment.','ეს მუდმივ მონაწილეობას ადასტურებს. ჩარიცხვა ოფიციალურ შეჯიბრებაში თამაშის უფლებას არ ანიჭებს.')}</p></section>}
                {c.enrollment?.status==='CANCELLED'&&<section className="admission-panel" role="status"><p className="admission-eyebrow">{copy('Enrollment ended','ჩარიცხვა დასრულდა')}</p><h2>{c.enrollment.groupName}</h2><p>{copy('This enrollment is no longer active. Its earlier agreement and the recorded reason remain in this case.', 'ეს ჩარიცხვა აღარ არის აქტიური. წინა შეთანხმება და დაფიქსირებული მიზეზი საქმეში შენარჩუნებულია.')}</p><p>{copy('Outstanding financial or registration work needs staff review. This receipt does not record a payment, refund or competition clearance.', 'დარჩენილ ფინანსურ ან სარეგისტრაციო საკითხებს თანამშრომელი განიხილავს. ეს ქვითარი გადახდას, თანხის დაბრუნებას ან შეჯიბრების ნებართვას არ აფიქსირებს.')}</p></section>}
                {c.stage==='COMPLETING_ENROLLMENT'&&<p className="admission-notice">{copy('The offer is accepted and the place is held while the named requirements are completed. Follow the completion deadline shown below.','შეთავაზება მიღებულია და ადგილი შენარჩუნებულია მოთხოვნების შესრულებამდე. დაიცავით ქვემოთ ნაჩვენები დასრულების ვადა.')}</p>}

                <div className="admission-actions"><Link className="admission-button" to={`?tab=sessions&player=${c.playerId}`}>{copy('Review sessions','სესიების განხილვა')}</Link><Link className="admission-button" to={`?tab=agreement&player=${c.playerId}`}>{copy('Review agreement','შეთანხმების განხილვა')}</Link><Link className="admission-button" to={`?tab=conversation&player=${c.playerId}`}>{copy('Contact the club','კლუბთან დაკავშირება')}</Link></div>
            </div><aside><section className="admission-panel"><h2>{copy('Player and group','მოთამაშე და ჯგუფი')}</h2><p><strong>{c.playerName}</strong> · {copy('Born','დაბადების წელი')} {c.dateOfBirth.slice(0,4)}</p><p>{c.groupName} · {c.intake}</p><p>{c.organizationName}</p>{c.primaryAffiliation&&<p>{copy('Current competitive club','მიმდინარე სათამაშო კლუბი')}: {c.primaryAffiliation.clubName}</p>}<p>{copy('Exploration does not end an existing affiliation. A competitive move requires its own explicit confirmation and applicable requirements.','ძიება არსებულ წევრობას არ ასრულებს. სათამაშო გადასვლას ცალკე დადასტურება და შესაბამისი მოთხოვნები სჭირდება.')}</p><Link className="admission-button" to="/parent">{copy('Family connections','ოჯახური კავშირები')}</Link></section></aside></div></AdmissionSection>
            <AdmissionSection active={tab==='sessions'}>{c.sessions.map(s=><SessionResponse key={s.id} {...props} session={s}/>)}
                {!c.sessions.length&&<section className="admission-empty"><h2>{copy('No sessions arranged yet','სესიები ჯერ არ შეთანხმებულა')}</h2><p>{copy('Your club will share a session invitation here.','კლუბი სესიის მოწვევას აქ გაგიზიარებთ.')}</p></section>}</AdmissionSection>
            <AdmissionSection active={tab==='agreement'}><CaseDates record={c} sessionId={sessionId} onChanged={detail.setData}/>{c.requirements.length>0&&<section className="admission-panel"><h2>{copy('Requirements and owners','მოთხოვნები და პასუხისმგებლები')}</h2>{c.requirements.map(r=><div className="admission-stack" key={r.id}><p><strong>{requirement(r.kind)}</strong> · {owner(r.owner)} · {r.status==='COMPLETE'?copy('Complete','შესრულებული'):copy('Needs action','საჭიროა ქმედება')}</p>{r.evidence&&<p className="admission-muted">{r.evidence}</p>}<RequirementResponse {...props} requirement={r}/></div>)}</section>}
                {c.nextAction.code==='GUARDIAN_REVIEW'&&<GuardianReviewStatus playerId={c.playerId}/>}

                {c.offer&&<OfferResponse key={c.offer.id} {...props} offer={c.offer}/>}
                <PrimaryChangeResponse {...props}/>
                {!c.offer&&!c.requirements.length&&<p className="admission-muted">{copy('No agreement to review yet.','შეთანხმება ჯერ არ არის განსახილველი.')}</p>}</AdmissionSection>
            <AdmissionSection active={tab==='conversation'}><section className="admission-panel"><h2>{copy('Conversation and choices','საუბარი და არჩევანი')}</h2>{c.actions.includes('MESSAGE')&&<MessageAction {...props} prompt={copy('Ask a question or follow up','კითხვის დასმა ან მოკითხვა')}/>}{c.actions.includes('WAITLIST')&&<ReasonAction {...props} action="WAITLIST" label={copy('Ask to remain on the waiting list','მოლოდინის სიაში დარჩენის მოთხოვნა')}/>}{c.actions.includes('WITHDRAW')&&<ReasonAction {...props} action="WITHDRAW" label={copy('Withdraw this request','ამ მოთხოვნის გაუქმება')}/>}{c.actions.includes('CANCEL_ENROLLMENT')&&<ReasonAction {...props} action="CANCEL_ENROLLMENT" label={copy('End this enrollment now','ამ ჩარიცხვის ახლავე დასრულება')}/>}{c.stage==='CLOSED'&&<Link className="admission-button" to={`/admissions/opportunities/${c.groupId}?player=${c.playerId}`}>{copy('Review a new linked request','ახალი დაკავშირებული მოთხოვნის განხილვა')}</Link>}</section></AdmissionSection>
            <AdmissionSection active={tab==='history'}><section className="admission-panel"><h2>{copy('Case history','საქმის ისტორია')}</h2><ol className="admission-timeline">{c.history.map(e=><li key={e.id}><time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleString()}</time><strong>{eventLabel(e.action)}</strong><p className="admission-muted">{e.actorName}</p>{e.message&&<p>{e.message}</p>}</li>)}</ol>{c.history.length===0&&<p>{copy('Request recorded. Future decisions will appear here.','მოთხოვნა დაფიქსირდა. მომავალი გადაწყვეტილებები აქ გამოჩნდება.')}</p>}{c.previousCaseId&&<Link className="admission-button" to={`/admissions/cases/${c.previousCaseId}`}>{copy('Earlier linked attempt','წინა დაკავშირებული მცდელობა')}</Link>}</section><AdmissionPrivacyRequests caseId={c.id}/></AdmissionSection>
        </div>}
    </AdmissionFrame>;
}
