import { IntroductionPermission } from '../components/IntroductionPermission';
import { useEffect, useState } from 'react';
import { useAuth } from '../../../context/AuthContext';
import { commandAdmission } from '../api';
import type { AdmissionCase, CaseCommand, Participation, Offer, Requirement } from '../types';
import { useAdmissionMutation } from './useAdmissionMutation';
import { AdmissionError } from './AdmissionFrame';
import { TermsFacts, termsComplete } from './OpportunityFacts';
import { useAdmissionCopy } from './copy';
type WithoutReceipt<T>=T extends unknown?Omit<T,'requestId'>:never;
export type ApplicantCommand=WithoutReceipt<CaseCommand>;
type Props={admissionCase:AdmissionCase;onChanged:(value:AdmissionCase)=>void;refresh:()=>void};
function useCommand(c:AdmissionCase,operation:string,onChanged:Props['onChanged'],refresh:()=>void) {
    const {sessionId}=useAuth();
    return useAdmissionMutation<ApplicantCommand,AdmissionCase>(c.playerId,`case:${c.id}:${operation}`,body=>commandAdmission(c.id,body,sessionId),onChanged,refresh);
}
function MutationFeedback({mutation}:{mutation:ReturnType<typeof useCommand>}) {
    const {copy}=useAdmissionCopy();
    return <>{mutation.error&&<AdmissionError message={mutation.error}/>} {mutation.pending&&<div className="admission-notice"><p>{copy('The original request is saved. Retry to confirm its result; changing details would be a different action.','საწყისი მოთხოვნა შენახულია. შედეგის დასადასტურებლად გაიმეორეთ; მონაცემების შეცვლა სხვა ქმედება იქნება.')}</p><button type="button" className="admission-button" disabled={mutation.busy} onClick={()=>void mutation.retry()}>{copy('Retry saved request','შენახული მოთხოვნის გამეორება')}</button></div>}</>;
}
export function SessionResponse({admissionCase:c,session:s,onChanged,refresh}:Props&{session:Participation}) {
    const {copy}=useAdmissionCopy();const [contact,setContact]=useState(s.emergencyContact||'');const [accept,setAccept]=useState(false);
    const mutation=useCommand(c,`session:${s.id}`,onChanged,refresh);
    useEffect(()=>setAccept(false),[s.id,s.version]);
    const confirm=['INVITED','RECONFIRM_REQUIRED'].includes(s.status)&&c.actions.includes('CONFIRM_SESSION')&&s.introductionPermission?.allowsParticipation!==false;
    const states:Record<string,string>={INVITED:copy('Invited — confirmation needed','მოწვეულია — საჭიროა დადასტურება'),CONFIRMED:copy('Confirmed','დადასტურებული'),RECONFIRM_REQUIRED:copy('Details changed — confirm again','დეტალები შეიცვალა — საჭიროა ხელახალი დადასტურება'),ATTENDED:copy('Attended','დაესწრო'),NO_SHOW:copy('Did not attend','არ დაესწრო'),CANCELLED:copy('Cancelled','გაუქმებული'),DECLINED:copy('Declined','უარყოფილი')};
    return <section className="admission-panel admission-session"><h3>{s.title}</h3><span className="admission-badge">{states[s.status]}</span><dl className="admission-details">
        <div><dt>{copy('When','როდის')}</dt><dd>{new Date(s.startsAt).toLocaleString()} — {new Date(s.endsAt).toLocaleTimeString()}<p>{copy('Club time zone','კლუბის დროის სარტყელი')}: {s.timezone}</p><p>{new Date(s.startsAt).toLocaleString(undefined,{timeZone:s.timezone})} — {new Date(s.endsAt).toLocaleTimeString(undefined,{timeZone:s.timezone})}</p></dd></div>
        <div><dt>{copy('Venue','ადგილი')}</dt><dd>{s.location.name}<p>{s.location.address}</p></dd></div><div><dt>{copy('Responsible contact','პასუხისმგებელი საკონტაქტო პირი')}</dt><dd>{s.contact}</dd></div><div><dt>{copy('Preparation','მომზადება')}</dt><dd>{s.preparation}</dd></div><div><dt>{copy('Session cost','სესიის ღირებულება')}</dt><dd>{s.cost}</dd></div><div><dt>{copy('Reply by','პასუხის ვადა')}</dt><dd>{new Date(s.responseDeadline).toLocaleString()}</dd></div>
    </dl>{s.status==='RECONFIRM_REQUIRED'&&<p className="admission-notice" role="status">{copy('The session details changed. Review the current time, venue and cost before confirming again. Your introductory seat is held until the response deadline shown above.', 'სესიის დეტალები შეიცვალა. ხელახლა დადასტურებამდე შეამოწმეთ მიმდინარე დრო, ადგილი და ღირებულება. შესავალი ადგილი ზემოთ ნაჩვენებ პასუხის ვადამდე შენარჩუნებულია.')}</p>}{s.status==='CANCELLED'&&<p className="admission-notice">{copy('This session was cancelled. A replacement needs a separate invitation and your confirmation; this does not confirm another date.', 'ეს სესია გაუქმდა. შემცვლელს ცალკე მოწვევა და თქვენი დადასტურება სჭირდება; სხვა თარიღი დადასტურებული არ არის.')}</p>}{s.noRegularPlaceGuaranteed&&<p className="admission-notice">{copy('This session does not guarantee an immediately available regular place.','სესია დაუყოვნებლივ მუდმივ ადგილს არ გპირდებათ.')}</p>}
        <IntroductionPermission session={s} playerName={c.playerName}/>
        {confirm&&<form className="admission-stack" onSubmit={e=>{e.preventDefault();void mutation.run({action:'CONFIRM_SESSION',expectedVersion:c.version,participationId:s.id,participationVersion:s.version,acceptTerms:true,emergencyContact:contact.trim()});}}>
            <p>{copy(`Confirm attendance for ${c.playerName}, for these details only (version ${s.version}).`,`დაადასტურეთ ${c.playerName}-ის დასწრება მხოლოდ ამ პირობებით (ვერსია ${s.version}).`)}</p>
            <label>{copy('Emergency contact: name and phone','გადაუდებელი საკონტაქტო პირი: სახელი და ტელეფონი')}<input required maxLength={500} value={contact} disabled={Boolean(mutation.pending)} onChange={e=>setContact(e.target.value)}/></label>
            <label className="admission-check"><input type="checkbox" required checked={accept} disabled={Boolean(mutation.pending)} onChange={e=>setAccept(e.target.checked)}/>{copy('I agree to participation in this session on the stated details.','ვეთანხმები ამ სესიაში მონაწილეობას მითითებული პირობებით.')}</label>
            {!mutation.pending&&<button className="admission-button admission-primary" disabled={mutation.busy||!accept||!contact.trim()}>{copy('Confirm this session','ამ სესიის დადასტურება')}</button>}
        </form>}
        <MutationFeedback mutation={mutation}/>
        {c.actions.includes('DECLINE_SESSION')&&['INVITED','CONFIRMED','RECONFIRM_REQUIRED'].includes(s.status)&&<ReasonAction {...{admissionCase:c,onChanged,refresh}} action="DECLINE_SESSION" participation={s} label={copy('Decline or cancel my attendance','დასწრების უარყოფა ან გაუქმება')}/>}
        {c.actions.includes('MESSAGE')&&['INVITED','CONFIRMED','RECONFIRM_REQUIRED'].includes(s.status)&&<MessageAction {...{admissionCase:c,onChanged,refresh}} prompt={copy(`Request another date for ${s.title}`,`${s.title} — სხვა თარიღის მოთხოვნა`)} prefill={copy(`Please help arrange another session instead of ${s.title} on ${new Date(s.startsAt).toLocaleString()}. My availability: `,`გთხოვთ შემითანხმოთ სხვა სესია: ${s.title}, ${new Date(s.startsAt).toLocaleString()}. ჩემი ხელმისაწვდომობა: `)}/>}
    </section>;
}
export function OfferResponse({admissionCase:c,offer:o,onChanged,refresh}:Props&{offer:Offer}) {
    const {copy}=useAdmissionCopy();const [accept,setAccept]=useState(false);const [contact,setContact]=useState('');
    const mutation=useCommand(c,`offer:${o.id}`,onChanged,refresh);
    useEffect(()=>setAccept(false),[o.id,o.version]);
    const offerStates:Record<Offer['status'],string>={PENDING:copy('Awaiting your decision','თქვენი გადაწყვეტილების მოლოდინში'),ACCEPTED:copy('Offer accepted','შეთავაზება მიღებულია'),DECLINED:copy('Offer declined','შეთავაზება უარყოფილია'),WITHDRAWN:copy('Offer withdrawn by the club','შეთავაზება კლუბმა გააუქმა'),SUPERSEDED:copy('Replaced by a newer offer','შეცვლილია ახალი შეთავაზებით'),EXPIRED:copy('Offer expired','შეთავაზების ვადა ამოიწურა')};
    const revised=o.status==='PENDING'&&(o.version>1||c.history.filter(e=>e.action==='OFFER').length>1);
    const canAccept=o.status==='PENDING'&&c.actions.includes('ACCEPT_OFFER');const needContact=c.requirements.some(r=>r.kind==='EMERGENCY_CONTACT'&&r.status==='PENDING')||o.terms.requirements.includes('EMERGENCY_CONTACT');
    return <section className="admission-panel admission-offer"><p className="admission-eyebrow">{copy('Regular place offer','მუდმივი ადგილის შეთავაზება')} · {copy('Version','ვერსია')} {o.version}</p><h2>{c.playerName} · {o.groupName}</h2><span className="admission-badge">{offerStates[o.status]}</span>{revised&&<p className="admission-notice" role="status">{copy('Review this current offer. A revised group, schedule or price needs your agreement to these details.', 'იხილეთ მიმდინარე შეთავაზება. შეცვლილ ჯგუფს, განრიგს ან ფასს ამ დეტალებზე თქვენი თანხმობა სჭირდება.')}</p>}<p>{o.location.name} · {o.location.address}</p><p>{o.schedule}</p><TermsFacts terms={o.terms}/>
        <p>{copy('Response deadline','პასუხის ვადა')}: {new Date(o.responseDeadline).toLocaleString()}</p>{o.completionDeadline&&<p>{copy('Completion deadline if requirements remain','დასრულების ვადა დარჩენილი მოთხოვნებისთვის')}: {new Date(o.completionDeadline).toLocaleString()}</p>}
        {canAccept&&<form className="admission-stack" onSubmit={e=>{e.preventDefault();void mutation.run({action:'ACCEPT_OFFER',expectedVersion:c.version,offerId:o.id,offerVersion:o.version,acceptTerms:true,emergencyContact:contact.trim()||undefined});}}>
            {needContact&&<label>{copy('Emergency contact: name and phone','გადაუდებელი საკონტაქტო პირი: სახელი და ტელეფონი')}<input required maxLength={500} value={contact} disabled={Boolean(mutation.pending)} onChange={e=>setContact(e.target.value)}/></label>}
            <label className="admission-check"><input type="checkbox" required checked={accept} disabled={Boolean(mutation.pending)} onChange={e=>setAccept(e.target.checked)}/>{copy(`I accept this named group and these terms for ${c.playerName}.`,`ვიღებ ამ დასახელებულ ჯგუფსა და პირობებს: ${c.playerName}.`)}</label>
            {!mutation.pending&&<button className="admission-button admission-primary" disabled={mutation.busy||!accept||!termsComplete(o.terms,o.schedule,o.location)}>{copy('Accept this place','ამ ადგილის მიღება')}</button>}
            {!termsComplete(o.terms,o.schedule,o.location)&&<p className="admission-notice">{copy('Essential terms are incomplete. Ask the club to complete them before accepting.','არსებითი პირობები არასრულია. მიღებამდე სთხოვეთ კლუბს შევსება.')}</p>}
        </form>}
        <MutationFeedback mutation={mutation}/>
        {o.status==='PENDING'&&c.actions.includes('DECLINE_OFFER')&&<ReasonAction {...{admissionCase:c,onChanged,refresh}} action="DECLINE_OFFER" offer={o} label={copy('Decline this offer','ამ შეთავაზების უარყოფა')}/>}
        {c.actions.includes('MESSAGE')&&<MessageAction {...{admissionCase:c,onChanged,refresh}} prompt={copy('Ask about this offer','შეთავაზების შესახებ კითხვა')} prefill=""/>}
        <p>{copy('Asking a question does not extend a deadline. Acceptance never creates a payment or grants official match eligibility.','კითხვა ვადას არ ახანგრძლივებს. მიღება გადახდას ან ოფიციალური თამაშის უფლებას არ ქმნის.')}</p>
    </section>;
}
export function MessageAction({admissionCase:c,onChanged,refresh,prompt,prefill=''}:Props&{prompt:string;prefill?:string}) {
    const {copy}=useAdmissionCopy();const [message,setMessage]=useState(prefill);const [sent,setSent]=useState(false);
    const mutation=useCommand(c,`message:${prefill?'reschedule':'general'}`,result=>{setMessage(prefill);setSent(true);onChanged(result);},refresh);
    return <details><summary className="admission-button">{prompt}</summary><form className="admission-stack" style={{marginTop:12}} onSubmit={e=>{e.preventDefault();setSent(false);void mutation.run({action:'MESSAGE',expectedVersion:c.version,message:message.trim()});}}><label>{copy('Message to responsible staff','შეტყობინება პასუხისმგებელ თანამშრომელს')}<textarea required maxLength={2000} value={message} disabled={Boolean(mutation.pending)} onChange={e=>setMessage(e.target.value)}/></label><MutationFeedback mutation={mutation}/>{sent&&<p role="status">{copy('Message recorded in this case. Any replacement session needs its own confirmation.','შეტყობინება საქმეში ჩაიწერა. შემცვლელ სესიას ცალკე დადასტურება სჭირდება.')}</p>}{!mutation.pending&&<button className="admission-button" disabled={mutation.busy||!message.trim()}>{copy('Send message','შეტყობინების გაგზავნა')}</button>}</form></details>;
}
export function ReasonAction({admissionCase:c,onChanged,refresh,action,label,participation,offer}:Props&{action:'DECLINE_SESSION'|'DECLINE_OFFER'|'WITHDRAW'|'CANCEL_ENROLLMENT'|'WAITLIST';label:string;participation?:Participation;offer?:Offer}) {
    const {copy}=useAdmissionCopy();const [reason,setReason]=useState('');const mutation=useCommand(c,action,onChanged,refresh);
    const submit=()=>{const base={expectedVersion:c.version,reason:reason.trim()};if(action==='DECLINE_SESSION'&&participation)return mutation.run({...base,action,participationId:participation.id,participationVersion:participation.version});if(action==='DECLINE_OFFER'&&offer)return mutation.run({...base,action,offerId:offer.id,offerVersion:offer.version});if(action==='WITHDRAW'||action==='CANCEL_ENROLLMENT'||action==='WAITLIST')return mutation.run({...base,action});};
    return <details><summary className="admission-button">{label}</summary><form className="admission-stack" style={{marginTop:12}} onSubmit={e=>{e.preventDefault();void submit();}}><p className="admission-muted">{copy(`This action applies only to ${c.playerName} and this arrangement. Earlier history stays recorded.`,`ქმედება მხოლოდ ${c.playerName}-ს და ამ შეთანხმებას ეხება. წინა ისტორია შენარჩუნდება.`)}</p>{action==='CANCEL_ENROLLMENT'&&<><h3>{copy('Agreed cancellation terms','შეთანხმებული გაუქმების პირობები')}</h3><p>{c.offer?.terms.cancellation||copy('Ask the responsible staff for the recorded cancellation terms before continuing.','გაგრძელებამდე პასუხისმგებელ თანამშრომელს ჰკითხეთ დაფიქსირებული გაუქმების პირობები.')}</p><p>{copy('The recorded cancellation terms apply. Outstanding finance or registration work needs staff review; no refund is assumed.','მოქმედებს დაფიქსირებული გაუქმების პირობები. დარჩენილ ფინანსურ ან სარეგისტრაციო საკითხებს თანამშრომელი განიხილავს; თანხის დაბრუნება არ ივარაუდება.')}</p></>}<label>{copy('Reason','მიზეზი')}<textarea required maxLength={2000} value={reason} disabled={Boolean(mutation.pending)} onChange={e=>setReason(e.target.value)}/></label><MutationFeedback mutation={mutation}/>{!mutation.pending&&<button className="admission-button" disabled={mutation.busy||!reason.trim()}>{label}</button>}</form></details>;
}
export function RequirementResponse({admissionCase:c,onChanged,refresh,requirement:r}:Props&{requirement:Requirement}) {
    const {copy,requirement}=useAdmissionCopy();const [evidence,setEvidence]=useState('');const mutation=useCommand(c,`requirement:${r.id}`,onChanged,refresh);
    if(r.kind==='PRIMARY_AFFILIATION_CONFIRMATION'||r.canComplete===false||(r.canComplete!==true&&r.owner!=='APPLICANT')||r.status!=='PENDING'||!c.actions.includes('COMPLETE_REQUIREMENT'))return null;
    return <form className="admission-stack" onSubmit={e=>{e.preventDefault();void mutation.run({action:'COMPLETE_REQUIREMENT',expectedVersion:c.version,requirementId:r.id,evidence:evidence.trim()});}}><label>{requirement(r.kind)}<textarea required maxLength={2000} value={evidence} disabled={Boolean(mutation.pending)} onChange={e=>setEvidence(e.target.value)}/></label><MutationFeedback mutation={mutation}/>{!mutation.pending&&<button className="admission-button" disabled={mutation.busy||!evidence.trim()}>{copy('Provide this information','ინფორმაციის მიწოდება')}</button>}</form>;
}
export function PrimaryChangeResponse({admissionCase:c,onChanged,refresh}:Props) {
    const {copy}=useAdmissionCopy();const [agree,setAgree]=useState(false);const [evidence,setEvidence]=useState('');const mutation=useCommand(c,'primary-change',onChanged,refresh);
    useEffect(()=>setAgree(false),[c.offer?.id,c.offer?.version,c.primaryAffiliation?.clubId]);
    if(!c.actions.includes('CONFIRM_PRIMARY_CHANGE')||c.offer?.terms.affiliationEffect!=='PRIMARY_CHANGE')return null;
    return <section className="admission-panel"><h2>{copy('Separate competitive club decision','სათამაშო კლუბის ცალკე გადაწყვეტილება')}</h2><p>{copy(`Proposed move from ${c.primaryAffiliation?.clubName||'the current club'} to ${c.organizationName}. This is separate from training enrollment. Required external registration must be resolved first.`,`შემოთავაზებული გადასვლა: ${c.primaryAffiliation?.clubName||'მიმდინარე კლუბი'} → ${c.organizationName}. ეს ვარჯიშში ჩარიცხვისგან ცალკეა. ჯერ უნდა შესრულდეს საჭირო გარე რეგისტრაცია.`)}</p><form className="admission-stack" onSubmit={e=>{e.preventDefault();void mutation.run({action:'CONFIRM_PRIMARY_CHANGE',expectedVersion:c.version,evidence:evidence.trim(),acceptTerms:true});}}><label>{copy('Reference for this explicit decision','ამ ცალკე გადაწყვეტილების მითითება')}<textarea required maxLength={2000} disabled={Boolean(mutation.pending)} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label className="admission-check"><input type="checkbox" required checked={agree} disabled={Boolean(mutation.pending)} onChange={e=>setAgree(e.target.checked)}/>{copy(`I explicitly agree to change ${c.playerName}’s primary competitive affiliation to ${c.organizationName}, subject to completed prerequisites.`,`ცალკე ვეთანხმები ${c.playerName}-ის ძირითადი სათამაშო წევრობის შეცვლას: ${c.organizationName}, შესრულებული წინაპირობების გათვალისწინებით.`)}</label><MutationFeedback mutation={mutation}/>{!mutation.pending&&<button className="admission-button" disabled={mutation.busy||!agree||!evidence.trim()}>{copy('Confirm the separate competitive move','ცალკე სათამაშო გადასვლის დადასტურება')}</button>}</form></section>;
}
