import { money } from './model';
import type { Plan } from './model';
import { ackCount, clashes, makeProposal, totals, workItems } from './store';
export interface Answer { text:string; links:{label:string;panel:string}[];intent:string }
export function answer(p:Plan,prompt:string):Answer {
  const q=prompt.toLowerCase();const t=totals(p);const links:Answer['links']=[];let text='',intent='explain';
  if(/repair|fix|reschedul|prepare|revise/.test(q)) {const proposal=p.proposal??makeProposal(p);intent='repair';text=p.incoming?`Move training to ${proposal.trainingStart}–${proposal.trainingEnd}, depart ${proposal.departure}, arrive around ${proposal.arrival}, warm up ${proposal.warmup} and kick off ${proposal.kickoff}. Review the preparation buffer and 45-minute venue requirement. Transport proposal v2 adds €480. ${t.headroom<0?`Request ${money(Math.abs(t.headroom))} above the current spending limit.`:'The current spending limit covers the revised estimate.'} Supplier status: ${p.supplier.decision}. ${p.incoming.status==='published'?'The revised itinerary is published.':'Supplier confirmation and publication remain necessary.'} Review or edit the proposal below.`:'No host revision is pending. Introduce the host change in Scenario tools to rehearse a schedule repair.';links.push({label:'Transport proposal v2 · Demo',panel:'transport'});}
  else if(/compare|accommod|hotel|lodge|stay/.test(q)){text=p.region==='Tbilisi'?'This local matchday has no overnight stay. The Tbilisi fixture has a ground, an academy meeting point and a confirmed group transfer. Review the transport and passenger records instead.':`North Coast is €3,520 for 22 people × 4 nights × €40, with onsite meals arranged. Harbour is €3,168 on the same basis at €36, saving €352, but meals need an offsite arrangement and the transfer estimate is 35 rather than 25 minutes. Your draft uses ${p.draft.accommodation==='harbour'?'Harbour; supplier confirmation and meals need review':p.draft.accommodation?'North Coast':'no overnight accommodation yet'}. Current total: ${money(t.estimate)}. A cheaper stay is a tradeoff, not a confirmed booking.`;links.push({label:'Compare supplier fixture records',panel:'compare'});}
  else if(/budget|cost|spend|money|approv/.test(q)){text=`Estimate ${money(t.estimate)}; committed ${money(t.committed)}; recorded payments ${money(t.paid)}. Spending limit ${money(p.approval.amount)}. ${t.headroom<0?`${money(-t.headroom)} additional authority approval is needed.`:`${money(t.headroom)} headroom remains.`} ${p.incoming?'The supplier amendment is €480; the approval difference depends on the whole plan.':''} Contingency is an allowance. An approval or supplier response records no payment.`;links.push({label:'Plan budget & approval',panel:'budget'});}
  else if(/parent|famil|guardian|message|update draft/.test(q)){text=p.incoming?.status==='applied'||p.incoming?.status==='published'?`Draft family update: “Our Wednesday friendly is now at Ridge Park, with kickoff at ${p.draft.activities.find(a=>a.id==='match3')?.start}. Training begins ${p.draft.activities.find(a=>a.id==='training3')?.start}; the coach departs ${p.draft.activities.find(a=>a.id==='transfer3')?.start}. Please review the revised itinerary after publication. Travel permission remains valid unless the overnight location changes.” ${ackCount(p)}/18 families acknowledge the published version. This text is prepared locally, not sent.`:`Families currently see itinerary v${p.published?.version??'—'}. ${p.incoming?'The host update is under review; unapproved details stay in the organiser draft.':'No revised host arrangements are ready to communicate.'} Acknowledgement and travel permission are separate decisions.`;links.push({label:'Published family projection',panel:'family'},{label:'Demo club policy',panel:'policy'});}
  else if(/impact|change|host|conflict/.test(q)){text=p.incoming?`The host proposes Ridge Park, a 12:00 kickoff and a 65-minute transfer instead of 25. ${clashes(p).length?clashes(p).join(' '):'The current draft schedule resolves the timing conflict.'} Estimate: ${money(t.estimate)}; ${t.headroom<0?`${money(-t.headroom)} over limit`:`${money(t.headroom)} within limit`}. Ana owns transport review, Maia owns the schedule, Nino owns spending approval and Salome owns family publication. ${p.incoming.status==='requested'?'The original-arrangement request is still awaiting a host response.':''}`:'No incoming host change. The original essential arrangements are confirmed in this fixture.';links.push({label:'Connected change review',panel:'impact'});}
  else if(/ground|opponent|find|suitab|pitch/.test(q)){text=p.region==='Tbilisi'?`Riverbank Friendly Ground fits ${p.squad} in the local fixture: 11-a-side, grass and changing rooms. The transfer estimate is 25 minutes. All availability and conditions are synthetic scenario records.`:`For ${p.squad}, Pinefield and the two U16 host academies fit the age band in the fixture. Lakeside is unavailable on 16 June morning; Greenhill only has U14 and Coastal Recovery availability is unknown. All availability comes from synthetic scenario records. Search and inspect these places before adding an activity.`;links.push({label:'Explore grounds & opponents',panel:'explore'});}
  else if(/unresolved|remaining|ready|task|what.*left|check/.test(q)){const work=workItems(p);text=work.length?work.map(w=>`${w.title}: ${w.detail}`).join('\n\n'):'No outstanding plan tasks. Check passengers before departure.';for(const w of work.slice(0,4))links.push({label:w.title,panel:w.panel});}
  else{text='This local Dola simulation can find suitable venues, compare stays, explain outstanding work or budget, review the host change, prepare a schedule repair, and draft a family update. Choose a suggestion or describe one of those tasks.';intent='unsupported';}
  return {text,links,intent};
}
