import { useState } from 'react';
import { ArrowDown, ArrowRight, BedDouble, Check, CheckCheck, ChevronRight, CircleAlert, Clock3, FileText, Flag, MapPin, Plus, Send, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { Activity, Plan, Proposal } from './model';
import { addMinutes, clone, dateLabel, money, ownerName, passengers, players, staff, timeLabel } from './model';
import { placeById, places } from './fixtures';
import { ackCount, clashes, costRows, departureReasons, makeProposal, permissionCount, publishReasons, repairActivities, totals, workItems } from './store';
import type { Command } from './store';
import { answer } from './assistant';
export interface PanelProps { p:Plan; panel:string; selected:string; activityId:string; day:string; send:(cmd:Command)=>void; open:(panel:string)=>void; select:(id:string)=>void; modal:(id:string)=>void; setActivity:(id:string)=>void }
export const Badge=({children,tone='neutral'}:{children:React.ReactNode;tone?:string})=><span className={`mw-badge ${tone}`}>{children}</span>;
export function Panel({p,panel,selected,activityId,day,send,open,select,modal,setActivity}:PanelProps) {
  const props={p,panel,selected,activityId,day,send,open,select,modal,setActivity};
  if(panel==='dola')return <DolaPanel {...props}/>;
  if(panel==='compare')return <ComparePanel {...props}/>;
  if(panel==='impact')return <ImpactPanel {...props}/>;
  if(panel==='budget')return <BudgetPanel {...props}/>;
  if(panel==='transport')return <TransportPanel {...props}/>;
  if(panel==='participants')return <ParticipantsPanel {...props}/>;
  if(panel==='accommodation')return <AccommodationPanel {...props}/>;
  if(panel==='policy')return <PolicyPanel/>;
  if(panel==='activity'||panel==='add')return <ActivityEditor key={`${p.id}-${panel}-${activityId}-${selected}`} {...props}/>;
  if(panel==='place')return <PlacePanel {...props}/>;
  const t=totals(p),work=workItems(p);
  return <>
    <div className="mw-panel-eyebrow"><Flag size={14}/>PLAN OVERVIEW<Badge tone="green">{p.published?`Published v${p.published.version}`:'New draft'}</Badge></div>
    <div className="mw-camp-art"><div className="pitch-lines"><span/><i/></div><span className="art-label">{p.region.toUpperCase()} / {p.start.slice(0,4)}</span><h2>{p.id.startsWith('plan-')?'One place to start.':p.region==='Tallinn'?'A team. A journey.':'One match. One plan.'}</h2></div>
    <h2>{p.name}</h2><p className="muted">{p.id.startsWith('plan-')?'A fresh draft. Add places and activities, then review their arrangements. This plan reuses the synthetic demo group.':p.region==='Tallinn'?'Five days of football, two friendlies and a team base on the north coast.':'An afternoon friendly, group travel and a clear return plan.'}</p>
    <div className="mw-facts"><div><Users size={17}/><span>18 players · 4 staff<small>Synthetic travelling group</small></span></div><div><Clock3 size={17}/><span>{dateLabel(p.start)}{p.start!==p.end?` – ${dateLabel(p.end)}`:''}<small>Times in {p.timezone}</small></span></div></div>
    <div className="mw-section-title">The plan, connected<span>{work.filter(w=>w.blocking).length} blocking</span></div>
    <Checklist {...props}/>
    <div className="mw-budget-mini"><div><small>Estimated plan cost</small><strong>{money(t.estimate)}</strong></div><Badge tone={t.headroom<0?'red':'green'}>{t.headroom<0?`${money(-t.headroom)} over`:`${money(t.headroom)} headroom`}</Badge></div>
    <button className="mw-button primary wide" onClick={()=>open(p.id.startsWith('plan-')?'explore':p.incoming?'impact':p.region==='Tbilisi'?'participants':'compare')}>{p.id.startsWith('plan-')?'Explore places & add activity':p.incoming?'Review connected change':p.region==='Tbilisi'?'Review travel & player checks':'Compare team stays'}<ArrowRight size={16}/></button>
    <button className="mw-button wide" onClick={()=>modal('publish')}>Review & publish itinerary<ChevronRight size={16}/></button>
    <p className="mw-footnote">Demo appointment: coach@talanti.ge · U16 planning at FC Dinamo Tbilisi Academy. Spending decisions belong to club leadership.</p>
  </>;
}
export function Checklist({p,open}:Pick<PanelProps,'p'|'open'>) {
  const t=totals(p);const entries:[string,string,string,LucideIcon][]=[
    ['participants','Travelling group',`${permissionCount(p)}/18 permissions · 22 expected`,Users],
    ['transport','Transport',p.baseCosts.some(c=>c.category==='Local transport')?(p.incoming?`Amendment v2 · ${p.supplier.decision}`:'Agreement v1 · confirmed'):'Not yet arranged',MapPin],
    ['budget','Budget',`${money(t.estimate)} · ${t.headroom<0?'approval needed':'within limit'}`,FileText],
    ['family','Family information',`Itinerary v${p.published?.version??'—'} · ${ackCount(p)}/18 acknowledged`,ShieldCheck],
  ];
  if(p.draft.accommodation)entries.splice(2,0,['accommodation','Team base',`${p.draft.hotelDecision}${!p.draft.mealsResolved?' · meals unresolved':''}`,BedDouble]);
  return <div className="mw-checklist">{entries.map(([id,title,detail,Icon])=><button key={id} onClick={()=>open(id as string)}><Icon size={17}/><span>{title as string}<small>{detail as string}</small></span><ChevronRight size={15}/></button>)}</div>;
}
function PlacePanel({p,selected,send,open}:PanelProps) {
  const place=placeById(selected);if(!place)return <p>Select a place on the map or in Explore.</p>;
  const planned=p.draft.activities.filter(a=>a.placeId===place.id);
  return <><div className="mw-panel-eyebrow"><MapPin size={14}/>{place.type.toUpperCase()}<Badge>Demo supplier</Badge></div><div className={`mw-place-art ${place.type}`}><div className="place-drawing">{place.type==='stay'?<BedDouble size={52}/>:place.type==='meeting'?<MapPin size={52}/>:<Flag size={52}/>}</div><span>{place.region} / illustrative location</span></div>
    <h2>{place.name}</h2><p className="muted">{place.description}</p><Badge tone={/unknown|unavailable|unsuitable/i.test(place.availability)?'amber':'green'}>{place.availability}</Badge>
    <div className="mw-facts"><div><Users size={17}/><span>Capacity {place.capacity}<small>{place.age} · 22 travellers in this plan</small></span></div><div><Clock3 size={17}/><span>{place.minutes} min transfer estimate<small>Illustrative timing · no live route</small></span></div></div>
    <h3>Conditions to consider</h3><ul className="mw-condition-list">{place.conditions.map(c=><li key={c}><Check size={14}/>{c}</li>)}</ul>
    {place.price&&<div className="mw-budget-mini"><div><small>22 people · 4 nights</small><strong>{money(place.price)}</strong></div><span className="muted">{money(place.price/88)} / person / night</span></div>}
    {planned.length>0&&<div className="mw-note green">{planned.length} linked plan activit{planned.length===1?'y':'ies'}. Planned stops remain visible when discovery is hidden.</div>}
    <button className="mw-button primary wide" onClick={()=>open('add')}><Plus size={16}/>Add activity to plan</button>
    <div className="mw-button-row"><button className="mw-button" onClick={()=>send({type:'save-place',id:place.id})}>{p.saved.includes(place.id)?<CheckCheck size={15}/>:<Plus size={15}/>} {p.saved.includes(place.id)?'Saved candidate':'Save candidate'}</button>{place.type==='stay'&&<button className="mw-button" onClick={()=>open('compare')}>Compare stays</button>}</div>
    <p className="mw-footnote">Source: {place.source}. Pin coordinates are simulation locations, not validated addresses.</p></>;
}
function ComparePanel({p,send,open,select}:PanelProps) {
  if(p.region==='Tbilisi')return <><h2>Keep the matchday light</h2><p className="muted">This local fixture needs a ground, a meeting point and group transport. There are no overnight stays to compare in the Tbilisi dataset.</p><button className="mw-button primary wide" onClick={()=>open('participants')}>Review matchday travel & players</button></>;
  const options=['lodge','harbour'].map(placeById);
  return <><div className="mw-panel-eyebrow"><BedDouble size={14}/>TEAM BASE COMPARISON<Badge>Demo</Badge></div><h2>A saving with tradeoffs</h2><p className="muted">Same group, same four nights. Compare the whole arrangement before choosing a new base.</p>
    <div className="mw-comparison">{options.map(place=><article key={place.id} className={p.draft.accommodation===place.id?'chosen':''}><div className="compare-art"><BedDouble size={27}/><Badge tone={p.draft.accommodation===place.id?'green':'neutral'}>{p.draft.accommodation===place.id?'In draft':'Candidate'}</Badge></div><h3>{place.name}</h3><strong className="compare-price">{money(place.price!)}</strong><small>22 people × 4 nights × {money(place.price!/88)}</small><dl><dt>Group capacity</dt><dd>{place.capacity} guests</dd><dt>Transfer estimate</dt><dd>{place.minutes} min · approximate</dd><dt>Meals</dt><dd>{place.id==='lodge'?'Onsite arrangement':'Offsite · unresolved'}</dd><dt>Meeting space</dt><dd>{place.id==='lodge'?'Included':'Shared'}</dd><dt>Supplier status</dt><dd>{p.draft.accommodation===place.id?p.draft.hotelDecision:place.id==='lodge'?'Original confirmed':'Fixture availability'}</dd><dt>Unknowns</dt><dd>{place.id==='lodge'?'Room allocations pending':'Meal supplier & accessibility'}</dd></dl><button className="mw-button primary wide" disabled={p.draft.accommodation===place.id} onClick={()=>send({type:'hotel',id:place.id})}>{p.draft.accommodation===place.id?'Selected in draft':'Choose this base'}</button><button className="mw-text-button" onClick={()=>select(place.id)}>See location <MapPin size={13}/></button></article>)}</div>
    <div className="mw-note amber">Harbour saves €352 on accommodation. Selecting it requires a new supplier confirmation and a meal arrangement; the existing €1,760 meal estimate stays in the budget.</div>
    <button className="mw-button wide" onClick={()=>send({type:'undo'})} disabled={!p.undo.length}>Undo draft choice</button><button className="mw-button wide" onClick={()=>open('accommodation')}>Review selected arrangement<ChevronRight size={15}/></button><p className="mw-footnote">Both records: Scenario supplier fixtures · 10 Jun 2027. No actual quotation or booking.</p></>;
}
function ActivityEditor({p,panel,activityId,selected,day,send,open}:PanelProps) {
  const existing=p.draft.activities.find(a=>a.id===activityId);
  const [form,setForm]=useState<Activity>(panel==='activity'&&existing?clone(existing):{id:`activity-${p.revision}-${p.draft.activities.length+1}`,day,start:'17:00',end:'18:00',title:'Additional training session',kind:'training',placeId:selected||p.draft.activities[0]?.placeId||'training',owner:'coach',note:'Draft activity · supplier availability needs review',arrangement:'pending'});
  const [error,setError]=useState('');const change=(field:keyof Activity,value:string)=>setForm(f=>({...f,[field]:value}));
  return <><div className="mw-panel-eyebrow"><Flag size={14}/>{panel==='add'?'NEW ACTIVITY':'ACTIVITY DETAILS'}<Badge tone="blue">Draft</Badge></div><h2>{panel==='add'?'Make room for football':form.title}</h2><p className="muted">A place, a time and a responsible person. Changes stay in the draft until publication.</p>
    <form className="mw-form" onSubmit={e=>{e.preventDefault();if(form.start>=form.end){setError('End time must be after the start.');return;}send({type:'activity',activity:form});open('overview');}}>
      <label>Activity name<input required value={form.title} onChange={e=>change('title',e.target.value)}/></label><label>Location<select value={form.placeId} onChange={e=>change('placeId',e.target.value)}>{places.filter(x=>x.region===p.region).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      <label>Day<input type="date" required min={p.start} max={p.end} value={form.day} onInput={e=>change('day',e.currentTarget.value)}/></label><div className="mw-form-two"><label>Start<input type="time" required value={form.start} onInput={e=>change('start',e.currentTarget.value)}/></label><label>End<input type="time" required value={form.end} onInput={e=>change('end',e.currentTarget.value)}/></label></div>
      <label>Activity type<select value={form.kind} onChange={e=>change('kind',e.target.value)}>{['training','match','travel','meal','stay','meeting'].map(k=><option key={k}>{k}</option>)}</select></label>
      <label>Arrangement status · simulated<select value={form.arrangement??'confirmed'} onChange={e=>change('arrangement',e.target.value)}><option value="pending">Pending supplier review</option><option value="confirmed">Confirmed in fixture</option><option value="declined">Declined · needs revision</option></select></label>
      <label>Responsible staff<select value={form.owner} onChange={e=>change('owner',e.target.value)}>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></label><label>Preparation & football context<textarea value={form.note} onChange={e=>change('note',e.target.value)} rows={3}/></label>
      {form.estimate&&<div className="mw-note">Transfer estimate {form.estimate} min · preparation buffer {form.buffer??0} min. Straight-line geometry does not prove route feasibility.</div>}
      {error&&<div role="alert" className="mw-note red">{error}</div>}<button className="mw-button primary wide" type="submit">Save activity to draft<Check size={16}/></button>
    </form>{panel==='activity'&&<button className="mw-button danger wide" onClick={()=>{send({type:'remove-activity',id:form.id});open('overview');}}>Remove activity from draft</button>}
    {clashes(p).map(c=><p className="mw-note amber" key={c}>{c}</p>)}<p className="mw-footnote">Times shown in {p.timezone}. Availability and arrangements are simulated.</p></>;
}
function ImpactPanel({p,open,send,select}:PanelProps) {
  if(!p.incoming)return <><h2>Everything in context</h2><p>No host update is pending.</p><button className="mw-button primary" disabled={p.id!=='camp'} onClick={()=>send({type:'host-change'})}>Introduce demo host change</button></>;
  const t=totals(p);const applied=['applied','published'].includes(p.incoming.status);
  const impacts=[
    ['Match & ground','14:00 · East Bay → 12:00 · Ridge Park','coach','place'],
    ['Journey','25 → 65 min · latest departure 10:10','travel','transport'],
    ['Training',applied?'Repair applied · timing reviewed':'10:00–11:00 clashes with required departure','coach','dola'],
    ['Spending',`${money(t.estimate)} estimate · ${t.headroom<0?`${money(-t.headroom)} approval needed`:`${money(t.headroom)} headroom`}`,'leader','budget'],
    ['Agreement',`Transport v2 · +€480 · ${p.supplier.decision}`,'travel','transport'],
    ['Families',`Published v${p.published?.version} · ${p.incoming.status==='published'?`${ackCount(p)}/18 acknowledgements`:'draft held for review'}`,'care','family'],
  ];
  return <><div className="mw-panel-eyebrow"><CircleAlert size={14}/>CONNECTED CHANGE<Badge tone={p.incoming.status==='published'?'green':'amber'}>{p.incoming.status==='published'?'Published':'Under review'}</Badge></div><h2>A new ground.<br/>A different day.</h2><p className="muted">East Bay’s host update changes Wednesday’s friendly. See the work it creates across the plan.</p>
    <div className="mw-change-hero"><span>16 JUN / FRIENDLY</span><div><s>14:00</s><ArrowRight size={20}/><strong>12:00</strong></div><button className="mw-text-button" onClick={()=>select('new-ground')}>Ridge Park Match Ground <MapPin size={14}/></button></div>
    <div className="mw-impact-list">{impacts.map(([title,detail,owner,target])=><button key={title} onClick={()=>target==='place'?select('new-ground'):open(target)}><span className="mw-impact-dot"/><span><strong>{title}</strong><small>{detail}</small><em>{ownerName(owner)}</em></span><ChevronRight size={16}/></button>)}</div>
    {clashes(p).length>0&&<div className="mw-note red"><CircleAlert size={17}/><span>{clashes(p)[0]}</span></div>}
    {p.incoming.status==='requested'&&<div className="mw-note amber">Request to retain the original ground and 14:00 kickoff recorded locally. No host response has been simulated. The incoming revision remains unresolved.</div>}
    <button className="mw-button primary wide" onClick={()=>{if(!p.proposal||p.proposal.applied)send({type:'prepare'});open('dola');}}><Sparkles size={16}/>{applied?'Review repair & remaining work':'Review Dola’s repair'}</button>
    {!applied&&<button className="mw-button wide" onClick={()=>send({type:'retain-original'})} disabled={p.incoming.status==='requested'}>{p.incoming.status==='requested'?'Original-arrangement request recorded':'Keep published plan & request original'}</button>}
    {applied&&<button className="mw-button wide" onClick={()=>open('overview')}>Review plan checklist<ArrowRight size={15}/></button>}<p className="mw-footnote">Source: East Bay host fixture · proposed version 2. Family information remains on the last published itinerary until the organiser publishes.</p></>;
}
function DolaPanel({p,send,open,modal}:PanelProps) {
  const [prompt,setPrompt]=useState(''),[last,setLast]=useState('What is still unresolved?');const response=answer(p,last);const q=p.proposal;const before=q?.before??makeProposal(p).before!;const stale=q&&!q.applied&&q.baseRevision!==p.revision;
  const valid=q?clashes({...clone(p),draft:{...clone(p.draft),activities:repairActivities(p.draft,q)},incoming:{status:'applied'}}):[];
  const ask=(text:string)=>{setLast(text);if(answer(p,text).intent==='repair'&&p.incoming)send({type:'prepare'});};
  return <><div className="mw-panel-eyebrow"><Sparkles size={15}/>AGENT DOLA<Badge tone="blue">Simulation</Badge></div><h2>A little help.<br/>The whole picture.</h2><p className="muted">Work from your plan. Review every proposal before it becomes a draft change.</p>
    <div className="mw-dola-suggestions">{['Explain the host change','Prepare a schedule repair','Compare accommodation','Explain the budget','Draft a parent update','Find suitable grounds'].map(text=><button key={text} onClick={()=>ask(text)}>{text}<ArrowRight size={13}/></button>)}</div>
    <div className="mw-chat-user">{last}</div><div className="mw-chat-answer"><span className="dola-avatar"><Sparkles size={15}/></span><p>{response.text}</p>{response.links.map(link=><button className="mw-source-link" key={link.label} onClick={()=>open(link.panel)}><FileText size={12}/>{link.label}<ChevronRight size={12}/></button>)}</div>
    {q&&<div className="mw-proposal"><div className="mw-section-title">Schedule repair<Badge tone={q.applied?'green':stale?'amber':'blue'}>{q.applied?'Applied':stale?'Outdated':'Proposal'}</Badge></div><p className="mw-footnote">Based on draft revision {q.baseRevision}. Your current revision is {p.revision}.</p><div className="mw-proposal-values">{[['Training',`${before.trainingStart}–${before.trainingEnd}`,`${q.trainingStart}–${q.trainingEnd}`],['Departure',before.departure,q.departure],['Arrival estimate',before.arrival,q.arrival],['Warm-up',before.warmup,q.warmup],['Kickoff',before.kickoff,q.kickoff]].map(([label,previous,after])=><div key={label}><span>{label}</span><s>{previous}</s><ArrowRight size={12}/><strong>{after}</strong></div>)}</div>
      <div className="mw-note">+€480 transport amendment · spending decision if needed · Ana reviews agreement · Salome reviews the family update.</div>
      {valid.map(c=><div className="mw-note red" key={c}>{c}</div>)}
      {stale?<button className="mw-button primary wide" onClick={()=>send({type:'prepare'})}>Recalculate from current plan</button>:<button className="mw-button primary wide" disabled={q.applied||!!valid.length} onClick={()=>send({type:'apply'})}>{q.applied?'Applied to draft':'Apply to draft'}<Check size={15}/></button>}
      {!q.applied&&<div className="mw-button-row"><button className="mw-button" onClick={()=>modal('proposal')}>Edit proposal</button><button className="mw-button" onClick={()=>send({type:'discard'})}>Discard</button></div>}
      {q.applied&&<button className="mw-button wide" onClick={()=>open('impact')}>Review outstanding decisions<ArrowRight size={15}/></button>}
    </div>}
    <form className="mw-dola-input" onSubmit={e=>{e.preventDefault();if(prompt.trim()){ask(prompt);setPrompt('');}}}><input aria-label="Ask Dola about this plan" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask about your plan…"/><button aria-label="Send prompt" disabled={!prompt.trim()}><Send size={17}/></button></form><p className="mw-footnote">Deterministic local answers from current records. No live AI, messages or bookings.</p></>;
}
function BudgetPanel({p,modal}:PanelProps) {
  const t=totals(p);
  return <><div className="mw-panel-eyebrow"><FileText size={14}/>PLAN FINANCES<Badge>EUR · Demo</Badge></div><h2>Know the whole cost</h2><div className="mw-finance-hero"><small>Total estimate</small><strong>{money(t.estimate)}</strong><Badge tone={t.headroom<0?'red':'green'}>{t.headroom<0?`${money(-t.headroom)} above limit`:`${money(t.headroom)} headroom`}</Badge></div>
    <div className="mw-section-title">Estimate breakdown</div><div className="mw-cost-list">{costRows(p).map(row=><div key={row.category}><span>{row.category}</span><strong>{money(row.cents)}</strong></div>)}</div>
    <div className="mw-facts finance"><div><span>Committed<small>Confirmed supplier obligations</small></span><strong>{money(t.committed)}</strong></div><div><span>Payment recorded<small>Recorded separately in fixture</small></span><strong>{money(t.paid)}</strong></div><div><span>Spending limit<small>Leadership decision v{p.approval.version}</small></span><strong>{money(p.approval.amount)}</strong></div></div>
    <div className="mw-note amber">{p.region==='Tallinn'?'Contingency is a €400 allowance, not a supplier invoice. ':''}Leadership approval and agreement confirmation never record a payment.</div>
    {p.incoming&&<div className="mw-note">Transport amendment: €480. Additional spending authority needed: {money(Math.max(0,-t.headroom))}. These amounts answer different questions.</div>}
    <Badge tone={p.approval.decision==='declined'?'red':p.approval.decision==='pending'?'amber':'green'}>Spending decision: {p.approval.decision}</Badge>
    <button className="mw-button primary wide" onClick={()=>modal('leadership')}>Preview leadership decision<ChevronRight size={16}/></button><button className="mw-button wide" onClick={()=>modal('invoice')}>Inspect sample transport invoice<FileText size={16}/></button><p className="mw-footnote">Owner: Nino Demo · club director. All prices are invented arithmetic fixtures, not quotations.</p></>;
}
function TransportPanel({p,modal}:PanelProps) {
  if(p.id.startsWith('plan-'))return <><div className="mw-panel-eyebrow">TRANSPORT<Badge tone="blue">New draft</Badge></div><h2>Start with the journey</h2><p className="muted">No transport supplier or price has been attached to this fresh plan. Add a travel activity and its responsible person from the schedule.</p><div className="mw-note">Detailed supplier agreements and departure playback are demonstrated by the camp and local-friendly presets.</div></>;
  if(p.region==='Tbilisi')return <><div className="mw-panel-eyebrow"><FileText size={14}/>MATCHDAY TRANSPORT<Badge>Demo agreement v1</Badge></div><h2>Riverbank group transfer</h2><div className="mw-document"><h3>Local coach arrangement</h3><p>{dateLabel(p.start,true)} · 22 passengers · 24-seat coach</p><dl><dt>Journey</dt><dd>Academy meeting point ↔ Riverbank Friendly Ground</dd><dt>Transfer estimate</dt><dd>25 minutes each way · approximate</dd><dt>Estimated and committed</dt><dd>€300 · confirmed fixture</dd><dt>Deposit recorded</dt><dd>€100 · separate from agreement status</dd><dt>Terms</dt><dd>Demo cancellation terms: review with supplier before the matchday</dd><dt>Review owner</dt><dd>Ana Demo · travel coordinator</dd></dl></div><p className="mw-footnote">Fictional local supplier arrangement. No real booking, payment or signature.</p></>;
  return <><div className="mw-panel-eyebrow"><FileText size={14}/>TRANSPORT AGREEMENT<Badge>Demo document</Badge></div><h2>Baltic Team Transport</h2><p className="muted">Local group coach arrangement · fictional supplier</p><div className="mw-document"><div className="document-header">BT / GROUP SERVICES<small>AGREEMENT {p.incoming?'V2 · AMENDMENT':'V1'}</small></div><h3>Academy camp transport</h3><dl><dt>Group</dt><dd>22 passengers · 24-seat coach</dd><dt>Dates</dt><dd>14–18 June 2027</dd><dt>Original estimate</dt><dd>€1,800 · confirmed fixture</dd><dt>Deposit</dt><dd>€450 recorded · unchanged</dd><dt>Included</dt><dd>Arrival, return, training and two friendly transfers</dd><dt>Cancellation</dt><dd>Demo terms: deposit retained within seven days; earlier cancellation reviewed by supplier</dd><dt>Review owner</dt><dd>Ana Demo · travel coordinator</dd></dl>{p.incoming&&<><h3>Proposed amendment</h3><p>16 June: Ridge Park replaces East Bay. Transfer estimate 65 minutes; additional group charge €480. Revised agreement total €2,280.</p><Badge tone={p.supplier.decision==='confirmed'?'green':p.supplier.decision==='declined'?'red':'amber'}>Version 2: {p.supplier.decision}</Badge></>}</div>
    {p.incoming&&<button className="mw-button primary wide" onClick={()=>modal('supplier')}>Preview supplier response<ChevronRight size={16}/></button>}
    {p.supplier.decision==='declined'&&<div className="mw-note red">Amendment declined. Ana must revise the arrangement or request another response before publication and departure.</div>}
    <p className="mw-footnote">Transport proposal version {p.incoming?2:1} · scenario record. No signature, request or payment is sent.</p></>;
}
function AccommodationPanel({p,send,open}:PanelProps) {
  if(!p.draft.accommodation)return <><h2>No overnight stay needed</h2><p className="muted">This plan keeps accommodation out of the way. Explore can add a candidate if your plan changes.</p></>;
  const place=placeById(p.draft.accommodation);
  return <><div className="mw-panel-eyebrow"><BedDouble size={14}/>TEAM BASE<Badge tone={p.draft.hotelDecision==='confirmed'?'green':'amber'}>{p.draft.hotelDecision}</Badge></div><h2>{place.name}</h2><p className="muted">22 people · 4 nights · {money(place.price!)} accommodation estimate</p><ul className="mw-condition-list">{place.conditions.map(c=><li key={c}><Check size={15}/>{c}</li>)}</ul>
    <div className="mw-note">Choosing a new overnight location creates an amendment. Confirmation from the original lodge does not transfer to the new supplier.</div>
    {p.draft.hotelDecision!=='confirmed'&&<><button className="mw-button primary wide" onClick={()=>send({type:'hotel-decision',confirmed:true})}>Simulate accommodation confirmation</button><button className="mw-button wide" onClick={()=>send({type:'hotel-decision',confirmed:false})}>Simulate supplier decline</button></>}
    {!p.draft.mealsResolved?<><div className="mw-note amber">Offsite meals are unresolved. Ana can confirm a fixture arrangement with Harbour Kitchen Demo: 22 people, same €1,760 estimate, meals delivered to the stay.</div><button className="mw-button primary wide" onClick={()=>send({type:'meals'})}>Arrange fixture meal delivery</button></>:<div className="mw-note green">Meals arranged in simulation · estimate €1,760.</div>}
    <button className="mw-button wide" onClick={()=>open('compare')}>Compare team stays</button><button className="mw-button wide" onClick={()=>open('policy')}>Review overnight-change policy<ShieldCheck size={16}/></button><p className="mw-footnote">Source: supplier fixture record. Conditions are invented for testing.</p></>;
}
function ParticipantsPanel({p,send}:PanelProps) {
  const reasons=departureReasons(p);const boarded=Object.values(p.boarding).filter(x=>x==='boarded').length;
  return <><div className="mw-panel-eyebrow"><Users size={14}/>TRAVELLING GROUP<Badge>Demo people</Badge></div><h2>Every person accounted for</h2><div className="mw-budget-mini"><div><strong>{boarded} / 22</strong><small>Boarded · {permissionCount(p)}/18 current permissions</small></div><Badge tone="blue">{p.progress}</Badge></div>
    <h3>Staff responsibilities</h3><div className="mw-staff-list">{staff.map(s=><div key={s.id}><span className="mw-avatar">{s.initials}</span><span>{s.name}<small>{s.role}</small></span></div>)}</div><label className="mw-field-label">Equipment check owner<select value={p.equipmentOwner} onChange={e=>send({type:'equipment',owner:e.target.value})}><option value="">Unassigned · nonblocking</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
    <h3>Boarding decisions</h3><p className="muted">Expected stays expected until a boarding decision. Absences must be resolved before departure.</p><div className="mw-boarding-list">{passengers.map(person=><label key={person.id}><span>{person.name}</span><select aria-label={`Boarding ${person.name}`} value={p.boarding[person.id]} onChange={e=>send({type:'boarding',id:person.id,status:e.target.value as 'expected'|'boarded'|'absent'})}><option value="expected">Expected</option><option value="boarded">Boarded</option><option value="absent">Absent</option></select></label>)}</div>
    {p.progress==='planning'&&<button className="mw-button wide" disabled={p.id.startsWith('plan-')} title={p.id.startsWith('plan-')?'Playback is available in the camp and local-friendly presets':'Advance the scenario clock'} onClick={()=>send({type:'advance'})}>Advance scenario to boarding</button>}
    <button className="mw-button wide" onClick={()=>send({type:'board-rest'})}>Simulate remaining boarding checks</button>
    {reasons.length>0&&<div className="mw-note amber"><div><strong>Before departure</strong><ul>{reasons.map(r=><li key={r}>{r}</li>)}</ul></div></div>}
    <button className="mw-button primary wide" disabled={p.progress!=='boarding'||!!reasons.length} onClick={()=>send({type:'depart'})}>Record departure</button><button className="mw-button wide" disabled={p.progress!=='departed'} onClick={()=>send({type:'arrive'})}>Record arrival</button><p className="mw-footnote">Synthetic players and guardians. Bulk rehearsal actions are recorded as scenario fixture events.</p></>;
}
export function PolicyPanel() {return <><div className="mw-panel-eyebrow"><ShieldCheck size={14}/>CLUB TRAVEL POLICY<Badge>Demo policy</Badge></div><h2>Permission ≠ acknowledgement</h2><p className="muted">A fictional FC Dinamo Tbilisi Academy travel policy for this scenario.</p><div className="mw-policy-block"><h3>Same-day ground or time change</h3><p>Publish a revised itinerary and ask guardians for a fresh acknowledgement. Existing travel permission remains valid.</p></div><div className="mw-policy-block"><h3>Overnight location change</h3><p>Publish the new arrangement and request renewed travel permission for that version. Preserve the original permission in its history.</p></div><div className="mw-note">A family acknowledgement records that the itinerary was reviewed. It cannot grant travel permission or approve spending.</div><p className="mw-footnote">Source: Club travel policy demo. This is an invented club rule for the simulation, not a legal or federation requirement.</p></>;}
export function ProposalEditor({p,send,close}:{p:Plan;send:PanelProps['send'];close:()=>void}) {
  const [q,setQ]=useState<Proposal>(clone(p.proposal??makeProposal(p)));const invalid=clashes({...clone(p),draft:{...clone(p.draft),activities:repairActivities(p.draft,q)},incoming:{status:'applied'}});
  return <><h2>Edit the schedule repair</h2><p className="muted">Adjust timing before applying. Arrival uses the 65-minute fixture estimate.</p><form className="mw-form" onSubmit={e=>{e.preventDefault();send({type:'edit-proposal',patch:q});close();}}>{([['trainingStart','Training start'],['trainingEnd','Training end'],['departure','Coach departure'],['warmup','Warm-up'],['kickoff','Kickoff']] as const).map(([key,label])=><label key={key}>{label}<input type="time" required value={q[key]} onInput={e=>{const value=e.currentTarget.value;setQ(prev=>({...prev,[key]:value,...(key==='departure'?{arrival:addMinutes(value,65)}:{})}));}}/></label>)}<div className="mw-note">Estimated arrival {q.arrival}. Requires 45 minutes before kickoff and 15 minutes after training.</div>{invalid.map(c=><div className="mw-note red" key={c}>{c}</div>)}<button className="mw-button primary wide" disabled={!!invalid.length}>Save proposal edits</button></form></>;
}
export function DecisionPreview({p,kind,send,close}:{p:Plan;kind:'leadership'|'supplier';send:PanelProps['send'];close:()=>void}) {
  const t=totals(p),leader=kind==='leadership';return <><div className="mw-panel-eyebrow"><Users size={15}/>PREVIEW AS {leader?'LEADERSHIP':'SUPPLIER'}<Badge>Demo only</Badge></div><h2>{leader?'A spending decision':'A supplier decision'}</h2><p className="muted">{leader?'Nino Demo · club director':'Baltic Team Transport Demo · fictional supplier'}</p><div className="mw-finance-hero"><small>{leader?'Requested spending limit':'Transport amendment v2'}</small><strong>{money(leader?Math.max(t.estimate,p.approval.amount):48000)}</strong><p>{leader?`${money(Math.max(0,-t.headroom))} above the existing limit. Agreement amendment remains €480.`:'New ground transfer · 65-minute estimate. Original agreement €1,800; revised total €2,280.'}</p></div><div className="mw-note">This preview records a synthetic actor’s decision in the same plan. Approval, supplier confirmation and recorded payment remain separate.</div><div className="mw-button-row"><button className="mw-button primary" disabled={!leader&&!p.incoming} onClick={()=>{send(leader?{type:'approve',approved:true}:{type:'supplier',confirmed:true});close();}}>{leader?'Approve spending':'Confirm amendment'}<Check size={16}/></button><button className="mw-button danger" disabled={!leader&&!p.incoming} onClick={()=>{send(leader?{type:'approve',approved:false}:{type:'supplier',confirmed:false});close();}}>Decline<X size={16}/></button></div></>;
}
export function PublishPreview({p,send,close}:{p:Plan;send:PanelProps['send'];close:()=>void}) {
  const reasons=publishReasons(p);return <><div className="mw-panel-eyebrow"><Send size={14}/>PUBLISH TO FAMILIES<Badge>Simulation</Badge></div><h2>One clear version to follow</h2><p className="muted">Families currently see itinerary v{p.published?.version??'—'}. The draft is revision {p.revision}. Publication saves a snapshot for the 18 linked demo guardians.</p><p>{p.incoming?'Wednesday’s friendly moves to Ridge Park at 12:00. The repaired day includes earlier training and departure.':'Review the current activities and accommodation before sharing.'}</p>{reasons.length?<div className="mw-note amber"><div><strong>Resolve before publication</strong><ul>{reasons.map(r=><li key={r}>{r}</li>)}</ul></div></div>:<div className="mw-note green">Required schedule, supplier and spending checks are satisfied.</div>}<div className="mw-note">A same-day change asks for acknowledgement. A new overnight location asks for renewed travel permission. Original decisions remain in history.</div><button className="mw-button primary wide" disabled={!!reasons.length||p.published?.revision===p.revision} onClick={()=>{send({type:'publish'});close();}}>Publish itinerary v{(p.published?.version??0)+1}</button></>;
}
export function FamilyView({p,send,close}:{p:Plan;send:PanelProps['send'];close:()=>void}) {
  const pub=p.published;const [day,setDay]=useState(p.id==='camp'?'2027-06-16':p.start);const family=p.families.find(f=>f.childId==='player-1')!;
  const days=[...new Set(pub?.draft.activities.map(a=>a.day)??[])].sort();const permission=pub&&family.permissions.find(x=>x.version===pub.permissionVersion)?.status==='granted';const acknowledged=pub&&family.acknowledgedVersion===pub.version;
  const age=p.milestone?Math.floor((new Date(p.clock).getTime()-new Date(p.milestone.at).getTime())/60000):0;
  return <div className="mw-family-page"><header><button className="mw-button" onClick={close}><ArrowDown size={15}/>Back to workspace</button><span>GrassKickZ <Badge tone="blue">Family preview · Demo</Badge></span></header><main className="mw-family-content"><div className="mw-family-identity"><span className="mw-avatar large">G1</span><div><small>GUARDIAN 01 DEMO</small><h2>Your child’s team journey</h2><p>{players[0].name} · {p.squad} · FC Dinamo Tbilisi Academy</p></div></div>
    <div className="mw-family-hero"><Badge tone="green">Published itinerary v{pub?.version??'—'}</Badge><h1>{p.name}</h1><p>{dateLabel(p.start,true)}{p.start!==p.end?` – ${dateLabel(p.end,true)}`:''} {p.start.slice(0,4)} · {p.timezone}</p></div>
    {!pub?<div className="mw-note">No itinerary has been published yet. The organiser is building the plan.</div>:<>
    {p.incoming&&p.incoming.status!=='published'&&<div className="mw-note amber"><CircleAlert size={18}/><span>An update is under review. Your published itinerary remains the current family information.</span></div>}
    {p.milestone?<div className={`mw-milestone ${age>60?'stale':''}`}><span className="live-dot"/><div><h3>{age>60?'No recent staff update':p.milestone.status}</h3><p>Last confirmed: {p.milestone.status} · {timeLabel(p.milestone.at,p.timezone)}</p><p>{p.milestone.next}</p><small>{p.milestone.actor} · {Math.max(0,age)} minutes ago · scenario playback</small></div></div>:<div className="mw-note">Travel has not started. Next confirmed activity: {pub.draft.activities[0]?.title} at {pub.draft.activities[0]?.start}.</div>}
    <section className="mw-family-card"><div className="mw-section-title">Latest published update<Badge>v{pub.version}</Badge></div><p>{pub.summary}</p><small className="muted">Source: Maia Demo · organiser · {timeLabel(pub.at,p.timezone)}</small><div className="mw-family-actions"><button className="mw-button primary" disabled={!!acknowledged} onClick={()=>send({type:'ack',childId:'player-1'})}>{acknowledged?<CheckCheck size={17}/>:<Check size={17}/>} {acknowledged?`Itinerary v${pub.version} acknowledged`:'Acknowledge this itinerary'}</button><small>Acknowledgement records review; travel permission is separate.</small></div></section>
    <section className="mw-family-card"><div className="mw-section-title">Your child’s travel permission<Badge tone={permission?'green':'amber'}>{permission?'Granted':'Decision needed'}</Badge></div><p>{permission?`Travel permission covers itinerary v${pub.permissionVersion}. A same-day time or ground change does not replace it.`:pub.permissionVersion>1?'The overnight location changed. Please review the new team base and grant renewed travel permission.':'Please review this first published itinerary and grant travel permission.'}</p>{!permission&&<button className="mw-button primary" onClick={()=>send({type:'permission',childId:'player-1'})}>{pub.permissionVersion>1?'Grant renewed travel permission':'Grant travel permission'}</button>}<details><summary>Permission history</summary>{family.permissions.map((r,i)=><p key={i}>Version {r.version} · {r.status} · {r.actor} · {timeLabel(r.at,p.timezone)}</p>)}</details></section>
    <section className="mw-family-card"><h3>Your published schedule</h3><div className="mw-family-days">{days.map(d=><button key={d} className={d===day?'active':''} onClick={()=>setDay(d)}>{dateLabel(d)}</button>)}</div><div className="mw-family-itinerary">{pub.draft.activities.filter(a=>a.day===day).sort((a,b)=>a.start.localeCompare(b.start)).map(a=><article key={a.id}><time>{a.start}</time><div><h4>{a.title}</h4><p><MapPin size={12}/>{placeById(a.placeId).name}</p><small>{a.start}–{a.end} · {ownerName(a.owner)}{a.estimate?` · ${a.estimate} min estimate`:''}</small>{a.kind==='travel'&&a.note&&<p>{a.note}</p>}</div></article>)}</div></section>
    {pub.draft.accommodation&&<section className="mw-family-card"><h3>Team base & care</h3><p><strong>{placeById(pub.draft.accommodation).name}</strong> · four nights</p><ul>{placeById(pub.draft.accommodation).conditions.map(c=><li key={c}>{c}</li>)}</ul><p>Supervision contact: Salome Demo · player care. Demo contact: care@example.invalid.</p><p>Meeting: {p.region==='Tallinn'?'Group check after Tallinn arrival, 14 Jun at 12:30. Origin departure 09:00 Asia/Tbilisi.':'Academy meeting point at 13:00.'}</p><p>Collection: {p.region==='Tallinn'?'18 Jun, 18:30 Asia/Tbilisi · academy meeting point, illustrative return schedule.':'Academy meeting point at 16:45.'}</p><p>Family contribution: {p.contribution?money(p.contribution):'None in this fixture'}.</p></section>}
    {!pub.draft.accommodation&&<section className="mw-family-card"><h3>Meeting, collection & supervision</h3><p>Meet at Academy meeting point at 13:00. Return collection at 16:45, same place.</p><p>Salome Demo · player care · care@example.invalid</p><p>Bring boots and water. Family contribution: none in this fixture.</p></section>}
    </>}<footer>Demo people and arrangements. Staff milestones are scenario playback, not live location tracking.</footer>
  </main></div>;
}
