import { CaseDates } from '../lifecycle/CaseDates';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { commandAdmission } from '../api';
import type { AdmissionCase, AdmissionWorkspace, CaseCommand, CommandBase, Opportunity, Participation, Requirement } from '../types';
import type { AuthSessionId } from '../../../utils/authStorage';
import type { OpenWorkspace } from '../../clubOperations/WorkspaceHome';
import { useClubAdmissionCopy, type ClubAdmissionCopyKey } from './copy';
import { AdmissionDate, AdmissionEmpty, AdmissionError, AdmissionField, AdmissionLinkButton, AdmissionPanel, AdmissionPill, AdmissionSessionHeading } from './ui';
import { ownerCopy, nextCopy, participationCopy, offerCopy, requirementCopy, stageCopy, localInput, utcInput } from './domain';
import { IntroductionPermission } from '../components/IntroductionPermission';
import { SessionEditor } from './SessionEditor';
import { completeOfferTerms, TermsSummary } from './TermsSummary';
import { useDurableMutation } from './useDurableMutation';
import { AssessmentEditor, type AssessmentDecision } from './AssessmentEditor';

type Payload<T> = T extends CommandBase ? Omit<T,keyof CommandBase> : never;
export type ClubCommandPayload = Payload<CaseCommand>;
type Execute = (payload:ClubCommandPayload)=>Promise<boolean>;

function ReasonForm({label,hint,busy,onConfirm,onCancel}:{label:string;hint?:string;busy:boolean;onConfirm:(reason:string)=>Promise<boolean>;onCancel:()=>void}) {
  const {c}=useClubAdmissionCopy();const [reason,setReason]=useState('');
  return <form onSubmit={e=>{e.preventDefault();void onConfirm(reason).then(ok=>{if(ok)onCancel();});}}>{hint&&<p className="admission-group-meta">{hint}</p>}<AdmissionField label={c('reason')}><textarea required maxLength={2000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></AdmissionField><div className="admission-actions"><button className="admission-button" disabled={busy}>{label}</button><button type="button" disabled={busy} className="admission-secondary" onClick={onCancel}>{c('cancel')}</button></div></form>;
}

function SessionRow({session,record,group,choices,busy,execute,onOpen}:{session:Participation;record:AdmissionCase;group?:Opportunity;choices?:AdmissionWorkspace['sessions'];busy:boolean;execute:Execute;onOpen:OpenWorkspace}) {
  const {c,locale}=useClubAdmissionCopy();const [edit,setEdit]=useState(false),[cancel,setCancel]=useState(false),[attendance,setAttendance]=useState<''|'ATTENDED'|'NO_SHOW'>(''),[note,setNote]=useState('');
  return <article className="admission-session-row">
    <AdmissionSessionHeading title={session.title}><AdmissionDate value={session.startsAt} locale={locale} timezone={session.timezone}/><p>{session.location.name} · {session.location.address}<br/>{session.contact}</p></AdmissionSessionHeading>
    <div className="admission-pills"><AdmissionPill tone={session.status==='CONFIRMED'||session.status==='ATTENDED'?'good':session.status==='RECONFIRM_REQUIRED'?'attention':'neutral'}>{c(participationCopy[session.status])}</AdmissionPill>{session.noRegularPlaceGuaranteed&&<AdmissionPill>{c('noPlace')}</AdmissionPill>}</div>
    <AdmissionDate value={session.responseDeadline} label={c('responseDeadline')} locale={locale} timezone={session.timezone}/>
    <p className="admission-group-meta">{c('sessionCost')}: {session.cost}<br/>{c('preparation')}: {session.preparation || '—'}</p>
    <IntroductionPermission session={session} playerName={record.playerName} busy={busy} onRecord={(currentClub,evidence)=>execute({action:'RECORD_INTRODUCTION_PERMISSION',participationId:session.id,participationVersion:session.version,currentClub,evidence})} onRevoke={reason=>execute({action:'REVOKE_INTRODUCTION_PERMISSION',participationId:session.id,participationVersion:session.version,reason})}/>
    {session.status==='CONFIRMED'&&session.introductionPermission?.allowsParticipation!==false&&<p className="admission-notice">{c('emergency')}: {session.emergencyContact??c('notProvided')}</p>}
    {record.actions.includes('RECORD_ATTENDANCE')&&session.status==='CONFIRMED'&&<form onSubmit={e=>{e.preventDefault();if(attendance)void execute({action:'RECORD_ATTENDANCE',participationId:session.id,participationVersion:session.version,attendance,...(note?{internalNote:note}:{})}).then(ok=>{if(ok){setAttendance('');setNote('');}});}}><div className="admission-form-grid"><AdmissionField label={c('recordAttendance')} hint={c('attendanceHint')}><select value={attendance} required disabled={busy} onChange={e=>setAttendance(e.target.value as typeof attendance)}><option value="">—</option><option value="ATTENDED">{c('attended')}</option><option value="NO_SHOW">{c('noShow')}</option></select></AdmissionField><AdmissionField label={c('internalNote')} hint={c('privateHint')}><textarea value={note} disabled={busy} maxLength={4000} onChange={e=>setNote(e.target.value)}/></AdmissionField></div><button className="admission-secondary" disabled={busy||!attendance}>{c('recordAttendance')}</button></form>}
    <div className="admission-actions">
      {session.squadSessionId&&group?.squadId&&['CONFIRMED','ATTENDED','NO_SHOW'].includes(session.status)&&<AdmissionLinkButton onClick={()=>onOpen('attendance',{squad:String(group.squadId),session:String(session.squadSessionId)})}>{c('attendanceLink')}</AdmissionLinkButton>}
      {record.actions.includes('CHANGE_SESSION')&&['INVITED','CONFIRMED','RECONFIRM_REQUIRED'].includes(session.status)&&group&&<button type="button" className="admission-secondary" disabled={busy} onClick={()=>{setEdit(v=>!v);setCancel(false);}}>{c('changeSession')}</button>}
      {record.actions.includes('CANCEL_SESSION')&&['INVITED','CONFIRMED','RECONFIRM_REQUIRED'].includes(session.status)&&<button type="button" className="admission-text-button" disabled={busy} onClick={()=>{setCancel(v=>!v);setEdit(false);}}>{c('cancelSession')}</button>}
    </div>
    {edit&&group&&<SessionEditor group={group} participation={session} choices={choices} busy={busy} onCancel={()=>setEdit(false)} onSubmit={(details,reason)=>execute({action:'CHANGE_SESSION',participationId:session.id,participationVersion:session.version,session:details,reason})}/>}
    {cancel&&<ReasonForm label={c('cancelSession')} busy={busy} onCancel={()=>setCancel(false)} onConfirm={reason=>execute({action:'CANCEL_SESSION',participationId:session.id,participationVersion:session.version,reason})}/>}
  </article>;
}

function RequirementRow({requirement,canComplete,busy,execute}:{requirement:Requirement;canComplete:boolean;busy:boolean;execute:Execute}) {
  const {c}=useClubAdmissionCopy();const [evidence,setEvidence]=useState('');
  return <article className="admission-task"><header><strong>{c(requirementCopy[requirement.kind])}</strong><AdmissionPill tone={requirement.status==='COMPLETE'?'good':'attention'}>{c(requirement.status==='COMPLETE'?'complete':'pending')}</AdmissionPill></header><p>{c('requirementOwner')}: {c(ownerCopy[requirement.owner])}</p>{requirement.evidence&&<p>{c('evidence')}: {requirement.evidence}</p>}
    {requirement.status==='PENDING'&&canComplete&&requirement.owner!=='APPLICANT'&&<form onSubmit={e=>{e.preventDefault();void execute({action:'COMPLETE_REQUIREMENT',requirementId:requirement.id,evidence}).then(ok=>{if(ok)setEvidence('');});}}><AdmissionField label={c('evidence')} hint={c('evidenceHint')}><input required value={evidence} disabled={busy} maxLength={2000} onChange={e=>setEvidence(e.target.value)}/></AdmissionField><div className="admission-actions"><button className="admission-secondary" disabled={busy}>{c('completeRequirement')}</button></div></form>}
  </article>;
}

function OfferForm({record,groups,busy,execute,onClose}:{record:AdmissionCase;groups:Opportunity[];busy:boolean;execute:Execute;onClose:()=>void}) {
  const {c}=useClubAdmissionCopy();const [groupId,setGroupId]=useState(record.groupId),[deadline,setDeadline]=useState(''),[completion,setCompletion]=useState(''),[reason,setReason]=useState(''),[note,setNote]=useState('');
  const group=groups.find(g=>g.id===groupId);const complete=group&&completeOfferTerms(group.terms,group.schedule,group.location);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!group||!complete)return;const payload:ClubCommandPayload={action:'OFFER',groupId:group.id,groupVersion:group.version,...(deadline?{responseDeadline:utcInput(deadline)}:{}),...(completion?{completionDeadline:utcInput(completion)}:{}),...(reason?{reason}:{}),...(note?{internalNote:note}:{})};if(await execute(payload))onClose();};
  return <form onSubmit={e=>void submit(e)}><p className="admission-group-meta">{c(record.offer?'replaceHint':'offerHint')}</p><fieldset disabled={busy} className="admission-form-grid"><AdmissionField label={c('chooseGroup')} wide><select required value={groupId} onChange={e=>setGroupId(Number(e.target.value))}>{groups.filter(g=>g.canManage!==false).map(g=><option key={g.id} value={g.id}>{g.name} · {g.remainingPlaces} {c('remaining')}</option>)}</select></AdmissionField><AdmissionField label={c('responseDeadline')} hint={`${c('sevenDays')} · ${Intl.DateTimeFormat().resolvedOptions().timeZone}`}><input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></AdmissionField><AdmissionField label={c('completeBy')} hint={`${c('sevenAfterAcceptance')} · ${Intl.DateTimeFormat().resolvedOptions().timeZone}`}><input type="datetime-local" value={completion} onChange={e=>setCompletion(e.target.value)}/></AdmissionField>
    <AdmissionField label={c('reason')} wide><textarea required={Boolean(record.offer)||record.groupId!==groupId} value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></AdmissionField><AdmissionField label={c('internalNote')} hint={c('privateHint')} wide><textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)}/></AdmissionField></fieldset>
    {group&&<div className="admission-offer-terms"><h3>{c('termsReview')} · {group.name}</h3><TermsSummary terms={group.terms} location={group.location} schedule={group.schedule}/></div>}
    {!complete&&<p className="admission-notice">{c('offerIncomplete')}</p>}<div className="admission-actions"><button className="admission-button" disabled={busy||!complete}>{c(record.offer?'replaceOffer':'createOffer')}</button><button type="button" className="admission-secondary" disabled={busy} onClick={onClose}>{c('cancel')}</button></div></form>;
}

export function CaseDetail({record,workspace,sessionId,onChanged,onBack,onOpen,onRefresh}:{record:AdmissionCase;workspace:AdmissionWorkspace;sessionId:AuthSessionId;onChanged:(value:AdmissionCase)=>void;onBack:()=>void;onOpen:OpenWorkspace;onRefresh?:()=>void}) {
  const {c,locale}=useClubAdmissionCopy();const mutation=useDurableMutation(`case:${sessionId}:${record.organizationId}:${record.id}`);
  const [form,setForm]=useState<'invite'|'offer'|'assign'|'message'|'waitlist'|'decline'|'cancelEnrollment'|'assessment'|'approval'|null>(null),[message,setMessage]=useState(''),[assignee,setAssignee]=useState(String(record.responsible?.id??'')),[offerAction,setOfferAction]=useState<'withdraw'|'extend'|null>(null),[deadline,setDeadline]=useState(record.offer?localInput(record.offer.responseDeadline):''),[extensionReason,setExtensionReason]=useState(''),[success,setSuccess]=useState(''),[assessmentGroup,setAssessmentGroup]=useState(record.groupId);
  const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{heading.current?.focus();},[record.id]);
  const operation=(body:CaseCommand)=>commandAdmission(record.id,body,sessionId);
  const execute:Execute=async(payload)=>{setSuccess('');const result=await mutation.send<AdmissionCase,CaseCommand>({...payload,expectedVersion:record.version},operation);if(result){onChanged(result);setSuccess(c('saved'));return true;}return false;};
  const allowed=(action:CaseCommand['action'])=>record.actions.includes(action);
  const group=workspace.groups.find(g=>g.id===record.groupId);
  const assessmentDecision:Record<AssessmentDecision,ClubAdmissionCopyKey>={offer:'offerRecommended',session:'anotherSession',waitlist:'waitlist',decline:'declineCase'};
  const actionButtons: {action:CaseCommand['action'];form:NonNullable<typeof form>;label:ClubAdmissionCopyKey}[]=[{action:'INVITE_SESSION',form:'invite',label:'invite'},{action:'OFFER',form:'offer',label:record.offer?'replaceOffer':'offer'},{action:'ASSIGN',form:'assign',label:'assign'},{action:'MESSAGE',form:'message',label:'message'},{action:'WAITLIST',form:'waitlist',label:'waitlistAction'},{action:'DECLINE',form:'decline',label:'declineCase'}];
  return <div className="admission-stack">
    <AdmissionLinkButton onClick={onBack} back>{c('back')}</AdmissionLinkButton>
    <header className="admission-heading"><div><span className="admission-eyebrow">{record.organizationName} · {record.intake}</span><h1 ref={heading} tabIndex={-1}>{record.playerName}</h1><div className="admission-pills"><AdmissionPill tone={record.stage==='ENROLLED'?'good':'neutral'}>{c(stageCopy[record.stage])}</AdmissionPill><AdmissionPill>{record.groupName}</AdmissionPill></div></div><AdmissionDate value={record.nextAction.dueAt} locale={locale} label={c('next')}/></header>
    {mutation.error&&<AdmissionError message={mutation.error} retry={c('refresh')} onRetry={onRefresh}/>}
    {success&&<p className="admission-success" role="status">{success}</p>}
    {mutation.pending&&<p className="admission-notice">{c('uncertain')} <button className="admission-text-button" disabled={mutation.busy} onClick={()=>void mutation.recover<AdmissionCase,CaseCommand>(operation).then(value=>{if(value){onChanged(value);setSuccess(c('saved'));}})}>{c('retry')}</button></p>}
    <CaseDates record={record} sessionId={sessionId} groups={workspace.groups} onChanged={onChanged}/>
    <div className="admission-grid"><div className="admission-stack">
      <AdmissionPanel title={c('next')} subtitle={`${c(ownerCopy[record.nextAction.owner])} · ${(nextCopy[record.nextAction.code]?c(nextCopy[record.nextAction.code]):record.nextAction.label)}`}>
        <div className="admission-actions">{actionButtons.filter(a=>allowed(a.action)).map(a=><button key={a.form} className={a.form==='invite'||a.form==='offer'?'admission-button':'admission-secondary'} disabled={mutation.busy||Boolean(mutation.pending)} onClick={()=>setForm(form===a.form?null:a.form)} aria-expanded={form===a.form}>{c(a.label)}</button>)}</div>
        {form==='invite'&&group&&allowed('INVITE_SESSION')&&<SessionEditor group={group} choices={workspace.sessions} busy={mutation.busy} onCancel={()=>setForm(null)} onSubmit={session=>execute({action:'INVITE_SESSION',session})}/>}
        {form==='offer'&&allowed('OFFER')&&<OfferForm record={record} groups={workspace.groups} busy={mutation.busy} execute={execute} onClose={()=>setForm(null)}/>}
        {form==='assign'&&allowed('ASSIGN')&&<form onSubmit={e=>{e.preventDefault();void execute({action:'ASSIGN',responsibleUserId:assignee?Number(assignee):null}).then(ok=>{if(ok)setForm(null);});}}><AdmissionField label={c('responsible')} hint={c('assignmentHint')}><select value={assignee} onChange={e=>setAssignee(e.target.value)} disabled={mutation.busy}><option value="">{c('queue')}</option>{workspace.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></AdmissionField><div className="admission-actions"><button className="admission-button" disabled={mutation.busy}>{c('save')}</button></div></form>}
        {form==='message'&&allowed('MESSAGE')&&<form onSubmit={e=>{e.preventDefault();void execute({action:'MESSAGE',message}).then(ok=>{if(ok){setMessage('');setForm(null);}});}}><AdmissionField label={c('message')} hint={c('messageHint')}><textarea value={message} required maxLength={2000} disabled={mutation.busy} onChange={e=>setMessage(e.target.value)}/></AdmissionField><div className="admission-actions"><button className="admission-button" disabled={mutation.busy}>{c('sendMessage')}</button></div></form>}
        {form==='waitlist'&&allowed('WAITLIST')&&<ReasonForm label={c('waitlistAction')} hint={c('waitlistHint')} busy={mutation.busy} onCancel={()=>setForm(null)} onConfirm={reason=>execute({action:'WAITLIST',reason})}/>}
        {form==='decline'&&allowed('DECLINE')&&<ReasonForm label={c('declineCase')} hint={c('declineHint')} busy={mutation.busy} onCancel={()=>setForm(null)} onConfirm={reason=>execute({action:'DECLINE',reason})}/>}
      </AdmissionPanel>
      <AdmissionPanel title={c('sessions')} subtitle={c('attendanceHint')}>{record.sessions.length?record.sessions.map(session=><SessionRow key={session.id} session={session} record={record} group={group} choices={workspace.sessions} busy={mutation.busy||Boolean(mutation.pending)} execute={execute} onOpen={onOpen}/>):<AdmissionEmpty title={c('noSessions')} hint={c('noSessionsHint')}/>}</AdmissionPanel>
      {(allowed('ASSESS')||allowed('RECOMMEND')||allowed('APPROVE_ADMISSION')||Boolean(record.assessments?.length))&&<AdmissionPanel title={c('review')} subtitle={c('privateHint')}>
        {group?.extraApprovalRequired&&<p className="admission-notice">{c('approvalNeeded')} · {workspace.staff.find(s=>s.id===group.decisionUserId)?.name??c('decisionMaker')}</p>}
        <div className="admission-actions">{(allowed('ASSESS')||allowed('RECOMMEND'))&&<button className="admission-secondary" disabled={mutation.busy||Boolean(mutation.pending)} onClick={()=>setForm(form==='assessment'?null:'assessment')}>{c('assessment')}</button>}{allowed('APPROVE_ADMISSION')&&<button className="admission-button" disabled={mutation.busy||Boolean(mutation.pending)} onClick={()=>setForm(form==='approval'?null:'approval')}>{c('approveAdmission')}</button>}</div>
        {form==='assessment'&&(allowed('ASSESS')||allowed('RECOMMEND'))&&<><AdmissionField label={c('group')}><select value={assessmentGroup} onChange={e=>setAssessmentGroup(Number(e.target.value))}>{workspace.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></AdmissionField><AssessmentEditor busy={mutation.busy} onCancel={()=>setForm(null)} onSave={(note,decision,shared)=>execute({action:decision&&allowed('RECOMMEND')?'RECOMMEND':allowed('ASSESS')?'ASSESS':'RECOMMEND',groupId:assessmentGroup,internalNote:decision?`${c(assessmentDecision[decision])}\n${note}`:note,...(shared?{message:shared}:{})})}/></>}
        {form==='approval'&&allowed('APPROVE_ADMISSION')&&<ReasonForm label={c('approveAdmission')} hint={c('coachBoundary')} busy={mutation.busy} onCancel={()=>setForm(null)} onConfirm={reason=>execute({action:'APPROVE_ADMISSION',groupId:record.groupId,reason})}/>}
        {(record.assessments??[]).map(assessment=><article className="admission-history" key={assessment.id}><strong>{assessment.actorName} · {c(assessment.kind==='APPROVE_ADMISSION'?'approveAdmission':assessment.kind==='RECOMMEND'?'recommendation':'assessment')}</strong><AdmissionDate value={assessment.createdAt} locale={locale}/><p>{workspace.groups.find(g=>g.id===assessment.groupId)?.name??record.groupName}</p><p>{assessment.note}</p></article>)}
      </AdmissionPanel>}
      <AdmissionPanel title={c('currentOffer')} subtitle={c('coachBoundary')}>
        {record.offer?<><div className="admission-pills"><AdmissionPill>{c(offerCopy[record.offer.status])}</AdmissionPill><AdmissionPill>{c('offerVersion')} {record.offer.version}</AdmissionPill></div><h3 className="admission-group-meta">{record.offer.groupName}</h3><AdmissionDate value={record.offer.responseDeadline} locale={locale} label={c('responseDeadline')}/><AdmissionDate value={record.offer.completionDeadline} locale={locale} label={c('completeBy')}/><div className="admission-offer-terms"><TermsSummary terms={record.offer.terms} location={record.offer.location} schedule={record.offer.schedule}/></div>
        {record.offer.status==='PENDING'&&<div className="admission-actions">{allowed('WITHDRAW_OFFER')&&<button className="admission-secondary" disabled={mutation.busy||Boolean(mutation.pending)} onClick={()=>setOfferAction(offerAction==='withdraw'?null:'withdraw')}>{c('withdrawOffer')}</button>}{allowed('EXTEND_OFFER')&&<button className="admission-secondary" disabled={mutation.busy||Boolean(mutation.pending)} onClick={()=>setOfferAction(offerAction==='extend'?null:'extend')}>{c('extendOffer')}</button>}</div>}
        {offerAction==='withdraw'&&allowed('WITHDRAW_OFFER')&&<ReasonForm label={c('withdrawOffer')} busy={mutation.busy} onCancel={()=>setOfferAction(null)} onConfirm={reason=>execute({action:'WITHDRAW_OFFER',offerId:record.offer!.id,offerVersion:record.offer!.version,reason})}/>}
        {offerAction==='extend'&&allowed('EXTEND_OFFER')&&<form onSubmit={e=>{e.preventDefault();void execute({action:'EXTEND_OFFER',offerId:record.offer!.id,offerVersion:record.offer!.version,responseDeadline:utcInput(deadline),reason:extensionReason}).then(ok=>{if(ok)setOfferAction(null);});}}><div className="admission-form-grid"><AdmissionField label={c('responseDeadline')} hint={Intl.DateTimeFormat().resolvedOptions().timeZone}><input required type="datetime-local" value={deadline} disabled={mutation.busy} onChange={e=>setDeadline(e.target.value)}/></AdmissionField><AdmissionField label={c('reason')}><textarea required value={extensionReason} maxLength={2000} disabled={mutation.busy} onChange={e=>setExtensionReason(e.target.value)}/></AdmissionField></div><div className="admission-actions"><button className="admission-button" disabled={mutation.busy}>{c('extendOffer')}</button></div></form>}</>:<AdmissionEmpty title={c('noOffer')} hint={c('offerHint')}/>}
      </AdmissionPanel>
      {record.enrollment&&<AdmissionPanel title={c('placement')} subtitle={c('placementHint')}><div className="admission-pills"><AdmissionPill tone={record.enrollment.status==='ACTIVE'?'good':'neutral'}>{c(record.enrollment.status==='ACTIVE'?'enrolled':'enrollmentCancelled')}</AdmissionPill><AdmissionPill>{record.enrollment.groupName}</AdmissionPill></div><AdmissionDate value={record.enrollment.startDate} locale={locale} label={c('startDate')}/><p className="admission-group-meta">{c('eligibility')}: {c('notGranted')}</p><div className="admission-actions">{record.enrollment.status==='ACTIVE'&&<Link className="admission-secondary" to={record.enrollment.squadId?`/squads/${record.enrollment.squadId}?tab=sessions`:record.enrollment.scheduleDestination}>{c('scheduleLink')}</Link>}<Link className="admission-secondary" to={record.enrollment.squadId&&record.clubId?'/clubs/'+record.clubId+'/squads?squad='+record.enrollment.squadId:record.enrollment.rosterDestination??('/clubs/'+record.clubId+'/workspace?tab=admissions&admissionView=groups&admissionGroup='+record.enrollment.groupId)}>{c('rosterLink')}</Link>{record.requirements.some(r=>r.kind==='EXTERNAL_REGISTRATION')&&<AdmissionLinkButton onClick={()=>onOpen('registration',{person:String(record.playerId)})}>{c('registrationLink')}</AdmissionLinkButton>}</div>
        {allowed('CANCEL_ENROLLMENT')&&<details className="admission-disclosure"><summary>{c('departure')}</summary><p className="admission-group-meta">{c('departureHint')}</p><h3>{c('cancellation')}</h3><p>{record.offer?.terms.cancellation||'—'}</p><ReasonForm label={c('cancelEnrollment')} busy={mutation.busy} onCancel={()=>setForm(null)} onConfirm={reason=>execute({action:'CANCEL_ENROLLMENT',reason})}/></details>}
      </AdmissionPanel>}
    </div><aside className="admission-stack">
      <AdmissionPanel title={c('player')}><dl className="admission-summary"><div><dt>{c('born')}</dt><dd>{record.dateOfBirth}</dd></div><div><dt>{c('group')}</dt><dd>{record.groupName}</dd></div><div><dt>{c('responsible')}</dt><dd>{record.responsible?.name??c('queue')}</dd></div><div><dt>{c('submitted')}</dt><dd><AdmissionDate value={record.submittedAt} locale={locale}/></dd></div>{record.primaryAffiliation&&<div><dt>{c('affiliation')}</dt><dd>{record.primaryAffiliation.clubName}<p className="admission-group-meta">{c('affiliationHint')}</p></dd></div>}</dl></AdmissionPanel>
      {record.siblingConstraint&&<AdmissionPanel title={c('familyConstraint')}><p>{record.siblingConstraint}</p></AdmissionPanel>}
      <AdmissionPanel title={c('prerequisites')}>{record.requirements.length?record.requirements.map(requirement=><RequirementRow key={requirement.id} requirement={requirement} canComplete={allowed('COMPLETE_REQUIREMENT')&&requirement.canComplete===true} busy={mutation.busy||Boolean(mutation.pending)} execute={execute}/>):<AdmissionEmpty title={c('noRequirements')}/>}</AdmissionPanel>
      <AdmissionPanel title={c('history')}>{record.history.length?record.history.map(event=><article className="admission-history" key={event.id}><strong>{event.actorName}</strong><AdmissionDate value={event.createdAt} locale={locale}/><p>{event.message ?? event.action.replaceAll('_',' ')}</p></article>):<p className="admission-group-meta">{c('noHistory')}</p>}</AdmissionPanel>
    </aside></div>
  </div>;
}


