import { act, cleanup, fireEvent, render, renderHook, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { CaseDetail } from './CaseDetail';
import { SessionEditor } from './SessionEditor';
import { InquiryQueue } from './InquiryQueue';
import { useDurableMutation } from './useDurableMutation';
import { useClubAdmissions } from './useClubAdmissions';
import { completeOfferTerms } from './TermsSummary';
import { clubAdmissionEn, clubAdmissionKa } from './copy';
import { utcInput, zonedInput } from './domain';
import type { AdmissionCase, AdmissionWorkspace } from '../types';

const api=vi.hoisted(()=>({command:vi.fn(),inquiry:vi.fn(),request:vi.fn(),workspace:vi.fn()}));
vi.mock('../api',()=>({fetchLifecycleDates:(id:number)=>Promise.resolve({caseId:id,caseVersion:1,reviewDueAt:null,reviewTimezone:'Asia/Tbilisi',reviewSource:'NONE',reviewOverdue:false,reviewOwner:'Admissions queue',departure:null,seasonCaseId:null,seasonGroupName:null,seasonDestination:null,actions:[]}),commandLifecycleDates:vi.fn(),fetchAdmissionCase:vi.fn(),commandAdmission:api.command,commandAdmissionInquiry:api.inquiry,newAdmissionRequestId:api.request,fetchClubAdmissions:api.workspace}));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{resolvedLanguage:'en'}})}));
vi.mock('../../squadCommunication/api',()=>({sessions:vi.fn().mockResolvedValue([])}));

const workspace:AdmissionWorkspace={organizationId:1,organizationName:'FC Dinamo Tbilisi Academy',clubId:1,canConfigure:false,staff:[{id:10,name:'Coach'}],squads:[{id:5,name:'Beginner group'}],groups:[{id:2,version:3,organizationId:1,organizationName:'FC Dinamo Tbilisi Academy',clubId:1,name:'Beginner group',squadId:5,intake:'2026-27',method:'INTRODUCTION',visibility:'PUBLIC',published:true,intakeOpen:true,capacity:20,beginnerWelcome:true,birthYearFrom:2016,birthYearTo:2019,referenceDate:'2026-09-01',gender:'ANY',location:{name:'Academy ground',address:'Tbilisi',latitude:null,longitude:null},schedule:'Tuesday 17:00–18:00',timezone:'Asia/Tbilisi',terms:{feesKnown:true,charges:[],cancellation:'Contact admissions before leaving.',participation:'Emergency contact before attendance.',startDate:'2026-10-12',endDate:null,affiliationEffect:'NONE',requirements:[]},responsibleUserId:10,waitlistEnabled:true,availability:'INTRODUCTION_AVAILABLE',remainingPlaces:1,destination:'/admissions/opportunities/2',canManage:true}],cases:[]};
const base:AdmissionCase={id:30,version:4,playerId:50,playerName:'Synthetic child',dateOfBirth:'2018-05-01',organizationId:1,organizationName:'FC Dinamo Tbilisi Academy',clubId:1,groupId:2,groupName:'Beginner group',intake:'2026-27',method:'INTRODUCTION',stage:'REQUEST_RECEIVED',responsible:{id:10,name:'Coach'},nextAction:{code:'CLUB_REVIEW',owner:'CLUB',label:'Review request',dueAt:null},requirements:[],sessions:[],offer:null,enrollment:null,history:[],actions:['MESSAGE'],primaryAffiliation:{clubId:7,clubName:'Existing club'},previousCaseId:null,submittedAt:'2026-10-04T00:00:00Z',updatedAt:'2026-10-04T00:00:00Z'};
function view(record:AdmissionCase){return render(<MemoryRouter><CaseDetail record={record} workspace={workspace} sessionId="staff-session" onChanged={vi.fn()} onBack={vi.fn()} onOpen={vi.fn()}/></MemoryRouter>);}
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();api.request.mockReturnValue('request-1');});
afterEach(cleanup);

describe('staff admission boundaries',()=>{
  it('opens ordinary attendance for confirmed introductory visitors without requiring enrollment',()=>{
    const session={id:80,version:1,squadSessionId:90,title:'Synthetic visitor session',startsAt:'2026-10-04T10:00:00Z',endsAt:'2026-10-04T11:00:00Z',timezone:'Asia/Tbilisi',location:workspace.groups[0].location,contact:'Coach',cost:'Free',preparation:'Water',responseDeadline:'2026-10-03T10:00:00Z',status:'CONFIRMED' as const,noRegularPlaceGuaranteed:true,emergencyContact:'Guardian phone'};
    const record:AdmissionCase={...base,stage:'INTRODUCTION_ASSESSMENT',sessions:[{...session,capacity:2}],actions:['RECORD_ATTENDANCE']};
    const first=view(record);
    expect(screen.getByRole('button',{name:clubAdmissionEn.recordAttendance})).toBeVisible();
    expect(screen.getByRole('button',{name:clubAdmissionEn.attendanceLink})).toBeVisible();
    first.unmount();view({...record,enrollment:{id:7,groupId:2,groupName:'Beginner group',startDate:'2026-10-04',endDate:null,status:'ACTIVE',matchEligibility:'NOT_GRANTED',squadId:5,scheduleDestination:'/squads/5?tab=sessions'}});
    expect(screen.getByRole('button',{name:clubAdmissionEn.attendanceLink})).toBeVisible();
  });
  it('does not advertise staff admission capability from an incomplete response',async()=>{api.workspace.mockResolvedValue({});const hook=renderHook(()=>useClubAdmissions(1,'staff-session'));await waitFor(()=>expect(hook.result.current.loading).toBe(false));expect(hook.result.current.data).toBeNull();expect(hook.result.current.error).toContain('incomplete');});
  it('retires prior club and account data immediately while the new authority request is pending',async()=>{api.workspace.mockResolvedValueOnce(workspace).mockImplementation(()=>new Promise(()=>{}));const hook=renderHook(({club,session})=>useClubAdmissions(club,session),{initialProps:{club:1,session:'staff-session'}});await waitFor(()=>expect(hook.result.current.data).toEqual(workspace));hook.rerender({club:2,session:'staff-session'});expect(hook.result.current.data).toBeNull();expect(hook.result.current.loading).toBe(true);hook.rerender({club:1,session:'different-account'});expect(hook.result.current.data).toBeNull();expect(hook.result.current.error).toBe('');expect(hook.result.current.loading).toBe(true);});
  it('keeps sporting decisions unavailable without current server authority',()=>{view(base);expect(screen.queryByRole('button',{name:'Offer a regular place'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Record completion'})).not.toBeInTheDocument();expect(screen.getByText('Existing club')).toBeInTheDocument();expect(api.command).not.toHaveBeenCalled();});
  it('sends a versioned named-group offer, without accepting for the guardian',async()=>{api.command.mockResolvedValue({...base,stage:'PLACE_OFFERED',version:5});view({...base,actions:['OFFER']});fireEvent.click(screen.getByRole('button',{name:'Offer a regular place'}));expect(screen.getByText('Tuesday 17:00–18:00')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Send place offer'}));await waitFor(()=>expect(api.command).toHaveBeenCalledTimes(1));expect(api.command.mock.calls[0]).toEqual([30,{action:'OFFER',groupId:2,groupVersion:3,expectedVersion:4,requestId:'request-1'},'staff-session']);});
  it('retains the family message after a stale version rejection',async()=>{api.command.mockRejectedValue({response:{status:409,data:{code:'STALE_VERSION'}}});view(base);fireEvent.click(screen.getByRole('button',{name:'Message to player or guardian'}));const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:'Can Tuesday work for your family?'}});fireEvent.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('These details changed'));expect(input).toHaveValue('Can Tuesday work for your family?');expect(screen.queryByText('Saved. The case now shows the server’s current result.')).not.toBeInTheDocument();});
  it('does not mistake an accepted offer with prerequisites for enrolled placement',()=>{const offer={id:41,version:2,groupId:2,groupName:'Beginner group',terms:workspace.groups[0].terms,location:workspace.groups[0].location,schedule:'Tuesday',status:'ACCEPTED' as const,responseDeadline:'2026-10-11T00:00:00Z',completionDeadline:'2026-10-18T00:00:00Z'};view({...base,stage:'COMPLETING_ENROLLMENT',offer,requirements:[{id:60,kind:'PAYMENT_CONFIRMATION',owner:'CLUB',status:'PENDING',evidence:null}]});expect(screen.getByText('Completing enrollment')).toBeInTheDocument();expect(screen.queryByText('Actual group placement')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Record completion'})).not.toBeInTheDocument();});
  it('requires current permission for the specific prerequisite before recording evidence',async()=>{const requirement={id:60,kind:'PAYMENT_CONFIRMATION' as const,owner:'CLUB' as const,status:'PENDING' as const,evidence:null,canComplete:false};view({...base,actions:['COMPLETE_REQUIREMENT'],requirements:[requirement]});expect(screen.queryByRole('button',{name:'Record completion'})).not.toBeInTheDocument();cleanup();api.command.mockResolvedValue({...base,version:5});view({...base,actions:['COMPLETE_REQUIREMENT'],requirements:[{...requirement,canComplete:true}]});fireEvent.change(screen.getByRole('textbox',{name:'Evidence / confirmation reference'}),{target:{value:'Synthetic finance receipt verified by authorized staff'}});fireEvent.click(screen.getByRole('button',{name:'Record completion'}));await waitFor(()=>expect(api.command).toHaveBeenCalledTimes(1));expect(api.command.mock.calls[0][1]).toMatchObject({action:'COMPLETE_REQUIREMENT',requirementId:60,expectedVersion:4,evidence:'Synthetic finance receipt verified by authorized staff'});});
  it('records a coach recommendation independently of attendance and private family text',async()=>{api.command.mockResolvedValue({...base,version:5});view({...base,actions:['ASSESS','RECOMMEND']});expect(screen.queryByRole('button',{name:'Offer a regular place'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Approve sporting recommendation'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Record assessment'}));fireEvent.change(screen.getByRole('textbox',{name:'Private assessment note'}),{target:{value:'Private football observation'}});fireEvent.change(screen.getByRole('combobox',{name:'Recommendation'}),{target:{value:'offer'}});fireEvent.change(screen.getByRole('textbox',{name:'Shared explanation'}),{target:{value:'The sporting lead will review the next step.'}});fireEvent.click(screen.getAllByRole('button',{name:'Record assessment'}).at(-1)!);await waitFor(()=>expect(api.command).toHaveBeenCalledTimes(1));const body=api.command.mock.calls[0][1];expect(body.action).toBe('RECOMMEND');expect(body.internalNote).toContain('Private football observation');expect(body.message).toBe('The sporting lead will review the next step.');expect(body).not.toHaveProperty('attendance');});
  it('uses the persisted squad ID for the real regular schedule link',()=>{view({...base,stage:'ENROLLED',enrollment:{id:70,groupId:2,groupName:'Beginner group',startDate:'2026-10-12',endDate:null,status:'ACTIVE',matchEligibility:'NOT_GRANTED',scheduleDestination:'/admissions/cases/30',squadId:5}});expect(screen.getByRole('link',{name:'Open regular schedule'})).toHaveAttribute('href','/squads/5?tab=sessions');});
  it('keeps exact linked calendar timestamps despite the minute based display',async()=>{const submit=vi.fn().mockResolvedValue(true);const slot={id:80,squadId:5,title:'Real training occurrence',startsAt:'2099-10-04T13:00:17.123Z',endsAt:'2099-10-04T14:00:23.456Z',location:'Academy ground',revision:2};render(<SessionEditor group={workspace.groups[0]} choices={[slot]} busy={false} onCancel={vi.fn()} onSubmit={submit}/>);fireEvent.change(screen.getByRole('combobox',{name:'Existing training session'}),{target:{value:'80'}});fireEvent.change(screen.getByRole('textbox',{name:'Responsible contact'}),{target:{value:'Synthetic coordinator'}});fireEvent.change(screen.getByRole('textbox',{name:'Session cost and charges'}),{target:{value:'Explicitly free'}});fireEvent.click(screen.getByRole('button',{name:'Send session invitation'}));await waitFor(()=>expect(submit).toHaveBeenCalledTimes(1));expect(submit.mock.calls[0][0]).toMatchObject({squadSessionId:80,startsAt:slot.startsAt,endsAt:slot.endsAt,timezone:'Asia/Tbilisi'});});
  it('routes an inquiry using exact group and inquiry versions without accepting participation',async()=>{const record={id:90,version:3,playerId:50,playerName:'Synthetic inquiry child',organizationId:1,organizationName:'FC Dinamo Tbilisi Academy',status:'OPEN' as const,message:'We are interested but have not selected a group.',caseId:null,actions:['MESSAGE' as const,'ROUTE' as const],history:[],createdAt:'2026-10-04T00:00:00Z',updatedAt:'2026-10-04T00:00:00Z'};const changed=vi.fn();api.inquiry.mockResolvedValue({...record,status:'ROUTED',caseId:30,version:4});render(<InquiryQueue records={[record]} groups={workspace.groups} sessionId="staff-session" onChanged={changed} onOpenCase={vi.fn()} onRefresh={vi.fn()}/>);fireEvent.click(screen.getByText('Synthetic inquiry child').closest('summary')!);fireEvent.change(screen.getByRole('combobox',{name:'Inquiry next step'}),{target:{value:'ROUTE'}});fireEvent.change(screen.getByRole('combobox',{name:'Group'}),{target:{value:'2'}});fireEvent.change(screen.getByRole('textbox',{name:'Shared explanation'}),{target:{value:'This beginner intake is the appropriate next conversation.'}});fireEvent.click(screen.getByRole('button',{name:'Continue with an agreed group'}));await waitFor(()=>expect(api.inquiry).toHaveBeenCalledTimes(1));expect(api.inquiry.mock.calls[0]).toEqual([90,{action:'ROUTE',message:'This beginner intake is the appropriate next conversation.',expectedVersion:3,groupId:2,groupVersion:3,requestId:'request-1'},'staff-session']);expect(changed).toHaveBeenCalledWith(expect.objectContaining({caseId:30,status:'ROUTED'}));expect(api.command).not.toHaveBeenCalled();});
});

describe('interrupted command receipt',()=>{
  type Body={requestId:string;expectedVersion:number;action:string;message:string};
  it('recovers the identical request after reload, even if the visible version advanced',async()=>{const operation=vi.fn().mockRejectedValueOnce(new Error('Response lost')).mockResolvedValueOnce({id:30});const first=renderHook(()=>useDurableMutation('staff:club:30'));await act(async()=>{await first.result.current.send<{id:number},Body>({action:'MESSAGE',message:'Tuesday works',expectedVersion:4},operation);});expect(first.result.current.pending).not.toBeNull();first.unmount();const second=renderHook(()=>useDurableMutation('staff:club:30'));await act(async()=>{await second.result.current.send<{id:number},Body>({action:'MESSAGE',message:'Tuesday works',expectedVersion:5},operation);});expect(operation.mock.calls[1][0]).toEqual(operation.mock.calls[0][0]);expect(api.request).toHaveBeenCalledTimes(1);expect(second.result.current.pending).toBeNull();});
  it('keeps sibling cases and account scopes separate',async()=>{const operation=vi.fn().mockRejectedValue(new Error('Response lost'));const first=renderHook(()=>useDurableMutation('actor-A:club:child-A'));await act(async()=>{await first.result.current.send<unknown,Body>({action:'MESSAGE',message:'A',expectedVersion:1},operation);});const second=renderHook(()=>useDurableMutation('actor-B:club:child-B'));expect(second.result.current.pending).toBeNull();});
  it('requires recovering the interrupted operation before a different action',async()=>{const operation=vi.fn().mockRejectedValueOnce(new Error('Response lost'));const hook=renderHook(()=>useDurableMutation('actor:case'));await act(async()=>{await hook.result.current.send<unknown,Body>({action:'MESSAGE',message:'A',expectedVersion:1},operation);});await act(async()=>{await hook.result.current.send<unknown,Body>({action:'MESSAGE',message:'Changed',expectedVersion:1},operation);});expect(operation).toHaveBeenCalledTimes(1);expect(hook.result.current.error).toContain('response was interrupted');});
  it('does not present a revoked-authority rejection as a successful recovery',async()=>{const operation=vi.fn().mockRejectedValue({response:{status:403,data:{code:'FORBIDDEN'}}});const hook=renderHook(()=>useDurableMutation('revoked:case'));await act(async()=>{await hook.result.current.send<unknown,Body>({action:'MESSAGE',message:'A',expectedVersion:1},operation);});expect(hook.result.current.error).toContain('current responsibilities');expect(hook.result.current.pending).toBeNull();});
});

it('keeps both maintained languages complete',()=>{expect(Object.keys(clubAdmissionKa).sort()).toEqual(Object.keys(clubAdmissionEn).sort());expect(Object.values(clubAdmissionKa).every(Boolean)).toBe(true);});
it('does not permit an offer with unknown fees or essential schedule',()=>{const group=workspace.groups[0];expect(completeOfferTerms({...group.terms,feesKnown:false},group.schedule,group.location)).toBe(false);expect(completeOfferTerms(group.terms,'',group.location)).toBe(false);expect(completeOfferTerms(group.terms,group.schedule,group.location)).toBe(true);});
it('round trips club-local session time independently of browser timezone',()=>{expect(utcInput('2026-10-04T17:00','Asia/Tbilisi')).toBe('2026-10-04T13:00:00.000Z');expect(zonedInput('2026-10-04T13:00:00Z','Asia/Tbilisi')).toBe('2026-10-04T17:00');expect(()=>utcInput('2026-03-08T02:30','America/New_York')).toThrow();});
