import { useState, type FormEvent } from 'react';
import { createAdmissionGroup, updateAdmissionGroup, newAdmissionRequestId } from '../api';
import type { AdmissionWorkspace, GroupInput, Opportunity, RequirementKind } from '../types';
import type { AuthSessionId } from '../../../utils/authStorage';
import { AdmissionField, AdmissionPanel, AdmissionError } from './ui';
import { useClubAdmissionCopy } from './copy';
import { methodCopy, requirementCopy } from './domain';
import { useDurableMutation } from './useDurableMutation';
import { TermsSummary } from './TermsSummary';
import { joiningSetupScope, joiningSetupDraftKey } from './joiningSetupStorage';

export type GroupDraft = Omit<GroupInput,'requestId'>;
type Draft = GroupDraft;
export type GroupEditorContext = { inquiryId: number; inquiryVersion: number; name: string; initial: Partial<Draft> };
type GroupEditorCommand = GroupInput & { setupExpectedVersion?: number; setupRequestId?: string };
function initialGroup(group:Opportunity|null):Draft {
  if(group) return {expectedVersion:group.version,name:group.name,squadId:group.squadId,intake:group.intake,method:group.method,visibility:group.visibility,published:group.published,intakeOpen:group.intakeOpen,capacity:group.capacity,beginnerWelcome:group.beginnerWelcome,birthYearFrom:group.birthYearFrom,birthYearTo:group.birthYearTo,referenceDate:group.referenceDate,gender:group.gender,location:{...group.location},schedule:group.schedule,timezone:group.timezone,terms:{...group.terms,charges:group.terms.charges.map(charge=>({...charge})),requirements:[...group.terms.requirements]},responsibleUserId:group.responsibleUserId,waitlistEnabled:group.waitlistEnabled,extraApprovalRequired:group.extraApprovalRequired??false,decisionUserId:group.decisionUserId??null,city:group.city??'',country:group.country??'',level:group.level??'',positions:group.positions??[],introductionPermission:group.introductionPermission??{required:group.terms.requirements.includes('CURRENT_CLUB_PERMISSION'),reason:''}};
  return {expectedVersion:0,name:'',squadId:null,intake:'',method:'INTRODUCTION',visibility:'PUBLIC',published:false,intakeOpen:true,capacity:0,beginnerWelcome:true,birthYearFrom:0,birthYearTo:0,referenceDate:'',gender:'ANY',location:{name:'',address:'',latitude:null,longitude:null},schedule:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,terms:{feesKnown:false,charges:[],cancellation:'',participation:'',startDate:'',endDate:null,affiliationEffect:'NONE',requirements:[]},responsibleUserId:null,waitlistEnabled:true,extraApprovalRequired:false,decisionUserId:null,city:'',country:'',level:'',positions:[],introductionPermission:{required:false,reason:''}};
}

export function GroupEditor({workspace,group,sessionId,onSaved,onCancel,onRefresh,context,saveOperation,recoveryOnly=false}:{workspace:AdmissionWorkspace;group:Opportunity|null;sessionId:AuthSessionId;onSaved:()=>void;onCancel:()=>void;onRefresh:()=>void;context?:GroupEditorContext;recoveryOnly?:boolean;saveOperation?:(body:GroupInput,setupExpectedVersion?:number,setupRequestId?:string)=>Promise<unknown>}) {
  const {c,locale}=useClubAdmissionCopy();
  const copy=(en:string,ka:string)=>locale.startsWith('ka')?ka:en;
  const draftKey=context?joiningSetupDraftKey(sessionId,workspace.organizationId,context.inquiryId):`gk-joining-setup-draft:${sessionId}:${workspace.organizationId}:group:${group?.id??'new'}`;
  const [draft,setDraft]=useState<Draft>(()=>{if(context){try{const saved=JSON.parse(sessionStorage.getItem(draftKey)??'null') as Partial<Draft>|null;if(saved&&typeof saved==='object')return {...initialGroup(group),...context.initial,...saved,name:context.initial.name||saved.name||'',squadId:context.initial.squadId??null};}catch{/* Keep known facts if storage is unavailable. */}}return {...initialGroup(group),...context?.initial};});
  const [reviews,setReviews]=useState<string[]>([]);
  const reviewItems=[['identity',copy('I reviewed the existing programme, age range and admission method.','განვიხილე არსებული პროგრამა, ასაკი და მიღების გზა.')],['capacity',copy('I checked the available capacity and responsible staff.','შევამოწმე ადგილების რაოდენობა და პასუხისმგებელი თანამშრომლები.')],['terms',copy('I reviewed the actual schedule, charges and participation terms.','განვიხილე რეალური განრიგი, გადასახადები და მონაწილეობის პირობები.')]];
  const [positionsText,setPositionsText]=useState((draft.positions??[]).join(', '));
  const mutation=useDurableMutation(context?joiningSetupScope(sessionId,workspace.organizationId,context.inquiryId):`group:${sessionId}:${workspace.organizationId}:${group?.id??'new'}`,sessionId);
  const updateDraft=(change:(draft:Draft)=>Draft)=>setDraft(value=>{const next=change(value);if(context){try{sessionStorage.setItem(draftKey,JSON.stringify(next));}catch{/* Pending command is still stored before sending. */}}return next;});
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>updateDraft(v=>({...v,[key]:value}));
  const term=<K extends keyof Draft['terms']>(key:K,value:Draft['terms'][K])=>updateDraft(v=>({...v,terms:{...v.terms,[key]:value}}));
  const location=<K extends keyof Draft['location']>(key:K,value:Draft['location'][K])=>updateDraft(v=>({...v,location:{...v.location,[key]:value}}));
  const operation=(body:GroupEditorCommand)=>{const {setupExpectedVersion,setupRequestId,...groupBody}=body;return saveOperation?saveOperation(groupBody,setupExpectedVersion,setupRequestId):group?updateAdmissionGroup(workspace.organizationId,group.id,groupBody,sessionId):createAdmissionGroup(workspace.organizationId,groupBody,sessionId);};
  const saved=()=>{try{sessionStorage.removeItem(draftKey);}catch{/* The confirmed receipt is already cleared. */}onSaved();};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(recoveryOnly||mutation.pending||context&&reviewItems.some(([key])=>!reviews.includes(key)))return;const result=await mutation.send<unknown,GroupEditorCommand>({...draft,positions:positionsText.split(',').map(value=>value.trim()).filter(Boolean),expectedVersion:group?.version??0,...(context?{setupExpectedVersion:context.inquiryVersion,setupRequestId:newAdmissionRequestId()}:{})},operation);if(result)saved();};
  const toggleRequirement=(kind:RequirementKind)=>term('requirements',draft.terms.requirements.includes(kind)?draft.terms.requirements.filter(v=>v!==kind):[...draft.terms.requirements,kind]);
  return <AdmissionPanel title={recoveryOnly?copy('Check the saved joining setup','შენახული გაწევრიანების პირობების შემოწმება'):context?copy('Configure joining for this programme','ამ პროგრამისთვის გაწევრიანების პირობების მომზადება'):c(group?'editGroup':'newGroup')} subtitle={context?context.name:c('leadershipOnly')}>
    {mutation.error && <AdmissionError message={mutation.error} retry={c('refresh')} onRetry={onRefresh}/>}
    {group&&group.version!==draft.expectedVersion&&<details className="admission-notice"><summary>{c('groupVersion')} {group.version} · {c('reviewCurrentGroup')}</summary><p>{group.name} · {c('capacity')}: {group.capacity}<br/>{c('birthFrom')}: {group.birthYearFrom} · {c('birthTo')}: {group.birthYearTo}<br/>{c('referenceDate')}: {group.referenceDate}</p><TermsSummary terms={group.terms} location={group.location} schedule={group.schedule}/></details>}
    {mutation.pending && <div className="admission-notice"><p>{c('uncertain')}</p>{context&&<p>{copy('Check the original saved request before making further changes. The club will confirm its result using your current access.','შემდგომ ცვლილებამდე შეამოწმეთ თავდაპირველად შენახული მოთხოვნა. კლუბი შედეგს თქვენი მიმდინარე წვდომის შესაბამისად დაადასტურებს.')}</p>}<button type="button" className="admission-text-button" disabled={mutation.busy} onClick={()=>void mutation.recover<unknown,GroupEditorCommand>(operation).then(result=>{if(result)saved();})}>{c('retry')}</button></div>}
    {recoveryOnly?<button type="button" className="admission-secondary" disabled={mutation.busy} onClick={onCancel}>{copy('Return to enquiry','კითხვაზე დაბრუნება')}</button>:<form onSubmit={e=>void submit(e)}>
      <fieldset disabled={mutation.busy||Boolean(mutation.pending)} className="admission-form-grid">
        <h3 className="admission-field-wide admission-section-label">{copy('Programme and responsibility','პროგრამა და პასუხისმგებლობა')}</h3>
        <AdmissionField label={c('groupName')}><input required readOnly={Boolean(context?.initial.name)} maxLength={150} value={draft.name} onChange={e=>set('name',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('squad')} hint={group?c('groupIdentityHint'):undefined}><select disabled={Boolean(group||context)} value={draft.squadId??''} onChange={e=>set('squadId',e.target.value?Number(e.target.value):null)}><option value="">{c('noSquad')}</option>{workspace.squads.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></AdmissionField>
        <AdmissionField label={c('intake')} hint={group?c('groupIdentityHint'):undefined}><input required readOnly={Boolean(group)} maxLength={80} value={draft.intake} onChange={e=>set('intake',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('method')} hint={draft.method==='DIRECT'?c('directHint'):undefined}><select value={draft.method} onChange={e=>set('method',e.target.value as Draft['method'])}>{Object.entries(methodCopy).map(([value,key])=><option key={value} value={value}>{c(key)}</option>)}</select></AdmissionField>
        <AdmissionField label={c('responsible')} hint={c('assignmentHint')}><select value={draft.responsibleUserId??''} onChange={e=>set('responsibleUserId',e.target.value?Number(e.target.value):null)}><option value="">{c('queue')}</option>{workspace.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></AdmissionField>
        <AdmissionField label={c('decisionMaker')}><select required={draft.extraApprovalRequired} value={draft.decisionUserId??''} onChange={e=>set('decisionUserId',e.target.value?Number(e.target.value):null)}><option value="">—</option>{workspace.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></AdmissionField>
        <label className="admission-check admission-field-wide"><input type="checkbox" checked={draft.extraApprovalRequired??false} onChange={e=>set('extraApprovalRequired',e.target.checked)}/>{c('approvalSetting')}</label>
        <h3 className="admission-field-wide admission-section-label">{copy('Eligibility and available places','შესაბამისობა და თავისუფალი ადგილები')}</h3>
        <AdmissionField label={c('capacity')} hint={c('regularCapacityHint')}><input type="number" min={0} max={10000} required value={draft.capacity} onChange={e=>set('capacity',Number(e.target.value))}/></AdmissionField>
        <AdmissionField label={c('birthFrom')}><input type="number" min={1900} max={2200} required value={draft.birthYearFrom||''} onChange={e=>set('birthYearFrom',Number(e.target.value))}/></AdmissionField>
        <AdmissionField label={c('birthTo')}><input type="number" min={draft.birthYearFrom||1900} max={2200} required value={draft.birthYearTo||''} onChange={e=>set('birthYearTo',Number(e.target.value))}/></AdmissionField>
        <AdmissionField label={c('referenceDate')}><input type="date" required value={draft.referenceDate} onChange={e=>set('referenceDate',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('gender')}><select value={draft.gender} onChange={e=>set('gender',e.target.value as Draft['gender'])}><option value="ANY">{c('anyGender')}</option><option value="MALE">{c('male')}</option><option value="FEMALE">{c('female')}</option></select></AdmissionField>
        <h3 className="admission-field-wide admission-section-label">{copy('Training and location','ვარჯიში და ადგილმდებარეობა')}</h3>
        <AdmissionField label={c('venue')}><input required value={draft.location.name} maxLength={240} onChange={e=>location('name',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('address')}><input required value={draft.location.address} maxLength={500} onChange={e=>location('address',e.target.value)}/></AdmissionField>
        <details className="admission-field-wide admission-disclosure"><summary>{copy('Optional location and football details','ადგილმდებარეობისა და ფეხბურთის არასავალდებულო მონაცემები')}</summary><div className="admission-form-grid">
        <AdmissionField label={c('city')}><input value={draft.city??''} maxLength={150} onChange={e=>set('city',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('country')}><input value={draft.country??''} maxLength={150} onChange={e=>set('country',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('level')}><input value={draft.level??''} maxLength={150} onChange={e=>set('level',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('positions')} hint={c('positionsHint')}><input value={positionsText} maxLength={500} onChange={e=>{setPositionsText(e.target.value);set('positions',e.target.value.split(',').map(value=>value.trim()).filter(Boolean));}}/></AdmissionField>
        <AdmissionField label={c('latitude')}><input type="number" min={-90} max={90} step="any" value={draft.location.latitude??''} onChange={e=>location('latitude',e.target.value?Number(e.target.value):null)}/></AdmissionField>
        <AdmissionField label={c('longitude')}><input type="number" min={-180} max={180} step="any" value={draft.location.longitude??''} onChange={e=>location('longitude',e.target.value?Number(e.target.value):null)}/></AdmissionField>
        </div></details>
        <AdmissionField label={c('schedule')} wide><textarea required value={draft.schedule} maxLength={2000} onChange={e=>set('schedule',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('timezone')}><input required value={draft.timezone} onChange={e=>set('timezone',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('visibility')}><select value={draft.visibility} onChange={e=>set('visibility',e.target.value as Draft['visibility'])}><option value="PUBLIC">{c('public')}</option><option value="INVITATION_ONLY">{c('inviteOnly')}</option></select></AdmissionField>
        <label className="admission-check"><input type="checkbox" checked={draft.beginnerWelcome} onChange={e=>set('beginnerWelcome',e.target.checked)}/>{c('beginner')}</label>
        <label className="admission-check"><input type="checkbox" checked={draft.waitlistEnabled} onChange={e=>set('waitlistEnabled',e.target.checked)}/>{c('waitlistEnabled')}</label>
        <label className="admission-check"><input type="checkbox" checked={draft.published} onChange={e=>set('published',e.target.checked)}/>{c('published')}</label>
        <label className="admission-check"><input type="checkbox" checked={draft.intakeOpen} onChange={e=>set('intakeOpen',e.target.checked)}/>{c('intakeOpen')}</label>
        <h3 className="admission-field-wide admission-section-label">{copy('Dates and joining terms','თარიღები და გაწევრიანების პირობები')}</h3>
        <AdmissionField label={c('startDate')}><input type="date" value={draft.terms.startDate} required onChange={e=>term('startDate',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('endDate')}><input type="date" value={draft.terms.endDate??''} min={draft.terms.startDate} onChange={e=>term('endDate',e.target.value||null)}/></AdmissionField>
        <AdmissionField label={c('effect')} wide><select value={draft.terms.affiliationEffect} onChange={e=>term('affiliationEffect',e.target.value as Draft['terms']['affiliationEffect'])}><option value="NONE">{c('noChange')}</option><option value="PRIMARY_CHANGE">{c('primaryChange')}</option></select></AdmissionField>
        <AdmissionField label={c('cancellation')} wide><textarea required={draft.published&&draft.terms.feesKnown} value={draft.terms.cancellation} maxLength={4000} onChange={e=>term('cancellation',e.target.value)}/></AdmissionField>
        <AdmissionField label={c('participation')} wide><textarea required={draft.published&&draft.terms.feesKnown} value={draft.terms.participation} maxLength={4000} onChange={e=>term('participation',e.target.value)}/></AdmissionField>
        <div className="admission-field-wide"><label className="admission-check"><input type="checkbox" checked={draft.terms.feesKnown} onChange={e=>term('feesKnown',e.target.checked)}/>{c('feesKnown')}</label><p className="admission-group-meta">{c('feesHint')}</p></div>
        {draft.terms.charges.map((charge,index)=><div className="admission-offer-terms admission-field-wide" key={index}><div className="admission-form-grid">{(['label','amount','currency','frequency'] as const).map(key=><AdmissionField key={key} label={c(key==='label'?'chargeLabel':key)}><input required type={key==='amount'?'number':'text'} min={key==='amount'?0:undefined} step={key==='amount'?'0.01':undefined} value={charge[key]} onChange={e=>term('charges',draft.terms.charges.map((v,i)=>i===index?{...v,[key]:key==='amount'?Number(e.target.value):e.target.value}:v))}/></AdmissionField>)}</div><button type="button" className="admission-text-button" onClick={()=>term('charges',draft.terms.charges.filter((_,i)=>i!==index))}>{c('removeCharge')}</button></div>)}
        <button type="button" className="admission-secondary" onClick={()=>term('charges',[...draft.terms.charges,{label:'',amount:0,currency:'GEL',frequency:''}])}>{c('addCharge')}</button>
        <div className="admission-field-wide"><h3>{copy('Before introductory sessions','გაცნობითი ვარჯიშების წინ')}</h3><label className="admission-check"><input type="checkbox" checked={draft.introductionPermission?.required??false} onChange={e=>set('introductionPermission',{required:e.target.checked,reason:draft.introductionPermission?.reason??''})}/>{copy('Require current-club permission before session confirmation','სესიის დადასტურებამდე მოითხოვეთ მიმდინარე კლუბის ნებართვა')}</label>{draft.introductionPermission?.required&&<AdmissionField label={copy('Why permission is needed','რატომ არის საჭირო ნებართვა')}><textarea required maxLength={2000} value={draft.introductionPermission.reason} onChange={e=>set('introductionPermission',{required:true,reason:e.target.value})}/></AdmissionField>}<p>{copy('The family supplies the reference; authorized host staff review and record actual evidence for each session.','ოჯახი წარმოადგენს მითითებას; უფლებამოსილი მასპინძელი თანამშრომელი განიხილავს და აფიქსირებს მტკიცებულებას თითოეული სესიისთვის.')}</p></div>
        <div className="admission-field-wide"><h3 className="admission-section-label">{c('prerequisites')}</h3><div className="admission-form-grid">{(Object.keys(requirementCopy) as RequirementKind[]).map(kind=><label key={kind} className="admission-check"><input type="checkbox" checked={draft.terms.requirements.includes(kind)} onChange={()=>toggleRequirement(kind)}/>{c(requirementCopy[kind])}</label>)}</div></div>
      </fieldset>
      {context&&<fieldset className="admission-setup-review" disabled={mutation.busy||Boolean(mutation.pending)}><legend>{copy('Review before saving','შენახვამდე განხილვა')}</legend>{reviewItems.map(([key,label])=><label className="admission-check" key={key}><input type="checkbox" required checked={reviews.includes(key)} onChange={event=>setReviews(value=>event.target.checked?[...value,key]:value.filter(item=>item!==key))}/>{label}</label>)}</fieldset>}
      <div className="admission-actions"><button className="admission-button" disabled={mutation.busy||Boolean(mutation.pending)||Boolean(context&&reviewItems.some(([key])=>!reviews.includes(key)))}>{context?copy('Save joining and return to enquiry','პირობების შენახვა და კითხვაზე დაბრუნება'):c(mutation.busy?'saving':'saveGroup')}</button><button type="button" className="admission-secondary" disabled={mutation.busy} onClick={onCancel}>{context?copy('Return to enquiry','კითხვაზე დაბრუნება'):c('cancel')}</button></div>
    </form>}
  </AdmissionPanel>;
}
