import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, Building2, CalendarDays, Compass, Grid2X2, Inbox, List, Loader2, Plus, RefreshCw, Search, Trophy, Users } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../context/AuthContext';
import { fetchMyOrganizations, fetchTournaments } from '../features/tournaments/api';
import {browsePersonalCompetitions} from '../features/competitions/api';
import type { TournamentSummary } from '../features/tournaments/domain';
import { CompetitionPagination } from '../features/competitions/CompetitionPagination';
import { TournamentScopeBadge, TournamentStatusBadge, TournamentVisual } from '../components/tournaments/TournamentPresentation';
import { formatTournamentDateRange, tournamentVisibilityText } from '../components/tournaments/tournamentFormatters';
import { TournamentInbox } from '../features/tournaments/components/TournamentInbox';
import { TournamentDiscovery, TournamentHosts } from '../features/tournaments/components/TournamentDiscovery';
import { extractApiErrorMessage } from '../utils/apiError';
import '../features/tournaments/components/tournament-workspace.css';
import '../features/tournaments/components/tournament-hub.css';

export const BrowseTournamentsPage = ({ embedded = false }: { embedded?: boolean } = {}) => {
    const { user, sessionId } = useAuth();
    const [params] = useSearchParams();
    return <TournamentDirectory embedded={embedded} key={`${user?.id}:${sessionId}:${params.get('view')}`}/>;
};
function TournamentDirectory({ embedded }: { embedded: boolean }) {
    const { isAuthenticated, user } = useAuth(); const { t, i18n } = useTranslation();
    const copy = (en: string, ka: string) => i18n.language.startsWith('ka') ? ka : en;
    const [params, setParams] = useSearchParams(); const requested = params.get('view');
    const view = isAuthenticated && (requested === 'mine' || requested === 'invitations') ? requested : requested === 'discover' || params.has('scope') ? 'discover' : requested === 'hosts' ? 'hosts' : 'overview';
    const [data,setData]=useState<TournamentSummary[]>([]),[pages,setPages]=useState(1),[total,setTotal]=useState(0);
    const bounded=(key:string,fallback:number,max:number)=>{const raw=params.get(key);return raw&&/^\d{1,6}$/.test(raw)&&Number(raw)<=max?Number(raw):fallback;};
    const page=bounded('page',0,100000),size=[6,12,24].includes(bounded('size',12,24))?bounded('size',12,24):12;
    const query=(params.get('q')||'').slice(0,200),scope=['CLUB','SQUAD','PLAYER'].includes(params.get('scope')||'')?params.get('scope')||'':'',status=['PLANNING','ACTIVE','COMPLETED','CANCELLED'].includes(params.get('status')||'')?params.get('status')||'':'';
    const [search,setSearch]=useState(query.trim());
    const filter=(key:string,value:string)=>setParams(previous=>{const next=new URLSearchParams(previous);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.delete('page');return next;},{replace:key==='q'});
    const setPage=(value:number)=>filter('page',String(value)),setSize=(value:number)=>filter('size',String(value)),setQuery=(value:string)=>filter('q',value),setScope=(value:string)=>filter('scope',value),setStatus=(value:string)=>filter('status',value);
    const [settledKey,setSettledKey]=useState(''),[savedError,setError]=useState(''),[attempt,setAttempt]=useState(0),[canCreate,setCanCreate]=useState(false);
    const [mode,setMode]=useState<'list'|'grid'>(()=>{try{return localStorage.getItem('tournament-view-mode')==='grid'?'grid':'list';}catch{return 'list';}});
    useEffect(()=>{const timer=setTimeout(()=>{setSearch(query.trim());},250);return()=>clearTimeout(timer);},[query]);
    useEffect(()=>{let active=true;if(!isAuthenticated)return;fetchMyOrganizations().then(orgs=>{if(active)setCanCreate(orgs.some(org=>org.canCreateTournament===true));}).catch(()=>{if(active)setCanCreate(false);});return()=>{active=false;};},[isAuthenticated,user?.id]);
    const requestKey = JSON.stringify([view,page,size,search,scope,status,attempt,i18n.language]);
    const loading = search!==query.trim()||requestKey !== settledKey, error = loading ? '' : savedError;
    useEffect(()=>{let active=true;if(view==='invitations'||view==='overview'||view==='hosts'||search!==query.trim())return;const request=view==='mine'?browsePersonalCompetitions({page,size,search:search||undefined,scope:scope||undefined,status:status||undefined}):fetchTournaments({page,size,search:search||undefined,scope:scope||undefined,status:status||undefined});request.then(result=>{if(active){setError('');setData(result.content);setTotal(result.totalElements);setPages(result.totalPages);}}).catch(err=>{if(active){setData([]);setError(extractApiErrorMessage(err,t('tournaments.public.browseLoadFailed')));}}).finally(()=>{if(active)setSettledKey(requestKey);});return()=>{active=false;};},[view,page,size,search,query,scope,status,attempt,t,requestKey]);
    useEffect(()=>{try{localStorage.setItem('tournament-view-mode',mode);}catch{/* Optional preference. */}},[mode]);
    const clear=()=>setParams(previous=>{const next=new URLSearchParams(previous);for(const key of ['q','scope','status','page'])next.delete(key);return next;});
    const selectView=(next:string)=>{clear();setParams(previous=>{const value=new URLSearchParams(previous);value.delete('scope');value.delete('kind');value.delete('host');if(next==='overview')value.delete('view');else value.set('view',next);return value;});};
    const managed=new Set(user?.navigationCapabilities?.workspaces.filter(w=>w.id==='tournament.workspace').map(w=>w.context.id)??[]);
    return <div className="tournament-directory tc-directory td-hub">{(!embedded || view==='mine')&&<header className="tc-directory-header"><div>{!embedded&&<p className="tw-eyebrow"><Trophy size={15}/>{t('tournaments.public.competitionHub')}</p>}{embedded ? <h2>{view === 'mine' ? copy('My competitions','ჩემი შეჯიბრებები') : view === 'hosts' ? copy('Competition hosts','მასპინძლები') : copy('Invitations','მოწვევები')}</h2> : <h1>{t('tournaments.public.browseTitle')}</h1>}<p>{copy('Find a competition. Bring your team. Follow every match.','იპოვეთ შეჯიბრება. ჩაერთეთ გუნდით. ადევნეთ თვალი ყველა მატჩს.')}</p></div>{!embedded&&isAuthenticated&&<Link className={canCreate?'tw-primary':'tw-button'} to="/tournaments/setup"><Plus size={16}/>{canCreate?t('tournaments.public.createTournament'):copy('Tournament setup','ტურნირის შექმნა')}</Link>}</header>}
        {!embedded && <nav className="tc-hub-tabs" aria-label={copy('Tournament hub','ტურნირების ცენტრი')}>{[{key:'overview',label:copy('Overview','მიმოხილვა'),icon:Compass},{key:'discover',label:copy('Browse tournaments','ტურნირების ნახვა'),icon:Trophy},{key:'hosts',label:copy('Hosts','მასპინძლები'),icon:Building2},...(isAuthenticated?[{key:'mine',label:copy('My tournaments','ჩემი ტურნირები'),icon:Users},{key:'invitations',label:copy('Invitations','მოწვევები'),icon:Inbox}]:[])].map(tab=><button key={tab.key} aria-pressed={view===tab.key} onClick={()=>selectView(tab.key)}><tab.icon size={17}/>{tab.label}</button>)}</nav>}
        {view==='overview'?<TournamentDiscovery onBrowse={next=>setParams(next?{view:'discover',scope:next}:{view:'discover'})} onHosts={()=>selectView('hosts')} onHost={host=>setParams({view:'hosts',kind:host.kind,host:String(host.id)})}/>:view==='hosts'?<TournamentHosts key={`${params.get('kind')}:${params.get('host')}`} kind={params.get('kind')==='CLUB'||params.get('kind')==='ORGANIZATION'?params.get('kind') as 'CLUB'|'ORGANIZATION':null} hostId={/^[1-9][0-9]*$/.test(params.get('host')||'')&&Number.isSafeInteger(Number(params.get('host')))?Number(params.get('host')):null} onHost={host=>setParams({view:'hosts',kind:host.kind,host:String(host.id)})} onBack={()=>selectView('hosts')}/>:view==='invitations'?<TournamentInbox/>:<div className="tc-directory-frame"><aside className="tc-directory-filters"><section className="tc-panel" aria-label={t('tournaments.public.filters')}><div className="tc-panel-heading"><Search size={17}/><h2>{t('tournaments.public.filters')}</h2><button className="tc-text-button" onClick={clear}>{t('tournaments.public.clearAll')}</button></div>{view==='discover'&&<><label>{t('tournaments.public.searchLabel')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('tournaments.public.searchPlaceholder')}/></label><label>{t('tournaments.public.scopeFilter')}<select value={scope} onChange={e=>{setScope(e.target.value);setPage(0);}}><option value="">{t('tournaments.public.allScopes')}</option>{['CLUB','SQUAD','PLAYER'].map(s=><option key={s} value={s}>{t(`tournaments.public.scope.${s.toLowerCase()}`)}</option>)}</select></label></>}
            <label>{t('tournaments.public.statusFilter')}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">{t('tournaments.public.allStatuses')}</option>{['PLANNING','ACTIVE','COMPLETED','CANCELLED'].map(s=><option key={s} value={s}>{t(`tournaments.public.status.${s.toLowerCase()}`)}</option>)}</select></label></section><section className="tc-directory-help"><Trophy size={23}/><h2>{view==='mine'?copy('Your competition connections','თქვენი შეჯიბრებები'):copy('From entry to final whistle','მონაწილეობიდან საფინალო სასტვენამდე')}</h2><p>{view==='mine'?copy('Events you organize or participate in. Workspace access follows your current tournament appointment.','თქვენი ორგანიზებული ან მონაწილეობით მიმდინარე ღონისძიებები. წვდომა დამოკიდებულია მოქმედ დანიშვნაზე.'):copy('Check the organizer, entry rules, clubs, fixtures and results before you enter.','მონაწილეობამდე შეამოწმეთ ორგანიზატორი, წესები, კლუბები, მატჩები და შედეგები.')}</p>{isAuthenticated&&<Link className="tc-text-button" to="/requests">{copy('Review requests','მოთხოვნების განხილვა')} <ArrowRight size={15}/></Link>}</section></aside>
        <section className="tc-directory-results" aria-labelledby="tournament-results-heading"><div className="tw-toolbar"><div><h2 id="tournament-results-heading">{view==='mine'?copy('My tournaments','ჩემი ტურნირები'):copy('Competitions','შეჯიბრებები')}</h2><p>{loading?copy('Loading competitions…','შეჯიბრებები იტვირთება…'):copy(`${data.length} of ${total} competitions`,`${data.length} / ${total} შეჯიბრება`)}</p></div><div className="tc-display" role="group" aria-label={t('tournaments.public.viewMode')}><button aria-label={t('tournaments.public.listView')} aria-pressed={mode==='list'} onClick={()=>setMode('list')}><List size={17}/></button><button aria-label={t('tournaments.public.gridView')} aria-pressed={mode==='grid'} onClick={()=>setMode('grid')}><Grid2X2 size={17}/></button><button aria-label={copy('Refresh tournaments','ტურნირების განახლება')} disabled={loading} onClick={()=>setAttempt(a=>a+1)}><RefreshCw size={16}/></button></div></div>
            {error?<div className="tw-error" role="alert"><p>{error}</p><button className="tw-button" onClick={()=>setAttempt(a=>a+1)}>{t('tournaments.public.tryAgain')}</button></div>:loading?<div className="tc-empty" role="status"><Loader2 className="animate-spin"/>{copy('Loading tournaments…','ტურნირები იტვირთება…')}</div>:data.length?<><div className={`tc-results tc-results--${mode}`}>{data.map(event=><article className="tc-event" key={event.id}><TournamentVisual name={event.name} imageUrl={event.bannerImageUrl} className="tc-event-art" overlay={false}><span className="tc-event-emblem" aria-hidden="true"><Trophy size={34}/></span></TournamentVisual><div className="tc-event-body"><div className="tc-event-badges"><TournamentStatusBadge status={event.status}/><TournamentScopeBadge scope={event.participantScope}/><small>{tournamentVisibilityText(event.visibility,t)}</small></div><Link to={`/tournaments/${event.id}`}><h3>{event.name}</h3></Link><p>{event.description||t('tournaments.public.noDescription')}</p><div className="tc-event-meta"><span><CalendarDays size={15}/>{formatTournamentDateRange(event.startDate,event.endDate,i18n.language)||t('tournaments.public.datesToBeConfirmed')}</span><span><Users size={15}/>{t('tournaments.public.entryCount',{count:event.entryCount})}</span></div>{event.hostClubName||event.organizerName?<small>{t('tournaments.public.hostedBy',{name:event.hostClubName||event.organizerName})}</small>:null}<div className="tc-event-footer"><Link className="tc-text-button" aria-label={`${copy('View','ნახვა')} ${event.name}`} to={`/tournaments/${event.id}`}>{copy('View competition','შეჯიბრების ნახვა')} <ArrowRight size={15}/></Link>{view==='mine'&&managed.has(event.id)&&<Link className="tw-button" to={`/tournaments/${event.id}/workspace`}>{copy('Workspace','სამუშაო სივრცე')}</Link>}</div></div></article>)}</div><CompetitionPagination page={page} totalPages={pages} pageSize={size} sizes={[12,24]} onPageChange={setPage} onPageSizeChange={setSize}/></>:<div className="tc-empty"><Trophy size={32}/><h3>{t('tournaments.public.noTournamentsFound')}</h3><p>{query||scope||status?t('tournaments.public.emptyFiltered'):view==='mine'?copy('Your organizing and participation connections will appear here.','თქვენი შეჯიბრებები აქ გამოჩნდება.'):t('tournaments.public.emptyDefault')}</p>{(query||scope||status)&&<button className="tw-button" onClick={clear}>{t('tournaments.public.clearAll')}</button>}</div>}
        </section></div>}
    </div>;
}
