import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, Check, Clock3, MapPin, Phone, ShieldCheck, UsersRound, Warehouse } from 'lucide-react';
import { formats, surfaces, type BookingKind, type Venue } from './api';
import { MediaImage } from '../../components/ui/MediaImage';
import { resolveMediaUrl } from '../../utils/resolveMediaUrl';
import { BookingRows } from './VenueBookings';
import { bookingsOnDate, currentStatus, needsDecision, requestOrder, setupChecks, type OwnerView } from './ownerWorkflow';
import { useOwnerBookings } from './useOwnerBookings';
import { bookingDate, money, today } from './utils';

export type OwnerNavigate = (view: OwnerView, step?: number) => void;
export function VenueOwnerHome({ venue, active, navigate, add }: { venue: Venue; active: boolean; navigate: OwnerNavigate; add: (kind: BookingKind) => void }) {
  const date = today(venue.timezone);
  const data = useOwnerBookings(venue.id, venue.timezone, date, 181, active);
  const requests = data.bookings.filter(b => needsDecision(b, data.now)).sort(requestOrder);
  const day = bookingsOnDate(data.bookings, date, venue.timezone).filter(b => currentStatus(b, data.now) === 'CONFIRMED');
  const next = day.filter(b => Date.parse(b.endsAt) > data.now).slice(0, 3);
  const checks = setupChecks(venue), incomplete = checks.filter(c => !c.ready);
  const intake = venue.capabilities?.enabledActivities.includes('VENUE');
  return <div className="venue-owner-home">
    {venue.capabilities?.canConfigureVenue && !venue.promotionBlocked && (!venue.published || incomplete.length > 0) && <section className="venue-owner-launch" aria-label="Prepare your venue"><div><p className="venue-eyebrow">{venue.published ? 'Finish your venue details' : 'Your venue page is a draft'}</p><h2>{incomplete[0]?.title || 'Ready to review your public page'}</h2><p>{incomplete[0]?.detail || 'Your saved details are ready. Preview the page, then publish when you are ready for bookings.'}</p></div><div className="venue-inline"><button className="venue-button venue-button--primary" onClick={() => navigate(incomplete[0]?.view || 'listing', incomplete[0]?.step ?? (incomplete.length ? undefined : 3))}>{incomplete.length ? 'Continue setup' : 'Review & publish'}<ArrowRight size={16}/></button><Link className="venue-button" to={`/stadiums/${venue.id}`}>Preview venue page</Link></div></section>}
    <section className="venue-owner-welcome"><div><p className="venue-eyebrow">Your working day</p><h2>Keep the next game running smoothly.</h2><p>Start with requests, check who is arriving, then record anything agreed by phone.</p></div><button className="venue-button venue-button--primary" disabled={!venue.pitches.some(p => p.active)} onClick={() => add(intake ? 'MANUAL' : 'CLOSURE')}>Add booking or closure<ArrowRight size={17}/></button></section>
    {data.error && <p className="venue-error" role="alert">{data.error} <button className="venue-link" onClick={data.refresh}>Retry</button></p>}
    <div className="venue-owner-metrics">
      <button onClick={() => navigate('requests')}><Clock3/><strong>{data.loading || data.error ? '—' : requests.length}</strong><span>Requests to review</span><small>Across the next 180 days</small></button>
      <button onClick={() => navigate('calendar')}><CalendarDays/><strong>{data.loading || data.error ? '—' : day.filter(b => b.kind !== 'CLOSURE').length}</strong><span>Bookings today</span><small>{day.filter(b => b.kind === 'CLOSURE').length} pitch closures today</small></button>
      <button onClick={() => navigate(venue.capabilities?.canConfigureVenue ? 'pitches' : 'calendar')}><Warehouse/><strong>{venue.pitches.filter(p => p.active).length}</strong><span>Active pitches</span><small>{venue.bookingMode === 'INSTANT' ? 'Instant online confirmation' : 'You confirm online requests'}</small></button>
    </div>
    <section className="venue-owner-pitches" aria-label="Your pitches"><div className="venue-section-heading"><div><p className="venue-eyebrow">At this venue</p><h2>Your pitches</h2><p>Each pitch belongs to this venue and appears on its public page when active.</p></div>{venue.capabilities?.canConfigureVenue && <button className="venue-button" onClick={() => navigate('pitches')}>Manage pitches<ArrowRight size={16}/></button>}</div>{venue.pitches.length ? <div className="venue-owner-pitch-grid">{venue.pitches.map(pitch => <article className="venue-owner-pitch-summary" key={pitch.id}><div className="venue-owner-pitch-photo">{pitch.photoUrl && !venue.promotionBlocked ? <MediaImage src={resolveMediaUrl(pitch.photoUrl)} alt={pitch.name}/> : <Warehouse size={30}/>}</div><div><span className="venue-tag">{pitch.active ? 'Active pitch' : 'Inactive pitch'}</span><h3>{pitch.name}</h3><p>{formats[pitch.format]} · {surfaces[pitch.surface]}</p><strong>{money(pitch.pricePerHour,venue.currency)} / hour</strong>{!venue.promotionBlocked && pitch.active && <Link className="venue-link" to={`/stadiums/${venue.id}#pitch-${pitch.id}`}>{venue.published ? 'View on venue page' : 'Preview on venue page'} →</Link>}</div></article>)}</div> : <div className="venue-panel venue-empty"><Warehouse size={32}/><h3>Your first pitch starts here</h3><p>Add a name, photo and hourly rate so teams can see what they are booking.</p>{venue.capabilities?.canConfigureVenue && <button className="venue-button venue-button--primary" onClick={() => navigate('pitches')}>Add your first pitch</button>}</div>}</section>
    <div className="venue-owner-columns"><section className="venue-panel venue-owner-next"><div className="venue-section-heading"><div><p className="venue-eyebrow">Attention first</p><h2>{requests.length ? 'A team is waiting for you' : 'Your request inbox'}</h2></div><Clock3/></div>
      {data.loading ? <p role="status">Checking upcoming requests…</p> : data.error ? <p>Request information is unavailable until the refresh succeeds.</p> : requests[0] ? <><h3>{requests[0].contactName || 'Booking request'}</h3><p>{requests[0].pitchName} · {bookingDate(requests[0].startsAt, venue.timezone)}</p>{requests[0].expiresAt && <p>Respond before {bookingDate(requests[0].expiresAt, venue.timezone)}.</p>}<button className="venue-button venue-button--primary" onClick={() => navigate('requests')}>Review requests<ArrowRight size={16}/></button></> : <><div className="venue-owner-clear"><Check size={22}/><h3>No requests waiting</h3></div><p>New online requests appear here. Unanswered requests expire and release the time.</p><button className="venue-link" onClick={() => navigate('requests')}>Open request inbox</button></>}
    </section><section className="venue-panel"><div className="venue-section-heading"><div><p className="venue-eyebrow">Coming up today</p><h2>Ready for arrival</h2></div><CalendarDays/></div>
      {data.loading ? <p>Loading today’s bookings…</p> : !next.length ? <p>{data.error ? 'Today’s calendar is unavailable.' : 'No more confirmed entries today. Check the calendar before promising a time.'}</p> : next.map(b => <div className="venue-owner-arrival" key={b.id}><strong>{b.kind === 'CLOSURE' ? 'Pitch closed' : b.contactName || 'Reserved'} · {b.pitchName}</strong><span>{bookingDate(b.startsAt, venue.timezone)}{Date.parse(b.startsAt) <= data.now ? ' · In progress' : ''}</span>{b.contactPhone && b.kind !== 'CLOSURE' && <a href={`tel:${b.contactPhone}`}><Phone size={13}/>{b.contactPhone}</a>}</div>)}
      <button className="venue-link" onClick={() => navigate('calendar')}>Open the calendar →</button>
    </section></div>
    {venue.capabilities?.canConfigureVenue && !venue.promotionBlocked && <section className="venue-owner-setup-nudge"><ShieldCheck size={27}/><div><h3>{incomplete.length ? `${incomplete.length} setup detail${incomplete.length === 1 ? '' : 's'} to check` : venue.published ? 'Keep your venue ready for visitors' : 'Your listing details are ready for review'}</h3><p>{incomplete.length ? incomplete.map(c => c.title).join(' · ') : 'Review existing bookings, arrival information and your team handover before opening online availability.'}</p></div><button className="venue-button" onClick={() => navigate('setup')}>Open setup guide</button></section>}
    <div className="venue-owner-quick-actions"><button disabled={!intake || !venue.pitches.some(p => p.active)} onClick={() => add('ACADEMY')}><UsersRound/><span><strong>Add regular team time</strong><small>Record weekly training already agreed.</small></span><ArrowRight/></button><button disabled={!venue.pitches.some(p => p.active)} onClick={() => add('CLOSURE')}><CalendarDays/><span><strong>Plan maintenance or weather closure</strong><small>Check existing bookings before blocking time.</small></span><ArrowRight/></button></div>
  </div>;
}

export function VenueSetup({ venue, navigate, add }: { venue: Venue; navigate: OwnerNavigate; add: (kind: BookingKind) => void }) {
  const checks = setupChecks(venue), count = checks.filter(c => c.ready).length;
  const [copied, setCopied] = useState('');
  async function copyLink() {
    try { await navigator.clipboard.writeText(`${window.location.origin}/stadiums/${venue.id}`); setCopied('Public page link copied.'); }
    catch { setCopied('Open the public page and copy its address from your browser.'); }
  }
  return <div className="venue-owner-setup">
    <section className="venue-owner-welcome"><div><p className="venue-eyebrow">From first setup to opening day</p><h2>A venue your team can run confidently.</h2><p>Prepare the page, bring the calendar up to date, and walk through the customer journey with the person who handles bookings.</p></div><span className="venue-owner-progress">{count} / {checks.length}<small>listing checks complete</small></span></section>
    <div className="venue-owner-columns"><section className="venue-panel"><p className="venue-eyebrow">01 · Build the essentials</p><h2>Your saved setup</h2><p>These checks reflect saved details. Unsaved edits appear after you save them.</p><div className="venue-owner-checks">{checks.map(c => <button key={c.title} onClick={() => navigate(c.view, c.step)}><span className={c.ready ? 'is-ready' : ''}>{c.ready ? <Check size={18}/> : <span>○</span>}</span><span><strong>{c.title}</strong><small>{c.detail}</small></span><ArrowRight size={17}/></button>)}</div></section>
      <section className="venue-panel"><p className="venue-eyebrow">02 · Bring your calendar with you</p><h2>Start with commitments you already made</h2><p>Bring phone bookings, messages and your old diary together. Include regular teams and unavailable dates for every pitch.</p><div className="venue-owner-task-list"><button className="venue-button" disabled={!venue.pitches.some(p => p.active) || !venue.capabilities?.enabledActivities.includes('VENUE')} onClick={() => add('MANUAL')}>Add an existing booking<ArrowRight size={16}/></button><button className="venue-button" disabled={!venue.pitches.some(p => p.active) || !venue.capabilities?.enabledActivities.includes('VENUE')} onClick={() => add('ACADEMY')}>Add weekly academy time<ArrowRight size={16}/></button><button className="venue-button" disabled={!venue.pitches.some(p => p.active)} onClick={() => add('CLOSURE')}>Block unavailable time<ArrowRight size={16}/></button><button className="venue-link" onClick={() => navigate('calendar')}>Review the full calendar →</button></div><p className="venue-muted">Only you can verify that every offline booking has been entered. An empty calendar does not prove that a pitch is free.</p></section>
      <section className="venue-panel"><p className="venue-eyebrow">03 · Agree the daily handover</p><h2>Who answers, who opens, who updates?</h2><ul className="venue-owner-guidance"><li>Name the person who checks requests and a backup when they are away.</li><li>Make sure the public phone reaches someone who can help teams arrive.</li><li>Agree who checks the pitch and contacts affected customers if weather interrupts play.</li><li>Record every new phone booking here before promising the same time elsewhere.</li></ul>{venue.capabilities?.canConfigureActivities && <Link className="venue-button" to={`/organizations/${venue.id}?settings=1`}>Manage activities & venue team<UsersRound size={16}/></Link>}<p className="venue-muted">Give staff their own venue access. The calendar remains available to permitted operators when intake is paused.</p></section>
      <section className="venue-panel"><p className="venue-eyebrow">04 · Walk through opening day</p><h2>See what your visitors will see</h2><ul className="venue-owner-guidance"><li>Check the entrance pin, photos, opening hours and cancellation notice.</li><li>Preview an available time and the customer details form. Submitting creates a real request; browsing does not.</li><li>Check that a full field and its halves share availability correctly.</li><li>Use owner approval while bringing the calendar under control. Enable instant confirmation once it stays accurate.</li></ul><div className="venue-inline">{!venue.promotionBlocked && <Link className="venue-button" to={`/stadiums/${venue.id}`}>Preview stadium page<MapPin size={16}/></Link>}<button className="venue-button venue-button--primary" onClick={() => navigate('listing', 3)}>{venue.published ? 'Review publication settings' : 'Review & publish'}</button></div>{venue.published && !venue.promotionBlocked && <button className="venue-link" onClick={() => void copyLink()}>Copy public page link</button>}{copied && <p role="status">{copied}</p>}</section>
    </div>
    <section className="venue-panel"><p className="venue-eyebrow">A useful daily rhythm</p><div className="venue-owner-routine"><div><strong>Before opening</strong><p>Review requests, check today’s arrivals and confirm the pitch is playable.</p></div><div><strong>After every phone call</strong><p>Add the booking or closure immediately. Changes to a weekly series are handled one date at a time.</p></div><div><strong>Before leaving</strong><p>Check tomorrow, tell the next operator about exceptions, and confirm who is covering requests.</p></div></div></section>
  </div>;
}

export function VenueRequestInbox({ venue, active }: { venue: Venue; active: boolean }) {
  const data = useOwnerBookings(venue.id, venue.timezone, today(venue.timezone), 181, active);
  const [pitch, setPitch] = useState(0);
  const requests = data.bookings.filter(b => needsDecision(b, data.now)).sort(requestOrder);
  const visible = requests.filter(b => !pitch || b.pitchId === pitch);
  return <section className="venue-owner-inbox"><div className="venue-section-heading"><div><p className="venue-eyebrow">Attention first</p><h2>Booking requests</h2><p>Upcoming requests across the next 180 days, ordered by response deadline. Times in {venue.timezone}.</p></div><button className="venue-button" disabled={data.loading} onClick={data.refresh}>Refresh requests</button></div><div className="venue-owner-inbox-toolbar"><span className="venue-tag">{data.loading || data.error ? 'Checking requests…' : `${requests.length} awaiting your decision`}</span><label className="venue-field"><span className="sr-only">Request pitch</span><select aria-label="Request pitch" value={pitch} onChange={e => setPitch(Number(e.target.value))}><option value={0}>All pitches</option>{venue.pitches.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
    {data.loading ? <p className="venue-empty" role="status">Checking every upcoming request…</p> : data.error ? <p role="alert" className="venue-error">{data.error}</p> : !visible.length ? <div className="venue-panel venue-empty"><Check size={30}/><h3>{requests.length ? 'No requests for this pitch' : 'You’re up to date'}</h3><p>{requests.length ? 'Choose another pitch to review the remaining requests.' : 'New online requests will appear here. Confirmed bookings are in the calendar.'}</p></div> : <BookingRows owner timezone={venue.timezone} bookings={visible} onChange={data.refresh}/>}
  </section>;
}
