import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, ChevronRight, Flag, Search, UserPlus, Users, ShieldCheck } from 'lucide-react';
import type { ClubManagedMember } from '../clubs/domain';
import { clubRoleLabel } from '../clubs/domain';
import type { StaffRole } from './useWorkspaceRoles';
import { StaffAppointmentForm } from './StaffAppointmentForm';
import { get, post, root, label, dateOnly, appointmentStatus, appointmentScope, moduleNames, type Appointment, type Bootstrap, type Choice } from './api';
import { extractApiErrorMessage } from '../../utils/apiError';
import './operations.css';
import './workspace-operations.css';
import './staff-team.css';

export function ClubStaffTeam({boot,members=[],roles,mode='staff',renderAdministration,onChanged,children}:{
  boot:Bootstrap;members?:ClubManagedMember[];roles?:StaffRole[];mode?:'staff'|'invites';renderAdministration?:(member:ClubManagedMember)=>ReactNode;onChanged?:()=>void;children?:ReactNode;
}){
  const [items,setItems]=useState<Appointment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
  const [personId,setPersonId]=useState<number|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('current');
  const [editor,setEditor]=useState<{appointment?:Appointment;person?:Choice}|null>(null),[ending,setEnding]=useState<Appointment|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');void get<Appointment[]>(`${root(boot.clubId)}/appointments`,c.signal).then(rows=>{if(!c.signal.aborted)setItems(rows);}).catch(e=>{if(!c.signal.aborted)setError(extractApiErrorMessage(e,'Could not load the staff team.'));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[boot.clubId,revision]);
  const current=(a:Appointment)=>['Active','Upcoming','Invited'].includes(appointmentStatus(a));
  const people=useMemo(()=>{
    const rows=new Map<number,{id:number;name:string;member?:ClubManagedMember;appointments:Appointment[]}>();
    for(const member of members)rows.set(member.userId,{id:member.userId,name:member.fullName||member.username,member,appointments:[]});
    for(const a of items){if(!rows.has(a.user_id))rows.set(a.user_id,{id:a.user_id,name:a.name??`Staff #${a.user_id}`,appointments:[]});rows.get(a.user_id)!.appointments.push(a);}
    return [...rows.values()].sort((a,b)=>a.name.localeCompare(b.name));
  },[members,items]);
  const selected=people.find(p=>p.id===personId),pending=items.filter(a=>appointmentStatus(a)==='Invited');
  const visible=people.filter(p=>(filter==='all'||p.member||p.appointments.some(current))&&`${p.name} ${p.appointments.map(a=>`${a.title} ${a.specialisations.map(label).join(' ')} ${appointmentScope(a,boot.squads)}`).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const refresh=()=>{setRevision(v=>v+1);onChanged?.();};
  async function end(){if(!ending||busy)return;setBusy(true);setError('');try{await post(`${root(boot.clubId)}/appointments/${ending.id}/transition`,{status:'ENDED',revision:ending.revision,note:ending.status==='INVITED'?'Invitation cancelled by club leadership.':'Appointment ended by club leadership.'});setEnding(null);setNotice('Appointment closed. Its access has ended.');refresh();}catch(e){setError(extractApiErrorMessage(e,'Could not close this appointment.'));}finally{setBusy(false);}}
  if(editor)return <section className="club-ops club-ops-embedded staff-team"><StaffAppointmentForm boot={boot} roles={roles} appointment={editor.appointment} initialPerson={editor.person} onCancel={()=>setEditor(null)} onSaved={()=>{setEditor(null);setNotice('Invitation sent. The person can review it in My responsibilities.');refresh();}}/></section>;
  const appointmentCard=(a:Appointment)=><article className="staff-appointment" key={a.id}><div className="ops-toolbar"><div><span className="ops-badge" data-status={appointmentStatus(a)}>{appointmentStatus(a)==='Invited'?'Awaiting acceptance':appointmentStatus(a)}</span><h3>{a.title}</h3><p>{a.specialisations.map(label).join(' · ')}</p></div>{a.specialisations.includes('REFEREE')?<Flag size={22}/>:<ShieldCheck size={22}/>}</div><dl className="workspace-review-list"><div><dt>Teams</dt><dd>{appointmentScope(a,boot.squads)}</dd></div><div><dt>Engagement</dt><dd>{label(a.engagement)}</dd></div><div><dt>Dates</dt><dd>{dateOnly(a.starts_on)} → {dateOnly(a.ends_on)||'Ongoing'}</dd></div><div><dt>Public profile</dt><dd>{a.published?'Published by staff member':'Not published by staff member'}</dd></div></dl>{a.unavailable_reason&&<p className="staff-access-note">{a.unavailable_reason}</p>}<details><summary>Workspace access · {a.permissions.length} areas</summary><ul className="staff-access-list">{a.permissions.map(p=><li key={p}><span>{moduleNames[p.split(':')[0]]}</span><strong>{p.endsWith(':WRITE')?'View and manage':'View only'}</strong></li>)}</ul>{!a.permissions.length&&<p>No club workspace access on this appointment.</p>}</details>{a.specialisations.includes('REFEREE')&&<p className="staff-access-note">Choose this referee when arranging a friendly. They receive the match invitation in their referee workspace and confirm each fixture.</p>}{boot.leadership&&['ACTIVE','INVITED'].includes(a.status)&&<div className="ops-footer"><button onClick={()=>setEditor({appointment:a})}>Change appointment</button><button onClick={()=>setEnding(a)}>{a.status==='INVITED'?'Cancel invitation':'End appointment'}</button></div>}{ending?.id===a.id&&<div className="staff-access-note" role="group" aria-label="Confirm appointment closure"><strong>{a.status==='INVITED'?'Cancel this invitation?':'End this appointment and its access?'}</strong><p>Other appointments and management memberships remain separate.</p><div className="ops-row"><button disabled={busy} onClick={()=>setEnding(null)}>Keep appointment</button><button disabled={busy} onClick={()=>{void end();}}>Confirm closure</button></div></div>}</article>;
  return <section className="club-ops club-ops-embedded staff-team">
    {selected&&mode==='staff'?<><button className="workspace-record-back" onClick={()=>{setPersonId(null);setEnding(null);}}><ArrowLeft size={16}/>All staff</button><header className="workspace-section-heading"><div><p className="workspace-section-kicker">People / Staff</p><h1>{selected.name}</h1><p>{selected.appointments.filter(current).map(a=>a.title).join(' · ')||selected.member?.publicTitle||'Club management'}</p></div>{boot.leadership&&<button className="workspace-add-button" onClick={()=>setEditor({person:{id:selected.id,name:selected.name}})}><UserPlus size={16}/>Add responsibility</button>}</header></>:<header className="workspace-section-heading"><div><p className="workspace-section-kicker">Club workspace / People</p><h1>{mode==='invites'?'Invitations':'Your staff team'}</h1><p>{mode==='invites'?'Invite a person with a clear role, teams and access. Follow their response here.':'Coaches, specialists, referees and club leadership, together.'}</p></div>{boot.leadership&&<button className="workspace-add-button" onClick={()=>setEditor({})}><UserPlus size={16}/>Invite staff</button>}</header>}
    {notice&&<p role="status" className="staff-access-note">{notice}</p>}{error&&<p role="alert" className="ops-alert">{error} <button onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}
    {loading?<p role="status">Loading staff…</p>:selected&&mode==='staff'?<div className="staff-person-detail">{selected.appointments.map(appointmentCard)}{!selected.appointments.length&&<div className="staff-access-note"><strong>No specialist appointment yet</strong><p>Add a football responsibility to define their squad and specialist tools.</p></div>}{selected.member&&renderAdministration&&<details className="staff-administration"><summary>Management access & public profile · {clubRoleLabel(selected.member.role)}</summary><p>These are administrative permissions. Coaching specialisations, travel duties and refereeing belong in appointments above.</p>{renderAdministration(selected.member)}</details>}</div>:mode==='invites'?<><h2 className="staff-subheading">Awaiting acceptance <span>{pending.length}</span></h2><p className="ops-muted">Recipients accept in My responsibilities. A sent invitation does not yet grant access.</p>{pending.length?<div className="staff-invitation-list">{pending.map(a=><section key={a.id}><h2>{a.name}</h2>{appointmentCard(a)}</section>)}</div>:<div className="staff-empty"><UserPlus size={26}/><h2>No outstanding staff invitations</h2><p>Invite a coach, referee or specialist to join your team.</p></div>}{children}</>:<>
      <div className="staff-roster-tools"><label><Search size={17}/><input aria-label="Find staff" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, responsibility or squad"/></label><label className="staff-roster-filter"><span>Show</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="current">Current team & invitations</option><option value="all">Including past appointments</option></select></label><span>{visible.length} people</span></div>
      <div className="staff-roster" role="list" aria-label="Club staff">{visible.map(p=>{const appointments=p.appointments.filter(current);return <button type="button" role="listitem" key={p.id} className="staff-person-row" onClick={()=>{setPersonId(p.id);setNotice('');}}><span className="staff-avatar" data-referee={appointments.some(a=>a.specialisations.includes('REFEREE'))}>{appointments.some(a=>a.specialisations.includes('REFEREE'))?<Flag size={21}/>:p.name.split(' ').filter(Boolean).slice(0,2).map(n=>n[0]).join('')}</span><span className="staff-person-name"><strong>{p.name}</strong><small>{appointments.map(a=>a.title).join(' · ')||p.member?.publicTitle||(p.member?clubRoleLabel(p.member.role):'Past staff member')}</small></span><span className="staff-person-scope">{appointments.length?[...new Set(appointments.map(a=>appointmentScope(a,boot.squads)))].join(' · '):p.member?'Club management':'Appointment history'}</span><span className="ops-badge">{appointments.some(a=>a.status==='INVITED')?'Invitation pending':p.member||appointments.some(a=>appointmentStatus(a)==='Active')?'Active':appointments.length?'Upcoming':'Past'}</span><ChevronRight size={16}/></button>;})}</div>{!visible.length&&<div className="staff-empty"><Users size={26}/><h2>{query?'No staff match this search':'Your team starts here'}</h2><p>{query?'Try a name, responsibility or squad.':'Invite a person and choose their football responsibilities.'}</p></div>}
    </>}
  </section>;
}
