import { useState, type FormEvent } from 'react';
import { extractApiErrorMessage } from '../../utils/apiError';
import { label, moduleNames, moduleGroups, put, root, type Bootstrap } from './api';

export function OperationsSettings({boot,onSaved}:{boot:Bootstrap;onSaved:()=>Promise<void>}) {
  const [settings,setSettings]=useState(boot.settings),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');setSaved(false);try{await put(`${root(boot.clubId)}/settings`,{setting:settings.setting,playingLevel:settings.playing_level,currency:settings.currency||null,countryCode:settings.country_code||null,timezone:settings.timezone||null,legalName:settings.legal_name||null,registrationReference:settings.registration_reference||null,enabledModules:settings.enabled_modules,revision:settings.revision});await onSaved();setSaved(true);}catch(e){setError(extractApiErrorMessage(e,'Could not save club settings.'));}finally{setBusy(false);}};
  return <form className="club-setup" onSubmit={e=>{void submit(e);}}><header className="role-page-heading"><h1>Club setup</h1><p>Club details and the tools your organisation uses.</p></header>{error&&<p className="ops-alert" role="alert">{error}</p>}{saved&&<p role="status">Settings saved.</p>}<fieldset disabled={busy}><section className="club-setup-section"><h2>About the club</h2><div className="ops-form-grid">
    <label>Organisation setting<select value={settings.setting} onChange={e=>setSettings(s=>({...s,setting:e.target.value}))}>{['UNSPECIFIED','SCHOOL','COMMUNITY','INDEPENDENT_ACADEMY','CLUB_ACADEMY','CLUB','OTHER'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
    <label>Playing level<select value={settings.playing_level} onChange={e=>setSettings(s=>({...s,playing_level:e.target.value}))}>{['UNSPECIFIED','RECREATIONAL','AMATEUR','SEMI_PROFESSIONAL','PROFESSIONAL','MIXED'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  </div></section><details className="club-setup-section"><summary>Location & currency</summary><div className="ops-form-grid">
    <label>Default currency<input maxLength={3} pattern="[A-Z]{3}" value={settings.currency??''} placeholder="Optional, e.g. EUR" onChange={e=>setSettings(s=>({...s,currency:e.target.value.toUpperCase()}))}/></label>
    <label>Operating country<input maxLength={2} pattern="[A-Z]{2}" value={settings.country_code??''} placeholder="Optional, e.g. EE" onChange={e=>setSettings(s=>({...s,country_code:e.target.value.toUpperCase()}))}/></label>
    <label>Timezone<input value={settings.timezone??''} placeholder="Optional, e.g. Europe/Tallinn" onChange={e=>setSettings(s=>({...s,timezone:e.target.value}))}/></label>
  </div></details><details className="club-setup-section"><summary>Company details</summary><div className="ops-form-grid">
    <label>Registered legal name<input maxLength={255} value={settings.legal_name??''} placeholder="Leave blank until confirmed" onChange={e=>setSettings(s=>({...s,legal_name:e.target.value}))}/></label>
    <label>Company registration reference<input maxLength={160} value={settings.registration_reference??''} placeholder="Optional" onChange={e=>setSettings(s=>({...s,registration_reference:e.target.value}))}/></label>
  </div></details><details className="club-setup-section"><summary>Available club tools <span>{settings.enabled_modules.length} enabled</span></summary><p className="ops-muted">Roles choose each person’s daily view. Turning a tool off here affects the whole club: new and edited records stop, while authorised history remains available.</p><div className="club-tool-groups">{moduleGroups.map(g=><section key={g.name}><h3>{g.name}</h3>{g.ids.map(m=><label className="club-tool-toggle" key={m}><span>{moduleNames[m]}</span><input type="checkbox" checked={settings.enabled_modules.includes(m)} onChange={e=>setSettings(s=>({...s,enabled_modules:e.target.checked?[...s.enabled_modules,m]:s.enabled_modules.filter(v=>v!==m)}))}/></label>)}</section>)}</div></details><div className="ops-footer"><button className="ops-primary">{busy?'Saving…':'Save club setup'}</button></div></fieldset></form>;
}
