import { AppointmentSummary } from './AppointmentSummary';
import { EmptyState } from '../../components/ui/EmptyState';
import { CalendarCheck2, ClipboardCheck, MailOpen, UsersRound } from 'lucide-react';
import { StaffScopePicker, type StaffScopeSelection } from './StaffScopePicker';
import { scopePayload } from './api';
import { appointmentScope } from './api';
import { useEffect, useRef, useState } from 'react';
import { useClubEditorClose } from './useClubEditorClose';
import { Link } from 'react-router-dom';
import { type RolesWorkspace, rolesRoot } from './useWorkspaceRoles';
import { get, post, root, moduleNames, label, type Choice, type OperationRecord } from './api';
import { extractApiErrorMessage } from '../../utils/apiError';
import type { WorkspaceTab } from '../../components/workspace/types';
import { operationTabs } from './workspaceNavigation';
import './workspace-roles.css';

export function RoleDay({data,club,onTab,enabledModules}:{data:RolesWorkspace;club:number;onTab:(tab:WorkspaceTab)=>void;enabledModules?:string[]}) {
 const [actions,setActions]=useState<OperationRecord[]>([]),[error,setError]=useState('');
 const view=data.current;
 useEffect(()=>{const c=new AbortController();if(view.modules.length)void get<OperationRecord[]>(`${rolesRoot(club)}/records?view=${encodeURIComponent(view.id)}&module=HOME`,c.signal).then(v=>{if(!c.signal.aborted)setActions(v);}).catch(()=>{if(!c.signal.aborted)setError('Could not load outstanding actions.');});return()=>c.abort();},[club,view]);
 const training=data.current.modules.some(m=>['ATTENDANCE','DEVELOPMENT'].includes(m));
 const modules=operationTabs.filter(t=>data.current.modules.includes(t.module)&&(!enabledModules||enabledModules.includes(t.module))&&!['STAFF','CREDENTIALS','SPECIALISTS'].includes(t.module));
 return <section className="role-day"><header className="role-page-heading"><h1>Your day</h1><p>{data.current.label} · {data.current.clubWide?'Whole club':data.squads.map(s=>s.name).join(', ')||'No squad assigned'}</p></header>
 <div className="role-day-columns"><section><h2>{training?'Coming up':'Needs attention'}</h2>{training?(data.sessions.length?data.sessions.slice(0,8).map(s=><div className="role-agenda-row" key={s.id}><time>{new Date(s.starts_at).toLocaleDateString(undefined,{day:'numeric',month:'short'})}<small>{new Date(s.starts_at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</small></time><div><strong>{s.title}</strong><p>{s.squad_name}</p></div></div>):<EmptyState compact icon={CalendarCheck2} title="No training sessions in the next two weeks." description="Upcoming sessions for your assigned squads will appear here, with the time and team together."/>):actions.length?actions.slice(0,8).map(r=><div className="role-agenda-row" key={r.id}><div><strong>{r.title}</strong><p>{label(r.status)}{r.attentionDate?` · ${r.attentionDate}`:''}</p></div></div>):!error&&<EmptyState compact icon={ClipboardCheck} title="No outstanding actions for this role." description="Decisions and deadlines for your approved responsibilities will appear here when they need attention."/>}{error&&<p role="alert">{error}</p>}{data.current.modules.length>0&&<button type="button" className="role-text-button" onClick={()=>onTab('actions')}>View outstanding actions{actions.length?` (${actions.length})`:''} →</button>}</section>
 <section><h2>Your tools</h2><div className="role-tool-list">{modules.map(t=><button type="button" key={t.id} onClick={()=>onTab(t.id)}><t.icon size={17}/><span>{t.label}</span><span aria-hidden>→</span></button>)}</div>{!modules.length&&<p className="role-muted">Request a staff role to start using the club workspace.</p>}<button type="button" className="role-text-button" onClick={()=>onTab('my-role')}>Your roles & requests →</button></section></div></section>;
}
export function RolePeople({data,squads=false,onTab}:{data:RolesWorkspace;squads?:boolean;onTab:(tab:WorkspaceTab)=>void}) {
 const [query,setQuery]=useState(''),[squad,setSquad]=useState('');
 const people=data.people.filter(p=>(!squad||String(p.squad_id)===squad)&&p.name.toLowerCase().includes(query.toLowerCase()));
 return <section><header className="role-page-heading"><h1>{squads?'Your squads':'Your players'}</h1><p>{data.current.label} · {data.current.clubWide?'Whole club':'Assigned squads'}</p></header>{squads?<div className="role-squad-list">{data.squads.map(s=><article key={s.id}><h2>{s.name}</h2><p>{s.player_count} players</p><button type="button" onClick={()=>onTab('my-people')}>View players →</button></article>)}{!data.squads.length&&<EmptyState icon={UsersRound} title="No squads assigned to this role yet." description="Club leadership assigns squads to your responsibility. Once assigned, you can open their players and shared work here."/>}</div>:<><div className="role-filters"><input aria-label="Find a player" placeholder="Find a player…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter by squad" value={squad} onChange={e=>setSquad(e.target.value)}><option value="">All assigned squads</option>{data.squads.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="role-people-list">{people.map(p=><div key={`${p.id}-${p.squad_id}`}><Link to={`/profile/${p.id}`}>{p.name}</Link><span>{p.squad_name}</span></div>)}</div>{!people.length&&<EmptyState icon={UsersRound} title="No players match this view." description="Try another name or squad. This view includes only players shared with your current responsibility." action={{label:"Clear filters",onClick:()=>{setQuery('');setSquad('');}}}/>}</>}</section>;
}

export function WorkspaceRolesPanel({club,data,admin=false,onChanged}:{club:number;data:RolesWorkspace;admin?:boolean;onChanged:()=>void}) {
 const [role,setRole]=useState(data.catalog[0]?.key??''),[scope,setScope]=useState<StaffScopeSelection>({clubWide:false,squadIds:[]}),[replace,setReplace]=useState(''),[note,setNote]=useState('');
 const [query,setQuery]=useState(''),[matches,setMatches]=useState<Choice[]>([]),[person,setPerson]=useState(''),[ends,setEnds]=useState('');
 const [mode,setMode]=useState<'list'|'request'|'assign'>('list'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [decision,setDecision]=useState<{id:number;revision:number;status:string}|null>(null),[reviewNote,setReviewNote]=useState('');
 const draft=JSON.stringify({role,scope,replace,note,query,person,ends}),initial=useRef(draft);
 const {requestClose,confirmation}=useClubEditorClose(mode!=='list'&&draft!==initial.current,busy,()=>{setMode('list');setRole(data.catalog[0]?.key??'');setScope({clubWide:false,squadIds:[]});setReplace('');setNote('');setQuery('');setMatches([]);setPerson('');setEnds('');});
 const pending=data.requests.find(r=>r.user_id===data.actorId&&r.status==='PENDING');
 const selected=data.catalog.find(r=>r.key===role);
 const run=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await work();setMode('list');setDecision(null);onChanged();}catch(e){setError(extractApiErrorMessage(e,'Could not update this role.'));}finally{setBusy(false);}};
 const submit=()=>{if(!scope.clubWide&&!scope.squadIds.length)throw new Error("Select at least one team or choose whole-club responsibility.");const original=data.views.find(v=>String(v.appointmentId)===replace);return mode==='assign'?post(`${rolesRoot(club)}/assignments`,{userId:Number(person),roleKey:role,...scopePayload(scope),startsOn:new Date().toISOString().slice(0,10),endsOn:ends||null}):post(`${rolesRoot(club)}/requests`,{roleKey:role,...scopePayload(scope),replaceAppointmentId:original?.appointmentId??null,replaceRevision:original?.revision??null,note:note||null});};
 const requests=admin?data.requests:data.requests.filter(r=>r.user_id===data.actorId);
 return <section className="role-management"><header className="role-page-heading"><div><h1>{admin?'Staff roles':'Your roles'}</h1><p>{admin?'Assign responsibilities and review staff requests.':'Choose your staff specialisation and ask your club to approve changes to your responsibilities.'}</p></div>{mode==='list'&&(admin?<button type="button" className="role-primary" onClick={()=>setMode('assign')}>Assign a role</button>:<button type="button" className="role-primary" disabled={Boolean(pending)} onClick={()=>setMode('request')}>Request a role change</button>)}</header>
 {error&&<p role="alert" className="ops-alert">{error}</p>}
 {mode!=='list'?<form className="role-request-form" onSubmit={e=>{e.preventDefault();void run(submit);}}><fieldset disabled={busy}><button type="button" className="role-text-button" onClick={requestClose}>← Back to roles</button><h2>{mode==='assign'?'Assign a staff role':'Request a role change'}</h2>
 {mode==='assign'&&<><div className="role-filters"><label>Find a person<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or username"/></label><button type="button" disabled={query.trim().length<2} onClick={()=>{setError('');void get<Choice[]>(`${root(club)}/staff-candidates?q=${encodeURIComponent(query)}`).then(setMatches).catch(e=>setError(extractApiErrorMessage(e,'Search failed.')));}}>Search</button></div><label>Person<select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose a person</option>{matches.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>}
 {mode==='request'&&data.views.some(v=>v.appointmentId)&&<label>Change an existing role<select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">Add another responsibility</option>{data.views.filter(v=>v.appointmentId).map(v=><option key={v.id} value={v.appointmentId!}>{v.label}</option>)}</select></label>}
 <label>Role<select required value={role} onChange={e=>setRole(e.target.value)}>{data.catalog.map(r=><option key={r.key} value={r.key}>{r.title}</option>)}</select></label><p className="role-muted">{selected?.description}</p>
 <StaffScopePicker squads={data.requestSquads} value={scope} onChange={setScope} disabled={busy}/>
 {mode==='assign'?<label>End date (optional)<input type="date" min={new Date().toISOString().slice(0,10)} value={ends} onChange={e=>setEnds(e.target.value)}/></label>:<label>Message to your admin<textarea maxLength={1000} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="What will you be helping with?"/></label>}
 <div className="role-access-preview"><h3>Access included</h3>{selected?.permissions.map(p=><p key={p}><span>{moduleNames[p.split(':')[0]]}</span><span>{p.endsWith(':WRITE')?'Read & manage':'Read'}</span></p>)}</div>
 <p className="role-muted">{mode==='assign'?'The staff member accepts before access starts. This creates a volunteer appointment; employment and custom permissions can be set in Appointments & duties.':'Sending this request confirms you accept the responsibilities shown. Access changes only after a club admin approves. Existing roles stay active while you wait.'}</p><button type="submit" className="role-primary">{busy?'Saving…':mode==='assign'?'Send role invitation':'Send for approval'}</button></fieldset></form>:<>
 {!admin&&<><div className="role-approved-list">{data.views.filter(v=>v.id!=='member').map(v=><article key={v.id}><strong>{v.label}</strong><p>{v.clubWide?'Whole club':data.requestSquads.filter(s=>v.squadIds.includes(s.id)).map(s=>s.name).join(', ')}</p><span className="role-muted">{v.appointmentId?'Active appointment':v.id==='club'?'Club leadership':'Recorded squad assignment'}</span></article>)}</div>{data.invitations.map(a=><AppointmentSummary key={a.id} appointment={a} squads={data.requestSquads}><Link className="appointment-summary__primary" to={`/club-operations?appointmentId=${a.id}`}>Review &amp; accept role</Link><button className="appointment-summary__quiet" disabled={busy} onClick={()=>void run(()=>post(`${root(club)}/appointments/${a.id}/transition`,{status:'DECLINED',revision:a.revision}))}>Decline</button></AppointmentSummary>)}</>}
 <h2>{admin?'Role requests':'Your requests'}</h2>{!requests.length&&<EmptyState compact icon={MailOpen} title={admin?'No role requests to review.':'No requests yet.'} description={admin?'Staff requests for additional responsibilities will appear here for your approval.':'When you request another responsibility, follow its review here. Your current access stays available.'}/>}
 {requests.map(r=><article className="role-review-row" key={r.id}><div><h3>{data.catalog.find(c=>c.key===r.role_key)?.title??label(r.role_key)}</h3><p>{admin?`${r.name} · `:''}{appointmentScope({squad_id:r.squad_id??null,...r},data.requestSquads)} · {label(r.effective_status??r.status)}</p>{r.replace_appointment_id&&<p>Replaces an existing appointment after approval.</p>}{r.unavailable_reason&&<p>{r.unavailable_reason}</p>}{r.note&&<p>{r.note}</p>}{r.review_note&&<p>Admin reply: {r.review_note}</p>}<details><summary>Requested access</summary>{r.permissions.map(p=><p key={p}>{moduleNames[p.split(':')[0]]} · {p.endsWith(':WRITE')?'Read & manage':'Read'}</p>)}</details></div>{r.status==='PENDING'&&<div>{admin&&r.user_id!==data.actorId&&r.effective_status!=='UNAVAILABLE'&&<><button disabled={busy} onClick={()=>{setReviewNote('');setDecision({id:r.id,revision:r.revision,status:'APPROVED'});}}>Review & approve</button><button disabled={busy} onClick={()=>{setReviewNote('');setDecision({id:r.id,revision:r.revision,status:'DECLINED'});}}>Decline</button></>}{r.user_id===data.actorId&&<button disabled={busy} onClick={()=>void run(()=>post(`${rolesRoot(club)}/requests/${r.id}`,{status:'WITHDRAWN',revision:r.revision}))}>Withdraw request</button>}</div>}</article>)}
 {decision&&<form className="role-decision" onSubmit={e=>{e.preventDefault();void run(()=>post(`${rolesRoot(club)}/requests/${decision.id}`,{status:decision.status,revision:decision.revision,note:reviewNote||null}));}}><h2>{decision.status==='APPROVED'?'Approve this role change?':'Decline this request?'}</h2><p>{decision.status==='APPROVED'?'The requested permissions and squad scope will take effect immediately. A replaced appointment will end.':'Their current access will stay unchanged.'}</p><label>Reply (optional)<textarea value={reviewNote} maxLength={1000} onChange={e=>setReviewNote(e.target.value)}/></label><div><button type="button" disabled={busy} onClick={()=>setDecision(null)}>Go back</button><button disabled={busy} className="role-primary">{decision.status==='APPROVED'?'Confirm approval':'Confirm decline'}</button></div></form>}
 </>}{confirmation}</section>;
}
