const en = {
    browse: 'Tournaments', eyebrow: 'Tournament setup', title: 'Create a tournament',
    intro: 'Start with the essentials. Add participants and build your bracket in the workspace.',
    stepsLabel: 'Tournament creation steps', basics: 'Basics', details: 'Details', review: 'Review',
    basicsTitle: 'Give your tournament a starting point', basicsHint: 'Choose who is organizing, when you play, and who can join.',
    name: 'Tournament name', namePlaceholder: 'e.g. Tbilisi Community Cup', organizer: 'Organizer',
    organizerHint: 'A company, healthcare provider, sponsor, or sports organization can run a tournament. A club is optional.',
    createOrganization: 'Create organization', noOrganizerTitle: 'Start with your organization',
    noOrganizer: 'You do not manage an organization with tournament creation access yet. Create one to continue; your tournament details will be kept.',
    starts: 'Starts', ends: 'Ends', participants: 'Who is competing?', clubs: 'Clubs', squads: 'Squads', players: 'Individual players',
    participantsHint: 'You will add the participants after creating the tournament.',
    detailsTitle: 'Add helpful details', optional: 'Optional', detailsHint: 'Add what you know now, or continue to review.',
    description: 'About the tournament', descriptionPlaceholder: 'What is the tournament about? Who is it for?',
    rules: 'Rules', rulesPlaceholder: 'Match length, team size, eligibility, and how ties are decided.',
    registration: 'Registration window', registrationHint: 'Leave these blank if you do not need a timed registration window.',
    registrationOpens: 'Registration opens', registrationCloses: 'Registration closes',
    hostClub: 'Host club', noHostClub: 'No host club', hostHint: 'Attach an eligible club if one is hosting. Your organization can run the tournament on its own.',
    reviewTitle: 'Ready to create?', reviewHint: 'Check the details and choose who can see your tournament.',
    visibility: 'Visibility', private: 'Private', public: 'Public', unlisted: 'Unlisted · link only',
    privateHint: 'Only people with access can see it. Choose Edit tournament to make it public before starting.',
    publicHint: 'Anyone can find your tournament and view its bracket, participants, and results.',
    unlistedHint: 'Anyone with the link can view it. It stays out of public tournament discovery.',
    readDetails: 'Read description and rules', nextTitle: 'Next: participants and bracket',
    nextHint: 'Your workspace opens after creation. Add clubs, arrange matches, and keep results up to date.',
    previewLabel: 'Tournament summary', previewTitle: 'Your tournament', previewName: 'Tournament name', previewOrganizer: 'Choose an organizer',
    previewHint: 'Prepare privately, then choose Edit tournament to set public visibility before starting.',
    notSet: 'Not set yet', footerHint: 'You can return to any step before creating.', back: 'Back', continue: 'Continue', reviewAction: 'Review tournament',
    create: 'Create tournament', creating: 'Creating…', loading: 'Loading your organizations…', loadingHostClubs: 'Loading host clubs…',
    organizationsError: 'Failed to load organizations.', hostClubsError: 'Failed to load host clubs. You can continue without a host club.',
    retryOrganizations: 'Retry organizations', retryHostClubs: 'Retry host clubs', createError: 'Failed to create the tournament. Your details have been kept.',
    organizerRequired: 'Choose an organization that can create tournaments.', nameRequired: 'Enter a tournament name.',
    startRequired: 'Choose when the tournament starts.', endRequired: 'Choose when the tournament ends.',
    futureStart: 'Choose a start date in the future.', futureEnd: 'Choose an end date in the future.',
    dateOrder: 'The tournament must end on or after it starts.', registrationOrder: 'Registration must close on or after it opens.',
    registrationBeforeStart: 'Registration must close by the tournament start.', hostRequired: 'Choose an available host club or continue without one.',
};

const ka: typeof en = {
    browse: 'ტურნირები', eyebrow: 'ტურნირის შექმნა', title: 'შექმენი ტურნირი',
    intro: 'დაიწყე ძირითადი ინფორმაციით. მონაწილეებს დაამატებ და ბადეს სამუშაო სივრცეში ააწყობ.',
    stepsLabel: 'ტურნირის შექმნის ნაბიჯები', basics: 'ძირითადი', details: 'დეტალები', review: 'გადახედვა',
    basicsTitle: 'შეავსე ძირითადი ინფორმაცია', basicsHint: 'აირჩიე ორგანიზატორი, თარიღები და მონაწილეთა ტიპი.',
    name: 'ტურნირის სახელი', namePlaceholder: 'მაგ. თბილისის სათემო თასი', organizer: 'ორგანიზატორი',
    organizerHint: 'ტურნირის ორგანიზება შეუძლია კომპანიას, სამედიცინო დაწესებულებას, სპონსორს ან სპორტულ ორგანიზაციას. კლუბი აუცილებელი არ არის.',
    createOrganization: 'ორგანიზაციის შექმნა', noOrganizerTitle: 'დაიწყე შენი ორგანიზაციით',
    noOrganizer: 'ჯერ არ მართავ ორგანიზაციას, რომელსაც ტურნირის შექმნის უფლება აქვს. შექმენი ორგანიზაცია გასაგრძელებლად; ტურნირის შევსებული დეტალები შენარჩუნდება.',
    starts: 'დაწყება', ends: 'დასრულება', participants: 'ვინ მონაწილეობს?', clubs: 'კლუბები', squads: 'შემადგენლობები', players: 'ინდივიდუალური მოთამაშეები',
    participantsHint: 'მონაწილეებს ტურნირის შექმნის შემდეგ დაამატებ.',
    detailsTitle: 'დაამატე სასარგებლო დეტალები', optional: 'არასავალდებულო', detailsHint: 'შეავსე რაც იცი, ან გადადი გადახედვაზე.',
    description: 'ტურნირის შესახებ', descriptionPlaceholder: 'რას ემსახურება ტურნირი და ვისთვის არის განკუთვნილი?',
    rules: 'წესები', rulesPlaceholder: 'მატჩის ხანგრძლივობა, გუნდის ზომა, მონაწილეობის პირობები და ფრის გადაწყვეტის წესი.',
    registration: 'რეგისტრაციის პერიოდი', registrationHint: 'დატოვე ცარიელი, თუ რეგისტრაციის დროის შეზღუდვა არ გჭირდება.',
    registrationOpens: 'რეგისტრაციის გახსნა', registrationCloses: 'რეგისტრაციის დახურვა',
    hostClub: 'მასპინძელი კლუბი', noHostClub: 'მასპინძელი კლუბის გარეშე', hostHint: 'თუ ტურნირს კლუბი მასპინძლობს, აირჩიე ხელმისაწვდომი კლუბი. ორგანიზაციას ტურნირის ჩატარება დამოუკიდებლადაც შეუძლია.',
    reviewTitle: 'მზად ხარ შესაქმნელად?', reviewHint: 'გადაამოწმე დეტალები და აირჩიე, ვინ ნახავს ტურნირს.',
    visibility: 'ხილვადობა', private: 'პირადი', public: 'საჯარო', unlisted: 'მხოლოდ ბმულით',
    privateHint: 'ტურნირს მხოლოდ წვდომის მქონე პირები ნახავენ. დაწყებამდე აირჩიე ტურნირის რედაქტირება და საჯარო გახადე.',
    publicHint: 'ყველას შეეძლება ტურნირის პოვნა და ბადის, მონაწილეებისა და შედეგების ნახვა.',
    unlistedHint: 'ტურნირს ბმულის მქონე ნებისმიერი ადამიანი ნახავს. ის საჯარო ძიებაში არ გამოჩნდება.',
    readDetails: 'აღწერისა და წესების წაკითხვა', nextTitle: 'შემდეგ: მონაწილეები და ბადე',
    nextHint: 'შექმნის შემდეგ გაიხსნება სამუშაო სივრცე. დაამატე კლუბები, დაალაგე მატჩები და განაახლე შედეგები.',
    previewLabel: 'ტურნირის შეჯამება', previewTitle: 'შენი ტურნირი', previewName: 'ტურნირის სახელი', previewOrganizer: 'აირჩიე ორგანიზატორი',
    previewHint: 'მომზადებისას ტურნირი პირადი დატოვე, დაწყებამდე კი ტურნირის რედაქტირებიდან ხილვადობა აირჩიე.',
    notSet: 'ჯერ არ არის მითითებული', footerHint: 'შექმნამდე ნებისმიერ ნაბიჯს შეგიძლია დაუბრუნდე.', back: 'უკან', continue: 'გაგრძელება', reviewAction: 'ტურნირის გადახედვა',
    create: 'ტურნირის შექმნა', creating: 'იქმნება…', loading: 'ორგანიზაციები იტვირთება…', loadingHostClubs: 'მასპინძელი კლუბები იტვირთება…',
    organizationsError: 'ორგანიზაციების ჩატვირთვა ვერ მოხერხდა.', hostClubsError: 'მასპინძელი კლუბები ვერ ჩაიტვირთა. შეგიძლია მასპინძელი კლუბის გარეშე გააგრძელო.',
    retryOrganizations: 'ორგანიზაციების ხელახლა ჩატვირთვა', retryHostClubs: 'კლუბების ხელახლა ჩატვირთვა', createError: 'ტურნირი ვერ შეიქმნა. შევსებული დეტალები შენარჩუნებულია.',
    organizerRequired: 'აირჩიე ორგანიზაცია, რომელსაც ტურნირის შექმნის უფლება აქვს.', nameRequired: 'შეიყვანე ტურნირის სახელი.',
    startRequired: 'აირჩიე ტურნირის დაწყების დრო.', endRequired: 'აირჩიე ტურნირის დასრულების დრო.',
    futureStart: 'აირჩიე დაწყების თარიღი მომავალში.', futureEnd: 'აირჩიე დასრულების თარიღი მომავალში.',
    dateOrder: 'ტურნირი დაწყებამდე ვერ დასრულდება.', registrationOrder: 'რეგისტრაცია გახსნამდე ვერ დაიხურება.',
    registrationBeforeStart: 'რეგისტრაცია ტურნირის დაწყებამდე ან დაწყებისას უნდა დაიხუროს.', hostRequired: 'აირჩიე ხელმისაწვდომი მასპინძელი კლუბი ან გააგრძელე მის გარეშე.',
};

export const tournamentSetupCopy = (language: string) => language.startsWith('ka') ? ka : en;

