import { useJourneyCopy } from '../squadCommunication/journeyCopy';
import { EmptyState } from '../../components/ui/EmptyState';
import { ChevronDown, HeartHandshake } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiClient, type AuthSessionRequestConfig } from '../../api/axiosConfig';
import { useAuth } from '../../context/AuthContext';
import { isCurrentAuthSession } from '../../utils/authStorage';
import { extractApiErrorMessage } from '../../utils/apiError';
import './family-relationships.css';
import { IdentityActivationForm } from './IdentityActivationForm';

type Guardian = { id: number; guardianId: number; name: string; provenance: string; canRevoke: boolean; self: boolean };
type Club = { id: number; clubId: number; name: string; status: string; consent: string };
type Child = { childId: number; name: string; birthYear: number; registered: boolean; activationEligible?: boolean; guardians: Guardian[]; clubs: Club[]; codes: { id: number; expiresAt: string }[]; squads?: { id: number; name: string }[]; history?: { action: string; createdAt: string; clubName?: string }[] };
type Invitation = { id: number; kind: string; status: string; sent: boolean; childName: string; otherName: string; canRespond: boolean; canCancel: boolean; expiresAt: string };
type ConsentRequest = { id: number; childName: string; clubName: string; expiresAt: string; status: string; canRespond: boolean };
type Family = { children: Child[]; invitations: Invitation[]; consentRequests: ConsentRequest[]; consentHistory?: { action: string; createdAt: string; clubName?: string }[]; ended: { id: number; reason: string; activationUserId?: number }[] };


export function FamilyRelationships({ revision = 0, onChanged, compact = false, revealChildId }: { revision?: number; onChanged: () => void; compact?: boolean; revealChildId?: number }) {
    const copy = useJourneyCopy();
    const label = (value: string) => copy(({ STAFF_PLAYING_DEPARTURE: 'Club ended playing enrollment', CLUB_DISSOLVED: 'Club dissolved' } as Record<string, string>)[value] ?? value.toLowerCase().replaceAll('_', ' '), ({ ACTIVE: 'აქტიური', PENDING: 'მოლოდინში', CONFIRMED: 'დადასტურებული', DECLINED: 'უარყოფილი', EXPIRED: 'ვადაგასული', REVOKED: 'გაუქმებული', CANCELLED: 'გაუქმებული', ACCEPTED: 'მიღებული', NEEDED: 'საჭიროა', TRIALIST: 'საცდელ პერიოდში', NOT_REQUIRED: 'არ არის საჭირო', STAFF_PLAYING_DEPARTURE: 'კლუბში მონაწილეობა დასრულდა', CLUB_DISSOLVED: 'კლუბი დაიშალა', PARENT_PROFILE_CREATED: 'ბავშვის პროფილი შეიქმნა', GUARDIAN_INVITED: 'მეურვე მოწვეულია', GUARDIAN_ADDED: 'მეურვე დაემატა', GUARDIAN_REVOKED: 'მეურვეობა გაუქმდა', GUARDIAN_TRANSFERRED: 'მეურვეობა გადაეცა', CONSENT_GRANTED: 'თანხმობა გაცემულია', CONSENT_WITHDRAWN: 'თანხმობა გაუქმდა', ENROLLMENT_CODE_CREATED: 'ჩარიცხვის კოდი შეიქმნა', CLUB_ENROLLED: 'კლუბში ჩაირიცხა', CLUB_CONSENT_CONFIRMED: 'კლუბის თანხმობა დადასტურდა', CLUB_CONSENT_DECLINED: 'კლუბის თანხმობა უარყოფილია', ENROLLMENT_REQUESTED: 'ჩარიცხვა მოთხოვნილია', INVITED_ADDITIONAL: 'დამატებითი მეურვე მოწვეულია', INVITED_TRANSFER: 'მეურვეობის გადაცემა მოთხოვნილია', INVITATION_CANCELLED: 'მოწვევა გაუქმდა', TRANSFERRED: 'პასუხისმგებლობა გადაეცა', CONSENT_PENDING: 'თანხმობის მოლოდინში', ALREADY_USED: 'უკვე გამოყენებულია' } as Record<string, string>)[value] ?? value.toLowerCase().replaceAll('_', ' '));
    const [expanded, setExpanded] = useState<boolean | null>(revealChildId ? true : null);
    const revealed = useRef(false);
    const newChildSummary = useRef<HTMLElement>(null);
    const { sessionId, refreshNavigationCapabilities } = useAuth();
    const [data, setData] = useState<Family | null>(null);
    const [error, setError] = useState('');
    const [notice, setNotice] = useState('');
    const [loading, setLoading] = useState(true);
    const [busy, setBusy] = useState(false);
    const [tick, setTick] = useState(0);
    const [form, setForm] = useState<{ child: number; email: string; kind: string; requestId: string } | null>(null);
    const [confirm, setConfirm] = useState<{ path: string; message: string; body?: unknown } | null>(null);
    const saving = useRef(false);
    const confirmation = useRef<HTMLDivElement>(null);
    useEffect(() => {
        if (revealChildId && data?.children.some(child => child.childId === revealChildId) && !revealed.current) {
            revealed.current = true;
            newChildSummary.current?.focus();
        }
    }, [data, revealChildId]);
    useEffect(() => { if (confirm) confirmation.current?.focus(); }, [confirm]);
    useEffect(() => {
        const abort = new AbortController();
        setLoading(true);setError('');
        const config: AuthSessionRequestConfig = { signal: abort.signal, _authSessionId: sessionId };
        void apiClient.get<Family>('/family', config).then(result => {
            if (!abort.signal.aborted && isCurrentAuthSession(sessionId)) setData(result.data);
        }).catch(e => { if (!abort.signal.aborted && isCurrentAuthSession(sessionId)) { setData(null); setError(extractApiErrorMessage(e, copy("Family connections could not load. Please try again.", "ოჯახური კავშირები ვერ ჩაიტვირთა. სცადეთ ხელახლა."))); } })
            .finally(() => { if (!abort.signal.aborted && isCurrentAuthSession(sessionId)) setLoading(false); });
        return () => abort.abort();
    }, [sessionId, revision, tick]);
    useEffect(() => {
        const refresh = () => { if (document.visibilityState === 'visible') { setTick(v => v + 1); } };
        document.addEventListener('visibilitychange', refresh);
        return () => document.removeEventListener('visibilitychange', refresh);
    }, []);
    const run = async (path: string, body?: unknown) => {
        if (saving.current) return;
        saving.current = true;setBusy(true);setError('');setNotice('');
        try {
            const config: AuthSessionRequestConfig = { _authSessionId: sessionId };
            await apiClient.post(path, body ?? {}, config);
            if (!isCurrentAuthSession(sessionId)) return;
            setConfirm(null);setForm(null);setNotice(copy("Your change is recorded. Current family and club access has been refreshed.", "ცვლილება შენახულია. ოჯახისა და კლუბის წვდომა განახლდა."));
            setTick(v => v + 1);onChanged();
            await refreshNavigationCapabilities().catch(() => setNotice(copy("Your change is recorded. Refresh the page to update navigation.", "ცვლილება შენახულია. ნავიგაციისთვის განაახლეთ გვერდი.")));
        } catch (e) { if (isCurrentAuthSession(sessionId)) setError(extractApiErrorMessage(e, copy("The change could not be saved. Please try again.", "ცვლილება ვერ შეინახა. სცადეთ ხელახლა."))); }
        finally { saving.current = false;setBusy(false); }
    };
    const pending = (data?.consentRequests.filter(r => r.canRespond).length ?? 0) + (data?.invitations.filter(i => i.canRespond).length ?? 0);
    const open = !compact || (expanded ?? (pending > 0 || data?.children.length === 0));
    return <section className={`family-connections parent-panel${compact ? ' family-connections-compact' : ''}`} aria-label={copy("Family connections", "ოჯახური კავშირები")}>
        {compact && <button type="button" className="family-connection-toggle" aria-expanded={open} aria-controls="family-connection-content" onClick={() => setExpanded(!open)}><HeartHandshake size={20}/><span><strong>{copy("Family connections", "ოჯახური კავშირები")}</strong><small>{pending ? copy(`${pending} ${pending === 1 ? 'request needs' : 'requests need'} your review`, `${pending} მოთხოვნა განსახილველია`) : copy("Guardians, club consent & account connections", "მეურვეები, კლუბის თანხმობა და ანგარიშები")}</small></span>{pending > 0 && <b>{pending}</b>}<ChevronDown size={18}/></button>}
        {compact && error && <p role="alert" className="family-error">{error}</p>}
        <div id="family-connection-content" hidden={!open}>
        <div className="family-heading"><div><h2>{copy("Family connections", "ოჯახური კავშირები")}</h2><p>{copy("Your family link stays with your child when they leave or change clubs. Each club needs separate participation consent.", "ოჯახური კავშირი რჩება კლუბის დატოვების ან შეცვლისას. თითოეულ კლუბს მონაწილეობის ცალკე თანხმობა სჭირდება.")}</p></div><button type="button" className="parent-button" disabled={loading || busy} onClick={() => setTick(v => v + 1)}>{copy("Refresh connections", "კავშირების განახლება")}</button></div>
        {!compact && error && <p role="alert" className="family-error">{error}</p>}
        {notice && <p role="status" className="family-notice">{notice}</p>}
        {loading && !data && <p role="status">{copy("Loading family connections…", "ოჯახური კავშირები იტვირთება…")}</p>}
        {confirm && <div className="family-confirm" ref={confirmation} tabIndex={-1} role="group" aria-label={copy("Confirm family change", "ოჯახური ცვლილების დადასტურება")}><p>{confirm.message}</p><div className="family-actions"><button className="parent-button" type="button" disabled={busy} onClick={() => void run(confirm.path, confirm.body)}>{copy("Confirm change", "ცვლილების დადასტურება")}</button><button className="parent-button" type="button" disabled={busy} onClick={() => setConfirm(null)}>{copy("Keep current arrangement", "მიმდინარე მდგომარეობის შენარჩუნება")}</button></div></div>}
        {data && <>
            {data.consentRequests.length > 0 && <div className="family-requests"><h3>{copy("Club consent invitations", "კლუბის თანხმობის მოწვევები")}</h3>{data.consentRequests.map(request => <article key={request.id}><strong>{request.childName} · {request.clubName}</strong>{request.canRespond ? <><p>{copy("The club nominated your verified account as guardian. Accept only if you have parental responsibility and agree to this child’s participation with this club.", "კლუბმა თქვენი დადასტურებული ანგარიში მეურვედ დაასახელა. მიიღეთ მხოლოდ თუ გაქვთ მშობლის პასუხისმგებლობა და ეთანხმებით ბავშვის ამ კლუბში მონაწილეობას.")}</p><p className="parent-muted">{copy("Expires ", "ვადა ")}{new Date(request.expiresAt).toLocaleDateString()}</p><div className="family-actions"><button type="button" className="parent-button parent-button-primary" disabled={busy} onClick={() => setConfirm({ path: `/family/consents/${request.id}`, body: { accept: true }, message: copy("Confirm your guardian responsibility and consent to participation with this club. This records the club nomination and your acceptance; it does not certify legal documents.", "დაადასტურეთ მეურვის პასუხისმგებლობა და ამ კლუბში მონაწილეობაზე თანხმობა. ფიქსირდება კლუბის მოწვევა და თქვენი პასუხი; ეს იურიდიული საბუთების შემოწმებას არ ნიშნავს.") })}>{copy("Review and accept", "განხილვა და მიღება")}</button><button type="button" className="parent-button" disabled={busy} onClick={() => void run(`/family/consents/${request.id}`, { accept: false })}>{copy("Decline", "უარყოფა")}</button></div></> : <p>{copy("This invitation is unavailable or expired. Ask the club to send a new consent invitation.", "მოწვევა მიუწვდომელია ან ვადა გაუვიდა. სთხოვეთ კლუბს ახალი მოწვევის გაგზავნა.")}</p>}</article>)}</div>}
            {data.invitations.length > 0 && <details className="family-history" open={data.invitations.some(i => i.canRespond)}><summary>{copy("Guardian invitations · ", "მეურვის მოწვევები · ")}{data.invitations.filter(i => i.status === 'PENDING').length} {copy('pending', 'მოლოდინში')}</summary>{data.invitations.map(invitation => <article key={invitation.id}><strong>{invitation.childName}</strong><p>{invitation.sent ? copy("To", "ვის") : copy("From", "ვისგან")} {invitation.otherName} · {invitation.kind === 'TRANSFER' ? copy("Transfer guardian responsibility", "მეურვის პასუხისმგებლობის გადაცემა") : copy("Additional guardian", "დამატებითი მეურვე")} · {label(invitation.status)}</p>{invitation.canRespond && <><p>{copy("Accept only if you are responsible for this child.", "მიიღეთ მხოლოდ თუ ამ ბავშვზე პასუხისმგებელი ხართ.")} {invitation.kind === 'TRANSFER' && copy("Acceptance ends the inviting guardian’s access. Club consent they granted must be reviewed again.", "მიღებისას სრულდება მომწვევი მეურვის წვდომა. მის მიერ გაცემული კლუბის თანხმობა ხელახლა უნდა განიხილოთ.")}</p><div className="family-actions"><button className="parent-button parent-button-primary" type="button" disabled={busy} onClick={() => setConfirm({ path: `/family/invitations/${invitation.id}/respond`, body: { accept: true }, message: copy("Confirm that you accept responsibility for this child and this family invitation.", "დაადასტურეთ ამ ბავშვზე პასუხისმგებლობისა და ოჯახური მოწვევის მიღება.") })}>{copy("Accept invitation", "მოწვევის მიღება")}</button><button className="parent-button" type="button" disabled={busy} onClick={() => void run(`/family/invitations/${invitation.id}/respond`, { accept: false })}>{copy("Decline invitation", "მოწვევის უარყოფა")}</button></div></>}{invitation.canCancel && <button className="parent-button" type="button" disabled={busy} onClick={() => void run(`/family/invitations/${invitation.id}/cancel`)}>{copy("Cancel invitation", "მოწვევის გაუქმება")}</button>}</article>)}</details>}
            {data.children.length === 0 && <EmptyState icon={HeartHandshake} title={copy("No current family connections", "აქტიური ოჯახური კავშირები არ არის")} description={copy("Ask your child’s club for a consent invitation, or ask their current guardian to invite your verified adult account. Review the invitation here to establish your family connection.", "სთხოვეთ ბავშვის კლუბს თანხმობის მოწვევა ან მოქმედ მეურვეს თქვენი დადასტურებული სრულწლოვანი ანგარიშის მოწვევა. ოჯახის დასაკავშირებლად განიხილეთ მოწვევა აქ.")}/>}
            {data.children.map(child => <details className="family-child" key={child.childId} open={child.clubs.length === 0 || child.childId === revealChildId}><summary ref={child.childId === revealChildId ? newChildSummary : undefined}><strong>{child.name}</strong><span>{copy("Born ", "დაბადების წელი ")}{child.birthYear} · {child.clubs.length ? copy(`${child.clubs.length} current club connection${child.clubs.length === 1 ? '' : 's'}`, `${child.clubs.length} აქტიური კლუბის კავშირი`) : copy("No current club", "ამჟამად კლუბის გარეშე")}</span></summary>
                {child.activationEligible && <IdentityActivationForm childId={child.childId} onChanged={() => { setTick(v => v + 1); onChanged(); }} />}
                {!!child.squads?.length && <nav className="family-actions" aria-label={copy(`${child.name} squads`, `${child.name} — გუნდები`)}>{child.squads.map(squad => <Link className="parent-button" key={squad.id} to={`/squads/${squad.id}`}>{squad.name} · {copy('Schedule and messages', 'განრიგი და შეტყობინებები')}</Link>)}</nav>}
                <h3>{copy("Guardians", "მეურვეები")}</h3><p className="parent-muted">{copy("These connections record parent-declared responsibility, an accepted club nomination or a guardian invitation. They are not legal-document verification. Guardian access ends when the child turns 18.", "ეს კავშირები ასახავს მშობლის მიერ გაცხადებულ პასუხისმგებლობას, მიღებულ კლუბის ან მეურვის მოწვევას. ისინი იურიდიული საბუთების შემოწმებას არ ნიშნავს. მეურვის წვდომა სრულდება ბავშვის 18 წლის ასაკში.")}</p>
                <ul className="family-guardian-list">{child.guardians.map(guardian => <li key={guardian.id}><div><strong>{guardian.name}{guardian.self ? copy(" (you)", " (თქვენ)") : ''}</strong><small>{guardian.provenance === 'PARENT_CREATED' ? copy("Parent-declared responsibility", "მშობლის მიერ გაცხადებული პასუხისმგებლობა") : guardian.provenance === 'GUARDIAN_INVITATION' ? copy("Invited by a guardian", "მეურვის მოწვევით") : guardian.provenance === 'GUARDIAN_TRANSFER' ? copy("Accepted a guardian transfer", "მეურვეობის გადაცემა მიღებულია") : copy("Club nomination and guardian acceptance", "კლუბის მოწვევა და მეურვის თანხმობა")}</small></div>{guardian.canRevoke && <button type="button" className="parent-button" disabled={busy} onClick={() => setConfirm({ path: `/family/children/${child.childId}/guardians/${guardian.id}/revoke`, message: copy(`${guardian.self ? 'End your guardian access' : `Revoke the guardian access you nominated for ${guardian.name}`}? Consent granted through this connection will end, and pending invitations and enrollment codes from it will be cancelled. Other guardians keep their own family links.`, `${guardian.self ? 'დასრულდეს თქვენი მეურვის წვდომა' : `გაუქმდეს თქვენ მიერ მინიჭებული მეურვის წვდომა: ${guardian.name}`}? ამ კავშირით გაცემული თანხმობა დასრულდება; მოლოდინში მყოფი მოწვევები და ჩარიცხვის კოდები გაუქმდება. სხვა მეურვეები საკუთარ კავშირებს ინარჩუნებენ.`) })}>{guardian.self ? copy("End my access", "ჩემი წვდომის დასრულება") : copy("Revoke access", "წვდომის გაუქმება")}</button>}</li>)}</ul>
                <div className="family-actions"><button type="button" className="parent-button" disabled={busy} onClick={() => setForm({ child: child.childId, email: '', kind: 'ADDITIONAL', requestId: crypto.randomUUID() })}>{copy("Invite another guardian", "სხვა მეურვის მოწვევა")}</button><button type="button" className="parent-button" disabled={busy} onClick={() => setForm({ child: child.childId, email: '', kind: 'TRANSFER', requestId: crypto.randomUUID() })}>{copy("Transfer my responsibility", "ჩემი პასუხისმგებლობის გადაცემა")}</button></div>
                {form?.child === child.childId && <form className="family-invite-form" onSubmit={e => { e.preventDefault();void run(`/family/children/${child.childId}/invitations`, { email: form.email, kind: form.kind, requestId: form.requestId }); }}><h4>{form.kind === 'TRANSFER' ? copy("Transfer your responsibility", "თქვენი პასუხისმგებლობის გადაცემა") : copy("Invite an additional guardian", "დამატებითი მეურვის მოწვევა")}</h4><p>{copy("The recipient needs their own verified adult account and must accept within seven days.", "მიმღებს საკუთარი დადასტურებული სრულწლოვანი ანგარიში სჭირდება და მოწვევა შვიდ დღეში უნდა მიიღოს.")} {form.kind === 'TRANSFER' ? copy("Your access stays active until they accept; then it ends and club consent needs review.", "თქვენი წვდომა მიღებამდე რჩება. შემდეგ სრულდება და კლუბის თანხმობა გადახედვას საჭიროებს.") : copy("Your own family connection stays active.", "თქვენი ოჯახური კავშირი აქტიური რჩება.")}</p><label>{copy("Guardian’s account email", "მეურვის ანგარიშის ელფოსტა")}<input type="email" required maxLength={255} value={form.email} onChange={e => setForm({ ...form, email: e.target.value, requestId: crypto.randomUUID() })} disabled={busy} autoComplete="off" /></label><div className="family-actions"><button className="parent-button parent-button-primary" disabled={busy}>{copy("Send invitation", "მოწვევის გაგზავნა")}</button><button className="parent-button" type="button" disabled={busy} onClick={() => setForm(null)}>{copy("Cancel", "გაუქმება")}</button></div></form>}
                <h3>{copy("Club participation", "კლუბში მონაწილეობა")}</h3>{child.clubs.length === 0 ? <p>{copy("Your family connection is active. Find a group or share a linking code from the selected player’s card in Parent Hub.", "ოჯახური კავშირი აქტიურია. მოძებნეთ ჯგუფი ან გააზიარეთ კოდი მშობლის სივრცეში.")}</p> : child.clubs.map(club => <article key={club.id}><div className="family-club-row"><Link to={`/clubs/${club.clubId}`}>{club.name}</Link><span>{label(club.status)} · {copy('Consent', 'თანხმობა')} {label(club.consent)}</span></div><div className="family-actions">{club.consent !== 'CONFIRMED' ? <button type="button" className="parent-button" disabled={busy} onClick={() => setConfirm({ path: `/family/consents/${club.id}`, body: { accept: true }, message: copy(`Consent to ${child.name} participating with ${club.name}? This applies only to this current club enrollment.`, `ეთანხმებით ${child.name}-ის მონაწილეობას კლუბში ${club.name}? თანხმობა ეხება მხოლოდ ამ მიმდინარე ჩარიცხვას.`) })}>{copy("Review participation consent", "მონაწილეობის თანხმობის განხილვა")}</button> : <button type="button" className="parent-button" disabled={busy} onClick={() => setConfirm({ path: `/family/consents/${club.id}`, body: { accept: false }, message: copy(`Withdraw participation consent for ${club.name}? Squad communication and participation will stop until a current guardian grants consent again. Your family connection stays active.`, `გაუქმდეს მონაწილეობის თანხმობა კლუბში ${club.name}? გუნდთან კომუნიკაცია და მონაწილეობა შეწყდება მეურვის ახალი თანხმობის მიღებამდე. ოჯახური კავშირი აქტიური რჩება.`) })}>{copy("Withdraw participation consent", "მონაწილეობის თანხმობის გაუქმება")}</button>}<button type="button" className="parent-button" disabled={busy} onClick={() => setConfirm({ path: `/family/children/${child.childId}/clubs/${club.clubId}/depart`, body: { affiliationId: club.id }, message: copy(`End ${child.name}'s playing enrollment with ${club.name}? This removes this club's squad access and keeps their identity and family connection. The player’s identity remains available for another joining arrangement.`, `დასრულდეს ${child.name}-ის მოთამაშის წევრობა კლუბში ${club.name}? კლუბის გუნდზე წვდომა შეწყდება, პროფილი და ოჯახური კავშირი შენარჩუნდება. შემდეგ შეგიძლიათ სხვა კლუბისთვის ჩარიცხვის კოდის შექმნა.`) })}>{copy('Leave or change club', 'კლუბის დატოვება ან შეცვლა')}</button></div></article>)}
                {child.codes.length > 0 && <details className="family-history"><summary>{copy("Active linking codes", "მოქმედი დაკავშირების კოდები")}</summary>{child.codes.map(c => <p key={c.id}>{copy("Code active until ", "კოდი მოქმედებს ")}{new Date(c.expiresAt).toLocaleString()} <button type="button" className="parent-button" disabled={busy} onClick={() => void run(`/family/enrollment-codes/${c.id}/cancel`)}>{copy("Cancel code", "კოდის გაუქმება")}</button></p>)}</details>}
                {!!child.history?.length && <details className="family-history"><summary>{copy("Connection history", "კავშირის ისტორია")}</summary>{child.history.map((event, index) => <p key={index}>{label(event.action)}{event.clubName ? ` · ${event.clubName}` : ''} · {new Date(event.createdAt).toLocaleDateString()}</p>)}</details>}
            </details>)}
            {!!data.consentHistory?.length && <details className="family-history"><summary>{copy("My club consent decisions", "კლუბის თანხმობის ჩემი გადაწყვეტილებები")}</summary>{data.consentHistory.map((item, index) => <p key={index}>{label(item.action)}{item.clubName ? ` · ${item.clubName}` : ''} · {new Date(item.createdAt).toLocaleDateString()}</p>)}</details>}
            {data.ended.length > 0 && <details className="family-history"><summary>{copy("Ended family authority · ", "დასრულებული მეურვეობა · ")}{data.ended.length}</summary><p>{copy("Ended connections do not give access to personal details, club records or schedules.", "დასრულებული კავშირები პირად მონაცემებზე, კლუბის ჩანაწერებსა და განრიგზე წვდომას არ იძლევა.")}</p>{data.ended.map(item => <div key={item.id}><p>{copy("Connection #", "კავშირი #")}{item.id} · {item.reason === 'ADULTHOOD' ? copy("The child reached adulthood and now controls their own account.", "ბავშვი სრულწლოვანი გახდა და საკუთარ ანგარიშს თავად მართავს.") : copy("Guardian authority ended.", "მეურვის უფლებამოსილება დასრულდა.")}</p>{item.activationUserId && <IdentityActivationForm childId={item.activationUserId} adult onChanged={() => { setTick(v => v + 1); onChanged(); }} />}</div>)}</details>}
        </>}
        </div>
    </section>;
}
